/* =========================================================================
   Events: the banner at the top of every page moves on to the next event
   as soon as an event's day is over, and an event page closes its form
   once the event has taken place.

   The list below is written by tools/build-events.py: add an event there,
   not here. Loaded by js/ui.js on every page.

   MOCK: the registration form sends nothing yet; wire it to the CRM in
   submit() below.
   ========================================================================= */
(function () {
  "use strict";
  /* events: generated by tools/build-events.py */
  var EVENTS = [
    {
      "href": "/event-toys-games.html",
      "hrefFr": "/fr/evenements/jeux-jouets/",
      "date": "2026-10-16",
      "k": [
        "Étude sectorielle · Jeux & jouets",
        "Sector study · Toys & games"
      ],
      "d": [
        "Vendredi 16 octobre · Musée de la Vie romantique",
        "Friday 16 October · Musée de la Vie romantique"
      ],
      "long": [
        "Vendredi 16 octobre 2026",
        "Friday 16 October 2026"
      ]
    },
    {
      "href": "/event-luxury.html",
      "hrefFr": "/fr/evenements/luxe/",
      "date": "2026-11-03",
      "k": [
        "Étude sectorielle · Luxe",
        "Sector study · Luxury"
      ],
      "d": [
        "Mardi 3 novembre · Ladurée Champs-Élysées",
        "Tuesday 3 November · Ladurée Champs-Élysées"
      ],
      "long": [
        "Mardi 3 novembre 2026",
        "Tuesday 3 November 2026"
      ]
    },
    {
      "href": "/event-food.html",
      "hrefFr": "/fr/evenements/alimentation/",
      "date": "2026-11-19",
      "k": [
        "Étude sectorielle · Food",
        "Sector study · Food"
      ],
      "d": [
        "Jeudi 19 novembre · Madame Rêve",
        "Thursday 19 November · Madame Rêve"
      ],
      "long": [
        "Jeudi 19 novembre 2026",
        "Thursday 19 November 2026"
      ]
    }
  ];

  var html = document.documentElement;
  function fr() { return (html.lang || "fr").slice(0, 2) === "fr"; }
  function L(pair) { return fr() ? pair[0] : pair[1]; }
  function esc(s) { return String(s).replace(/[&<>"]/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]; }); }
  /* an event is over once its day is: until 23:59 local time it is "next" */
  function hrefOf(e) { return fr() && e.hrefFr ? e.hrefFr : e.href; }
  function over(date) { return new Date(date + "T23:59:59") < new Date(); }
  var next = EVENTS.filter(function (e) { return !over(e.date); })[0] || null;

  /* ---------------------------------------------------------- the banner */
  var banner = document.querySelector("aside.banner:not(.banner--float)");
  /* the banner can be closed: it stays closed until the end of the event it
     announced (30 days for the guide), then the next one shows. js/theme.js
     reads the same key in <head>, so a closed banner never flashes in. */
  var OFF = "licter-banner-off";
  function closer() {
    var b = document.createElement("button");
    b.type = "button"; b.className = "banner__x";
    b.setAttribute("aria-label", fr() ? "Fermer le bandeau" : "Close the banner");
    b.innerHTML = '<span aria-hidden="true">×</span>';
    b.addEventListener("click", function () {
      var until = next ? new Date(next.date + "T23:59:59").getTime() : Date.now() + 30 * 864e5;
      try { localStorage.setItem(OFF, String(until)); } catch (e) {}
      html.classList.add("banner-off");
      banner.hidden = true;
      measure();
    });
    banner.appendChild(b);
  }
  if (banner && html.classList.contains("banner-off")) banner.hidden = true;
  function paintBanner() {
    if (!banner) return;
    paintBannerInner();
    if (!banner.querySelector(".banner__x")) closer();
  }
  function paintBannerInner() {
    if (!next) {
      /* nothing upcoming: back to the free guide */
      if (!banner.classList.contains("banner--event")) return;
      banner.className = "banner";
      banner.setAttribute("aria-label", fr() ? "Guide gratuit" : "Free guide");
      banner.innerHTML = '<a class="banner__a" href="/guide.html"><b>' + (fr() ? "Guide gratuit." : "Free guide.") + "</b> <span>" +
        (fr() ? "Les 12 questions auxquelles la social data répond mieux qu\u2019une étude" : "The 12 questions social data answers better than a survey") + "</span> →</a>";
      return;
    }
    banner.className = "banner banner--event";
    banner.setAttribute("aria-label", fr() ? "Prochain événement" : "Next event");
    banner.innerHTML = '<a class="banner__a" href="' + hrefOf(next) + '">' +
      '<i class="banner__tag">' + (fr() ? "Prochain événement" : "Next event") + "</i> <b>" + esc(L(next.k)) + "</b> <span>" + esc(L(next.d)) + "</span> <u>" +
      (fr() ? "S'inscrire" : "Register") + ' <span aria-hidden="true">→</span></u></a>';
  }

  /* ------------------------------------------------------ an event page */
  var page = document.querySelector("[data-ev-date]");
  var form = document.querySelector(".ev__form"), done = document.querySelector(".ev__done");
  var sent = null;
  function paintPage() {
    if (!page || !form) return;
    if (over(page.getAttribute("data-ev-date"))) {
      form.hidden = true;
      done.hidden = false;
      done.classList.add("is-past");
      done.innerHTML = esc(fr() ? "Cet événement a eu lieu." : "This event has taken place.") +
        (next ? ' <a href="' + hrefOf(next) + '">' + esc(fr() ? "Voir le prochain" : "See the next one") + " : " + esc(L(next.k)) + ' <span aria-hidden="true">→</span></a>' : "");
      return;
    }
    if (sent) {
      done.innerHTML = fr()
        ? "Merci, <b>" + esc(sent.first) + "</b>. Votre demande d\u2019inscription est bien reçue. Votre place sera confirmée par e-mail à <b>" + esc(sent.email) + "</b>, sous réserve de places disponibles."
        : "Thank you, <b>" + esc(sent.first) + "</b>. Your registration request is in. Your seat will be confirmed by email to <b>" + esc(sent.email) + "</b>, subject to availability.";
    }
  }
  if (form) {
    var EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;
    var email = form.querySelector('[name="email"]');
    if (window.LicterLead && !email.value) email.value = window.LicterLead.get() || "";
    form.addEventListener("submit", function (e) {
      e.preventDefault();
      var v = {}, bad = null;
      Array.prototype.forEach.call(form.querySelectorAll("input"), function (i) {
        v[i.name] = i.value.trim();
        var ok = i.name === "email" ? EMAIL.test(v[i.name]) : !!v[i.name];
        i.setAttribute("aria-invalid", ok ? "false" : "true");
        if (!ok && !bad) bad = i;
      });
      document.getElementById("ev-err").hidden = !bad;
      if (bad) { bad.focus(); return; }
      if (window.LicterSend) window.LicterSend("event", ((document.querySelector("h1") || {}).textContent || "").replace(/\s+/g, " ").trim() + (page ? " · " + page.getAttribute("data-ev-date") : ""), form);
      if (window.LicterLead) window.LicterLead.set(v.email);
      sent = v;
      if (window.LicterTrack) window.LicterTrack("form_submit", { form: "event", event: page ? page.getAttribute("data-ev-date") : "" });
      form.hidden = true;
      done.hidden = false;
      paintPage();
      done.setAttribute("tabindex", "-1");
      done.focus();
    });
  }

  /* ----------------------------------------------- the list of events */
  Array.prototype.forEach.call(document.querySelectorAll(".evl__list [data-ev-date]"), function (li) {
    if (over(li.getAttribute("data-ev-date"))) li.classList.add("is-past");
  });

  /* the banner is pinned: its height goes to --banner-h, which the compact
     bar, anchors and sticky panels use to sit under it */
  function measure() {
    if (!banner) return;
    var away = banner.hidden || banner.classList.contains("banner--away");
    html.style.setProperty("--banner-h", (away ? 0 : banner.offsetHeight) + "px");
  }
  if (banner) {
    if (window.ResizeObserver) new ResizeObserver(measure).observe(banner);
    window.addEventListener("resize", measure);
  }

  /* on a phone the banner steps out of the way while reading down, and comes
     back as soon as the visitor scrolls up (with the compact bar) */
  if (banner && window.matchMedia) {
    var phone = window.matchMedia("(max-width: 720px)"), lastY = window.scrollY, tick = false;
    window.addEventListener("scroll", function () {
      if (tick) return; tick = true;
      requestAnimationFrame(function () {
        tick = false;
        var y = window.scrollY, d = y - lastY;
        if (Math.abs(d) < 8) return;
        var away = phone.matches && d > 0 && y > banner.offsetHeight + 40;
        if (banner.classList.contains("banner--away") !== away) { banner.classList.toggle("banner--away", away); measure(); }
        lastY = y;
      });
    }, { passive: true });
  }

  function paint() { paintBanner(); paintPage(); measure(); }
  paint();
  new MutationObserver(paint).observe(html, { attributes: true, attributeFilter: ["lang"] });
})();
