/* =========================================================================
   Events: the banner at the top of every page moves on to the next event
   as soon as an event's day is over, and an event page closes its form
   once the event has taken place.

   The list below is written by tools/build-events.py: add an event there,
   not here. Loaded by js/ui.js on every page.

   MOCK: the registration form sends nothing yet; wire it to the CRM in
   submit() below.
   ========================================================================= */
(function () {
  "use strict";
  /* events: generated by tools/build-events.py */
  var EVENTS = [
    {
      "href": "/event-toys-games.html",
      "date": "2026-10-16",
      "k": [
        "Étude sectorielle · Jeux & jouets",
        "Sector study · Toys & games"
      ],
      "d": [
        "Vendredi 16 octobre · Musée de la Vie romantique",
        "Friday 16 October · Musée de la Vie romantique"
      ],
      "long": [
        "Vendredi 16 octobre 2026",
        "Friday 16 October 2026"
      ]
    },
    {
      "href": "/event-luxury.html",
      "date": "2026-11-03",
      "k": [
        "Étude sectorielle · Luxe",
        "Sector study · Luxury"
      ],
      "d": [
        "Mardi 3 novembre · Ladurée Champs-Élysées",
        "Tuesday 3 November · Ladurée Champs-Élysées"
      ],
      "long": [
        "Mardi 3 novembre 2026",
        "Tuesday 3 November 2026"
      ]
    },
    {
      "href": "/event-food.html",
      "date": "2026-11-19",
      "k": [
        "Étude sectorielle · Food",
        "Sector study · Food"
      ],
      "d": [
        "Jeudi 19 novembre · Madame Rêve",
        "Thursday 19 November · Madame Rêve"
      ],
      "long": [
        "Jeudi 19 novembre 2026",
        "Thursday 19 November 2026"
      ]
    }
  ];

  var html = document.documentElement;
  function fr() { return (html.lang || "fr").slice(0, 2) === "fr"; }
  function L(pair) { return fr() ? pair[0] : pair[1]; }
  function esc(s) { return String(s).replace(/[&<>"]/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]; }); }
  /* an event is over once its day is: until 23:59 local time it is "next" */
  function over(date) { return new Date(date + "T23:59:59") < new Date(); }
  var next = EVENTS.filter(function (e) { return !over(e.date); })[0] || null;

  /* ---------------------------------------------------------- the banner */
  var banner = document.querySelector("aside.banner:not(.banner--float)");
  function paintBanner() {
    if (!banner) return;
    if (!next) {
      /* nothing upcoming: back to the free guide */
      if (!banner.classList.contains("banner--event")) return;
      banner.className = "banner";
      banner.setAttribute("aria-label", fr() ? "Guide gratuit" : "Free guide");
      banner.innerHTML = '<a class="banner__a" href="/guide.html"><b>' + (fr() ? "Guide gratuit." : "Free guide.") + "</b> <span>" +
        (fr() ? "Les 12 questions auxquelles la social data répond mieux qu\u2019une étude" : "The 12 questions social data answers better than a survey") + "</span> →</a>";
      return;
    }
    banner.className = "banner banner--event";
    banner.setAttribute("aria-label", fr() ? "Prochain événement" : "Next event");
    banner.innerHTML = '<a class="banner__a" href="' + next.href + '">' +
      '<i class="banner__tag">' + (fr() ? "Prochain événement" : "Next event") + "</i> <b>" + esc(L(next.k)) + "</b> <span>" + esc(L(next.d)) + "</span> <u>" +
      (fr() ? "S'inscrire" : "Register") + ' <span aria-hidden="true">→</span></u></a>';
  }

  /* ------------------------------------------------------ an event page */
  var page = document.querySelector("[data-ev-date]");
  var form = document.querySelector(".ev__form"), done = document.querySelector(".ev__done");
  var sent = null;
  function paintPage() {
    if (!page || !form) return;
    if (over(page.getAttribute("data-ev-date"))) {
      form.hidden = true;
      done.hidden = false;
      done.classList.add("is-past");
      done.innerHTML = esc(fr() ? "Cet événement a eu lieu." : "This event has taken place.") +
        (next ? ' <a href="' + next.href + '">' + esc(fr() ? "Voir le prochain" : "See the next one") + " : " + esc(L(next.k)) + ' <span aria-hidden="true">→</span></a>' : "");
      return;
    }
    if (sent) {
      done.innerHTML = fr()
        ? "Merci, <b>" + esc(sent.first) + "</b>. Votre demande d\u2019inscription est bien reçue. Votre place sera confirmée par e-mail à <b>" + esc(sent.email) + "</b>, sous réserve de places disponibles."
        : "Thank you, <b>" + esc(sent.first) + "</b>. Your registration request is in. Your seat will be confirmed by email to <b>" + esc(sent.email) + "</b>, subject to availability.";
    }
  }
  if (form) {
    var EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;
    var email = form.querySelector('[name="email"]');
    if (window.LicterLead && !email.value) email.value = window.LicterLead.get() || "";
    form.addEventListener("submit", function (e) {
      e.preventDefault();
      var v = {}, bad = null;
      Array.prototype.forEach.call(form.querySelectorAll("input"), function (i) {
        v[i.name] = i.value.trim();
        var ok = i.name === "email" ? EMAIL.test(v[i.name]) : !!v[i.name];
        i.setAttribute("aria-invalid", ok ? "false" : "true");
        if (!ok && !bad) bad = i;
      });
      document.getElementById("ev-err").hidden = !bad;
      if (bad) { bad.focus(); return; }
      /* MOCK: send { event: page.getAttribute("data-ev-date"), first, last, company, email } to the CRM */
      if (window.LicterLead) window.LicterLead.set(v.email);
      sent = v;
      form.hidden = true;
      done.hidden = false;
      paintPage();
      done.setAttribute("tabindex", "-1");
      done.focus();
    });
  }

  /* ----------------------------------------------- the list of events */
  Array.prototype.forEach.call(document.querySelectorAll(".evl__list [data-ev-date]"), function (li) {
    if (over(li.getAttribute("data-ev-date"))) li.classList.add("is-past");
  });

  /* ------------------------------- the home's "next event" card */
  var card = document.querySelector("[data-next-event]");
  var MON = [["janv.", "févr.", "mars", "avr.", "mai", "juin", "juil.", "août", "sept.", "oct.", "nov.", "déc."],
             ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]];
  function paintCard() {
    if (!card) return;
    var box = card.closest(".res__item") || card;
    if (!next) { box.hidden = true; return; }
    var d = new Date(next.date + "T12:00:00");
    card.setAttribute("href", next.href);
    box.querySelector('[data-ev="day"]').textContent = d.getDate();
    box.querySelector('[data-ev="mon"]').textContent = MON[fr() ? 0 : 1][d.getMonth()];
    /* never a line starting with the separator */
    box.querySelector('[data-ev="title"]').textContent = L(next.k).replace(/ · /g, "\u00a0· ");
    box.querySelector('[data-ev="place"]').textContent = L(next.d);
  }

  function paint() { paintBanner(); paintPage(); paintCard(); }
  paint();
  new MutationObserver(paint).observe(html, { attributes: true, attributeFilter: ["lang"] });
})();
