/* Dictionnaire EN → FR. Toute chaîne absente reste en anglais. */
window.LicterFR = {

  /* ---- bandeau, navigation, pied de page ---- */

  /* ---- les interviews clients (clients.html) ---- */
  "IN THEIR OWN WORDS": "DANS LEURS MOTS",
  "They tell it better than we do.": "Ils le racontent mieux que nous.",
  "On video.": "En vidéo.",
  "Full conversations with the people who run listening inside their organisation — what they were trying to decide, and what the data changed. In French, on our channel, uncut.":
    "Des conversations entières avec celles et ceux qui pilotent l'écoute dans leur organisation : ce qu'ils avaient à décider, et ce que la donnée a changé. En français, sur notre chaîne, sans coupe.",
  "It is not a study if there is no action plan.": "Ce n'est pas une étude s'il n'y a pas de plan d'action.",
  "Social media helps us build better products.": "Les réseaux sociaux aident à créer de meilleurs produits.",
  "Millions of tweets to handle, live.": "Des millions de tweets à gérer, en direct.",
  "Every episode of": "Chaque épisode d'", "is on the channel — one conversation a week with the people who read the conversation.":
    "est sur la chaîne — une conversation par semaine avec celles et ceux qui lisent la conversation.",
  "Get the next one": "Recevoir le prochain",
  "NOTED - THE NEXT EPISODE LANDS IN YOUR INBOX": "C'EST NOTÉ - LE PROCHAIN ÉPISODE ARRIVE DANS VOTRE BOÎTE",
  "One email when it is out. No sequence.": "Un email à sa sortie. Pas de séquence.",

  /* ---- cartes plateformes (tech-tools) ---- */
  "Listening suite": "Suite d'écoute", "Real time": "Temps réel",
  "Visual AI": "IA visuelle", "See the platform": "Voir la plateforme",
  "The broadest coverage on the market — volume, topics and sentiment across languages, read over long periods.":
    "La couverture la plus large du marché — volumes, sujets et sentiment, toutes langues, sur longue période.",
  "The live conversation and the media sphere, with an alert that reaches you in fifteen minutes, around the clock.":
    "La conversation en direct et la sphère média, avec une alerte qui vous parvient en quinze minutes, 24/7.",
  "Reads what appears in the image, not only in the caption: logos, products and contexts nobody writes down.":
    "Lit ce qui apparaît dans l'image, pas seulement dans la légende : logos, produits et contextes que personne n'écrit.",
  "Who the communities actually are — interests, affinities and overlaps, at the detail a persona needs.":
    "Qui sont vraiment les communautés — intérêts, affinités et recoupements, au niveau de détail qu'exige un persona.",
  "The guide —": "Le guide —",
  "the 12 questions social data answers better than a survey": "les 12 questions auxquelles la social data répond mieux qu'une étude",
  "USE CASES": "CAS D'USAGE", "OFFERS": "OFFRES", "WHY LICTER": "POURQUOI LICTER",
  "TECH & TOOLS": "TECHNO & OUTILS", "CLIENTS": "CLIENTS", "BLOG": "BLOG",
  "Licter — home": "Licter — accueil", "Main": "Principal", "Language": "Langue",
  "FOUR FAMILIES OF QUESTIONS": "QUATRE FAMILLES DE QUESTIONS",
  "Communication": "Communication", "Brand health": "Santé de marque",
  "Audiences": "Audiences", "Trends & innovation": "Tendances & innovation",
  "Campaign impact, leader advocacy, the right ambassadors.": "Impact des campagnes, prise de parole des dirigeants, bons ambassadeurs.",
  "Image, messaging and the risks worth catching early.": "Image, discours, et les risques qu'il vaut mieux voir tôt.",
  "Segmentation, rejuvenation, expectations at every touchpoint.": "Segmentation, rajeunissement, attentes à chaque point de contact.",
  "Product verdicts, market opportunities, emerging topics.": "Verdicts produits, opportunités de marché, sujets émergents.",
  "FLAGSHIP QUESTIONS": "QUESTIONS PHARES",
  "Analyze the impact of a campaign": "Mesurer l'impact d'une campagne",
  "Monitor your brand reputation": "Surveiller la réputation de votre marque",
  "Segment your target profiles": "Segmenter vos profils cibles",
  "Test and evaluate your products": "Tester et évaluer vos produits",
  "Book a meeting": "Prendre rendez-vous", "All twelve use cases": "Les douze cas d'usage",
  "THREE WAYS TO WORK WITH US": "TROIS FAÇONS DE TRAVAILLER AVEC NOUS",
  "Fixed fee, unlimited studies, no commitment.": "Forfait fixe, études illimitées, sans engagement.",
  "Alerts in 15 minutes, 24/7, in 20+ languages.": "Alerte en 15 minutes, 24/7, en plus de 20 langues.",
  "We make the platform you already own produce decisions.": "Nous faisons produire des décisions à la plateforme que vous payez déjà.",
  "HOW AN ENGAGEMENT RUNS": "COMMENT SE DÉROULE UNE MISSION",
  "Framing": "Cadrage", "Collection": "Collecte", "Analysis": "Analyse", "Decision": "Décision",
  "Compare the offers": "Comparer les offres",
  "THE PLATFORMS WE RUN": "LES PLATEFORMES QUE NOUS OPÉRONS",
  "Broad listening and analytics, across markets and languages.": "Écoute large et analytics, tous marchés et toutes langues.",
  "Real-time monitoring, and the media conversation as it breaks.": "Veille temps réel, et la conversation média au moment où elle démarre.",
  "Visual listening: what appears in the image, not only in the text.": "Écoute visuelle : ce qui apparaît dans l'image, pas seulement dans le texte.",
  "Audience intelligence: who the communities are, in detail.": "Audience intelligence : qui sont les communautés, en détail.",
  "WHERE THE DATA COMES FROM": "D'OÙ VIENNENT LES DONNÉES",
  "Generative AI": "IA générative", "See the stack": "Voir la stack",
  "OFFERS": "OFFRES", "COMPANY": "L'ENTREPRISE", "GET STARTED": "COMMENCER",
  "Social Insights": "Social Insights", "Vigie 360 — 24/7 monitoring": "Vigie 360 — veille 24/7",
  "Social Listening as a Service": "Social Listening as a Service",
  "Why Licter": "Pourquoi Licter", "Tech & tools": "Techno & outils", "Clients": "Clients", "Blog": "Blog",
  "The free guide": "Le guide gratuit", "Request a diagnostic": "Demander un diagnostic",
  "The Social Data Intelligence consultancy. We turn data from the world's largest panel — social media, search, generative AI — into decisions.":
    "Le cabinet de conseil en Social Data Intelligence. Nous transformons la donnée du plus grand panel du monde — réseaux sociaux, recherche, IA générative — en décisions.",
  "© 2026 Licter — Social Data Intelligence": "© 2026 Licter — Social Data Intelligence",
  "50+ clients · 160+ projects · Top 50 worldwide, SI Lab 2024": "50+ clients · 160+ projets · Top 50 mondial, SI Lab 2024",

  /* ---- hero ---- */
  "AI & DATA AGENCY FOR ENTERPRISES": "AGENCE IA & DATA POUR LES ENTREPRISES",
  "STOP GUESSING,": "ARRÊTEZ DE SUPPOSER,", "START LISTENING.": "COMMENCEZ À ÉCOUTER.",
  "Licter is the Social Data Intelligence consultancy. We turn data from the world's largest panel – social media, search, generative AI – into decisions.":
    "Licter est le cabinet de conseil en Social Data Intelligence. Nous transformons la donnée du plus grand panel du monde – réseaux sociaux, recherche, IA générative – en décisions.",
  "Your work email...": "Votre e-mail professionnel...", "Your work email": "Votre e-mail professionnel",
  "BOOK A MEETING": "PRENDRE RENDEZ-VOUS",
  "NOTED - WE GET BACK TO YOU WITHIN 24 HOURS": "BIEN REÇU - NOUS REVENONS VERS VOUS SOUS 24 H",
  "THEY TRUST US": "ILS NOUS FONT CONFIANCE",

  /* ---- home ---- */
  "client organisations already read their market with us": "organisations lisent déjà leur marché avec nous",
  "projects delivered since 2022": "projets livrés depuis 2022",
  "consumer profiles in the panel": "profils consommateurs dans le panel",
  "social intelligence providers worldwide, SI Lab 2024": "acteurs mondiaux de la social intelligence, SI Lab 2024",
  "Buy answers, not licences.": "Achetez des réponses, pas des licences.",
  "Fixed fee, unlimited studies, no commitment. Consultants frame the question, configure the collection and produce the analysis.":
    "Forfait fixe, études illimitées, sans engagement. Nos consultants cadrent la question, configurent la collecte et produisent l'analyse.",
  "Your analyses, run by experts": "Vos analyses, menées par des experts",
  "A fixed monthly fee, unlimited studies, no tool licence to staff.": "Un forfait mensuel fixe, des études illimitées, aucune licence à faire vivre.",
  "Alerts in 15 minutes, 24/7": "Alerte en 15 minutes, 24/7",
  "Your brand, your executives and your markets, in 20+ languages.": "Votre marque, vos dirigeants et vos marchés, en plus de 20 langues.",
  "Make your platform produce decisions": "Faites produire des décisions à votre plateforme",
  "We take over the taxonomy, the dashboards and the recurring analyses.": "Nous reprenons la taxonomie, les tableaux de bord et les analyses récurrentes.",
  "Talk to an expert": "Parler à un expert",
  "OUR USE CASES": "NOS CAS D'USAGE",
  "EVERY BUSINESS QUESTION": "CHAQUE QUESTION BUSINESS", "HAS A DATA ANSWER.": "A UNE RÉPONSE DANS LA DATA.",
  "We help brands tap into the data of the world's largest panel.": "Nous aidons les marques à exploiter la donnée du plus grand panel du monde.",
  "COMMUNICATION": "COMMUNICATION", "BRAND HEALTH": "SANTÉ DE MARQUE", "AUDIENCES": "AUDIENCES", "INNOVATION": "INNOVATION",
  "Three of the twelve questions social data answers better than a survey.":
    "Trois des douze questions auxquelles la social data répond mieux qu'une étude.",
  "Analyze the impact of an event or campaign": "Mesurer l'impact d'un événement ou d'une campagne",
  "Optimize your leader advocacy strategy": "Optimiser la prise de parole de vos dirigeants",
  "Identify the right ambassadors": "Identifier les bons ambassadeurs",
  "Monitor your brand image and reputation": "Surveiller l'image et la réputation de votre marque",
  "Develop your brand messaging": "Construire votre discours de marque",
  "Identify and mitigate brand risks": "Identifier et désamorcer les risques de marque",
  "Rejuvenate your audiences": "Rajeunir vos audiences",
  "Understand expectations at every touchpoint": "Comprendre les attentes à chaque point de contact",
  "Analyze markets and identify opportunities": "Analyser les marchés et repérer les opportunités",
  "Map out your stakeholders and future trends": "Cartographier vos parties prenantes et les tendances à venir",
  "Discover the use cases": "Découvrir les cas d'usage",
  "Four steps, no black box.": "Quatre étapes, aucune boîte noire.",
  "BEFORE YOU ASK": "AVANT DE NOUS ÉCRIRE",
  "Five questions we get every week.": "Cinq questions qu'on nous pose chaque semaine.",
  "THREE WAYS TO START": "TROIS FAÇONS DE COMMENCER",
  "Pick the one that matches where you are.": "Choisissez celle qui correspond à votre situation.",
  "Just exploring": "Vous explorez",
  "The twelve questions social data answers better than a survey, and the method behind each one.":
    "Les douze questions auxquelles la social data répond mieux qu'une étude, et la méthode derrière chacune.",
  "Get the free guide": "Recevoir le guide gratuit",
  "You already run listening": "Vous faites déjà du social listening",
  "An independent diagnostic: audit, maturity score on six dimensions, quick wins and a roadmap.":
    "Un diagnostic indépendant : audit, score de maturité sur six dimensions, quick wins et feuille de route.",
  "You have a decision to make": "Vous avez une décision à prendre",
  "Thirty minutes with a consultant. You describe the decision, we say what the data can settle.":
    "Trente minutes avec un consultant. Vous décrivez la décision, nous disons ce que la data peut trancher.",

  /* ---- titres et accroches des autres pages ---- */
  "EVERY BUSINESS QUESTION HAS A DATA ANSWER.": "CHAQUE QUESTION BUSINESS A UNE RÉPONSE DANS LA DATA.",
  "BUY ANSWERS, NOT LICENCES.": "ACHETEZ DES RÉPONSES, PAS DES LICENCES.",
  "REPLACE INTUITION WITH DATA.": "REMPLACEZ L'INTUITION PAR LA DATA.",
  "FOUR LAYERS OF SIGNAL.": "QUATRE COUCHES DE SIGNAL.",
  "50+ TEAMS ALREADY LISTEN.": "50+ ÉQUIPES ÉCOUTENT DÉJÀ.",
  "WHAT WE SEE IN THE DATA.": "CE QUE NOUS VOYONS DANS LA DATA.",
  "YOUR SOCIAL DATA DIAGNOSTIC.": "VOTRE DIAGNOSTIC SOCIAL DATA.",
  "THIRTY MINUTES, ONE QUESTION.": "TRENTE MINUTES, UNE QUESTION.",
  "THE 12 QUESTIONS SOCIAL DATA ANSWERS BETTER THAN A SURVEY.": "LES 12 QUESTIONS AUXQUELLES LA SOCIAL DATA RÉPOND MIEUX QU'UNE ÉTUDE.",
  "FREE GUIDE": "GUIDE GRATUIT", "DIAGNOSTIC": "DIAGNOSTIC", "BOOK A MEETING": "PRENDRE RENDEZ-VOUS",
  "See the offers": "Voir les offres", "See the use cases": "Voir les cas d'usage",
  "NAME": "NOM", "COMPANY": "ENTREPRISE", "WORK EMAIL": "E-MAIL PROFESSIONNEL", "PHONE": "TÉLÉPHONE",
  "FIRST NAME": "PRÉNOM", "LAST NAME": "NOM", "YOUR CONTEXT": "VOTRE CONTEXTE",
  "THE QUESTION YOU WANT ANSWERED": "LA QUESTION À LAQUELLE VOUS VOULEZ RÉPONDRE",
  "Get the free guide →": "Recevoir le guide gratuit →",
  "Request my diagnostic →": "Demander mon diagnostic →",
  "Book the call →": "Réserver l'appel →",
  "100% free · sent by email immediately · no sequence afterwards": "100 % gratuit · envoi immédiat par e-mail · aucune séquence ensuite",
  "No commitment · Reply within 24 hours · Independent of any follow-up project": "Sans engagement · réponse sous 24 h · indépendant de toute suite",
  "Reply within 24 hours · 30 minutes · No commitment": "Réponse sous 24 h · 30 minutes · sans engagement",
  "Guide sent. Check your inbox — and your spam folder, it happens.": "Guide envoyé. Vérifiez votre boîte de réception — et vos spams, ça arrive.",
  "Request received. A consultant comes back to you within 24 hours to book the scoping call.":
    "Demande reçue. Un consultant revient vers vous sous 24 h pour caler l'appel de cadrage.",
  "Booked. We come back within 24 hours with two or three slots.": "C'est noté. Nous revenons sous 24 h avec deux ou trois créneaux.",
  "Story · 2 h": "Story · 2 h", "Reel · 14 min": "Reel · 14 min",
  "Story · 47 min": "Story · 47 min", "Reel · 1 h": "Reel · 1 h",
  "Post · 3 h": "Post · 3 h", "Story · 22 min": "Story · 22 min",
  "Already running social listening?": "Vous faites déjà du social listening ?",
  "Request a diagnostic instead →": "Demandez plutôt un diagnostic →"
};
