"""The long-form section of the audience listening expertise page (SEO plan:
the page was too thin for "audience intelligence", "analyse d'audience" and
"étude d'audience réseaux sociaux"): what audience intelligence is, how it
differs from personas, audience measurement and social listening, the data,
segmentation, the tools, what it helps decide, the limits, and what an agency
or a consultancy adds. Each block is (heading, [paragraphs]), every string a
(French, English) pair. Same structure as tools/sl_guide.py.

Licter facts come from the site's own files: the behavioural panel (about
over 7,000 criteria per Audiense, which acquired SOPRISM; the social media population, 5.66 billion active users, per Kepios / DataReportal Digital 2026) and the affinity, penetration and
opportunity scores from tools/uc_content.py; the HP case from
tools/build-offers.py; the SoPrism limits and the "19 tools" from
tools/tools_data.py and fr/outils/soprism/; the Charles Besson quote from
article-comment-loreal-utilise-le-social-listening-pour-capter-la-voix-du-consommateur.html.
Generic scenarios are marked "par exemple" and are not Licter cases."""

KICKER = ("L'AUDIENCE INTELLIGENCE, EN DÉTAIL", "AUDIENCE INTELLIGENCE, IN DETAIL")
TITLE = ("Tout ce qu'il faut savoir avant de lancer une étude d'audience.", "What to know before you start an audience study.")

BLOCKS = [
    (("Qu'est-ce que l'audience intelligence ?", "What is audience intelligence?"), [
        ("L'audience intelligence, ou intelligence des audiences, consiste à décrire un public à partir de ce qu'il fait en ligne : les comptes qu'il suit, les contenus qu'il partage, les marques et les médias qu'il consomme, les sujets qu'il recherche. Le résultat n'est pas une moyenne, mais une carte de communautés, chacune avec sa taille, ses passions et ses canaux.",
         "Audience intelligence means describing a public from what it does online: the accounts it follows, the content it shares, the brands and media it consumes, the subjects it searches for. The result is not an average, but a map of communities, each with its size, its passions and its channels."),
        ("Le terme recouvre ce qu'on appelle aussi analyse d'audience, étude d'audience sur les réseaux sociaux ou consumer intelligence, quand l'étude porte sur les consommateurs d'une catégorie. Chez Licter, nous parlons d'audience listening, l'une de nos six écoutes. La question de départ reste la même : qui sont vraiment les gens que vous voulez toucher, au-delà de ce que vous croyez savoir d'eux, et où les trouver ?",
         "The term covers what is also called audience analysis, a social media audience study, or consumer intelligence when the study looks at the consumers of a category. At Licter, we call it audience listening, one of our six listenings. The starting question stays the same: who really are the people you want to reach, beyond what you think you know about them, and where can you find them?"),
    ]),
    (("Qu'est-ce que la consumer intelligence ?", "What is consumer intelligence?"), [
        ("La consumer intelligence désigne l'étude des consommateurs d'une catégorie à partir de leurs traces en ligne : ce qu'ils disent des produits, ce qu'ils recherchent, les marques et les médias qu'ils suivent. Elle croise le plus souvent social listening, audience intelligence et données de recherche, pour répondre à une question de marché plutôt qu'à une question de marque. Les consumer insights en sont le résultat : ce que l'on retient de cette lecture pour décider.",
         "Consumer intelligence means studying the consumers of a category from what they leave online: what they say about products, what they search for, the brands and media they follow. It usually crosses social listening, audience intelligence and search data, to answer a market question rather than a brand question. Consumer insights are its output: what you keep from that reading to make a decision."),
        ("Elle se distingue d'une étude de marché déclarative : personne n'est interrogé, on observe ce que des consommateurs réels font et disent, en continu. Chez Licter, une étude de consumer intelligence part d'une question, par exemple pourquoi une catégorie perd des clients ou ce qu'une cible attend d'un produit, choisit les sources qui y répondent, et se termine par des recommandations.",
         "It differs from a declared market study: nobody is asked anything, we observe what real consumers do and say, continuously. At Licter, a consumer intelligence study starts from a question, for example why a category is losing customers or what a target expects from a product, picks the sources that answer it, and ends with recommendations."),
    ]),
    (("Audience intelligence et persona : quelle différence ?", "Audience intelligence and personas: what is the difference?"), [
        ("Un persona classique naît souvent en atelier : quelques entretiens, des données de vente, et ce que l'équipe croit savoir de ses clients. Il décrit une personne type, avec un âge, un métier et des motivations supposées. Utile pour aligner une équipe, il reste déclaratif, et il vieillit vite, parce que personne ne le confronte aux données.",
         "A classic persona is often born in a workshop: a few interviews, sales data, and what the team believes it knows about its customers. It describes a typical person, with an age, a job and assumed motivations. Useful to align a team, it remains declarative, and it ages fast, because nobody tests it against data."),
        ("L'audience intelligence part dans l'autre sens : du comportement observé vers le portrait. Elle ne cherche pas une cliente type, mais les groupes réels qui composent une audience, et ce qui les distingue. Par exemple, un même public peut réunir des parents pressés, des passionnés de cuisine et des sportifs, qui n'attendent pas la même chose. Des personas en sortent, mais bâtis sur des critères mesurés.",
         "Audience intelligence works the other way round: from observed behaviour to the portrait. It does not look for a typical customer, but for the real groups that make up an audience, and what sets them apart. For example, one public can bring together busy parents, cooking enthusiasts and sports fans, who do not expect the same thing. Personas come out of it, but built on measured criteria."),
        ("Charles Besson, à la tête du social listening monde chez L'Oréal, le dit à sa façon dans notre podcast Audience First : « l'advocacy est en train de dépasser l'influence ». Pour une marque, cela revient à chercher des communautés aux centres d'intérêt multiples, et les ambassadeurs qui les animent, plutôt qu'une cible définie par un seul critère.",
         "Charles Besson, head of global social listening at L'Oréal, puts it his own way in our Audience First podcast: advocacy is overtaking influence. For a brand, that means looking for communities with several interests, and the advocates who drive them, rather than a target defined by a single criterion."),
    ]),
    (("Analyse d'audience, mesure d'audience, social listening : ce qui les distingue", "Audience analysis, audience measurement, social listening: what sets them apart"), [
        ("La mesure d'audience compte : combien de personnes ont vu une émission, visité un site ou suivent un compte. Les statistiques natives des réseaux sociaux en font partie : elles décrivent vos propres abonnés, avec quelques données d'âge, de sexe et de lieu. L'analyse d'audience répond à une autre question : qui sont ces gens, et que font-ils ailleurs que chez vous ?",
         "Audience measurement counts: how many people watched a programme, visited a site or follow an account. The native analytics of social networks belong here: they describe your own followers, with some data on age, gender and location. Audience analysis answers another question: who are these people, and what do they do away from you?"),
        ("Le social listening, lui, lit ce que les gens disent d'une marque ou d'un sujet. Les deux se complètent : l'un dit ce qu'on pense de vous, l'autre qui sont les gens et ce qu'ils aiment. Une même étude les croise souvent, par exemple pour savoir ce qu'une communauté repérée dans le panel dit de votre catégorie, et avec quels mots.",
         "Social listening reads what people say about a brand or a subject. The two complement each other: one says what people think of you, the other who they are and what they like. A single study often crosses them, for example to learn what a community found in the panel says about your category, and in which words."),
    ]),
    (("Quelles données utilise une étude d'audience ?", "What data does an audience study use?"), [
        ("Le socle, c'est un panel comportemental tiré des réseaux sociaux, où 5,66 milliards d'utilisateurs actifs publient (68,7 % de la population mondiale), décrits par plus de 7 000 critères, dont les centres d'intérêt, le régime média, les affinités de marque et la sociodémographie. Ces données sont agrégées et anonymes : on lit des groupes, jamais une personne. Elles décrivent ce que les gens font déjà, sans questionnaire, donc sans biais de déclaration.",
         "The base is a behavioural panel drawn from social networks, where 5.66 billion active users post (68.7% of the world's population), described by more than 7,000 criteria, including interests, media diet, brand affinities and sociodemographics. This data is aggregated and anonymous: we read groups, never a person. It describes what people already do, with no questionnaire, and so with no declaration bias."),
        ("À ce socle s'ajoutent la conversation publique, pour savoir qui parle de vous et de votre catégorie, et la recherche, pour savoir ce que chaque communauté cherche. Vos propres données, comme un fichier clients ou une étude existante, peuvent être croisées si vous le souhaitez, mais elles ne sont pas nécessaires pour une première segmentation.",
         "On top of this base come the public conversation, to know who talks about you and your category, and search, to know what each community looks for. Your own data, such as a customer file or an existing study, can be crossed in if you wish, but it is not needed for a first segmentation."),
    ]),
    (("Comment segmenter une audience à partir de son comportement ?", "How do you segment an audience from its behaviour?"), [
        ("On part d'une audience de référence : vos clients, les abonnés de votre marque, ceux d'un concurrent, ou une population comme les 18-30 ans d'un pays. Le panel fait apparaître les groupes qui la composent, à partir de ce qu'ils suivent et consomment ensemble. On obtient en général cinq à huit communautés, assez distinctes pour qu'on puisse agir sur chacune.",
         "We start from a reference audience: your customers, your brand's followers, a competitor's, or a population such as a country's 18 to 30 year-olds. The panel brings out the groups that make it up, from what they follow and consume together. We usually get five to eight communities, distinct enough to act on each one."),
        ("Chaque communauté est ensuite mesurée. L'affinité dit à quel point elle aime votre marque ou votre catégorie. La pénétration dit quelle part d'entre elle vous touchez déjà. L'opportunité rapproche les deux : une communauté qui vous aime mais que vous touchez peu est souvent celle où le budget rapporte le plus. Le cas d'usage Segmenter vos profils cibles montre un livrable de ce type.",
         "Each community is then measured. Affinity says how much it likes your brand or your category. Penetration says what share of it you already reach. Opportunity brings the two together: a community that likes you but that you barely reach is often where the budget pays most. The use case Segment your target profiles shows a deliverable of this kind."),
        ("Un analyste lit ensuite ces groupes, les nomme et vérifie qu'ils ont un sens pour le marché. Un algorithme regroupe, il ne comprend pas pourquoi. Par exemple, une communauté de « sportifs » peut cacher des coureurs du dimanche et des triathlètes, qui n'achètent rien de la même façon et ne se parlent pas sur les mêmes réseaux.",
         "An analyst then reads these groups, names them and checks that they make sense for the market. An algorithm groups; it does not understand why. For example, a community of \"sports fans\" can hide weekend joggers and triathletes, who buy nothing the same way and do not talk on the same networks."),
    ]),
    (("Quels outils pour l'analyse d'audience ?", "Which tools for audience analysis?"), [
        # source: https://tech.eu/2022/12/05/audiense/ (Audiense acquired SoPrism, December 2022)
        ("Plusieurs familles d'outils coexistent. Les statistiques natives des réseaux décrivent vos abonnés, plateforme par plateforme. Les outils d'analyse d'audience, comme SoPrism, racheté en 2022 par Audiense, profilent n'importe quelle audience à partir de données agrégées : centres d'intérêt, affinités, géographie. Les plateformes de social listening, enfin, décrivent ceux qui parlent d'un sujet.",
         "Several families of tools exist side by side. The networks' native analytics describe your followers, platform by platform. Audience analysis tools, such as SoPrism, bought in 2022 by Audiense, profile any audience from aggregated data: interests, affinities, geography. Social listening platforms, finally, describe the people who talk about a subject."),
        ("Aucun ne suffit seul. SoPrism lit Facebook et Instagram, pas les autres réseaux, et il dit qui sont les gens, pas ce qu'ils disent. Nous le croisons donc avec une plateforme d'écoute comme Talkwalker, avec Social Blade pour suivre abonnés et vues, ou avec Meta Ads pour voir les publicités en cours des concurrents. Notre page SoPrism détaille ces limites.",
         "None is enough alone. SoPrism reads Facebook and Instagram, not the other networks, and it says who people are, not what they say. So we cross it with a listening platform such as Talkwalker, with Social Blade to follow followers and views, or with Meta Ads to see competitors' running ads. Our SoPrism page details these limits."),
    ]),
    (("Ce que l'audience intelligence permet de décider", "What audience intelligence helps you decide"), [
        ("D'abord, où mettre le budget. Une segmentation peut montrer que la cible du brief n'est pas celle où l'opportunité est la plus forte, et qu'une communauté oubliée aime déjà la marque sans l'acheter. Le choix des plateformes, des formats et des créateurs suit : on retient un créateur pour l'audience qu'il touche réellement, pas pour son nombre d'abonnés.",
         "First, where to put the budget. A segmentation can show that the brief's target is not where the opportunity is strongest, and that an overlooked community already likes the brand without buying it. The choice of platforms, formats and creators follows: a creator is picked for the audience they really reach, not for their follower count."),
        ("Ensuite, comment gagner un public nouveau. Le cas d'usage Rajeunir vos audiences compare la génération visée à la base actuelle, sujet par sujet et plateforme par plateforme, pour trouver les ponts entre les deux. Comparer vos audiences à celles d'un concurrent montre de la même façon ce qu'il touche et pas vous, et les angles pour aller chercher ces publics.",
         "Then, how to win a new public. The use case Rejuvenate your audiences compares the target generation with the current base, subject by subject and platform by platform, to find the bridges between the two. Comparing your audiences with a competitor's shows in the same way what they reach and you do not, and the angles to go after those publics."),
        ("L'audience intelligence nourrit aussi la stratégie produit. Pour HP, aux États-Unis, nous avons construit pendant six mois une segmentation hybride, croisant données de panel et données des réseaux sociaux sur plus de 5 000 critères, complétée de user stories, pour segmenter des niches de consommateurs et renforcer la stratégie produit à partir d'études existantes.",
         "Audience intelligence also feeds product strategy. For HP, in the United States, we built over six months a hybrid segmentation, crossing panel and social data on more than 5,000 criteria, completed with user stories, to segment consumer niches and strengthen product strategy from existing studies."),
    ]),
    (("Étude ponctuelle ou suivi dans le temps ?", "One-off study or ongoing tracking?"), [
        ("Une première étude répond à une question précise : qui compose notre audience, où se trouve l'opportunité, comment toucher une nouvelle génération. Une première lecture prend une dizaine de jours, du cadrage à la restitution ; une analyse d'écart complète entre deux audiences demande plutôt deux à trois semaines.",
         "A first study answers a precise question: who makes up our audience, where the opportunity lies, how to reach a new generation. A first read takes about ten days, from scoping to readout; a full gap analysis between two audiences takes more like two to three weeks."),
        ("Mais une audience bouge : de nouveaux créateurs émergent, une plateforme prend la place d'une autre, une communauté se déplace. Relire régulièrement les mêmes communautés montre si un plan média a vraiment changé quelque chose. Dans notre offre Social Insights, les études d'audience alternent avec les lectures de campagne et les benchmarks, selon les questions du trimestre.",
         "But an audience moves: new creators emerge, one platform takes another's place, a community shifts. Reading the same communities again at regular intervals shows whether a media plan really changed anything. In our Social Insights offer, audience studies alternate with campaign reads and benchmarks, driven by the questions of the quarter."),
    ]),
    (("Les limites de l'audience intelligence", "The limits of audience intelligence"), [
        ("Une étude d'audience décrit des comportements numériques. Elle lit mieux les publics actifs en ligne que ceux qui le sont peu, et certaines sources ne couvrent qu'une partie des réseaux : un outil fondé sur les données de Meta ne voit ni TikTok ni Twitch. Elle dit qui sont les gens et ce qu'ils aiment, pas pourquoi ils achètent ou renoncent à acheter.",
         "An audience study describes digital behaviour. It reads publics that are active online better than those that are not, and some sources cover only part of the networks: a tool built on Meta's data sees neither TikTok nor Twitch. It says who people are and what they like, not why they buy or give up buying."),
        ("Elle travaille sur des groupes, jamais sur des individus : c'est une garantie pour la vie privée, et une limite pour qui voudrait viser une personne précise. Enfin, un regroupement statistique sans lecture reste un tableau. C'est pourquoi nous croisons l'audience intelligence avec le social listening, la recherche ou vos études existantes.",
         "It works on groups, never on individuals: that protects privacy, and it is a limit for anyone who would want to target one specific person. Finally, a statistical grouping without a reading remains a table. That is why we cross audience intelligence with social listening, search or your existing studies."),
    ]),
    (("Agence ou cabinet d'audience intelligence : ce que vous achetez", "Audience intelligence agency or consultancy: what you buy"), [
        ("Avec une agence ou un cabinet d'audience intelligence, vous n'achetez pas un accès à un outil de profilage, mais une réponse à une question de marketing. Le choix des sources, la définition des audiences à comparer, la lecture des communautés et la recommandation sont pris en charge par des consultants, qui lisent eux-mêmes ce qu'ils ont configuré.",
         "With an audience intelligence agency or consultancy, you do not buy access to a profiling tool, but an answer to a marketing question. The choice of sources, the definition of the audiences to compare, the reading of the communities and the recommendation are handled by consultants, who read for themselves what they have set up."),
        ("Licter est un cabinet indépendant de social data intelligence : nous opérons SoPrism et 18 autres outils sans en être l'éditeur, et nous choisissons la source selon la question. Pour un marché étranger, la lecture est confiée à des analystes qui parlent la langue et connaissent le marché. Le plus simple pour commencer : le flash Audience listening offert sur votre marque.",
         "Licter is an independent social data intelligence consultancy: we run SoPrism and 18 other tools without being their publisher, and we pick the source by the question. For a foreign market, the reading goes to analysts who speak the language and know the market. The simplest way to start: the free Audience listening flash on your brand."),
    ]),
]
# source: https://help.audiense.com/knowledge/audiense-data-sources
# source: https://www.cnil.fr/fr/reglement-europeen-protection-donnees/chapitre2
# source: https://www.cnil.fr/fr/les-bases-legales/interet-legitime
# source: https://www.cnil.fr/fr/recommandations-reutilisateurs-donnees-internet
# source: https://datareportal.com/reports/digital-2026-two-in-three-people-use-social-media
