#!/usr/bin/env python3
"""The home page in both languages, for search engines.

    python3 tools/build-home.py

index.html is the English home ("/") and stays the file you edit. This
script
  1. writes its SEO head (title, description, canonical, hreflang, Open
     Graph, structured data) between the <!-- seo --> markers;
  2. generates the French home, /fr/index.html, with its text translated in
     the HTML itself (js/fr.js), so Google indexes the French too.

Run it after any change to index.html or js/fr.js. tools/build-usecases.py
runs it at the end, so one command rebuilds every generated page.
"""
import html, importlib.util, json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location("ucb", ROOT / "tools" / "build-usecases.py")
U = importlib.util.module_from_spec(spec)
spec.loader.exec_module(U)

SITE = U.SITE
FR, EN = 0, 1

SEO = {
    # one positioning sentence everywhere (title, description, schema, why-licter, LinkedIn)
    "title": ("Cabinet de conseil en social data intelligence | Licter",
              "Social data intelligence consultancy | Licter"),
    "desc": ("Licter est un cabinet de conseil en social data intelligence fondé à Paris en 2022 : social listening, audiences et veille, lus par des consultants.",
             "Licter is a social data intelligence consultancy founded in Paris in 2022: social listening, audiences and monitoring, read by consultants."),
    "og_alt": ("Licter, cabinet de conseil en social data intelligence", "Licter, the social data intelligence consultancy"),
}
PATH = ("/fr/", "/")
SAME_AS = ["https://www.linkedin.com/company/licter/", "https://www.instagram.com/licter_listening/",
           "https://www.youtube.com/@audience_first"]


def faq(src, lang):
    out = []
    for q, a in re.findall(r"<details>\s*<summary>(.*?)</summary>\s*<p>(.*?)</p>\s*</details>", src, re.S):
        q = re.sub(r"\s+", " ", html.unescape(q)).strip()
        a = re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", "", a))).strip()
        if lang == FR:
            q, a = U.DICT.get(q, q), U.DICT.get(a, a)
        out.append({"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": a}})
    return out


def head(lang, src):
    v = U.version()
    t, d = U.typo(SEO["title"][lang], lang), U.typo(SEO["desc"][lang], lang)
    org = {"@type": "Organization", "@id": SITE + "/#org", "name": "Licter", "url": SITE + "/",
           "logo": SITE + "/assets/img/logo-navy.png", "sameAs": SAME_AS,
           "description": d,
           "founder": [{"@type": "Person", "name": "Adrien Krebs"},
                       {"@type": "Person", "name": "Antoine Khaitrine", "sameAs": "https://www.thesilab.com/insider-50/antoine-khaitrine"}],
           "knowsLanguage": ["fr", "en", "zh", "es", "hi", "yue", "ar"],
           "areaServed": "Worldwide"}
    ld = [
        {"@context": "https://schema.org", **org},
        {"@context": "https://schema.org", "@type": "WebSite", "@id": SITE + "/#website", "name": "Licter", "url": SITE + "/",
         "inLanguage": ["fr", "en"], "publisher": {"@id": SITE + "/#org"}},
        {"@context": "https://schema.org", "@type": "WebPage", "name": t, "description": d, "url": SITE + PATH[lang],
         "inLanguage": U.LANGS[lang], "isPartOf": {"@id": SITE + "/#website"}, "about": {"@id": SITE + "/#org"},
         "dateModified": U.TODAY.isoformat()},
        {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faq(src, lang)},
    ]
    ld_tags = "\n".join('<script type="application/ld+json">%s</script>' % json.dumps(x, ensure_ascii=False) for x in ld)
    img = "%s/assets/img/og/home-%s.png" % (SITE, U.LANGS[lang])
    return f'''<!-- seo: generated by tools/build-home.py -->
<title>{U.esc(t)}</title>
<meta name="description" content="{U.esc(d)}" />
<link rel="canonical" href="{SITE}{PATH[lang]}" />
<link rel="alternate" hreflang="fr" href="{SITE}/fr/" />
<link rel="alternate" hreflang="en" href="{SITE}/" />
<link rel="alternate" hreflang="x-default" href="{SITE}/" />
<meta name="robots" content="index, follow, max-image-preview:large" />
<meta property="og:site_name" content="Licter" />
<meta property="og:type" content="website" />
<meta property="og:locale" content="{'fr_FR' if lang == FR else 'en_GB'}" />
<meta property="og:locale:alternate" content="{'en_GB' if lang == FR else 'fr_FR'}" />
<meta property="og:url" content="{SITE}{PATH[lang]}" />
<meta property="og:title" content="{U.esc(t)}" />
<meta property="og:description" content="{U.esc(d)}" />
<meta property="og:image" content="{img}" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />
<meta property="og:image:alt" content="{U.esc(SEO['og_alt'][lang])}" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="{U.esc(t)}" />
<meta name="twitter:description" content="{U.esc(d)}" />
<meta name="twitter:image" content="{img}" />
<link rel="preload" href="/assets/fonts/AiglonProWide-Demi.woff2?v={v}" as="font" type="font/woff2" crossorigin />
<link rel="preload" href="/assets/fonts/Raleway-latin.woff2" as="font" type="font/woff2" crossorigin />
<link rel="preconnect" href="https://i.ytimg.com" />
{ld_tags}
<!-- /seo -->'''


SLOTS = {
    "families": re.compile(r"<!-- home-families -->.*?<!-- /home-families -->", re.S),
    "compare": re.compile(r"<!-- home-compare -->.*?<!-- /home-compare -->", re.S),
}


def fill(src, lang):
    """the four families and, further down, the comparison with a tool: the
    same blocks as the use-cases hub, in the page's language"""
    src = SLOTS["families"].sub(lambda m: "<!-- home-families -->\n%s\n  <!-- /home-families -->" % U.families(lang), src, count=1)
    return SLOTS["compare"].sub(lambda m: "<!-- home-compare -->\n%s\n  <!-- /home-compare -->" % U.compare(lang), src, count=1)


def main():
    src = (ROOT / "index.html").read_text()
    src = fill(src, EN)

    # --- 1. the English home: its SEO head, static English, no dictionary
    src = re.sub(r"\s*<!-- seo: generated.*?<!-- /seo -->", "", src, flags=re.S)
    src = re.sub(r"\s*<title>.*?</title>", "", src, flags=re.S)
    for pat in (r'<meta name="description"[^>]*/>', r'<meta property="og:[^"]+"[^>]*/>', r'<meta name="twitter:[^"]+"[^>]*/>',
                r'<link rel="canonical"[^>]*/>', r'<link rel="alternate"[^>]*/>', r'<meta name="robots"[^>]*/>',
                r'<link rel="preload"[^>]*as="font"[^>]*/>', r'<link rel="preconnect" href="https://i\.ytimg\.com"[^>]*/>'):
        src = re.sub(r"\s*" + pat, "", src)
    src = src.replace('<meta name="viewport" content="width=device-width, initial-scale=1" />',
                      '<meta name="viewport" content="width=device-width, initial-scale=1" />\n' + head(EN, src), 1)
    src = re.sub(r'<html[^>]*>', '<html lang="en" data-i18n-static data-alt-fr="/fr/" data-alt-en="/">', src, count=1)
    # links to the use-case pages: English here, the French one kept for the French home
    src = re.sub(r'href="(/fr/cas-usage/[^"]*)" data-en="([^"]*)"', r'href="\2" data-fr="\1"', src)
    # the English page needs no dictionary
    src = re.sub(r'\s*<script src="(?:/)?js/fr\.js[^"]*"(?: defer)?></script>', "", src)
        # no automatic redirect by language (Google advises against it): the
    # hreflang tags send French searchers to /fr/, and a French browser that
    # lands here is offered the French site in a banner (js/ui.js)
    redirect = ""
    src = re.sub(r"\s*<script>\(function\(\)\{try\{var l=localStorage\.getItem\(\"licter-lang\"\).*?</script>", "", src, flags=re.S)
    (ROOT / "index.html").write_text(src)

    # --- 2. the French home, generated
    fr = src
    fr = re.sub(r"<!-- seo: generated.*?<!-- /seo -->", head(FR, src), fr, flags=re.S)
    fr = re.sub(r'<html[^>]*>', '<html lang="fr" data-i18n-static data-alt-fr="/fr/" data-alt-en="/">', fr, count=1)
    fr = re.sub(r'href="([^"]*)" data-fr="([^"]*)"', r'href="\2"', fr)
    fr = fr.replace('href="index.html"', 'href="/fr/"')
    fr = re.sub(r'href="index\.html#', 'href="/fr/#', fr)
    # every relative path made absolute, from the sub-folder
    fr = re.sub(r'(href|src)="(?!https?:|/|#|mailto:|data:)([^"]+)"', r'\1="/\2"', fr)
    fr = re.sub(r'srcset="([^"]+)"', lambda m: 'srcset="%s"' % ", ".join(
        (p if p.startswith(("/", "http")) else "/" + p) for p in (x.strip() for x in m.group(1).split(","))), fr)
    # the dictionary, before the switch
    v = U.version()
    fr = re.sub(r'(\s*)<script src="/js/i18n\.js', r'\1<script src="/js/fr.js?v=%s" defer></script>\1<script src="/js/i18n.js' % v, fr, count=1)
    # the visible text, in French, in the HTML itself
    b0, b1 = fr.index("<body"), fr.index("</body>")
    body = U.translate(fr[b0:b1])
    body = body.replace(">Skip to content<", ">Aller au contenu<")
    fr = fr[:b0] + body + fr[b1:]
    fr = fill(fr, FR)
    fr = fr.replace("<!-- seo: generated by tools/build-home.py -->",
                    "<!-- Generated by tools/build-home.py from index.html: edit that file, not this one. -->\n<!-- seo -->", 1)
    out = ROOT / "fr" / "index.html"
    out.parent.mkdir(exist_ok=True)
    out.write_text(fr)
    print("home: / (en) and /fr/ (fr) written")


if __name__ == "__main__":
    main()
