"""The long-form section of the ChatGPT tool page (SEO audit: the page was
too short for "veille ChatGPT marque", "ce que ChatGPT dit de ma marque",
"suivre les mentions de marque dans ChatGPT"): how to find out what ChatGPT
says about a brand, why its answers vary, where it gets what it knows, the
difference web search makes, which questions to ask and how often, what to do
about false or outdated information, competitors, the other assistants, and
what an audit delivers. Each block is (heading, [paragraphs]), every string a
(French, English) pair. Licter statements come from the site's own pages
(fr/outils/chatgpt, fr/outils/geo, fr/expertise/ai-listening,
tools/tools_data.py, tools/ai_engines.py); public facts about ChatGPT carry a
`# source:` comment."""

KICKER = ("VOTRE MARQUE DANS CHATGPT, EN DÉTAIL", "YOUR BRAND IN CHATGPT, IN DETAIL")
TITLE = ("Votre marque dans ChatGPT : audit des réponses", "Your brand in ChatGPT: an audit of its answers")

BLOCKS = [
    (("Comment savoir ce que ChatGPT dit de ma marque ?", "How do I find out what ChatGPT says about my brand?"), [
        ("Pour savoir ce que ChatGPT dit de votre marque, il faut lui poser les questions que posent vos clients, pas seulement votre nom. « Que penser de cette marque ? » compte, mais « quelle marque choisir pour ce besoin ? » compte davantage : c'est là qu'il recommande, compare et écarte. Une question posée une seule fois ne permet aucune conclusion.",
         "To find out what ChatGPT says about your brand, you have to ask it the questions your customers ask, not just your name. \"What do you think of this brand?\" matters, but \"which brand should I choose for this need?\" matters more: that is where it recommends, compares and rules out. A question asked only once supports no conclusion."),
        ("Il faut ensuite relever ce qui revient : les marques citées et leur ordre, les qualités et les défauts attribués, les sources affichées quand il cherche sur le web. C'est ce relevé, répété et comparé, qui permet de suivre les mentions de votre marque dans ChatGPT. Une capture d'écran isolée montre une réponse possible, pas ce que voient la plupart de vos clients.",
         "You then need to record what comes back: the brands cited and their order, the strengths and weaknesses attributed, the sources shown when it searches the web. This record, repeated and compared, is what lets you track your brand's mentions in ChatGPT. A single screenshot shows one possible answer, not what most of your customers see."),
    ]),
    (("Pourquoi ChatGPT ne donne pas toujours la même réponse", "Why ChatGPT does not always give the same answer"), [
        ("ChatGPT ne donne pas toujours la même réponse, parce qu'il rédige chaque réponse au moment où on la lui demande. Deux essais sur la même question peuvent citer d'autres marques, dans un autre ordre, avec d'autres nuances. La formulation compte aussi : un mot de plus ou de moins suffit parfois à changer la recommandation.",
         "ChatGPT does not always give the same answer, because it writes each answer at the moment it is asked. Two tries on the same question can cite other brands, in another order, with other nuances. Wording matters too: one word more or less is sometimes enough to change the recommendation."),
        # source: https://help.openai.com/en/articles/8590148-memory-faq (memory: saved memories and chat history are used to personalise responses; can be turned off in Settings > Personalization)
        ("La réponse dépend aussi de la personne qui pose la question. Quand la mémoire est activée, ChatGPT tient compte des informations enregistrées et des conversations passées pour personnaliser ce qu'il répond. Pour savoir ce que voit un client qui découvre votre catégorie, mieux vaut interroger l'assistant sans historique ni mémoire.",
         "The answer also depends on who asks. When memory is turned on, ChatGPT takes saved information and past conversations into account to personalise what it answers. To know what a customer discovering your category sees, it is better to question the assistant with no history and no memory."),
        ("Enfin, l'assistant lui-même change : nouveaux modèles, nouvelles fonctions, nouvelles pages lues. Une réponse relevée au printemps ne dit pas ce qu'il répond à l'automne. C'est pourquoi on mesure une tendance sur plusieurs essais et plusieurs mois, plutôt qu'une phrase relevée une fois et commentée comme un verdict.",
         "Finally, the assistant itself changes: new models, new features, new pages read. An answer recorded in spring does not say what it answers in autumn. That is why you measure a trend over several tries and several months, rather than a sentence recorded once and discussed as a verdict."),
    ]),
    (("D'où ChatGPT tire ce qu'il sait d'une marque", "Where ChatGPT gets what it knows about a brand"), [
        ("Ce que ChatGPT sait d'une marque vient de deux endroits. D'abord ses données d'entraînement : une grande quantité de textes publics, arrêtée à une date. Ensuite, quand il cherche sur le web, les pages qu'il lit au moment de répondre. La première source explique ce qu'il croit savoir, la seconde ce qu'il vérifie ou corrige.",
         "What ChatGPT knows about a brand comes from two places. First its training data: a large body of public texts, frozen at a date. Then, when it searches the web, the pages it reads at the moment of answering. The first source explains what it thinks it knows, the second what it checks or corrects."),
        # source: https://developers.openai.com/api/docs/bots (GPTBot crawls content that may be used to train models; OAI-SearchBot surfaces sites in ChatGPT search; the two robots.txt settings are independent)
        ("OpenAI distingue deux robots d'exploration. GPTBot collecte des contenus qui peuvent servir à entraîner ses modèles ; OAI-SearchBot sert à faire apparaître des sites dans la recherche de ChatGPT. Les deux se règlent séparément dans le fichier robots.txt d'un site : bloquer l'un ne bloque pas l'autre.",
         "OpenAI distinguishes two crawlers. GPTBot collects content that may be used to train its models; OAI-SearchBot is used to show sites in ChatGPT's search. The two are set separately in a site's robots.txt file: blocking one does not block the other."),
        ("Dans les deux cas, ChatGPT ne lit pas une fiche officielle de votre marque. Il reprend ce que d'autres ont écrit : votre site, la presse, les comparatifs, les forums, les avis. Une marque peu documentée sera décrite à partir de peu de choses, parfois d'une seule page ancienne que personne n'a mise à jour.",
         "In both cases, ChatGPT does not read an official profile of your brand. It picks up what others have written: your site, the press, comparison articles, forums, reviews. A poorly documented brand will be described from very little, sometimes from a single old page nobody has updated."),
    ]),
    (("Avec ou sans recherche web : deux réponses différentes", "With or without web search: two different answers"), [
        # source: https://techcrunch.com/snippet/2932195/openai-brings-search-to-all-users/ (16 December 2024: search, paid-only since its October launch, now available to free users)
        # source: https://seroundtable.com/chatgpt-search-open-38588.html (December 2024: ChatGPT search opened to all logged-in users)
        # source: https://help.openai.com/en/articles/9237897-chatgpt-search (ChatGPT searches automatically when a question may benefit from it; users can also trigger search manually; answers show inline citations or a Sources panel)
        ("Avec ou sans recherche web, ChatGPT ne répond pas de la même façon. La recherche, lancée fin octobre 2024 pour les abonnés, a été ouverte aux utilisateurs gratuits connectés en décembre de la même année. L'assistant décide seul de chercher quand la question s'y prête, et l'utilisateur peut aussi la déclencher lui-même.",
         "With or without web search, ChatGPT does not answer the same way. Search, launched at the end of October 2024 for subscribers, was opened to logged-in free users in December of the same year. The assistant decides on its own to search when the question calls for it, and users can also trigger it themselves."),
        ("Quand il cherche, il affiche ses sources, en lien dans le texte ou dans un panneau à part. On voit alors quelles pages pèsent sur la réponse. Sans recherche, il n'y a pas de source à lire : il faut deviner d'où vient l'image de la marque, à partir de ce qu'il dit et des erreurs qu'il commet.",
         "When it searches, it shows its sources, as links in the text or in a separate panel. You can then see which pages weigh on the answer. Without search, there is no source to read: you have to infer where the brand's image comes from, based on what it says and the mistakes it makes."),
        ("C'est pourquoi nous posons chaque question dans les deux modes. L'écart entre les deux réponses montre ce qui est daté dans sa mémoire : un ancien nom, une gamme arrêtée, un prix qui a changé. Il montre aussi quelles pages il va chercher aujourd'hui pour corriger, ou confirmer, ce qu'il pense savoir.",
         "That is why we ask each question in both modes. The gap between the two answers shows what is outdated in its memory: an old name, a discontinued range, a price that has changed. It also shows which pages it goes to today to correct, or confirm, what it thinks it knows."),
    ]),
    (("Quelles questions poser, et combien de fois", "Which questions to ask, and how many times"), [
        ("Les questions à poser à ChatGPT se construisent à partir de celles de vos clients, pas de vos mots-clés internes. On en distingue trois familles : les questions de choix, du type « quelle marque pour ce besoin ? », les questions sur la marque elle-même (avis, prix, fiabilité, engagements) et les comparaisons avec un concurrent nommé.",
         "The questions to ask ChatGPT are built from your customers' questions, not from your internal keywords. There are three families: choice questions, such as \"which brand for this need?\", questions about the brand itself (reviews, price, reliability, commitments) and comparisons with a named competitor."),
        ("Le vocabulaire des clients se lit ailleurs : dans les recherches qu'ils tapent, dans ce qu'ils publient sur les réseaux, dans les avis. C'est là que l'audit rejoint le search listening et le social listening. Une question que personne ne pose n'a pas d'intérêt, même si la réponse de l'assistant est flatteuse.",
         "Customers' vocabulary is read elsewhere: in the searches they type, in what they post on social networks, in reviews. That is where the audit meets search listening and social listening. A question nobody asks is of no interest, even if the assistant's answer is flattering."),
        ("Chaque question est posée plusieurs fois, puis les réponses sont comparées : ce qui revient à chaque essai compte plus que ce qui apparaît une fois. Le même panel est ensuite reposé chaque mois, avec les mêmes formulations, pour que les écarts viennent de l'assistant et non de la façon de demander.",
         "Each question is asked several times, then the answers are compared: what comes back on every try counts more than what appears once. The same panel is then asked again every month, with the same wording, so that the differences come from the assistant and not from the way of asking."),
    ]),
    (("Que faire d'une information fausse ou datée", "What to do about false or outdated information"), [
        ("Une information fausse ou datée dans ChatGPT ne se corrige pas en reformulant la question. Personne ne contrôle la réponse d'une IA, et l'on ne peut pas la modifier directement. On agit en amont, sur les sources publiques qui la nourrissent, puis on mesure si la réponse change dans les semaines et les mois qui suivent.",
         "False or outdated information in ChatGPT is not fixed by rewording the question. Nobody controls an AI's answer, and it cannot be changed directly. You act upstream, on the public sources that feed it, then measure whether the answer changes in the weeks and months that follow."),
        ("La première étape consiste à trouver d'où vient l'erreur. Quand ChatGPT cherche sur le web, ses sources le disent souvent : un article ancien, un comparatif jamais mis à jour, une fiche erronée. Sans recherche, on remonte aux pages publiques qui répètent la même information, et on regarde lesquelles font autorité.",
         "The first step is to find where the error comes from. When ChatGPT searches the web, its sources often tell you: an old article, a comparison never updated, a wrong listing. Without search, you trace back to the public pages that repeat the same information, and look at which ones carry authority."),
        # source: https://help.openai.com/en/articles/12627856-publishers-and-developers-faq (any public website can appear in ChatGPT search; sites should not block OAI-SearchBot to be included)
        ("Il faut ensuite corriger ou compléter ces sources : votre site d'abord, avec une information claire et à jour, puis la presse et les pages de référence. OpenAI indique qu'un site public peut apparaître dans la recherche de ChatGPT s'il ne bloque pas OAI-SearchBot : un réglage à vérifier avec vos équipes techniques. C'est le terrain du GEO.",
         "You then need to correct or complete these sources: your site first, with clear and current information, then the press and reference pages. OpenAI states that a public site can appear in ChatGPT search if it does not block OAI-SearchBot: a setting to check with your technical teams. This is the ground of GEO."),
    ]),
    (("Suivre ses concurrents dans les réponses", "Tracking your competitors in the answers"), [
        ("Suivre ses concurrents dans les réponses de ChatGPT, c'est regarder qui il recommande quand votre nom n'est pas dans la question. Sur les questions de choix, il cite en général quelques marques, dans un certain ordre, avec une raison pour chacune. Ces raisons disent comment il résume votre catégorie.",
         "Tracking your competitors in ChatGPT's answers means looking at whom it recommends when your name is not in the question. On choice questions, it usually cites a few brands, in a certain order, with a reason for each. These reasons say how it sums up your category."),
        ("La comparaison porte sur la fréquence des citations, l'ordre, les qualités associées à chaque marque et les sources mobilisées. Un concurrent cité plus souvent que vous l'est rarement par hasard : il est mieux documenté, plus présent dans la presse ou les comparatifs. Le suivi mensuel montre aussi les nouvelles marques qui apparaissent.",
         "The comparison covers how often each brand is cited, the order, the qualities attached to each brand and the sources used. A competitor cited more often than you rarely is by chance: it is better documented, more present in the press or in comparison articles. Monthly tracking also shows the new brands that appear."),
    ]),
    (("ChatGPT et les autres assistants", "ChatGPT and the other assistants"), [
        ("ChatGPT n'est pas le seul assistant que vos clients interrogent. Gemini s'appuie sur la recherche Google, Perplexity cherche sur le web à chaque question et affiche ses sources, Claude répond d'abord depuis ses données d'entraînement, Grok lit les publications de X. Sur une même question, ils ne citent pas toujours les mêmes marques.",
         "ChatGPT is not the only assistant your customers ask. Gemini relies on Google Search, Perplexity searches the web for every question and shows its sources, Claude answers first from its training data, Grok reads posts on X. On the same question, they do not always cite the same brands."),
        ("Un audit limité à ChatGPT donne donc une vue partielle. Selon votre marché et vos clients, nous définissons avec vous les assistants à interroger, toujours avec les mêmes questions, pour comparer leurs réponses et repérer les sources qu'ils partagent. Une source reprise par plusieurs assistants mérite d'être traitée en priorité.",
         "An audit limited to ChatGPT therefore gives a partial view. Depending on your market and your customers, we define with you which assistants to question, always with the same questions, to compare their answers and spot the sources they share. A source picked up by several assistants deserves to be handled first."),
    ]),
    (("Ce qu'un audit livre concrètement", "What an audit actually delivers"), [
        ("Un audit des réponses de ChatGPT livre d'abord un état des lieux : les questions clés de votre catégorie, ce que répond l'assistant, votre place face aux concurrents et les erreurs à corriger. Chaque constat est rattaché aux réponses relevées et, quand elles existent, aux sources citées par l'assistant.",
         "An audit of ChatGPT's answers first delivers an inventory: your category's key questions, what the assistant answers, your place against competitors and the errors to correct. Each finding is tied to the answers recorded and, when they exist, to the sources the assistant cited."),
        ("Il livre ensuite un plan d'action : les contenus qui manquent, les sources à renforcer, les messages à clarifier. Licter ne produit pas ces contenus ; vos équipes ou vos agences s'en chargent. Un suivi régulier reprend les mêmes questions chaque mois pour voir ce qui a bougé, sans promesse de résultat : on agit sur les sources, et on mesure l'effet.",
         "It then delivers an action plan: missing content, sources to strengthen, messages to clarify. Licter does not produce this content; your teams or your agencies do. Regular tracking asks the same questions every month to see what has moved, with no promise of results: you act on the sources, and measure the effect."),
        ("Un audit ne dit pas tout. Il montre ce que l'assistant répond, pas combien de personnes lui posent ces questions : pour l'estimer, on le croise avec le search listening. Et ce que dit ChatGPT ne remplace pas ce que disent vos clients eux-mêmes : la conversation sur les réseaux se lit avec l'écoute sociale.",
         "An audit does not tell everything. It shows what the assistant answers, not how many people ask it these questions: to estimate that, it is crossed with search listening. And what ChatGPT says does not replace what your customers say themselves: the conversation on social networks is read through social listening."),
    ]),
]
