"""The long-form section of the Claude tool page (SEO audit: the page was too
short, about 550 words, for "agence Claude", "ce que Claude dit de ma marque",
"Claude marque IA"): how to find out what Claude says about a brand, the
difference web search makes, where Claude gets what it knows, why it sometimes
says it does not know, who uses it, Anthropic's crawlers, what to do when it
is wrong or silent about a brand, and what tracking delivers. Each block is
(heading, [paragraphs]), every string a (French, English) pair. Licter
statements come from the site's own pages (fr/outils/claude,
fr/expertise/ai-listening, tools/tools_data.py, tools/ai_engines.py, and the
method wording of tools/chatgpt_guide.py and tools/geo_guide.py); public facts
about Claude and Anthropic carry a `# source:` comment."""

KICKER = ("CLAUDE, EN DÉTAIL", "CLAUDE, IN DETAIL")
TITLE = ("Claude et votre marque : ce qu'il sait, ce qu'il cherche", "Claude and your brand: what it knows, what it looks up")

BLOCKS = [
    (("Comment savoir ce que Claude dit de ma marque ?", "How do I find out what Claude says about my brand?"), [
        ("Pour savoir ce que Claude dit de votre marque, il faut l'interroger comme le feraient vos clients, et en particulier vos clients professionnels. On lui pose des questions de choix, des questions sur la marque elle-même et des comparaisons avec un concurrent nommé. C'est sur les questions de choix qu'il recommande et écarte. Chaque question est posée plusieurs fois : une réponse isolée ne permet aucune conclusion.",
         "To find out what Claude says about your brand, you have to question it the way your customers would, and your business customers in particular. You ask it choice questions, questions about the brand itself and comparisons with a named competitor. It is on choice questions that it recommends and rules out. Each question is asked several times: a single answer supports no conclusion."),
        # source: https://claude.com/blog/memory (11 September 2025: memory for Team and Enterprise; 23 October 2025 update: extended to Pro and Max; incognito chat available to all users, not saved to history or memory)
        ("La réponse dépend aussi du compte qui pose la question. Depuis septembre 2025, Claude peut garder en mémoire les projets et les préférences de ses utilisateurs, d'abord sur les offres Team et Enterprise. Le mode incognito, ouvert à tous, repart d'une page blanche : c'est ce qui se rapproche le plus du regard d'un client qui découvre votre catégorie.",
         "The answer also depends on the account asking. Since September 2025, Claude can remember its users' projects and preferences, first on the Team and Enterprise plans. Incognito mode, open to everyone, starts from a blank page: it is the closest thing to the view of a customer discovering your category."),
    ]),
    (("Claude avec et sans recherche web", "Claude with and without web search"), [
        # source: https://claude.com/blog/web-search (20 March 2025: web search in feature preview for all paid Claude users in the United States, with direct citations; 27 May 2025 update: "Web search is now available globally on all Claude plans")
        ("Claude avec et sans recherche web, ce sont deux sources de réponse distinctes. La recherche a été lancée en mars 2025 pour les abonnés payants aux États-Unis, puis ouverte à toutes les offres, partout dans le monde, en mai 2025. Quand il cherche, Claude cite les pages qu'il a lues : on voit alors d'où vient ce qu'il affirme. Sans recherche, aucune source n'est affichée.",
         "Claude with and without web search are two distinct sources of answers. Search was launched in March 2025 for paying subscribers in the United States, then opened to all plans, worldwide, in May 2025. When it searches, Claude cites the pages it read: you can then see where what it states comes from. Without search, no source is shown."),
        # source: https://support.claude.com/en/articles/10684626-enable-and-use-web-search (web search toggle in the chat menu; "If you have the new Claude experience, there's no web search toggle. Claude searches the web when it helps."; on Team and Enterprise, an Owner or Primary Owner must first enable web search for the workspace)
        ("Selon l'interface, la recherche s'active à la main, ou Claude la lance seul quand elle lui semble utile. Sur les offres Team et Enterprise, un administrateur doit d'abord l'autoriser pour toute l'organisation. Un acheteur peut donc interroger Claude sans recherche web et n'obtenir qu'une réponse de mémoire. C'est pourquoi nous posons chaque question dans les deux modes : l'écart montre ce qui est daté dans sa mémoire.",
         "Depending on the interface, search is turned on by hand, or Claude starts it on its own when it seems useful. On the Team and Enterprise plans, an administrator must first allow it for the whole organisation. A buyer can therefore question Claude without web search and get an answer from memory only. That is why we ask each question in both modes: the gap shows what is outdated in its memory."),
    ]),
    (("D'où Claude tire ce qu'il sait d'une marque", "Where Claude gets what it knows about a brand"), [
        # source: https://www.anthropic.com/transparency (training data: a proprietary mix of publicly available information from the internet, public and private datasets, and other sources such as synthetic data)
        # source: https://privacy.claude.com/en/articles/7996885-how-do-you-use-personal-data-in-model-training ("we do not access password protected pages or bypass CAPTCHA controls")
        ("Ce que Claude sait d'une marque sans chercher vient de ses données d'entraînement. Anthropic les décrit comme un mélange d'informations publiques sur internet, de jeux de données publics et privés, et d'autres sources. L'entreprise indique ne pas accéder aux pages protégées par un mot de passe : un espace client ou un document réservé n'y entre pas par ce biais.",
         "What Claude knows about a brand without searching comes from its training data. Anthropic describes it as a mix of public information on the internet, public and private datasets, and other sources. The company states that it does not access password-protected pages: a customer area or a restricted document does not get in that way."),
        # source: https://platform.claude.com/docs/en/about-claude/models/overview ("Reliable knowledge cutoff: The date through which the model's knowledge is most extensive and reliable. Training data cutoff ... is the broader range of data used.")
        ("Ces données s'arrêtent à une date. Pour chaque modèle, Anthropic publie une date de fiabilité des connaissances : celle jusqu'à laquelle ce qu'il sait est le plus complet et le plus sûr. Après cette date, ce qu'il sait est plus partiel. Un changement de nom, un nouveau produit ou un rachat récent peuvent donc lui échapper tant qu'il ne cherche pas sur le web.",
         "This data stops at a date. For each model, Anthropic publishes a reliable knowledge cutoff: the date up to which what it knows is most complete and most reliable. After that date, what it knows is more partial. A name change, a new product or a recent acquisition can therefore escape it as long as it does not search the web."),
    ]),
    (("Pourquoi Claude répond parfois « je ne sais pas »", "Why Claude sometimes answers \"I don't know\""), [
        # source: https://www.anthropic.com/constitution (honesty, "Calibrated": Claude "acknowledges its own uncertainty or lack of knowledge when relevant, and avoids conveying beliefs with more or less confidence than it actually has")
        ("Claude répond parfois « je ne sais pas », et ce n'est pas un hasard. Les principes publiés par Anthropic pour guider son comportement lui demandent de reconnaître son incertitude ou son manque de connaissances quand c'est le cas, sans montrer plus ou moins d'assurance qu'il n'en a. Face à une marque peu documentée, il dit souvent qu'il ne la connaît pas.",
         "Claude sometimes answers \"I don't know\", and that is no accident. The principles Anthropic published to guide its behaviour ask it to acknowledge its uncertainty or lack of knowledge when that is the case, without showing more or less confidence than it has. Faced with a poorly documented brand, it often says it does not know it."),
        # source: https://platform.claude.com/docs/en/test-and-evaluate/strengthen-guardrails/reduce-hallucinations ("Even the most advanced language models, like Claude, can sometimes generate text that is factually incorrect")
        ("Pour une marque, cela change la nature du risque. Sur Claude, une marque mal documentée est plus souvent absente que mal décrite. Une absence ne fait pas de bruit, mais elle compte : un concurrent mieux documenté est cité à votre place. Les erreurs restent possibles, Anthropic le reconnaît dans sa documentation : il faut donc vérifier les deux, l'oubli et l'information fausse.",
         "For a brand, this changes the nature of the risk. On Claude, a poorly documented brand is more often missing than misdescribed. An absence makes no noise, but it counts: a better documented competitor is cited in your place. Errors remain possible, as Anthropic acknowledges in its documentation: so you need to check both, the omission and the false information."),
    ]),
    (("Qui utilise Claude, et pourquoi cela compte", "Who uses Claude, and why it matters"), [
        # source: https://www.anthropic.com/news/the-anthropic-economic-index (10 February 2025: about one million anonymised Claude.ai conversations analysed; computer and mathematical tasks first, then arts and media, mostly writing and editing)
        # source: https://claude.com/blog/claude-for-enterprise (September 2024: Claude Enterprise plan, with company knowledge uploaded as documents, SSO and role-based permissions)
        ("Claude est surtout utilisé pour travailler. En février 2025, Anthropic a publié l'analyse d'environ un million de conversations anonymisées : les tâches informatiques arrivaient en tête, devant l'écriture et l'édition. Depuis 2024, Anthropic propose aussi une offre Enterprise pour les organisations, avec des documents internes partagés et des droits d'accès par rôle.",
         "Claude is mostly used for work. In February 2025, Anthropic published the analysis of about one million anonymised conversations: computing tasks came first, ahead of writing and editing. Since 2024, Anthropic has also offered an Enterprise plan for organisations, with shared internal documents and role-based access rights."),
        ("C'est ce qui distingue Claude pour une marque. Il sert à rédiger, analyser et préparer des décisions : ses réponses touchent des acheteurs, des analystes, des journalistes. Une note d'achat ou une étude de marché préparée avec lui peut reprendre ce qu'il dit de vous, sans que vous le sachiez. Votre place dans ses réponses pèse donc sur des décideurs.",
         "That is what sets Claude apart for a brand. It is used to write, analyse and prepare decisions: its answers reach buyers, analysts and journalists. A purchasing memo or a market study prepared with it can repeat what it says about you, without your knowing. Your place in its answers therefore weighs on decision makers."),
    ]),
    (("ClaudeBot, Claude-SearchBot, Claude-User : les robots d'Anthropic", "ClaudeBot, Claude-SearchBot, Claude-User: Anthropic's crawlers"), [
        # source: https://support.claude.com/en/articles/8896518-does-anthropic-crawl-data-from-the-web-and-how-can-site-owners-block-the-crawler (ClaudeBot collects web content that could contribute to training; Claude-SearchBot improves search result quality; Claude-User may access websites when individuals ask Claude questions; the bots honor robots.txt directives)
        ("Les robots d'Anthropic sont trois, chacun avec son rôle. ClaudeBot collecte des contenus qui peuvent servir à entraîner ses modèles. Claude-SearchBot parcourt le web pour améliorer les résultats de recherche de Claude. Claude-User visite une page quand un utilisateur pose une question qui le demande. Tous trois respectent les consignes du fichier robots.txt, où chacun se désigne par son propre nom pour être autorisé ou bloqué.",
         "Anthropic's crawlers are three, each with its own role. ClaudeBot collects content that may be used to train its models. Claude-SearchBot browses the web to improve Claude's search results. Claude-User visits a page when a user asks a question that calls for it. All three follow the instructions in the robots.txt file, where each is named on its own to be allowed or blocked."),
        # source: https://support.claude.com/en/articles/8896518-does-anthropic-crawl-data-from-the-web-and-how-can-site-owners-block-the-crawler (blocking ClaudeBot signals future materials should be excluded from training datasets; blocking Claude-User or Claude-SearchBot "may reduce your site's visibility" in user-directed web search and search results)
        ("Bloquer ces robots n'a pas le même effet selon le robot. Bloquer ClaudeBot signale que les futurs contenus du site doivent être exclus de l'entraînement. Bloquer Claude-SearchBot ou Claude-User peut réduire la visibilité du site dans les réponses de recherche, selon Anthropic. Un blocage ancien, posé par précaution, explique parfois une absence : à vérifier avec vos équipes techniques.",
         "Blocking these crawlers does not have the same effect for each one. Blocking ClaudeBot signals that the site's future content should be excluded from training. Blocking Claude-SearchBot or Claude-User can reduce the site's visibility in search answers, according to Anthropic. An old block, set as a precaution, sometimes explains an absence: something to check with your technical teams."),
    ]),
    (("Que faire si Claude se trompe sur votre marque, ou l'ignore", "What to do if Claude gets your brand wrong, or ignores it"), [
        ("Si Claude se trompe sur votre marque ou l'ignore, reformuler la question n'y change rien. Personne ne contrôle sa réponse, et on ne peut pas la modifier directement. On commence par chercher la cause : une page ancienne citée quand il cherche, une information absente des sources publiques, ou un robot bloqué sur votre site. Quand il cherche, les sources qu'il affiche mettent souvent sur la piste.",
         "If Claude gets your brand wrong or ignores it, rewording the question changes nothing. Nobody controls its answer, and it cannot be changed directly. You start by looking for the cause: an old page cited when it searches, information missing from public sources, or a crawler blocked on your site. When it searches, the sources it shows often point the way."),
        ("On agit ensuite sur la documentation publique : votre site, avec une information claire et à jour, puis la presse et les pages de référence. Quand Claude cherche, une page corrigée peut être reprise dès qu'il la trouve. Quand il répond de mémoire, rien ne bouge avant un nouveau modèle. Licter ne produit pas ces contenus ; vos équipes ou vos agences s'en chargent.",
         "You then act on public documentation: your site, with clear and current information, then the press and reference pages. When Claude searches, a corrected page can be picked up as soon as it finds it. When it answers from memory, nothing moves before a new model. Licter does not produce this content; your teams or your agencies do."),
    ]),
    (("Ce qu'un suivi de Claude livre", "What tracking Claude delivers"), [
        ("Un suivi de Claude livre d'abord un audit des réponses : les questions clés de votre catégorie, ce qu'il répond avec et sans recherche web, votre place face aux concurrents et les erreurs à corriger. Les mêmes questions sont ensuite reposées chaque mois, avec les mêmes formulations, pour suivre l'évolution des réponses et des sources citées. Chaque constat est rattaché aux réponses relevées.",
         "Tracking Claude first delivers an audit of its answers: your category's key questions, what it answers with and without web search, your place against competitors and the errors to correct. The same questions are then asked again every month, with the same wording, to follow how the answers and the sources cited evolve. Each finding is tied to the answers recorded."),
        ("Claude est aussi comparé aux autres assistants, ChatGPT, Gemini, Perplexity et Grok, sur les mêmes questions : qui vous cite, qui vous oublie, quels écarts de discours apparaissent. Ce suivi ne promet aucun résultat et ne remplace pas l'écoute sociale : Claude ne lit pas la conversation des réseaux. Nous posons des questions publiques, sans transmettre de donnée client.",
         "Claude is also compared with the other assistants, ChatGPT, Gemini, Perplexity and Grok, on the same questions: who cites you, who leaves you out, which differences in discourse appear. This tracking promises no result and does not replace social listening: Claude does not read the social conversation. We ask public questions, without sending any client data."),
    ]),
]
