"""The long-form section of the Gemini tool page (SEO audit: the page was too
short, about 550 words, for "agence Gemini", "ce que Gemini dit de ma marque",
"être cité dans les AI Overviews"): how Gemini, AI Overviews and AI Mode
differ, where Gemini's answers come from, why the Google Business Profile
matters, what Google says about being cited in its AI answers, what
Google-Extended and the Search Console setting control, how to find out what
Gemini says about a brand, what to do about an error, and what tracking
delivers. Each block is (heading, [paragraphs]), every string a (French,
English) pair. Licter statements come from the site's own pages
(fr/outils/gemini, fr/expertise/ai-listening, tools/tools_data.py,
tools/ai_engines.py, tools/geo_guide.py, tools/chatgpt_guide.py); public facts
about Google carry a `# source:` comment."""

KICKER = ("GEMINI, EN DÉTAIL", "GEMINI, IN DETAIL")
TITLE = ("Gemini, AI Overviews, mode IA : ce que l'IA de Google dit de votre marque.", "Gemini, AI Overviews, AI Mode: what Google's AI says about your brand.")

BLOCKS = [
    (("Gemini, AI Overviews et mode IA : quelle différence ?", "Gemini, AI Overviews and AI Mode: what is the difference?"), [
        # source: https://blog.google/intl/fr-fr/nouveautes-produits/explorez-obtenez-des-reponses/recherche-ia-apercus-mode/ (22 July 2026: Aperçus IA and Mode IA launched in Google Search in France; both use "notre dernière famille de modèles Gemini"; Aperçus IA give "une vue d'ensemble", Mode IA is conversational)
        ("Gemini, les AI Overviews et le mode IA sont trois façons d'accéder à l'IA de Google. Les AI Overviews, appelés Aperçus IA en français, résument un sujet en haut des résultats. Le mode IA permet une recherche plus poussée, sous forme de conversation. Google indique que les deux reposent sur sa famille de modèles Gemini ; il les a lancés en France le 22 juillet 2026.",
         "Gemini, AI Overviews and AI Mode are three ways into Google's AI. AI Overviews, called Aperçus IA in French, sum up a subject at the top of the results. AI Mode allows a deeper search, in the form of a conversation. Google states that both rely on its Gemini family of models; it launched them in France on 22 July 2026."),
        ("L'application Gemini, elle, est un assistant à part entière, présent sur le web, dans Android et dans les outils Google. On ne lui pose pas les questions comme dans la barre de recherche, et ses réponses ne recoupent pas toujours celles des AI Overviews. C'est pourquoi nous comparons ces trois formats sur les mêmes questions, au lieu d'en observer un seul.",
         "The Gemini app, for its part, is a full assistant, available on the web, in Android and in Google's tools. People do not ask it questions the way they type in the search bar, and its answers do not always match those of AI Overviews. That is why we compare these three formats on the same questions, instead of watching only one."),
    ]),
    (("D'où viennent les réponses de Gemini", "Where Gemini's answers come from"), [
        # source: https://support.google.com/gemini/answer/13695044 (Gemini automatically uses public information from Google Search, Google Flights, Google Hotels, Google Maps and YouTube; Search always, the others when Keep Activity is on)
        ("Les réponses de Gemini s'appuient sur la recherche Google, mais pas seulement. Selon l'aide de Google, l'application peut aussi utiliser d'elle-même les informations publiques de Google Maps, de YouTube, de Google Flights et de Google Hotels. Une marque y est donc décrite à partir de ce que l'écosystème Google sait d'elle : pages indexées, fiche d'établissement, avis, vidéos.",
         "Gemini's answers draw on Google Search, but not only. According to Google's help pages, the app can also use, on its own, public information from Google Maps, YouTube, Google Flights and Google Hotels. A brand is therefore described from what Google's ecosystem knows about it: indexed pages, Business Profile, reviews, videos."),
        # source: https://support.google.com/gemini/answer/14143489 (a Sources button opens related links; not every response includes sources)
        ("Quand Gemini s'appuie sur des pages web, il peut afficher un bouton Sources qui ouvre la liste des liens liés à sa réponse. Google précise que toutes les réponses n'en comportent pas. Ces liens sont précieux : ils montrent quelles pages pèsent sur ce que l'assistant dit de vous, et lesquelles il faudrait corriger ou compléter.",
         "When Gemini draws on web pages, it can show a Sources button that opens the list of links related to its answer. Google states that not every answer includes one. These links are valuable: they show which pages weigh on what the assistant says about you, and which ones would need correcting or completing."),
    ]),
    (("Pourquoi votre fiche Google compte", "Why your Google Business Profile matters"), [
        # source: https://support.google.com/business/answer/7091 ("Businesses with complete and accurate info are more likely to show up in local search results"; "There's no way to request or pay for a better local ranking on Google")
        # source: https://support.google.com/gemini/answer/13695044 (Gemini uses public information from Google Maps)
        ("Votre fiche d'établissement Google compte, parce qu'elle fait partie de ce que Google sait de vous. Google indique que les fiches complètes et exactes ont plus de chances d'apparaître dans les résultats locaux, et qu'on ne peut pas payer pour un meilleur classement local. Comme Gemini peut puiser dans les informations publiques de Maps, une fiche datée peut finir dans ses réponses.",
         "Your Google Business Profile matters, because it is part of what Google knows about you. Google states that complete and accurate profiles are more likely to show up in local results, and that you cannot pay for a better local ranking. Since Gemini can draw on public information from Maps, an outdated profile can end up in its answers."),
        # source: https://blog.google/products-and-platforms/products/maps/ask-maps-immersive-navigation/ (12 March 2026: Ask Maps, a conversational experience powered by Gemini, analyses "information from over 300 million places, including reviews from our community of more than 500 million contributors"; rolling out in the U.S. and India)
        ("Les avis pèsent tout autant. En mars 2026, Google a lancé aux États-Unis et en Inde Ask Maps, une recherche conversationnelle dans Maps fondée sur Gemini. Il indique qu'elle analyse les informations de plus de 300 millions de lieux, dont les avis de plus de 500 millions de contributeurs. Ce que vos clients écrivent sur votre fiche devient ainsi matière à réponse.",
         "Reviews weigh just as much. In March 2026, Google launched Ask Maps in the United States and India, a conversational search in Maps built on Gemini. It states that it analyses information from more than 300 million places, including reviews from more than 500 million contributors. What your customers write on your profile thus becomes material for answers."),
    ]),
    (("Être cité dans les réponses IA de Google", "Being cited in Google's AI answers"), [
        # source: https://developers.google.com/search/docs/appearance/ai-features (a page must be "indexed and eligible to be shown in Google Search with a snippet"; "There are no additional requirements to appear in AI Overviews or AI Mode, nor other special optimizations necessary")
        ("Être cité dans les réponses IA de Google ne demande pas de recette secrète. Google l'écrit dans sa documentation : pour apparaître comme lien dans les AI Overviews ou le mode IA, une page doit être indexée et pouvoir s'afficher dans la recherche avec un extrait. Il n'y a, selon lui, aucune exigence supplémentaire ni optimisation spéciale à prévoir.",
         "Being cited in Google's AI answers does not take a secret recipe. Google says so in its documentation: to appear as a link in AI Overviews or AI Mode, a page must be indexed and eligible to show in Search with a snippet. According to Google, there is no additional requirement and no special optimization to plan for."),
        # source: https://developers.google.com/search/docs/appearance/ai-features (best practices: helpful, reliable content; crawlability; page experience; textual content with quality images and videos; structured data matching visible content)
        ("Google renvoie donc aux bonnes pratiques habituelles : des contenus utiles et fiables, des pages explorables, du texte accompagné d'images et de vidéos de qualité, des données structurées exactes. Le SEO aide, puisque Gemini s'appuie sur la recherche Google, mais il ne suffit pas : les pages des autres qui parlent de vous (presse, avis, comparatifs) comptent aussi.",
         "Google therefore points to the usual good practices: helpful and reliable content, crawlable pages, text backed by quality images and videos, accurate structured data. SEO helps, since Gemini draws on Google Search, but it is not enough: other people's pages that talk about you (press, reviews, comparison articles) count too."),
    ]),
    (("Google-Extended et le réglage de la Search Console", "Google-Extended and the Search Console setting"), [
        # source: https://developers.google.com/search/docs/crawling-indexing/google-common-crawlers (Google-Extended manages whether crawled content may be used for training future Gemini models and "for grounding in Gemini Apps"; "does not impact a site's inclusion in Google Search nor is it used as a ranking signal"; no separate user agent string)
        ("Google-Extended est un repère que l'on inscrit dans le fichier robots.txt d'un site. Selon Google, il décide si les contenus explorés peuvent servir à entraîner les futurs modèles Gemini et à étayer les réponses de l'application Gemini. Il n'a pas de robot à part, et Google précise qu'il ne change ni la présence d'un site dans la recherche, ni son classement.",
         "Google-Extended is a token written into a site's robots.txt file. According to Google, it decides whether crawled content may be used to train future Gemini models and to ground the answers of the Gemini app. It has no crawler of its own, and Google states that it changes neither a site's presence in Search nor its ranking."),
        # source: https://blog.google/products-and-platforms/products/search/new-controls-website-owners/ (3 June 2026, updated 31 August 2026: Search Console control to opt out of AI Overviews, AI Mode and AI Overviews in Discover; "Sites that opt out will not receive traffic or impressions from our generative AI features"; tested first in the UK, available to all sites by 31 August 2026)
        ("Les AI Overviews et le mode IA relèvent d'un autre réglage. Testé à partir de juin 2026, puis ouvert à tous les sites fin août, un contrôle de la Search Console permet de sortir de ces fonctions, comme des AI Overviews de Discover. Un site qui s'en retire ne reçoit plus d'impressions ni de trafic de ces réponses : une décision à prendre avec vos équipes techniques.",
         "AI Overviews and AI Mode fall under another setting. Tested from June 2026, then opened to all sites at the end of August, a Search Console control lets a site leave these features, as well as AI Overviews in Discover. A site that opts out no longer gets impressions or traffic from these answers: a decision to make with your technical teams."),
    ]),
    (("Comment savoir ce que Gemini dit de votre marque", "How to find out what Gemini says about your brand"), [
        # source: https://gemini.google/overview/personalization/ (Gemini can consider past chats and connected Google apps such as Gmail, Photos, Search and YouTube; these experiences are optional)
        ("Pour savoir ce que Gemini dit de votre marque, il faut lui poser les questions de vos clients, puis poser les mêmes à la recherche Google pour lire les AI Overviews et le mode IA. Gemini peut personnaliser ses réponses à partir des conversations passées et des applications Google connectées : nous l'interrogeons donc sans cet historique, comme un client qui découvre votre catégorie.",
         "To find out what Gemini says about your brand, you have to ask it your customers' questions, then ask the same ones in Google Search to read AI Overviews and AI Mode. Gemini can personalise its answers from past conversations and connected Google apps: so we question it without that history, like a customer discovering your category."),
        # source: https://blog.google/products-and-platforms/products/search/new-controls-website-owners/ (new Search Console insights on the appearance of pages in generative AI Search features, including "impressions metrics and information about which pages appear in AI responses")
        ("La Search Console apporte un autre éclairage. Google y déploie des données sur la présence des pages dans ses fonctions d'IA générative : des impressions, et la liste des pages qui apparaissent dans les réponses. Elles disent si votre site est repris, pas ce que l'IA dit de vous, ni qui elle recommande à votre place. Pour cela, il faut lire les réponses elles-mêmes, plusieurs fois.",
         "Search Console offers another view. Google is rolling out data there on how pages appear in its generative AI features: impressions, and the list of pages that show up in the answers. This data says whether your site is used, not what the AI says about you, nor whom it recommends in your place. For that, you have to read the answers themselves, several times."),
    ]),
    (("Que faire d'une erreur dans Gemini", "What to do about an error in Gemini"), [
        # source: https://support.google.com/gemini/answer/13275746 ("Good response" / "Bad response" with an optional reason; "Report legal issue" under a response)
        ("Une erreur dans Gemini ne se corrige pas directement. L'application permet de noter une réponse comme mauvaise en expliquant pourquoi, ou de signaler un problème juridique, mais personne ne contrôle ce qu'écrit une IA. Et comme Gemini s'appuie sur la recherche Google, une erreur dans l'un se retrouve souvent dans l'autre : il faut regarder les deux.",
         "An error in Gemini cannot be fixed directly. The app lets you rate an answer as bad and say why, or report a legal issue, but nobody controls what an AI writes. And since Gemini draws on Google Search, an error in one often shows up in the other: you have to look at both."),
        # source: https://support.google.com/gemini/answer/14143489 (double-check uses Google Search to find content likely similar to or different from Gemini's statements, shown as highlighted statements)
        ("Il faut donc remonter à la source. Les liens affichés par Gemini aident, tout comme sa fonction de vérification, qui confronte ses phrases à ce que trouve la recherche Google. Une fois la page fautive repérée (votre site, votre fiche, un article ancien), on la corrige ou on la complète, puis on mesure si la réponse change dans les mois qui suivent.",
         "So you have to trace back to the source. The links Gemini shows help, as does its double-check feature, which compares its statements with what Google Search finds. Once the faulty page is found (your site, your profile, an old article), you correct or complete it, then measure whether the answer changes in the months that follow."),
    ]),
    (("Ce qu'un suivi Gemini livre", "What Gemini tracking delivers"), [
        ("Un suivi Gemini reprend chaque mois les mêmes questions, posées plusieurs fois, dans Gemini et dans les réponses IA de la recherche Google. Il livre l'évolution des réponses, les sources citées relevées et classées, votre place face à vos concurrents et une note pour la communication. Les mêmes questions peuvent être posées à ChatGPT, Claude, Perplexity ou Grok, pour comparer.",
         "Gemini tracking asks the same questions every month, several times each, in Gemini and in Google Search's AI answers. It delivers how the answers evolve, the sources cited collected and sorted, your place against your competitors and a note for communications. The same questions can be put to ChatGPT, Claude, Perplexity or Grok, to compare."),
        ("Le suivi dit ce qu'il faut corriger, et où agir ; il ne promet aucun résultat. Licter ne produit pas les contenus : vos équipes ou vos agences s'en chargent. Gemini ne lit pas non plus la conversation des réseaux : il complète l'écoute sociale, sans la remplacer. Pour commencer, nous proposons un flash AI listening offert sur votre marque, envoyé sous 48 heures.",
         "Tracking says what to correct, and where to act; it promises no result. Licter does not produce the content: your teams or your agencies do. Nor does Gemini read the social conversation: it completes social listening, without replacing it. To start, we offer a free AI listening flash on your brand, sent within 48 hours."),
    ]),
]
