"""The long-form section of the GEO tool page (SEO audit: the page was too
short, about 900 words, for "GEO", "generative engine optimization", "GEO
marque IA", "être cité par ChatGPT", "agence GEO"): what GEO is, how it
differs from SEO, how an AI picks its sources, how to measure visibility in AI
answers, which content gets cited, the weight of press, forums and Wikipedia,
what GEO cannot promise, how long an effect takes, and what an agency or a
consultancy adds. Each block is (heading, [paragraphs]), every string a
(French, English) pair. Licter statements come from the site's own pages
(fr/outils/geo, fr/outils/chatgpt, fr/outils/perplexity, fr/outils/gemini,
fr/expertise/ai-listening, tools/tools_data.py, tools/ai_engines.py); public
facts carry a `# source:` comment."""

KICKER = ("LE GEO, EN DÉTAIL", "GEO, IN DETAIL")
TITLE = ("Ce qu'il faut savoir avant de travailler sa place dans les réponses des IA.", "What to know before you work on your place in AI answers.")

BLOCKS = [
    (("Qu'est-ce que le GEO ?", "What is GEO?"), [
        ("Le GEO, ou generative engine optimization, désigne l'ensemble des actions qui visent à faire apparaître une marque, un produit ou une source dans les réponses rédigées par une IA. Ces réponses viennent de ChatGPT, de Gemini, de Perplexity ou des AI Overviews de Google. Elles ne renvoient pas vers une liste de liens : elles donnent directement un avis, une recommandation, un nom.",
         "GEO, or generative engine optimization, covers the actions meant to make a brand, a product or a source appear in the answers written by an AI. Those answers come from ChatGPT, Gemini, Perplexity or Google's AI Overviews. They do not point to a list of links: they give an opinion, a recommendation, a name, directly."),
        # source: https://arxiv.org/abs/2311.09735 (title "GEO: Generative Engine Optimization", v1 16 November 2023, KDD 2024, GEO-bench, "up to 40%" visibility boost)
        # source: https://arxiv.org/html/2311.09735v3 (GEO-bench: 10,000 queries; nine methods tested)
        ("Le mot GEO a été proposé dans un article de recherche mis en ligne en novembre 2023, puis présenté à la conférence KDD en 2024. Ses auteurs ont construit un banc d'essai de 10 000 questions, baptisé GEO-bench, et testé neuf façons de réécrire une page. Ils concluent que certaines réécritures augmentent la visibilité d'une source dans les réponses jusqu'à 40 %, selon les domaines.",
         "The word GEO was coined in a research paper posted in November 2023, then presented at the KDD conference in 2024. Its authors built a test bench of 10,000 questions, called GEO-bench, and tried nine ways of rewriting a page. They conclude that some rewrites raise a source's visibility in the answers by up to 40%, depending on the domain."),
    ]),
    (("GEO et SEO : quelle différence ?", "GEO and SEO: what is the difference?"), [
        ("Le GEO et le SEO ne mesurent pas la même chose. Le SEO vise une position dans une liste de résultats, puis un clic. Le GEO vise une mention dans un texte rédigé par une machine, que l'utilisateur lit souvent sans cliquer. Une marque peut être bien classée sur Google et absente des réponses d'une IA, ou l'inverse.",
         "GEO and SEO do not measure the same thing. SEO aims for a position in a list of results, then a click. GEO aims for a mention in a text written by a machine, which the user often reads without clicking. A brand can rank well on Google and be absent from an AI's answers, or the other way round."),
        # source: https://developers.google.com/search/docs/appearance/ai-features ("To be eligible to be shown as a supporting link in AI Overviews or AI Mode, a page must be indexed and eligible to be shown in Google Search with a snippet"; "There are no additional requirements ... nor other special optimizations necessary")
        # source: https://arxiv.org/html/2311.09735v3 (keyword stuffing: "little to no improvement on generative engine's responses")
        ("Les deux disciplines se recoupent pourtant. Google l'écrit dans sa documentation : pour apparaître comme lien dans les AI Overviews ou le mode IA, une page doit être indexée et pouvoir s'afficher avec un extrait, sans optimisation spéciale. En revanche, l'article fondateur du GEO note que le bourrage de mots-clés, vieille recette du SEO, n'apporte presque rien dans une réponse d'IA.",
         "The two disciplines still overlap. Google says so in its documentation: to appear as a link in AI Overviews or AI Mode, a page must be indexed and eligible to show with a snippet, with no special optimization. On the other hand, the founding GEO paper notes that keyword stuffing, an old SEO recipe, brings almost nothing in an AI answer."),
    ]),
    (("Comment une IA choisit ses sources", "How an AI chooses its sources"), [
        ("Une IA construit sa réponse à partir de deux réservoirs. Le premier est sa mémoire : les textes lus pendant son entraînement, arrêtés à une date. Le second est la recherche web : l'assistant lit des pages en direct et cite ses liens. ChatGPT utilise les deux, Perplexity cherche à chaque question, Gemini s'appuie sur la recherche Google. L'écart entre mémoire et recherche explique bien des réponses datées.",
         "An AI builds its answer from two reservoirs. The first is its memory: the texts read during training, frozen at a date. The second is web search: the assistant reads pages live and cites its links. ChatGPT uses both, Perplexity searches on every question, Gemini relies on Google Search. The gap between memory and search explains many outdated answers."),
        # source: https://developers.google.com/search/docs/appearance/ai-features ("query fan-out" technique: "issuing multiple related searches across subtopics and data sources")
        # source: https://developers.openai.com/api/docs/bots ("Sites that are opted out of OAI-SearchBot will not be shown in ChatGPT search answers")
        ("La sélection des pages dépend aussi de règles techniques. Google explique que ses AI Overviews et son mode IA lancent plusieurs recherches liées en parallèle, sur des sous-sujets, avant de rédiger. OpenAI précise qu'un site qui bloque son robot de recherche, OAI-SearchBot, n'apparaît plus dans les réponses de recherche de ChatGPT. Le premier contrôle est donc simple : vos pages sont-elles lisibles par ces robots ?",
         "The choice of pages also depends on technical rules. Google explains that its AI Overviews and AI Mode run several related searches in parallel, on subtopics, before writing. OpenAI states that a site blocking its search crawler, OAI-SearchBot, no longer appears in ChatGPT's search answers. The first check is therefore simple: can these crawlers read your pages?"),
    ]),
    (("Comment mesurer sa visibilité dans les réponses des IA", "How to measure your visibility in AI answers"), [
        ("La visibilité dans les réponses des IA se mesure à partir d'un panel de questions. Ce sont celles que posent vos clients : « quelle marque choisir », « quelle différence entre », « est-ce fiable ». Sur ce panel, on compte combien de fois votre marque est citée, à quelle place, face à quels concurrents. C'est ce que nous appelons la part de réponse.",
         "Visibility in AI answers is measured from a panel of questions. They are the ones your customers ask: \"which brand to choose\", \"what is the difference between\", \"is it reliable\". On that panel, you count how often your brand is cited, in which position, against which competitors. That is what we call the share of answer."),
        ("Une mesure fiable demande de la répétition. La même question ne donne pas toujours la même réponse : nous posons donc chaque question plusieurs fois, à chaque moteur. Sur ChatGPT, nous la posons avec et sans recherche web, pour séparer la mémoire de ce qu'il lit aujourd'hui. Nous relevons enfin les sources citées, pour savoir d'où vient chaque mention.",
         "A reliable measure needs repetition. The same question does not always give the same answer: so we ask each question several times, on each engine. On ChatGPT, we ask it with and without web search, to separate its memory from what it reads today. Finally, we record the sources cited, to know where each mention comes from."),
        ("La mesure se fait moteur par moteur, car ChatGPT, Gemini, Perplexity et les AI Overviews de Google ne citent pas les mêmes marques. Nous comparons par exemple Gemini et les réponses IA de la recherche Google sur les mêmes questions, puis nous remontons aux pages et aux fiches qui les nourrissent. Un bon score sur un moteur ne dit rien des autres.",
         "Measurement is done engine by engine, because ChatGPT, Gemini, Perplexity and Google's AI Overviews do not cite the same brands. For instance, we compare Gemini and the AI answers of Google Search on the same questions, then trace back to the pages and listings that feed them. A good score on one engine says nothing about the others."),
    ]),
    (("Quels contenus sont cités par les IA ?", "Which content do AIs cite?"), [
        # source: https://arxiv.org/html/2311.09735v3 (best methods: Quotation Addition, Statistics Addition, Cite Sources; also validated on Perplexity.ai)
        ("Les contenus cités par les IA ont un point commun : ils donnent une réponse nette, facile à reprendre. Dans l'article fondateur du GEO, les réécritures les plus efficaces ajoutent des citations, des statistiques ou des références à des sources. Les auteurs ont vérifié ce résultat sur Perplexity, en conditions réelles. Un texte vague ou purement promotionnel offre peu de prise.",
         "The content AIs cite has one thing in common: it gives a clear answer that is easy to reuse. In the founding GEO paper, the most effective rewrites add quotations, statistics or references to sources. The authors checked this result on Perplexity, in real conditions. A vague or purely promotional text offers little to hold on to."),
        ("Concrètement, une page utile pour une IA répond à une question précise dès ses premières lignes. Elle donne des faits datés et vérifiables : prix, caractéristiques, conditions. Elle reste à jour, car une information ancienne finit par être reprise comme vraie. Le travail porte autant sur vos pages que sur les pages des autres qui parlent de vous.",
         "In practice, a page useful to an AI answers a precise question in its first lines. It gives dated, verifiable facts: prices, features, conditions. It stays up to date, because old information ends up repeated as true. The work concerns your own pages as much as other people's pages that talk about you."),
    ]),
    (("Le rôle de la presse, des forums et de Wikipédia", "The role of the press, forums and Wikipedia"), [
        ("La presse, les forums et les sites d'avis pèsent lourd dans les réponses des IA, parce qu'une marque y est décrite par d'autres qu'elle. Sur Perplexity, qui affiche ses sources, les pages récentes, les articles et les discussions reviennent souvent. Une marque absente de ces espaces a peu de chances d'être recommandée, même avec un excellent site.",
         "The press, forums and review sites weigh heavily in AI answers, because there a brand is described by others than itself. On Perplexity, which shows its sources, recent pages, articles and discussions come back often. A brand absent from these spaces has little chance of being recommended, even with an excellent site."),
        # source: https://fr.wikipedia.org/wiki/Wikipédia:Conflit_d'intérêts (Wikipedia conflict-of-interest guideline)
        # source: https://arxiv.org/abs/2005.14165 (GPT-3 paper, section 2.2: training data includes "English-language Wikipedia")
        ("Wikipédia joue un rôle à part. L'encyclopédie fait partie des données d'entraînement déclarées de modèles comme GPT-3, et elle sert souvent de référence pour décrire une entreprise. Une fiche fausse ou datée peut donc se retrouver dans la mémoire d'une IA. On ne la corrige pas soi-même : les règles de Wikipédia encadrent strictement les conflits d'intérêts.",
         "Wikipedia plays a special role. The encyclopedia is part of the declared training data of models such as GPT-3, and it often serves as the reference to describe a company. A wrong or outdated entry can therefore end up in an AI's memory. You do not fix it yourself: Wikipedia's rules strictly govern conflicts of interest."),
    ]),
    (("Ce que le GEO ne peut pas promettre", "What GEO cannot promise"), [
        ("Le GEO ne peut pas garantir une place dans une réponse. Personne ne contrôle ce qu'écrit une IA : ni la marque, ni son agence, ni un consultant. Les moteurs changent de modèle, de sources et de règles sans prévenir. Une offre qui promet d'être « premier sur ChatGPT » promet ce qu'elle ne maîtrise pas.",
         "GEO cannot guarantee a place in an answer. Nobody controls what an AI writes: not the brand, not its agency, not a consultant. Engines change model, sources and rules without warning. An offer that promises to be \"first on ChatGPT\" promises something it does not control."),
        ("Ce que le GEO permet, c'est d'agir sur les sources qui nourrissent les réponses, puis de mesurer l'effet sur le même panel de questions. Il ne remplace pas non plus l'écoute sociale : une IA ne lit pas toute la conversation des réseaux. Et il ne dit pas combien de personnes posent ces questions ; pour cela, il faut le search listening.",
         "What GEO allows is to act on the sources that feed the answers, then measure the effect on the same question panel. Nor does it replace social listening: an AI does not read the whole social conversation. And it does not say how many people ask these questions; for that, you need search listening."),
    ]),
    (("Combien de temps pour voir un effet ?", "How long before you see an effect?"), [
        ("Le délai d'un effet GEO dépend du réservoir que l'IA utilise. Quand elle cherche sur le web, comme Perplexity ou ChatGPT avec la recherche, une page nouvelle ou corrigée peut être reprise dès qu'elle est trouvée. Quand elle répond de mémoire, rien ne bouge avant la sortie d'un nouveau modèle, dont personne ne connaît la date à l'avance.",
         "The time a GEO effect takes depends on the reservoir the AI uses. When it searches the web, like Perplexity or ChatGPT with search, a new or corrected page can be picked up as soon as it is found. When it answers from memory, nothing moves before a new model comes out, and nobody knows that date in advance."),
        ("C'est pourquoi nous partons d'une première mesure, puis suivons le même panel chaque mois ou chaque trimestre. Les réponses variant d'un essai à l'autre, seule une série de mesures comparables dit si une évolution est réelle. Un écart d'une semaine sur une seule question ne prouve rien.",
         "That is why we start from a first measure, then follow the same panel every month or every quarter. Since answers vary from one try to the next, only a series of comparable measures tells whether a change is real. A one-week gap on a single question proves nothing."),
    ]),
    (("Agence ou cabinet GEO : ce que vous achetez", "GEO agency or consultancy: what you buy"), [
        ("Avec une agence ou un cabinet GEO, vous n'achetez pas un logiciel, mais une méthode et une lecture. Le choix des questions, des moteurs et des concurrents, la répétition des mesures, le relevé des sources et la recommandation sont pris en charge. Vos équipes reçoivent une liste de priorités, pas un tableau de bord à faire tourner.",
         "With a GEO agency or consultancy, you do not buy software, but a method and a reading. The choice of questions, engines and competitors, the repeated measures, the record of sources and the recommendation are taken care of. Your teams receive a list of priorities, not a dashboard to run."),
        ("Licter est un cabinet indépendant, sans lien avec les éditeurs des IA. Nous mesurons, expliquons et recommandons ; la production des contenus reste à vos équipes ou à vos agences, avec qui nous faisons le lien. Pour commencer, nous proposons un flash AI listening offert sur votre marque, envoyé sous 48 heures et lu par un consultant.",
         "Licter is an independent consultancy, with no tie to the AI publishers. We measure, explain and recommend; content production stays with your teams or agencies, with whom we make the link. To start, we offer a free AI listening flash on your brand, sent within 48 hours and read by a consultant."),
    ]),
    # neutral on purpose: no agency named or ranked (owner rule); the questions any buyer can ask (audit of 9 October 2026)
    (("Cinq questions à poser à une agence GEO", "Five questions to ask a GEO agency"), [
        ("Comment mesurez-vous notre visibilité avant d'agir ? Sans mesure de départ, aucun résultat ne pourra être démontré. Sur quelles questions et quels modèles ? Ce doivent être les questions de vos clients, posées aux assistants qu'ils utilisent, et plusieurs fois, puisque les réponses varient.",
         "How do you measure our visibility before acting? Without a starting measure, no result can be shown. On which questions and which models? They should be your customers' questions, put to the assistants they use, and several times, since answers vary."),
        ("Comment repérez-vous les sources que les IA citent ? C'est là que se joue l'essentiel du travail. Que livrez-vous, et à quel rythme ? Une liste de priorités vaut mieux qu'un tableau de bord. Enfin, comment saurons-nous si cela fonctionne ? Méfiez-vous d'une promesse de place garantie : aucun acteur ne contrôle les réponses d'un modèle.",
         "How do you identify the sources the assistants cite? That is where most of the work happens. What do you deliver, and how often? A list of priorities is worth more than a dashboard. Finally, how will we know it works? Beware of a guaranteed position: nobody controls a model's answers."),
    ]),
]
