"""The long-form section of the Grok tool page (SEO audit: the page was too
short, about 550 words, for "agence Grok", "ce que Grok dit de ma marque",
"Grok X marque"): what Grok is and where its answers come from, why it picks
up a controversy on X so fast, its public replies in X threads, rumours, how
to find out what it says about a brand, what it says during and after a
crisis, what to do about a false answer, and what tracking delivers and leaves
out. Each block is (heading, [paragraphs]), every string a (French, English)
pair. Licter statements come from the site's own pages (fr/outils/grok,
fr/sources/x-twitter, fr/offres/vigie-360, tools/tools_data.py,
tools/ai_engines.py, tools/chatgpt_guide.py); public facts about Grok carry a
`# source:` comment."""

KICKER = ("GROK, EN DÉTAIL", "GROK, IN DETAIL")
TITLE = ("Ce que Grok dit de votre marque, et pourquoi.", "What Grok says about your brand, and why.")

BLOCKS = [
    (("Qu'est-ce que Grok, et d'où viennent ses réponses ?", "What is Grok, and where do its answers come from?"), [
        # source: https://x.ai/news/grok (announcement dated 3 November 2023: "A unique and fundamental advantage of Grok is that it has real-time knowledge of the world via the X platform")
        ("Grok est l'assistant conversationnel de xAI, présenté en novembre 2023 et intégré au réseau X. Dès l'annonce, xAI a mis en avant son accès en temps réel à ce qui se publie sur X. C'est ce qui le sépare des autres assistants : interrogé sur une marque, il peut lire ce que les comptes de X en disent depuis quelques heures, et pas seulement ce qu'il a appris pendant son entraînement.",
         "Grok is xAI's conversational assistant, unveiled in November 2023 and built into the X network. From the announcement, xAI highlighted its real-time access to what is posted on X. That is what sets it apart from other assistants: asked about a brand, it can read what X accounts have been saying about it for the past few hours, not only what it learned during training."),
        # source: https://help.x.com/en/using-x/about-grok ("Grok has a unique feature that allows it to decide whether or not to search X public posts and conduct a real-time web search on the Internet")
        # source: https://x.ai/news/grok-1212 (12 December 2024: "We also added citations, so you can easily dive deeper into a source to learn more or verify the information provided by Grok")
        ("Selon la question, Grok décide lui-même de chercher dans les publications publiques de X, sur le web, ou dans les deux. Depuis décembre 2024, il affiche des citations pour remonter à la source et vérifier. Pour une marque, ces citations sont précieuses : elles montrent quels comptes et quelles publications ont nourri la réponse, donc où se joue ce qu'il dit de vous.",
         "Depending on the question, Grok decides for itself whether to search public posts on X, the web, or both. Since December 2024, it shows citations so you can go back to the source and check. For a brand, these citations are valuable: they show which accounts and which posts fed the answer, and therefore where what it says about you is decided."),
    ]),
    (("Pourquoi Grok réagit vite à une polémique sur X", "Why Grok reacts fast to a controversy on X"), [
        ("Grok réagit vite à une polémique sur X parce qu'il lit le réseau où elle naît. X reste le réseau de l'actualité en direct : journalistes, politiques et experts y réagissent souvent les premiers, et c'est souvent là qu'un sujet devient une affaire. Les publications qui portent la polémique deviennent vite des sources pour l'assistant, qui peut les reprendre en quelques heures, bien avant les autres assistants.",
         "Grok reacts fast to a controversy on X because it reads the network where the controversy starts. X remains the network of live news: journalists, politicians and experts often react there first, and it is often there that a topic turns into an affair. The posts carrying the controversy quickly become sources for the assistant, which can pick them up within hours, well before other assistants."),
        ("Cette vitesse a un revers. Au plus fort d'un pic, les publications les plus visibles sont souvent les plus tranchées, pas forcément les plus exactes. Grok peut alors reprendre le ton de la polémique en cours, ses formules, parfois ses raccourcis. Une réponse relevée à ce moment-là décrit l'état de la conversation sur X, pas l'opinion générale sur votre marque.",
         "This speed has a downside. At the height of a spike, the most visible posts are often the most clear-cut, not necessarily the most accurate. Grok can then pick up the tone of the ongoing controversy, its phrases, sometimes its shortcuts. An answer recorded at that moment describes the state of the conversation on X, not general opinion about your brand."),
    ]),
    (("Grok répond aussi en public, dans les fils de X", "Grok also answers in public, in X threads"), [
        # source: https://techcrunch.com/2025/03/07/x-now-lets-you-query-grok-by-mentioning-it-in-replies (7 March 2025: "people can now mention Grok in replies and ask a question to get an explanation about a post")
        # source: https://tech.yahoo.com/articles/ask-grok-supposed-x-better-182752572.html (Business Insider, 1 April 2025: users reply "@grok, is this true?" and Grok answers publicly in the thread)
        ("Grok répond aussi en public, et pas seulement dans une fenêtre de discussion privée. Depuis mars 2025, les utilisateurs de X peuvent le mentionner dans une réponse à une publication et lui poser une question ; sa réponse s'affiche dans le fil. Beaucoup s'en servent pour lui demander si une publication dit vrai. Sur un sujet qui vous concerne, sa réponse est lue par tous ceux qui suivent la discussion.",
         "Grok also answers in public, not only in a private chat window. Since March 2025, X users can mention it in a reply to a post and ask it a question; its answer appears in the thread. Many use it to ask whether a post is true. On a topic that concerns you, its answer is read by everyone following the discussion."),
        # source: https://x.ai/news/grok-1212 ("Today we're also introducing the Grok button, a new feature that will appear on posts across your home timeline")
        ("Depuis décembre 2024, un bouton Grok apparaît aussi sur les publications du fil d'actualité, pour interroger l'assistant sur un message. Pendant une crise, ces réponses comptent autant que les publications elles-mêmes : elles résument l'affaire pour ceux qui arrivent en cours de route. C'est pourquoi nous lisons ce que dit Grok avec la conversation de X, jamais seul.",
         "Since December 2024, a Grok button also appears on posts in the home timeline, to ask the assistant about a post. During a crisis, these answers matter as much as the posts themselves: they sum up the affair for those arriving midway. That is why we read what Grok says alongside the conversation on X, never on its own."),
    ]),
    (("Grok et les rumeurs", "Grok and rumours"), [
        # source: https://x.ai/news/grok ("our model can still generate false or contradictory information")
        # source: https://help.x.com/en/using-x/about-grok ("It may confidently provide factually incorrect information, missummarize, or miss some context"; users are encouraged to "independently verify any information you receive")
        ("Grok et les rumeurs forment un sujet à part. xAI l'a écrit dès l'annonce de l'assistant : malgré son accès à la recherche, le modèle peut produire des informations fausses ou contradictoires. L'aide de X ajoute qu'il peut affirmer avec assurance une information inexacte, mal résumer ou manquer de contexte, et invite chacun à vérifier par lui-même ce qu'il reçoit.",
         "Grok and rumours are a topic of their own. xAI wrote it from the assistant's announcement: despite its access to search, the model can produce false or contradictory information. X's help centre adds that it may confidently state inaccurate information, missummarize or miss some context, and asks everyone to check for themselves what they receive."),
        ("Pour une marque, le risque se décrit simplement. Une rumeur lancée sur X peut être reprise par Grok tant qu'elle circule, puis rester dans ses réponses une fois retombée sur le réseau, surtout si aucun démenti n'est aussi visible qu'elle. C'est l'une des choses que nous vérifions : si une rumeur survit dans Grok après le pic, et quelles publications continuent de la porter.",
         "For a brand, the risk is simple to describe. A rumour started on X can be picked up by Grok while it circulates, then stay in its answers once it has died down on the network, especially if no denial is as visible as the rumour. It is one of the things we check: whether a rumour survives in Grok after the spike, and which posts keep carrying it."),
    ]),
    (("Comment savoir ce que Grok dit de votre marque ?", "How do you find out what Grok says about your brand?"), [
        ("Pour savoir ce que Grok dit de votre marque, il faut lui poser les questions de vos clients, et pas une seule fois. La même question ne donne pas toujours la même réponse, et chez Grok la réponse dépend aussi du moment : une semaine calme et un jour de pic sur X ne donnent pas la même image. Nous posons donc les mêmes questions plusieurs fois, chaque mois, et nous comparons.",
         "To find out what Grok says about your brand, you have to ask it your customers' questions, and not just once. The same question does not always give the same answer, and with Grok the answer also depends on the moment: a quiet week and a day of spike on X do not give the same picture. So we ask the same questions several times, every month, and compare."),
        ("Le relevé porte sur ce qui revient : les qualités et les défauts attribués à votre marque, les concurrents cités et leur ordre, les comptes et les publications de X mis en avant, les pages web citées. Ces sources sont relevées et classées. Elles disent si Grok s'appuie sur la presse, sur vos propres comptes, ou sur quelques voix très actives sur le réseau.",
         "The record covers what comes back: the strengths and weaknesses attributed to your brand, the competitors cited and their order, the X accounts and posts put forward, the web pages cited. These sources are collected and sorted. They say whether Grok relies on the press, on your own accounts, or on a few very active voices on the network."),
    ]),
    (("Grok pendant et après une crise", "Grok during and after a crisis"), [
        ("Pendant une crise, Grok devient un relais de plus. Ce qu'il répond sur votre marque montre comment l'affaire est résumée, quels comptes servent de référence et quels faits sont retenus. Nous relevons ces réponses à côté de la conversation de X, suivie à l'instant avec des outils comme Visibrain, pour voir ce que l'assistant reprend et ce qu'il laisse de côté.",
         "During a crisis, Grok becomes one more relay. What it answers about your brand shows how the affair is summed up, which accounts serve as a reference and which facts are kept. We record these answers alongside the conversation on X, followed as it happens with tools such as Visibrain, to see what the assistant picks up and what it leaves out."),
        ("Pour une crise en cours, c'est le rôle de Vigie 360 : un analyste vous alerte en 15 minutes, 24 h/24, puis un point quotidien suit la conversation jusqu'à ce qu'elle retombe. Le suivi de Grok sert à autre chose : vérifier ce qui reste dans ses réponses une fois le calme revenu, et si elles citent encore les publications du pic.",
         "For a crisis in progress, that is the role of Vigie 360: an analyst alerts you within 15 minutes, 24/7, then a daily update follows the conversation until it dies down. Tracking Grok serves another purpose: checking what remains in its answers once things have calmed down, and whether they still cite the posts from the spike."),
    ]),
    (("Que faire d'une réponse fausse de Grok ?", "What to do about a false answer from Grok?"), [
        ("Une réponse fausse de Grok ne se corrige pas en écrivant à l'assistant. Il faut remonter à ce qui la nourrit : ses citations montrent souvent les publications de X ou les pages web d'où vient l'erreur. Une publication ancienne très reprise, un compte qui répète une information datée, une page jamais mise à jour : chaque cause appelle une action différente.",
         "A false answer from Grok is not corrected by writing to the assistant. You have to go back to what feeds it: its citations often show the X posts or web pages the error comes from. An old post widely shared, an account repeating outdated information, a page never updated: each cause calls for a different action."),
        ("L'action se joue alors sur les sources : une prise de parole claire sur vos comptes, une mise à jour de vos pages, une réponse aux comptes qui comptent sur le sujet. Licter ne produit pas ces contenus ; vos équipes ou vos agences s'en chargent. Nous mesurons ensuite, question par question, si la réponse change, sans promettre qu'elle changera.",
         "The action then plays out on the sources: a clear statement on your accounts, an update of your pages, a reply to the accounts that matter on the topic. Licter does not produce this content; your teams or your agencies do. We then measure, question by question, whether the answer changes, without promising that it will."),
    ]),
    (("Ce qu'un suivi de Grok livre, et ce qu'il ne dit pas", "What tracking Grok delivers, and what it does not tell"), [
        ("Un suivi de Grok livre d'abord un audit des réponses : les questions clés de votre catégorie, ce que répond l'assistant, votre place face aux concurrents et les erreurs à corriger. Il se poursuit chaque mois avec les mêmes questions, l'évolution des réponses, les sources citées et une note pour la communication. Une comparaison avec ChatGPT, Claude, Gemini et Perplexity montre qui vous cite, et qui ne vous cite pas.",
         "Tracking Grok first delivers an audit of its answers: your category's key questions, what the assistant answers, your place against competitors and the errors to correct. It continues every month with the same questions, how the answers evolve, the sources cited and a note for communications. A comparison with ChatGPT, Claude, Gemini and Perplexity shows who cites you, and who does not."),
        ("Ce suivi ne dit pas tout. Grok s'appuie sur X et sur le web, et X n'est qu'un réseau parmi d'autres : une marque critiquée ailleurs mais peu discutée sur X peut sembler épargnée dans ses réponses, et l'inverse est vrai aussi. Ce que dit Grok ne remplace pas ce que disent vos clients eux-mêmes : cette conversation se lit avec l'écoute sociale, sur X comme sur les autres réseaux.",
         "This tracking does not tell everything. Grok relies on X and the web, and X is only one network among others: a brand criticised elsewhere but little discussed on X can seem spared in its answers, and the reverse is true too. What Grok says does not replace what your customers say themselves: that conversation is read through social listening, on X as on the other networks."),
    ]),
]
