"""Long-form detail for 11 of the 22 network pages (source-<slug>.html and
/fr/sources/<slug>/), to make them less thin and less alike: pinterest,
discord, twitch, telegram, bluesky, vk, wechat, weibo, douyin, xiaohongshu,
bilibili. Each network has exactly three blocks, in this order: what a brand
can actually read there, what makes listening there different, and the limits
of data access. Each block is ((heading FR, heading EN), (paragraph FR,
paragraph EN)). The text complements tools/networks.py and does not repeat it.

Sources rule: every public fact about a platform (features, API policy,
regulation, access) carries a `# source: <url>` comment above the block that
uses it. No invented figures, user counts, clients, results or quotes. Nothing
here claims access to private messages, private groups or closed servers.
"""

NET_DETAIL = {
    "pinterest": [
        (("Que peut-on lire sur Pinterest pour une marque ?", "What can a brand read on Pinterest?"),
         ("Sur Pinterest, on lit surtout des images et les mots qui les accompagnent : le titre d'une épingle, sa description, et le nom du tableau où elle est rangée. Ce nom est souvent le plus parlant. « Cuisine de la future maison » ou « Tenues mariage septembre » dit le projet, l'échéance et le style recherché. Les commentaires y sont rares. La conversation se lit donc moins dans les échanges que dans les gestes : ce qu'on enregistre, à côté de quoi, et pour quel projet. Une épingle de votre produit rangée avec celles d'un concurrent dit déjà comment on vous compare.",
          "On Pinterest, you mostly read images and the words that go with them: a Pin's title, its description, and the name of the board it is saved to. That name is often the most telling part. \"Future house kitchen\" or \"September wedding outfits\" states the project, the deadline and the style sought. Comments are rare. The conversation is therefore read less in exchanges than in gestures: what people save, next to what, and for which project. A Pin of your product saved alongside a competitor's already tells you how you are compared.")),
        # source: https://help.pinterest.com/business/article/pinterest-trends
        (("En quoi l'écoute de Pinterest est-elle différente ?", "How is listening on Pinterest different?"),
         ("Pinterest ne se lit pas comme un réseau de débat. On y vient pour soi, pour préparer quelque chose, rarement pour réagir à l'actualité ou interpeller une marque. Le ton est calme et le réseau se prête mal à la polémique. En revanche, Pinterest publie son propre outil, Pinterest Trends : les tendances de recherche, d'enregistrement et d'achat sur les deux dernières années, par région, avec une répartition par âge et par genre pour chaque mot-clé. Une marque s'en sert pour caler un calendrier saisonnier, ou pour comparer l'intérêt pour plusieurs styles avant de choisir lequel mettre en avant.",
          "Pinterest is not read like a network of debate. People come for themselves, to prepare something, rarely to react to the news or call out a brand. The tone is calm and the network lends itself poorly to controversy. On the other hand, Pinterest publishes its own tool, Pinterest Trends: search, save and shopping trends over the last two years, by region, with an age and gender breakdown for each keyword. A brand uses it to set a seasonal calendar, or to compare interest in several styles before choosing which one to push.")),
        # source: https://help.pinterest.com/en/articles/secret-boards
        # source: https://help.pinterest.com/business/article/pinterest-trends
        (("Quelles sont les limites des données Pinterest ?", "What are the limits of Pinterest data?"),
         ("Sur Pinterest, une partie de l'activité reste invisible. Les tableaux secrets ne sont vus que par leur auteur et les personnes qu'il invite, et une épingle enregistrée sur un tableau secret ne fait pas monter son compteur. Les recherches de chacun ne sont jamais publiques : Pinterest n'en montre que des tendances agrégées. Enfin, beaucoup d'épingles portent très peu de texte. Pour savoir si un produit apparaît, il faut souvent lire l'image elle-même, avec une reconnaissance visuelle, puis vérifier à la main ce que l'outil a cru reconnaître.",
          "On Pinterest, part of the activity stays invisible. Secret boards are seen only by their owner and the people they invite, and a Pin saved to a secret board does not raise its count. Individual searches are never public: Pinterest only shows aggregated trends. Finally, many Pins carry very little text. To know whether a product appears, you often have to read the image itself, with visual recognition, then check by hand what the tool thought it recognised.")),
    ],

    "discord": [
        (("Que peut-on lire sur Discord pour une marque ?", "What can a brand read on Discord?"),
         ("Sur Discord, la conversation est découpée en salons : annonces, entraide, retours, discussions libres, parfois un forum où chaque sujet a son propre fil. C'est cette structure qui rend la lecture utile. Le salon des retours d'un serveur de jeu, ou celui des questions techniques d'une communauté tech, rassemble des avis détaillés et argumentés, souvent écrits par des membres réguliers. On y lit ce qui bloque, ce qui manque, et ce que les plus engagés attendent de la suite. Le reste du serveur donne le contexte : le ton de la communauté, ses règles, et qui y fait autorité.",
          "On Discord, the conversation is split into channels: announcements, help, feedback, open discussion, sometimes a forum where each subject has its own thread. That structure is what makes reading useful. The feedback channel of a gaming server, or the technical questions channel of a tech community, gathers detailed, reasoned opinions, often written by regular members. You read what blocks people, what is missing, and what the most engaged expect next. The rest of the server gives the context: the community's tone, its rules, and who carries authority there.")),
        (("En quoi l'écoute de Discord est-elle différente ?", "How is listening on Discord different?"),
         ("Discord ne ressemble pas à un fil public. On n'y croise pas un inconnu par hasard : on rejoint un serveur parce qu'on partage un intérêt, et on y revient souvent. Les échanges sont rapides, pleins de références internes et de blagues que seuls les membres comprennent. Un sujet ne s'y diffuse pas par un algorithme, il passe d'un serveur à l'autre par les membres communs, puis sort parfois sous forme de captures d'écran. Pour une marque, l'usage type est le lancement : suivre la réaction des premiers utilisateurs, et repérer les membres dont l'avis compte pour les autres.",
          "Discord does not look like a public feed. You do not run into a stranger by chance: you join a server because you share an interest, and you come back often. Exchanges are fast, full of in-jokes and references only members understand. A subject does not spread there through an algorithm; it moves from one server to another through shared members, then sometimes leaves as screenshots. For a brand, the typical use is a launch: following the first users' reactions, and spotting the members whose opinion counts for the others.")),
        # source: https://support.discord.com/hc/en-us/articles/360030843331-Enabling-Server-Discovery
        # source: https://docs.discord.com/developers/gateway/you-might-not-need-a-privileged-intent
        (("Quelles sont les limites des données Discord ?", "What are the limits of Discord data?"),
         ("Discord n'a pas de partie publique au sens d'un réseau ouvert. Les serveurs visibles dans son annuaire sont des serveurs communautaires qui ont demandé à y figurer et qui remplissent ses critères. Côté technique, une application ne reçoit les données que des serveurs où elle a été ajoutée, et le contenu des messages fait partie des données que Discord classe comme « privilégiées » : leur accès doit être déclaré, puis validé par Discord au-delà d'une certaine taille. C'est pourquoi l'analyse d'un serveur passe par l'accord de ses administrateurs, et jamais par une collecte à leur insu.",
          "Discord has no public part in the sense of an open network. The servers visible in its directory are community servers that asked to be listed and meet its criteria. Technically, an app only receives data from the servers it has been added to, and message content is among the data Discord classes as \"privileged\": access to it must be declared, then approved by Discord beyond a certain size. That is why analysing a server goes through its administrators' consent, and never through collection behind their back.")),
    ],

    "twitch": [
        (("Que peut-on lire sur Twitch pour une marque ?", "What can a brand read on Twitch?"),
         ("Sur Twitch, il y a deux matières à lire. La première est le chat : des messages très courts, envoyés pendant le direct, souvent en rafale au même moment. La seconde est ce que dit le streamer lui-même, à l'oral, parfois pendant des heures : c'est là qu'un produit est montré, testé, commenté. Le titre du live et sa catégorie complètent le tableau. Les clips que les spectateurs découpent sont souvent le meilleur indice : ils signalent le moment que le public a jugé digne d'être gardé, puis partagé.",
          "On Twitch, there are two materials to read. The first is the chat: very short messages, sent during the stream, often in bursts at the same moment. The second is what the streamer says, out loud, sometimes for hours: that is where a product is shown, tested, discussed. The stream's title and category complete the picture. The clips viewers cut are often the best clue: they flag the moment the audience judged worth keeping, then sharing.")),
        (("En quoi l'écoute de Twitch est-elle différente ?", "How is listening on Twitch different?"),
         ("Twitch se lit dans le temps du direct. Une réaction n'y a de sens qu'à côté de ce qui se passe à l'écran à la même seconde : une blague, une annonce, une démonstration ratée. Le chat parle en émoticônes, en abréviations et en codes propres à chaque chaîne, et une même émoticône peut être ironique sur une chaîne et sincère sur une autre. La relation entre un streamer et sa communauté est longue et quotidienne. Pour une marque, la question est souvent de savoir si une intégration est acceptée par la communauté ou vécue comme une coupure publicitaire, et cela se lit dans le chat, à la minute près.",
          "Twitch is read in the time of the live stream. A reaction only makes sense next to what is happening on screen at the same second: a joke, an announcement, a failed demo. The chat speaks in emotes, abbreviations and codes specific to each channel, and the same emote can be ironic on one channel and sincere on another. The relationship between a streamer and their community is long and daily. For a brand, the question is often whether an integration is accepted by the community or felt as an ad break, and that is read in the chat, minute by minute.")),
        # source: https://dev.twitch.tv/docs/chat/
        # source: https://www.pcgamer.com/twitch-eliminates-save-forever-option-as-it-moves-to-improve-video-on-demand-service/
        (("Quelles sont les limites des données Twitch ?", "What are the limits of Twitch data?"),
         ("Twitch transmet son chat en temps réel aux applications connectées à une chaîne. Concrètement, un chat qui n'a pas été capté pendant le live est difficile à reconstituer ensuite. Les rediffusions ne restent en ligne que pour une durée limitée, qui dépend du statut de la chaîne, et le streamer peut choisir de ne pas les conserver. La parole du streamer, elle, n'existe qu'en vidéo : il faut la transcrire pour pouvoir la chercher. Une étude Twitch se prépare donc avant le live, avec la liste des chaînes et des dates à suivre, et pas après coup.",
          "Twitch delivers its chat in real time to the apps connected to a channel. In practice, a chat that was not captured during the stream is hard to rebuild afterwards. Past broadcasts stay online only for a limited time, which depends on the channel's status, and the streamer can choose not to keep them. The streamer's speech exists only as video: it has to be transcribed before it can be searched. A Twitch study is therefore prepared before the stream, with the list of channels and dates to follow, not after the fact.")),
    ],

    "telegram": [
        # source: https://telegram.org/tour/channels
        # source: https://core.telegram.org/api/channel
        (("Que peut-on lire sur Telegram pour une marque ?", "What can a brand read on Telegram?"),
         ("Sur Telegram, la partie lisible est celle des canaux publics et des groupes publics. Un canal est un fil de diffusion : un administrateur publie, les abonnés lisent. Chaque publication y porte un compteur de vues, qui inclut les vues des copies transférées ailleurs. Quand l'administrateur a relié un groupe de discussion au canal, les publications reçoivent aussi des commentaires. On lit donc à la fois ce qui est diffusé, l'audience que cela a touchée, et ce qu'en disent les abonnés qui réagissent. Les groupes publics, eux, ressemblent davantage à un forum en continu.",
          "On Telegram, the readable part is public channels and public groups. A channel is a broadcast feed: an administrator posts, subscribers read. Each post carries a view counter, which includes views of copies forwarded elsewhere. When the administrator has linked a discussion group to the channel, posts also get comments. You therefore read what is broadcast, the audience it reached, and what the subscribers who react say about it. Public groups, for their part, look more like a continuous forum.")),
        (("En quoi l'écoute de Telegram est-elle différente ?", "How is listening on Telegram different?"),
         ("Telegram ne fonctionne pas comme TikTok ou X. Il n'a pas de fil principal piloté par un algorithme : un message y circule surtout parce qu'il est transféré, de canal en canal et de groupe en groupe. Suivre un sujet sur Telegram, c'est donc suivre ces chaînes de transfert et repérer les canaux qui servent de relais. Son poids varie beaucoup selon les pays et les sujets. Pour une marque, l'usage type est la veille de risque : une fuite de documents, une arnaque qui usurpe son nom, une rumeur qui part de là avant d'atteindre les autres réseaux.",
          "Telegram does not work like TikTok or X. It has no main feed driven by an algorithm: a message travels mostly because it is forwarded, from channel to channel and group to group. Following a subject on Telegram therefore means following those forwarding chains and spotting the channels that act as relays. Its weight varies a lot by country and topic. For a brand, the typical use is risk monitoring: a document leak, a scam impersonating its name, a rumour that starts there before reaching other networks.")),
        # source: https://telegram.org/tour/channels
        # source: https://core.telegram.org/api/channel
        (("Quelles sont les limites des données Telegram ?", "What are the limits of Telegram data?"),
         ("Sur Telegram, la frontière entre public et privé est nette. Le contenu d'un canal public peut se lire sur le web sans compte, et il est indexé par les moteurs de recherche. Un canal ou un groupe privé, accessible seulement par un lien d'invitation, reste fermé, comme les conversations entre personnes. Un nouveau canal naît d'ailleurs privé : c'est son administrateur qui choisit de l'ouvrir. Les groupes publics demandent enfin un vrai tri : les messages y sont nombreux, courts, souvent hors sujet, et une mention isolée ne fait pas une tendance.",
          "On Telegram, the line between public and private is clear. The content of a public channel can be read on the web without an account, and it is indexed by search engines. A private channel or group, reachable only through an invite link, stays closed, like conversations between people. A new channel is in fact born private: its administrator chooses to open it. Public groups, finally, need real sorting: messages there are many, short, often off topic, and an isolated mention does not make a trend.")),
    ],

    "bluesky": [
        # source: https://bsky.network/docs/protocol-services
        # source: https://bsky.social/about/blog/7-27-2023-custom-feeds
        (("Que peut-on lire sur Bluesky pour une marque ?", "What can a brand read on Bluesky?"),
         ("Sur Bluesky, l'essentiel de l'activité est public : les messages, les réponses, les citations, les mentions j'aime et les abonnements. Le format ressemble à celui de X, avec des messages courts et des fils de discussion. Les fils personnalisés sont une particularité utile. N'importe qui peut créer un fil thématique, sur un métier, une science ou un secteur, que d'autres choisissent de suivre. Repérer ceux qui touchent votre catégorie permet de voir où se retrouvent les personnes qui en parlent avec compétence, et ce qu'elles mettent en avant.",
          "On Bluesky, most of the activity is public: posts, replies, quotes, likes and follows. The format resembles X, with short posts and threads. Custom feeds are a useful feature. Anyone can create a themed feed, on a profession, a science or a sector, that others choose to follow. Spotting the ones that touch your category shows where the people who discuss it knowledgeably gather, and what they highlight.")),
        (("En quoi l'écoute de Bluesky est-elle différente ?", "How is listening on Bluesky different?"),
         ("Bluesky réunit un public plus resserré que X, où l'on trouve beaucoup de journalistes, de chercheurs et de communautés engagées, qui y discutent souvent entre pairs. Le ton y est plus conversationnel, et les échanges se font davantage par réponses et citations que par reprises massives. Un sujet y circule de compte en compte, puis remonte dans les fils thématiques qui le concernent. Pour une marque, c'est souvent là que se lit la réaction des experts de son secteur à une annonce, dans leurs propres mots, avant ou à côté de ce qu'ils publient ailleurs.",
          "Bluesky gathers a narrower audience than X, with many journalists, researchers and committed communities, who often talk among peers. The tone is more conversational, and exchanges happen more through replies and quotes than through mass reposting. A subject travels from account to account, then rises in the themed feeds that concern it. For a brand, it is often where the reaction of its sector's experts to an announcement can be read, in their own words, before or alongside what they publish elsewhere.")),
        # source: https://bsky.network/docs/protocol-services
        # source: https://bsky.social/about/blog/05-22-2024-direct-messages
        # source: https://anderegg.ca/2024/05/23/digging-into-bluesky-dms
        (("Quelles sont les limites des données Bluesky ?", "What are the limits of Bluesky data?"),
         ("Bluesky repose sur un protocole ouvert, l'AT Protocol. Toutes les données publiques du réseau, messages, mentions j'aime et graphe des abonnements, y sont accessibles par un flux continu documenté, que n'importe quel développeur peut lire. Pour l'écoute, c'est un accès rare. Les messages privés, eux, ne passent pas par ce protocole public : Bluesky les gère à part. La vraie limite est ailleurs, dans la taille du réseau et la composition de son public. Un faible volume de mentions ne veut pas dire que le sujet n'existe pas, mais peut-être qu'il se discute sur d'autres réseaux.",
          "Bluesky runs on an open protocol, the AT Protocol. All the network's public data, posts, likes and the follow graph, is available through a documented continuous stream that any developer can read. For listening, that is rare access. Direct messages do not go through this public protocol: Bluesky handles them separately. The real limit lies elsewhere, in the network's size and the make-up of its audience. A low volume of mentions does not mean the subject does not exist, but perhaps that it is discussed on other networks.")),
    ],

    "vk": [
        # source: https://dev.vk.ru/en/wall.get
        (("Que peut-on lire sur VK pour une marque ?", "What can a brand read on VK?"),
         ("Sur VK, la conversation publique se lit surtout sur les murs. Chaque page et chaque communauté a son mur, où l'administrateur publie et où, selon les réglages, les membres peuvent publier aussi, avec des commentaires sous chaque message. Les communautés sont très variées : fans d'une marque, acheteurs d'une catégorie, villes, quartiers, bons plans. VK sert aussi de plateforme vidéo et de messagerie. Pour une marque, la matière la plus utile est souvent dans les communautés de consommateurs, où les gens se conseillent entre eux, et dans les messages laissés par les membres sur les murs des pages officielles.",
          "On VK, the public conversation is mostly read on walls. Every page and every community has a wall, where the administrator posts and where, depending on the settings, members can post too, with comments under each post. Communities are very diverse: fans of a brand, buyers in a category, cities, neighbourhoods, deals. VK also works as a video platform and a messenger. For a brand, the most useful material is often in consumer communities, where people advise each other, and in the posts members leave on official pages' walls.")),
        # source: https://www.opb.org/article/2022/03/11/russia-widens-social-media-crackdown-by-blocking-instagram/
        # source: https://www.hrw.org/news/2017/05/16/ukraine-revoke-ban-dozens-russian-web-companies
        (("En quoi l'écoute de VK est-elle différente ?", "How is listening on VK different?"),
         ("VK s'écoute dans un contexte particulier. En Russie, l'accès à Facebook et à Instagram est bloqué depuis mars 2022, ce qui change la répartition de la conversation entre les réseaux. À l'inverse, l'Ukraine a bloqué l'accès à VK par décret en 2017. La conversation lue sur VK ne représente donc pas tous les russophones, et son poids diffère d'un pays à l'autre. Pour une marque, l'usage type est de comprendre comment elle est perçue sur un marché où ses propres comptes sont peut-être absents ou à l'arrêt, à partir de ce que les consommateurs disent sans elle.",
          "VK is listened to in a particular context. In Russia, access to Facebook and Instagram has been blocked since March 2022, which changes how the conversation is spread across networks. Conversely, Ukraine blocked access to VK by decree in 2017. The conversation read on VK therefore does not represent all Russian speakers, and its weight differs from one country to another. For a brand, the typical use is understanding how it is perceived in a market where its own accounts may be absent or dormant, from what consumers say without it.")),
        # source: https://dev.vk.ru/en/wall.get
        (("Quelles sont les limites des données VK ?", "What are the limits of VK data?"),
         ("VK propose une API officielle qui permet de lire les murs des pages et des communautés publiques, avec une clé d'accès. Les profils fermés, les communautés privées et les messages restent hors de portée. Ce que l'API rend possible ne l'est pas forcément dans les plateformes d'écoute du marché : leur couverture de VK varie d'un éditeur à l'autre, et elle peut changer. VK n'est enfin qu'une partie du web russophone. Telegram, les sites d'avis et les médias en ligne complètent souvent la lecture, et un sujet absent de VK peut très bien vivre ailleurs.",
          "VK offers an official API that lets you read the walls of public pages and communities, with an access key. Closed profiles, private communities and messages stay out of reach. What the API makes possible is not necessarily available in the listening platforms on the market: their VK coverage varies from one publisher to another, and it can change. VK, finally, is only one part of the Russian-speaking web. Telegram, review sites and online media often complete the reading, and a subject absent from VK may well live elsewhere.")),
    ],

    "wechat": [
        # source: https://weixin.sogou.com/
        (("Que peut-on lire sur WeChat pour une marque ?", "What can a brand read on WeChat?"),
         ("Sur WeChat, la partie publique est faite d'articles publiés par des comptes officiels : marques, médias, institutions, mais aussi auteurs indépendants qui écrivent sur la beauté, l'automobile, la finance ou le luxe. Ce sont souvent de vrais articles de fond, avec un point de vue et une signature. Sous chaque article, on peut lire les commentaires affichés et des indicateurs d'audience. Une partie de ces articles est aussi indexée par le moteur de recherche chinois Sogou, qui permet de les retrouver hors de l'application. Pour une marque, c'est la lecture la plus proche d'une revue de presse spécialisée.",
          "On WeChat, the public part is made of articles published by official accounts: brands, media, institutions, but also independent writers covering beauty, cars, finance or luxury. They are often real in-depth articles, with a point of view and a byline. Under each article, you can read the displayed comments and audience indicators. Part of these articles is also indexed by the Chinese search engine Sogou, which makes them findable outside the app. For a brand, it is the reading closest to a specialist press review.")),
        (("En quoi l'écoute de WeChat est-elle différente ?", "How is listening on WeChat different?"),
         ("WeChat est d'abord une messagerie. La plupart des échanges y ont lieu dans des conversations privées et des groupes, et c'est par là que les articles circulent : on les partage à un ami, dans un groupe, dans ses Moments. Un article ne se diffuse pas par un fil public mais par ces partages entre proches. Pour l'écoute, cela veut dire qu'on voit le point de départ, l'article, sans voir tout le chemin qu'il a fait. L'usage type pour une marque est de lire comment les médias et les comptes spécialisés chinois racontent sa catégorie, ses concurrents et ses prises de parole.",
          "WeChat is a messenger first. Most exchanges happen in private chats and groups, and that is how articles travel: shared with a friend, in a group, in one's Moments. An article does not spread through a public feed but through these shares between people who know each other. For listening, that means you see the starting point, the article, without seeing the whole path it took. The typical use for a brand is reading how Chinese media and specialist accounts tell the story of its category, its competitors and its announcements.")),
        # source: https://walkthechat.com/new-wechat-comments-function-subscription-accounts/
        # source: https://developers.weixin.qq.com/doc/service/en/api/leaving/api_listcomment
        # source: https://www.jonesday.com/en/insights/2021/09/highlights-of-chinas-new-personal-information-protection-law
        (("Quelles sont les limites des données WeChat ?", "What are the limits of WeChat data?"),
         ("WeChat laisse au compte qui publie la main sur ses commentaires. Le propriétaire d'un compte officiel peut mettre des commentaires en avant, les masquer ou les supprimer, et selon ses réglages, ils peuvent devoir être validés avant d'apparaître. Les commentaires visibles ne sont donc pas forcément tous ceux qui ont été écrits. Les Moments ne sont visibles que par les contacts, et les groupes ne se consultent pas de l'extérieur. Enfin, la collecte de données personnelles en Chine est encadrée par la loi sur la protection des informations personnelles, en vigueur depuis novembre 2021, y compris pour leur transfert hors du pays.",
          "WeChat leaves the publishing account in control of its comments. An official account's owner can feature comments, hide them or delete them, and depending on its settings, they may have to be approved before appearing. The visible comments are therefore not necessarily all those that were written. Moments are visible only to contacts, and groups cannot be viewed from outside. Finally, collecting personal data in China is governed by the Personal Information Protection Law, in force since November 2021, including for transfers out of the country.")),
    ],

    "weibo": [
        # source: https://abc17news.com/money/cnn-social-media-technology/2022/04/28/chinas-weibo-shows-user-locations-to-combat-bad-behavior/
        (("Que peut-on lire sur Weibo pour une marque ?", "What can a brand read on Weibo?"),
         ("Sur Weibo, on lit des messages publics, courts ou longs, avec images et vidéos, leurs commentaires et leurs repartages. Les sujets se regroupent sous des mots-dièse encadrés de deux signes #, qui ont chacun leur page. Le classement des recherches les plus populaires, le « hot search », montre ce qui occupe le pays à un moment donné. Depuis avril 2022, Weibo affiche aussi la province de l'auteur d'un message ou d'un commentaire, ou son pays s'il publie depuis l'étranger. On peut donc lire la géographie d'une réaction, et voir si une critique vient d'une région, de tout le pays, ou de l'étranger.",
          "On Weibo, you read public posts, short or long, with images and videos, their comments and their reposts. Subjects gather under hashtags framed by two # signs, each with its own page. The ranking of the most popular searches, the \"hot search\", shows what occupies the country at a given moment. Since April 2022, Weibo also displays the province of the author of a post or comment, or their country if they post from abroad. You can therefore read the geography of a reaction, and see whether a criticism comes from one region, the whole country, or abroad.")),
        (("En quoi l'écoute de Weibo est-elle différente ?", "How is listening on Weibo different?"),
         ("Weibo est le réseau où le débat public chinois devient visible. Les célébrités, les médias officiels, les comptes d'influence et les marques y parlent tous au même endroit, et un sujet peut passer d'un fil de fans au classement national. Les communautés de fans y sont très organisées : elles peuvent défendre une marque liée à leur idole, ou s'en détourner en bloc. Pour une marque étrangère, l'usage type est la veille de sujets sensibles : une publicité mal reçue, un ambassadeur pris dans une polémique, une prise de position jugée offensante, qui peuvent devenir une affaire nationale.",
          "Weibo is the network where China's public debate becomes visible. Celebrities, official media, influencer accounts and brands all speak in the same place, and a subject can move from a fan thread to the national ranking. Fan communities there are highly organised: they can defend a brand linked to their idol, or turn away from it en masse. For a foreign brand, the typical use is monitoring sensitive subjects: a poorly received ad, an ambassador caught in a controversy, a stance judged offensive, any of which can become a national affair.")),
        # source: https://www.sixthtone.com/news/1005795
        (("Quelles sont les limites des données Weibo ?", "What are the limits of Weibo data?"),
         ("Weibo est un espace public très encadré. Le classement des tendances n'y est pas un simple reflet du volume : il est soumis à la régulation. En juin 2020, le régulateur chinois d'internet a ainsi imposé à Weibo de suspendre pendant une semaine la mise à jour de ses classements de sujets populaires. Des messages peuvent être retirés, des mots-dièse disparaître, des commentaires être fermés. Lire Weibo, c'est donc aussi noter ce qui n'apparaît pas, ou plus, et ne pas confondre l'absence d'un sujet dans les résultats avec l'absence de conversation.",
          "Weibo is a tightly supervised public space. Its trending ranking is not a simple reflection of volume: it is subject to regulation. In June 2020, China's internet regulator ordered Weibo to suspend updates to its trending topic rankings for a week. Posts can be removed, hashtags can disappear, comments can be closed. Reading Weibo therefore also means noting what does not appear, or no longer does, and not confusing a subject's absence from the results with an absence of conversation.")),
    ],

    "douyin": [
        (("Que peut-on lire sur Douyin pour une marque ?", "What can a brand read on Douyin?"),
         ("Sur Douyin, on lit des vidéos courtes, leurs descriptions, leurs mots-dièse et leurs commentaires, mais aussi des directs de vente où un créateur présente des produits, avec un lien d'achat. Les avis s'y lisent dans les commentaires sous les vidéos de démonstration, et dans le chat des directs, où les acheteurs posent leurs questions en temps réel : prix, taille, livraison, comparaison avec une autre marque. Ces questions disent ce qui freine l'achat. Les classements de sujets populaires de Douyin donnent en plus l'état du moment, et la place que votre catégorie y occupe.",
          "On Douyin, you read short videos, their descriptions, hashtags and comments, but also live selling streams where a creator presents products, with a purchase link. Opinions are read in the comments under demo videos, and in the live chat, where buyers ask their questions in real time: price, size, delivery, comparison with another brand. Those questions say what holds a purchase back. Douyin's popular topic rankings also give the state of the moment, and the place your category holds in it.")),
        # source: https://www.whatsonweibo.com/are-douyin-and-tiktok-the-same/
        (("En quoi l'écoute de Douyin est-elle différente ?", "How is listening on Douyin different?"),
         ("Douyin et TikTok appartiennent au même groupe, mais les comptes et les contenus des deux applications sont séparés, et Douyin applique les règles chinoises sur les contenus. Une tendance y suit donc son propre chemin, avec ses propres créateurs. Le commerce y est beaucoup plus intégré : on passe de la vidéo ou du direct à l'achat sans quitter l'application. La frontière entre contenu et vente y est donc floue. Pour une marque, l'usage type est le lancement en Chine : suivre quels créateurs présentent le produit, comment il est démontré, et ce que les acheteurs en disent après l'avoir reçu.",
          "Douyin and TikTok belong to the same group, but the two apps' accounts and content are separate, and Douyin applies Chinese content rules. A trend there follows its own path, with its own creators. Commerce is far more integrated: you go from a video or a live stream to a purchase without leaving the app. The line between content and selling is therefore blurred. For a brand, the typical use is a launch in China: following which creators present the product, how it is demonstrated, and what buyers say about it once they have received it.")),
        # source: https://www.whatsonweibo.com/are-douyin-and-tiktok-the-same/
        # source: https://www.jonesday.com/en/insights/2021/09/highlights-of-chinas-new-personal-information-protection-law
        (("Quelles sont les limites des données Douyin ?", "What are the limits of Douyin data?"),
         ("Douyin est une application pensée pour le marché chinois : les magasins d'applications chinois proposent Douyin, les magasins internationaux proposent TikTok. Les plateformes d'écoute occidentales le couvrent de façon inégale, et chaque étude commence par vérifier ce qui est réellement collecté. Les directs de vente posent un problème à part : ce qui s'y dit se capte surtout pendant la diffusion. Et comme pour les autres plateformes chinoises, la collecte de données personnelles d'utilisateurs en Chine relève de la loi chinoise sur la protection des informations personnelles. Nous travaillons sur des contenus publics, sans chercher à identifier les personnes.",
          "Douyin is an app designed for the Chinese market: Chinese app stores offer Douyin, international stores offer TikTok. Western listening platforms cover it unevenly, and every study starts by checking what is actually collected. Live selling streams raise a separate problem: what is said there is mostly captured during the broadcast. And as with other Chinese platforms, collecting personal data of users in China falls under China's Personal Information Protection Law. We work on public content, without seeking to identify individuals.")),
    ],

    "xiaohongshu": [
        (("Que peut-on lire sur Xiaohongshu pour une marque ?", "What can a brand read on Xiaohongshu?"),
         ("Sur Xiaohongshu, l'unité de base est la note : quelques photos ou une courte vidéo, un titre accrocheur, et un texte souvent long qui raconte un usage, compare des produits ou donne une liste de conseils. Sous chaque note, les commentaires posent des questions précises : le prix, la taille, le type de peau, où l'acheter. Les réponses de l'auteur et des autres lecteurs complètent l'avis. Les notes sont faites pour être retrouvées : leur titre reprend souvent les mots que les gens tapent dans la recherche. Lire ces titres, c'est lire la manière dont le public formule ses besoins.",
          "On Xiaohongshu, the basic unit is the note: a few photos or a short video, a catchy title, and an often long text that describes a use, compares products or gives a list of tips. Under each note, comments ask precise questions: price, size, skin type, where to buy. Replies from the author and other readers complete the review. Notes are made to be found: their title often uses the words people type into search. Reading those titles means reading how the public phrases its needs.")),
        # source: https://jingdaily.com/intels/2024-12/16/xiaohongshu-search-volume-doubles-baidu-s-lead-shrinks
        # source: https://kr-asia.com/xiaohongshu-sues-ghostwriter-brokers-over-fraudulent-promotional-content
        (("En quoi l'écoute de Xiaohongshu est-elle différente ?", "How is listening on Xiaohongshu different?"),
         ("Xiaohongshu est utilisé comme un moteur de recherche autant que comme un réseau social, par un public plutôt jeune, urbain et majoritairement féminin. Le ton est celui du conseil entre pairs, détaillé et pratique, rarement celui du débat. Mais la plateforme dit lutter contre les fausses notes rémunérées, présentées comme des avis spontanés, et a déjà sanctionné des marques et des intermédiaires pour cela. Lire Xiaohongshu demande donc de distinguer l'avis sincère de la promotion déguisée. Pour une marque, l'usage type est de comparer, produit par produit, ce qui est vraiment loué et ce qui revient comme reproche.",
          "Xiaohongshu is used as a search engine as much as a social network, by a rather young, urban and mostly female audience. The tone is peer advice, detailed and practical, rarely debate. But the platform says it fights paid fake notes presented as spontaneous reviews, and has already sanctioned brands and middlemen for it. Reading Xiaohongshu therefore means telling a sincere review from disguised promotion. For a brand, the typical use is comparing, product by product, what is genuinely praised and what keeps coming back as criticism.")),
        # source: https://www.bellingcat.com/resources/2026/04/20/xiaohongshu-rednote-open-source-guide/
        (("Quelles sont les limites des données Xiaohongshu ?", "What are the limits of Xiaohongshu data?"),
         ("Xiaohongshu n'offre pas d'accès ouvert comparable à celui de Bluesky. Ce que l'on y voit dépend aussi de qui regarde : selon un guide publié par Bellingcat, la langue de recherche et l'usage d'un compte international changent la version de la plateforme que l'on voit, et les filtres de recherche restent sommaires. Une écoute sérieuse se fait donc en chinois, du point de vue d'un utilisateur chinois, en croisant plusieurs formulations d'une même requête. Les messages et les comptes privés restent hors de portée, et nous ne lisons que les notes publiques.",
          "Xiaohongshu offers no open access comparable to Bluesky's. What you see also depends on who is looking: according to a guide published by Bellingcat, the search language and the use of an international account change the version of the platform you see, and search filters remain basic. Serious listening is therefore done in Chinese, from a Chinese user's point of view, crossing several phrasings of the same query. Messages and private accounts stay out of reach, and we only read public notes.")),
    ],

    "bilibili": [
        (("Que peut-on lire sur Bilibili pour une marque ?", "What can a brand read on Bilibili?"),
         ("Sur Bilibili, on lit des vidéos souvent longues et construites : tests détaillés, comparatifs, tutoriels, analyses. Deux couches de réactions s'y superposent. Les commentaires défilants, attachés à une seconde précise de la vidéo, disent ce qui fait réagir à l'instant. Les commentaires classiques, sous la vidéo, sont plus argumentés et donnent l'avis d'ensemble. Un test de produit y est donc lu à la fois globalement et moment par moment : le passage où le prix est annoncé, celui où le produit est démonté, celui où le créateur rend son verdict.",
          "On Bilibili, you read videos that are often long and structured: detailed tests, comparisons, tutorials, analyses. Two layers of reactions overlap. Scrolling comments, pinned to a precise second of the video, say what triggers a reaction in the moment. Regular comments, under the video, are more reasoned and give the overall opinion. A product test is therefore read both as a whole and moment by moment: the part where the price is announced, the part where the product is taken apart, the part where the creator gives a verdict.")),
        # source: https://ir.bilibili.com/
        # source: https://www.goldthread2.com/culture/gain-full-access-these-videos-you-must-pass-exam-100-very-niche-questions/article/2157030
        (("En quoi l'écoute de Bilibili est-elle différente ?", "How is listening on Bilibili different?"),
         ("Bilibili se présente comme une communauté vidéo pour les jeunes générations chinoises, née autour de l'animation, de la bande dessinée et du jeu vidéo. Cette communauté a ses codes et y tient : Bilibili a longtemps demandé aux nouveaux venus de réussir un questionnaire sur les règles du site et sa culture pour accéder à toutes les fonctions, dont les commentaires défilants. Le public y repère vite une publicité déguisée, et le dit. Pour une marque, l'usage type est de tester un message auprès de ce public exigeant, à travers les créateurs qu'il suit et respecte.",
          "Bilibili presents itself as a video community for China's young generations, born around animation, comics and gaming. This community has its codes and cares about them: Bilibili long required newcomers to pass a quiz on the site's rules and culture to unlock all features, scrolling comments included. The audience quickly spots disguised advertising, and says so. For a brand, the typical use is testing a message with this demanding audience, through the creators it follows and respects.")),
        (("Quelles sont les limites des données Bilibili ?", "What are the limits of Bilibili data?"),
         ("Bilibili pose d'abord une question de méthode. Sur une vidéo populaire, les commentaires défilants peuvent être très nombreux, très courts, souvent répétés à l'identique, et ils n'ont de sens qu'à côté de l'image. Les lire en bloc, comme un corpus de textes, fait perdre l'essentiel : on les lit plutôt par moments clés, en revenant à la vidéo. Ensuite, toutes les plateformes d'écoute ne collectent pas ces commentaires défilants, et il faut le vérifier avant de promettre une analyse. Enfin, les messages entre membres et les contenus réservés restent fermés.",
          "Bilibili first raises a question of method. On a popular video, scrolling comments can be very numerous, very short, often repeated word for word, and they only make sense next to the image. Reading them in bulk, like a body of text, loses the essentials: they are rather read by key moments, going back to the video. Next, not every listening platform collects these scrolling comments, and that must be checked before promising an analysis. Finally, messages between members and restricted content stay closed.")),
    ],
}
