"""Long-form detail for ten network pages (source-<slug>.html and
/fr/sources/<slug>/), batch A: facebook, instagram, threads, whatsapp,
messenger, x-twitter, youtube, linkedin, reddit, snapchat.

The 22 network pages built from tools/networks.py were thin and close to each
other. Each entry here adds three blocks specific to the network, written to
complement (not repeat) its lead, cards, access and limits in networks.py:
(1) what can actually be read there for a brand, (2) what makes it different
for listening, (3) the limits of data access. Each block is
((heading FR, heading EN), (paragraph FR, paragraph EN)); the first sentence
of every paragraph restates the network name.

Sources rule: no invented figures, clients, results or quotes. Every public
fact about a platform (API access, research programmes, encryption,
retention) carries a `# source:` comment with the page it was checked
against; anything unsure or likely to change is phrased generally or left
out. We never claim access to private messages.
"""

NET_DETAIL = {
    "facebook": [
        # source: https://about.fb.com/news/2019/08/groups-privacy-settings/
        (("Que peut-on écouter sur Facebook ?", "What can you listen to on Facebook?"),
         ("Sur Facebook, la conversation sur une marque se lit à plusieurs endroits à la fois. Il y a les publications des pages, mais surtout les fils de commentaires, où les clients se répondent entre eux et se donnent des conseils. Il y a les groupes publics, dont les membres et les publications sont visibles par tous, sans y adhérer. Il y a enfin les pages de médias locaux, de quartiers ou d'associations, où un magasin ou un service est souvent discuté sans que la marque y soit présente. Une écoute utile lit ces espaces ensemble, pas seulement la page officielle.",
          "On Facebook, the conversation about a brand is read in several places at once. There are page posts, but above all comment threads, where customers answer each other and swap advice. There are public groups, whose members and posts anyone can see without joining. And there are pages run by local media, neighbourhoods or associations, where a shop or a service is often discussed without the brand being there. Useful listening reads these spaces together, not only the official page.")),
        # source: https://about.fb.com/news/2023/08/new-features-and-additional-transparency-measures-as-the-digital-services-act-comes-into-effect/
        (("Qu'est-ce qui distingue l'écoute de Facebook ?", "What makes listening on Facebook different?"),
         ("Facebook est un réseau de conversation lente. Un sujet y avance moins vite que sur X, mais il dure : un fil de commentaires peut rester actif plusieurs jours, et une publication ancienne peut revenir quand quelqu'un la partage à nouveau. Le ton est direct, souvent personnel, avec des récits d'expérience détaillés. Facebook offre aussi un repère public : en Europe, la Bibliothèque publicitaire de Meta montre toutes les publicités diffusées, archivées un an après leur dernière diffusion. On peut ainsi relier la campagne d'un concurrent aux réactions qu'elle suscite dans les commentaires.",
          "Facebook is a slow conversation network. A topic moves more slowly there than on X, but it lasts: a comment thread can stay active for several days, and an old post can come back when someone shares it again. The tone is direct, often personal, with detailed accounts of experience. Facebook also offers a public reference point: in Europe, Meta's Ad Library shows every ad delivered, archived for a year after its last delivery. You can therefore link a competitor's campaign to the reactions it draws in the comments.")),
        # source: https://transparency.meta.com/en-gb/researchtools/meta-content-library/
        # source: https://www.opb.org/article/2024/08/14/meta-shutters-tool-used-to-fight-disinformation-despite-outcry
        (("Qu'est-ce qu'on ne peut pas voir sur Facebook ?", "What can't you see on Facebook?"),
         ("Facebook garde fermée une grande partie de ce qui s'y dit. Les groupes privés ne montrent leurs publications qu'à leurs membres, et beaucoup de profils ne partagent leurs messages qu'avec leurs amis. Une page peut aussi masquer ou supprimer des commentaires : la conversation visible est déjà filtrée. Côté accès, Meta a fermé CrowdTangle en août 2024 au profit de la Meta Content Library, réservée aux chercheurs d'organismes académiques ou à but non lucratif. Ce n'est pas un outil de veille pour les marques. Les outils d'écoute passent par leurs propres accès, et nous vérifions leur couverture avant chaque étude.",
          "Facebook keeps much of what is said there closed. Private groups only show their posts to members, and many profiles only share their posts with friends. A page can also hide or delete comments: the visible conversation is already filtered. On access, Meta shut down CrowdTangle in August 2024 in favour of the Meta Content Library, reserved for researchers at academic or not-for-profit organisations. It is not a monitoring tool for brands. Listening tools rely on their own access, and we check their coverage before every study.")),
    ],

    "instagram": [
        (("Que peut-on lire sur Instagram pour une marque ?", "What can a brand read on Instagram?"),
         ("Instagram mêle plusieurs formats, et chacun dit autre chose d'une marque. Les publications et les carrousels montrent comment un produit est mis en scène, les reels comment un format se diffuse et se copie d'un compte à l'autre. Les identifications et les mentions indiquent qui associe volontairement votre marque à son contenu. Les commentaires, eux, se trouvent souvent sous les publications des créateurs plutôt que sous celles de la marque. Une écoute utile part donc de la marque, puis remonte vers les comptes qui en parlent, là où le public s'exprime le plus librement.",
          "Instagram mixes several formats, and each says something different about a brand. Posts and carousels show how a product is staged, reels how a format spreads and gets copied from one account to the next. Tags and mentions show who deliberately links your brand to their content. Comments, for their part, often sit under creators' posts rather than the brand's own. Useful listening therefore starts from the brand, then works back to the accounts that talk about it, where the audience speaks most freely.")),
        (("En quoi l'écoute d'Instagram est-elle différente ?", "How is listening on Instagram different?"),
         ("Instagram organise la conversation autour de personnes plus que de sujets. Un produit y gagne en visibilité quand des créateurs le montrent, et la discussion suit leur audience. Le ton y est souvent plus mis en scène qu'ailleurs : l'enthousiasme s'affiche, la critique passe plutôt par l'ironie, la comparaison ou une question en commentaire. Pour une marque, l'usage typique est d'évaluer une campagne avec des créateurs : qui a repris le sujet, ce que les abonnés ont répondu, et si l'univers dans lequel la marque apparaît correspond à celui qu'elle vise.",
          "Instagram organises the conversation around people more than topics. A product gains visibility when creators show it, and the discussion follows their audience. The tone is often more staged than elsewhere: enthusiasm is on display, while criticism tends to come through irony, comparison or a question in the comments. For a brand, the typical use is to assess a campaign with creators: who picked up the subject, what followers replied, and whether the world the brand appears in matches the one it is aiming for.")),
        # source: https://help.instagram.com/1729008150678239/
        # source: https://developers.facebook.com/documentation/instagram-platform/instagram-api-with-facebook-login/hashtag-search
        (("Qu'est-ce qui échappe à l'écoute d'Instagram ?", "What escapes listening on Instagram?"),
         ("Instagram limite ce qu'une écoute peut voir. Les comptes privés et les messages restent fermés, et les stories disparaissent au bout de 24 heures, sauf si leur auteur les met à la une. L'accès officiel est aussi encadré : l'API de recherche par hashtag de Meta demande une validation, se limite à 30 hashtags différents par période glissante de sept jours pour un même compte, et ne couvre pas les hashtags des stories. Les outils d'écoute combinent donc plusieurs accès, avec une couverture qui varie. Nous indiquons ce qui est réellement collecté avant de commencer.",
          "Instagram limits what listening can see. Private accounts and messages stay closed, and stories disappear after 24 hours unless their author adds them to highlights. Official access is also restricted: Meta's hashtag search API requires approval, is limited to 30 different hashtags per rolling seven-day period for a given account, and does not cover hashtags in stories. Listening tools therefore combine several access routes, with coverage that varies. We state what is actually collected before starting.")),
    ],

    "threads": [
        # source: https://techcrunch.com/2024/09/12/threads-makes-it-easier-to-evangelize-the-open-social-web-with-a-new-direct-link-feature
        (("Que peut-on lire sur Threads ?", "What can you read on Threads?"),
         ("Threads s'organise autour de publications courtes, de leurs réponses et de leurs citations. C'est dans les réponses que se joue l'essentiel : une publication de marque y reçoit des questions, des critiques et des comparaisons, parfois de comptes qui ne la suivent pas. Les sujets, signalés par un mot-clé, regroupent les discussions sur un même thème. Threads est aussi relié au fédivers : quand un utilisateur active ce partage, ses publications publiques peuvent être lues sur des services comme Mastodon. Une partie de la conversation circule donc hors de l'application.",
          "Threads is built around short posts, their replies and their quotes. Most of what matters happens in the replies: a brand post gets questions, criticism and comparisons there, sometimes from accounts that do not follow it. Topics, marked by a keyword, group discussions on the same theme. Threads is also connected to the fediverse: when a user turns on this sharing, their public posts can be read on services such as Mastodon. Part of the conversation therefore travels outside the app.")),
        (("Faut-il écouter Threads différemment de X ?", "Should you listen to Threads differently from X?"),
         ("Threads ne se lit pas comme X, même si les formats se ressemblent. Son public vient en partie d'Instagram, et le ton s'en rapproche souvent : plus personnel, moins tourné vers l'actualité chaude. Les marques y prennent parfois une voix plus libre que sur leurs autres comptes, et le public y répond sur le même registre. Pour une marque, l'usage typique est de comparer la réception d'une même annonce sur X et sur Threads. Ce ne sont pas toujours les mêmes personnes, ni les mêmes réactions, et l'écart dit quelque chose de la cible réellement touchée.",
          "Threads is not read like X, even if the formats look alike. Part of its audience comes from Instagram, and the tone is often closer to it: more personal, less focused on breaking news. Brands sometimes take a freer voice there than on their other accounts, and the audience answers in the same register. For a brand, the typical use is to compare how the same announcement is received on X and on Threads. They are not always the same people, nor the same reactions, and the gap says something about the audience actually reached.")),
        # source: https://developers.facebook.com/documentation/threads/keyword-search
        # source: https://developers.facebook.com/docs/content-library-and-api/content-library
        (("Quelles données de Threads sont accessibles ?", "Which Threads data can be accessed?"),
         ("Threads s'ouvre progressivement aux outils. Meta propose une API Threads qui permet, après validation, de chercher des publications publiques par mot-clé ou par sujet, avec un nombre de requêtes limité ; les mots jugés sensibles ne renvoient aucun résultat. Les comptes privés restent fermés. Threads figure aussi dans la Meta Content Library, mais cet accès est réservé aux chercheurs. La couverture dépend donc de l'outil et de ses accès. Nous mesurons ce qui est réellement collecté avant de lancer une étude, et nous le disons.",
          "Threads is gradually opening up to tools. Meta offers a Threads API that, after approval, lets you search public posts by keyword or topic, with a limited number of queries; terms deemed sensitive return no results. Private accounts stay closed. Threads is also part of the Meta Content Library, but that access is reserved for researchers. Coverage therefore depends on the tool and its access. We measure what is actually collected before starting a study, and we say so.")),
    ],

    "whatsapp": [
        # source: https://blog.whatsapp.com/introducing-whatsapp-channels-a-private-way-to-follow-what-matters
        (("Que trouve-t-on de public sur WhatsApp ?", "What is public on WhatsApp?"),
         ("WhatsApp a ouvert un espace public avec les chaînes, lancées en 2023. Une chaîne est un outil de diffusion à sens unique : son administrateur publie des textes, des photos, des vidéos ou des sondages, et les abonnés les reçoivent sans pouvoir y répondre comme dans un groupe. Pour une marque, une chaîne se lit comme une publication officielle : ce que disent les médias, les personnalités ou les concurrents qui en ont une, sur quels sujets et à quel rythme. La réaction du public, elle, se lit surtout ailleurs, quand ces contenus sont repris sur d'autres réseaux.",
          "WhatsApp opened a public space with channels, launched in 2023. A channel is a one-way broadcast tool: its admin posts text, photos, videos or polls, and followers receive them without being able to reply as they would in a group. For a brand, a channel reads like an official publication: what the media, public figures or competitors who run one are saying, on which topics and how often. The public's reaction is mostly read elsewhere, when this content is picked up on other networks.")),
        # source: https://faq.whatsapp.com/1053543185312573
        (("Comment reconnaître un contenu venu de WhatsApp ?", "How do you recognise content that came from WhatsApp?"),
         ("WhatsApp laisse des traces visibles sur les contenus qui en sortent. L'application signale les messages transférés, et marque d'une double flèche ceux qui ont été transférés de nombreuses fois. Sur une capture publiée sur X ou Facebook, cette mention indique souvent qu'un message a déjà beaucoup circulé en privé, sans auteur ni date d'origine claire. Pour une marque, l'usage typique est là : repérer ces captures tôt, retrouver leur première apparition publique, et mesurer leur diffusion avant de décider s'il faut répondre, et sur quel réseau.",
          "WhatsApp leaves visible traces on content that comes out of it. The app labels forwarded messages, and marks with a double arrow those that have been forwarded many times. On a screenshot posted on X or Facebook, this label often shows that a message has already circulated widely in private, with no clear author or original date. That is the typical use for a brand: spotting these screenshots early, finding their first public appearance, and measuring their spread before deciding whether to respond, and on which network.")),
        # source: https://www.whatsapp.com/privacy
        # source: https://blog.whatsapp.com/introducing-whatsapp-channels-a-private-way-to-follow-what-matters
        (("Pourquoi les conversations WhatsApp restent-elles inaccessibles ?", "Why do WhatsApp conversations stay out of reach?"),
         ("WhatsApp protège les messages personnels par un chiffrement de bout en bout : seuls l'expéditeur et le destinataire peuvent les lire, pas même WhatsApp. Les chaînes, conçues pour un large public, ne sont pas chiffrées de bout en bout par défaut. Mais le numéro de l'administrateur n'est pas montré aux abonnés, ni celui des abonnés aux autres, et WhatsApp ne garde leur historique sur ses serveurs que 30 jours au plus. Une écoute de WhatsApp ne voit donc ni les groupes, ni les conversations, ni l'identité des abonnés : seulement ce que les chaînes publient, et ce qui en sort.",
          "WhatsApp protects personal messages with end-to-end encryption: only the sender and recipient can read them, not even WhatsApp. Channels, designed for a wide audience, are not end-to-end encrypted by default. But the admin's phone number is not shown to followers, nor followers' numbers to others, and WhatsApp keeps channel history on its servers for 30 days at most. Listening to WhatsApp therefore sees neither groups, nor conversations, nor who follows a channel: only what channels publish, and what comes out of them.")),
    ],

    "messenger": [
        (("Que peut-on analyser de Messenger ?", "What can be analysed from Messenger?"),
         ("Messenger n'a pas d'espace public à écouter : ce qui s'y échange est privé. La matière utile, pour une marque, ce sont ses propres conversations avec ses clients, quand elle choisit de les faire analyser. Une conversation exportée garde sa date, son déroulé et souvent son issue. On y lit à quel moment du parcours le client bloque, combien d'échanges il faut pour régler une demande, et ce qui transforme une simple question en réclamation. C'est une lecture du service client tel qu'il est vécu, à compléter par ce que les clients disent ensuite en public.",
          "Messenger has no public space to listen to: what is exchanged there is private. The useful material, for a brand, is its own conversations with its customers, when it chooses to have them analysed. An exported conversation keeps its date, its sequence and often its outcome. You can read at which point of the journey the customer gets stuck, how many exchanges it takes to settle a request, and what turns a simple question into a complaint. It is a reading of customer service as it is experienced, to be completed by what customers later say in public.")),
        (("Qu'apporte Messenger que les réseaux publics n'apportent pas ?", "What does Messenger add that public networks do not?"),
         ("Messenger montre les deux côtés de l'échange, ce que ne fait aucun réseau public. On voit la question du client, mais aussi la réponse de la marque. On peut donc juger la réponse elle-même : son délai, son ton, sa cohérence d'un conseiller à l'autre, et les réponses automatiques qui tournent en rond. Pour une marque, l'usage typique est d'auditer un canal de service client : repérer les demandes mal traitées, les formulations qui agacent, et les sujets où une réponse claire publiée ailleurs éviterait des dizaines de messages.",
          "Messenger shows both sides of the exchange, which no public network does. You see the customer's question, but also the brand's answer. You can therefore judge the answer itself: its speed, its tone, its consistency from one agent to another, and the automated replies that go round in circles. For a brand, the typical use is to audit a customer service channel: spotting badly handled requests, wording that irritates, and topics where a clear answer published elsewhere would save many messages.")),
        # source: https://about.fb.com/news/2023/12/default-end-to-end-encryption-on-messenger/
        (("Peut-on écouter les conversations Messenger ?", "Can Messenger conversations be listened to?"),
         ("Messenger chiffre de bout en bout par défaut les messages et les appels personnels, selon un déploiement lancé par Meta en décembre 2023 : personne d'autre que les participants, Meta compris, ne peut les lire. Aucune écoute ne peut donc y accéder, et nous ne le cherchons pas. Ce que nous analysons vient uniquement des conversations de votre page que vous nous confiez, et des captures que des clients rendent publiques eux-mêmes. Ces exports restent partiels : ils ne disent rien des clients mécontents qui n'écrivent jamais.",
          "Messenger encrypts personal messages and calls end to end by default, following a rollout Meta started in December 2023: nobody other than the participants, Meta included, can read them. No listening can access them, and we do not try to. What we analyse comes only from your page's conversations that you share with us, and from screenshots customers make public themselves. These exports remain partial: they say nothing about unhappy customers who never write.")),
    ],

    "x-twitter": [
        # source: https://help.x.com/en/using-x/community-notes
        (("Que peut-on lire sur X ?", "What can you read on X?"),
         ("X se lit à travers plusieurs façons de reprendre un message. La republication le diffuse tel quel, la citation l'accompagne d'un commentaire, souvent critique, et la réponse ouvre un débat sous le message d'origine. Suivre ces trois chemins montre comment un sujet change de sens en circulant. X affiche aussi des notes de la communauté : des contributeurs ajoutent du contexte à une publication jugée trompeuse, et la note devient visible quand des contributeurs aux points de vue différents la jugent utile. Pour une marque, une note peut changer la lecture d'une polémique.",
          "X is read through several ways of picking up a message. A repost spreads it as is, a quote adds a comment, often a critical one, and a reply opens a debate under the original message. Following these three paths shows how a topic changes meaning as it travels. X also displays Community Notes: contributors add context to a post seen as misleading, and the note becomes visible when contributors with different points of view rate it helpful. For a brand, a note can change how a controversy is read.")),
        (("Pourquoi le volume ne suffit-il pas sur X ?", "Why is volume not enough on X?"),
         ("X donne facilement une image déformée de l'opinion, et il faut le savoir pour bien l'écouter. Quelques comptes très actifs peuvent produire une grande partie des messages sur un sujet et faire paraître une polémique plus large qu'elle ne l'est. Des comptes automatisés ou des campagnes coordonnées peuvent aussi gonfler un volume. Pour une marque, la question utile n'est donc pas combien de messages, mais qui les écrit, et si le sujet atteint la presse et les autres réseaux. C'est ce qui sépare une agitation passagère d'une vraie crise.",
          "X easily gives a distorted picture of opinion, and you need to know it to listen well. A few very active accounts can produce a large share of the messages on a topic and make a controversy look bigger than it is. Automated accounts or coordinated campaigns can also inflate volume. For a brand, the useful question is therefore not how many messages, but who writes them, and whether the topic reaches the press and other networks. That is what separates passing noise from a real crisis.")),
        # source: https://docs.x.com/x-api/getting-started/pricing
        # source: https://developer.x.com/en/docs/x-api/compliance/streams/integrate/honoring-user-intent
        (("Quelles sont les limites d'accès aux données de X ?", "What are the limits on access to X data?"),
         ("X fait payer l'accès à ses données. Son API fonctionne au paiement à l'usage : chaque lecture de publication est facturée, et les gros volumes passent par des offres entreprise. Les outils d'écoute dépendent de ces accès, et leur couverture de X varie d'un éditeur à l'autre. Les comptes protégés et les messages privés restent hors de portée. Quand une publication est supprimée ou un compte protégé, X le signale aux développeurs pour que les données collectées suivent ce choix. Nous indiquons ce qui est réellement couvert avant chaque étude.",
          "X charges for access to its data. Its API runs on pay-per-use: every post read is billed, and large volumes go through enterprise offers. Listening tools depend on this access, and their coverage of X varies from one publisher to another. Protected accounts and direct messages remain out of reach. When a post is deleted or an account is protected, X notifies developers so that collected data follows that choice. We state what is actually covered before every study.")),
    ],

    "youtube": [
        (("Que peut-on écouter sur YouTube ?", "What can you listen to on YouTube?"),
         ("YouTube se lit à plusieurs niveaux. Le titre et la description disent comment le créateur présente sa vidéo, et la transcription ce qu'il affirme vraiment sur un produit. Les commentaires et leurs réponses forment de vrais fils de discussion, où le public corrige, complète ou contredit la vidéo. Les Shorts, plus courts, circulent comme sur TikTok, et les directs ont leur propre chat. Ces formats ne captent ni le même public, ni le même moment de la décision : une écoute utile les sépare avant de les comparer.",
          "YouTube is read at several levels. The title and description say how the creator presents the video, and the transcript what they actually claim about a product. Comments and their replies form real discussion threads, where the audience corrects, completes or contradicts the video. Shorts, being shorter, circulate the way they do on TikTok, and live streams have their own chat. These formats capture neither the same audience nor the same moment in the decision: useful listening separates them before comparing them.")),
        (("Pourquoi YouTube compte-t-il avant un achat ?", "Why does YouTube matter before a purchase?"),
         ("YouTube a une mémoire longue. Une vidéo de test peut continuer à être vue et commentée des années après sa mise en ligne, parce qu'elle remonte dans les recherches au moment où quelqu'un hésite à acheter. Le ton y est plus posé que sur les réseaux de flux, et les avis s'appuient sur un usage réel du produit. Pour une marque, l'usage typique est de lire ces vidéos de référence avant un lancement ou une nouvelle version : ce qui est reproché au modèle précédent, ce que les concurrents font mieux, et les questions restées sans réponse dans les commentaires.",
          "YouTube has a long memory. A test video can keep being watched and commented on years after it was posted, because it comes up in searches when someone is hesitating over a purchase. The tone is calmer than on feed-based networks, and opinions rest on real use of the product. For a brand, the typical use is to read these reference videos before a launch or a new version: what is held against the previous model, what competitors do better, and the questions left unanswered in the comments.")),
        # source: https://support.google.com/youtube/answer/9483359?hl=en
        # source: https://developers.google.com/youtube/terms/developer-policies
        # source: https://research.youtube.com/
        (("Qu'est-ce qui échappe à l'écoute de YouTube ?", "What escapes listening on YouTube?"),
         ("YouTube ne montre que ce que ses créateurs rendent public. Les vidéos privées et non répertoriées échappent à la collecte, et un créateur peut désactiver les commentaires ou retenir ceux qu'il veut relire avant publication. L'accès officiel passe par l'API de YouTube, dont les règles imposent de rafraîchir ou de supprimer régulièrement les données stockées, pour suivre les suppressions. Le programme de YouTube qui ouvre un accès élargi est réservé aux chercheurs universitaires. Enfin, les transcriptions automatiques peuvent se tromper sur un nom de marque ou de produit.",
          "YouTube only shows what its creators make public. Private and unlisted videos escape collection, and a creator can turn off comments or hold the ones they want to review before they appear. Official access goes through YouTube's API, whose rules require stored data to be refreshed or deleted regularly, so that deletions are followed. YouTube's programme offering wider access is reserved for university researchers. Finally, automatic transcripts can get a brand or product name wrong.")),
    ],

    "linkedin": [
        (("Que peut-on lire sur LinkedIn ?", "What can you read on LinkedIn?"),
         ("LinkedIn fait parler les personnes autant que les entreprises. Un dirigeant, un salarié ou un candidat y raconte une expérience en son nom, et ce récit circule dans son réseau professionnel. Les commentaires sont signés du nom et souvent de la fonction de leur auteur, ce qui permet de savoir qui réagit : des pairs, des clients, des recrues possibles, des concurrents. Les articles, les newsletters et les événements complètent ces publications, et les pages d'entreprise donnent le point de vue officiel. Une écoute utile lit les deux, et l'écart entre eux.",
          "LinkedIn gets people talking as much as companies. An executive, an employee or a candidate tells an experience in their own name there, and the story travels through their professional network. Comments are signed with the author's name and often their job title, which tells you who is reacting: peers, customers, potential hires, competitors. Articles, newsletters and events complement these posts, and company pages give the official view. Useful listening reads both, and the gap between them.")),
        (("En quoi la conversation LinkedIn est-elle différente ?", "How is the LinkedIn conversation different?"),
         ("LinkedIn a un ton à part : professionnel, signé, rarement anonyme. Les critiques y sont souvent plus mesurées qu'ailleurs, parce que chacun parle sous son nom et devant ses collègues. Un sujet y avance de relation en relation, d'une entreprise ou d'un secteur à l'autre, plus que par des tendances de masse. Pour une marque, l'usage typique est de suivre un sujet sensible pour ses salariés ou son secteur : une réorganisation, une prise de position, un débat réglementaire. On voit alors qui le porte, avec quels arguments, et si la parole des salariés suit celle de l'entreprise.",
          "LinkedIn has a tone of its own: professional, signed, rarely anonymous. Criticism there is often more measured than elsewhere, because everyone speaks under their own name and in front of their colleagues. A topic moves from connection to connection, from one company or sector to another, more than through mass trends. For a brand, the typical use is to follow a topic that is sensitive for its employees or sector: a reorganisation, a public stance, a regulatory debate. You then see who carries it, with which arguments, and whether employees' voices follow the company's.")),
        # source: https://www.linkedin.com/help/linkedin/answer/a1341387
        (("Pourquoi l'écoute de LinkedIn est-elle partielle ?", "Why is listening on LinkedIn partial?"),
         ("LinkedIn encadre strictement la collecte automatisée. Ses règles interdisent les robots, les extensions de navigateur et les autres outils qui copient ses pages ou ses profils, et LinkedIn restreint les comptes qui les utilisent. Les outils d'écoute n'en voient donc qu'une partie, selon les accès dont ils disposent. Les messages, les publications réservées aux relations et les profils restreints restent hors de portée. Une étude LinkedIn peut donc s'appuyer sur une sélection de comptes suivis de près plutôt que sur une collecte large, et nous disons toujours ce qui manque.",
          "LinkedIn tightly restricts automated collection. Its rules prohibit bots, browser extensions and other tools that copy its pages or profiles, and LinkedIn restricts the accounts that use them. Listening tools therefore see only part of it, depending on the access they have. Messages, connections-only posts and restricted profiles remain out of reach. A LinkedIn study may therefore rely on a selection of closely followed accounts rather than broad collection, and we always say what is missing.")),
    ],

    "reddit": [
        (("Que peut-on lire sur Reddit ?", "What can you read on Reddit?"),
         ("Reddit se lit fil par fil. Une discussion part d'une question ou d'un retour d'expérience, puis se ramifie en réponses imbriquées où les arguments se répondent. Chaque communauté a ses règles, ses modérateurs et souvent ses étiquettes de sujet, qui aident à trier les discussions. Pour une marque, les fils les plus utiles sont souvent les demandes de conseil : quel produit choisir, lequel éviter, et pourquoi. Les fils anciens restent consultables et peuvent ressortir dans les moteurs de recherche, ce qui leur donne une longue vie.",
          "Reddit is read thread by thread. A discussion starts from a question or an experience report, then branches into nested replies where arguments answer each other. Each community has its rules, its moderators and often its topic labels, which help sort discussions. For a brand, the most useful threads are often requests for advice: which product to choose, which to avoid, and why. Old threads stay available and can surface in search engines, which gives them a long life.")),
        (("Qu'est-ce qui rend Reddit différent pour l'écoute ?", "What makes Reddit different for listening?"),
         ("Reddit valorise la compétence et se méfie de la publicité. Une réponse détaillée monte grâce aux votes, alors qu'un message qui ressemble à de la promotion est souvent rejeté par la communauté ou retiré par les modérateurs. Le pseudonymat libère aussi la parole sur des sujets délicats : santé, argent, travail. Pour une marque, l'usage typique est de comprendre les vrais critères de choix d'une catégorie et les défauts qu'on lui reproche, tels que des utilisateurs avertis les formulent entre eux. C'est aussi un bon terrain pour éprouver une idée de produit avant un lancement.",
          "Reddit rewards expertise and distrusts advertising. A detailed answer rises through votes, while a message that looks like promotion is often rejected by the community or removed by moderators. Pseudonymity also frees people to speak on delicate topics: health, money, work. For a brand, the typical use is to understand the real choice criteria in a category and the flaws people point out, as experienced users put them to each other. It is also a good place to test a product idea before a launch.")),
        # source: https://redditinc.com/policies/data-api-terms
        (("Quelles sont les limites d'accès aux données de Reddit ?", "What are the limits on access to Reddit data?"),
         ("Reddit contrôle de près l'accès à ses données. Ses conditions d'utilisation de l'API exigent un accord distinct pour tout usage commercial, et ces conditions évoluent régulièrement. La couverture de Reddit dépend donc des accords de chaque outil. Les communautés privées et les messages restent fermés, et un message supprimé par son auteur ou retiré par les modérateurs n'est plus lisible. Nous vérifions la couverture avant chaque étude.",
          "Reddit closely controls access to its data. Its Data API terms require a separate agreement for any commercial use, and these terms change regularly. Reddit coverage therefore depends on each tool's agreements. Private communities and messages stay closed, and a message deleted by its author or removed by moderators can no longer be read. We check coverage before every study.")),
    ],

    "snapchat": [
        # source: https://help.snapchat.com/hc/en-us/articles/7012347065876-What-is-a-Public-Profile-on-Snapchat
        # source: https://www.snap.com/terms/spotlight-terms
        (("Que peut-on voir de public sur Snapchat ?", "What is public on Snapchat?"),
         ("Snapchat a une partie publique, distincte des échanges entre amis. Les profils publics, ouverts aux utilisateurs de 16 ans et plus qui choisissent de s'en servir, présentent des stories publiques et des Snaps mis en avant, et d'autres utilisateurs peuvent s'y abonner. Les Snaps envoyés sur Spotlight sont publics : ils peuvent être vus par tous les utilisateurs, et parfois hors de l'application. Pour une marque, c'est là que se lisent les créateurs, les médias et les formats qui s'adressent aux plus jeunes, avec leurs codes et leurs mots.",
          "Snapchat has a public side, separate from exchanges between friends. Public profiles, open to users aged 16 and over who choose to use them, show public stories and featured Snaps, and other users can subscribe to them. Snaps submitted to Spotlight are public: all users can see them, and sometimes people outside the app too. For a brand, that is where you read the creators, media and formats that speak to the youngest, with their codes and words.")),
        (("Que dit vraiment Snapchat d'une audience jeune ?", "What does Snapchat really say about a young audience?"),
         ("Snapchat est d'abord une messagerie entre proches, ce qui change la nature de ce qu'on y voit en public. Ce qui est public vient de comptes qui choisissent de publier pour un large public : créateurs, médias, marques. On y lit donc des formats, des tons et des sujets qui plaisent, plus qu'une opinion spontanée sur une marque. Pour une marque, l'usage typique est de repérer les créateurs qui parlent à une audience jeune et les thèmes qu'ils abordent, puis de vérifier sur TikTok et Instagram si ces signaux se retrouvent ailleurs.",
          "Snapchat is first a messaging app between close friends, which changes the nature of what you see in public there. What is public comes from accounts that choose to post for a wide audience: creators, media, brands. You therefore read formats, tones and topics that people like, more than spontaneous opinions about a brand. For a brand, the typical use is to spot the creators who speak to a young audience and the themes they cover, then check on TikTok and Instagram whether those signals show up elsewhere.")),
        # source: https://help.snapchat.com/hc/en-us/articles/7012334940948-When-does-Snapchat-delete-Snaps-and-Chats
        # source: https://help.snapchat.com/hc/en-us/articles/7012338216468-What-s-the-difference-between-posting-to-My-Story-Public-and-My-Story-Friends
        (("Pourquoi l'essentiel de Snapchat reste-t-il invisible ?", "Why does most of Snapchat stay invisible?"),
         ("Snapchat est conçu pour que la plupart des messages disparaissent. Les Snaps envoyés entre amis sont effacés des serveurs une fois vus par tous les destinataires, et les discussions sont supprimées par défaut peu après leur lecture. Pour les 16 et 17 ans, les stories publiques ne sont recommandées qu'à leurs amis, à leurs abonnés et aux personnes avec qui ils ont des amis en commun. Une écoute ne voit donc qu'une petite partie publique, et seulement tant qu'elle est en ligne. Nous ne collectons jamais les échanges privés.",
          "Snapchat is designed so that most messages disappear. Snaps sent between friends are deleted from the servers once all recipients have viewed them, and chats are deleted by default shortly after being read. For 16 and 17-year-olds, public stories are only recommended to their friends, their followers and people they share mutual friends with. Listening therefore sees only a small public part, and only while it is online. We never collect private exchanges.")),
    ],
}
