"""The 22 networks of "Where the data comes from": one page each
(tools/build-tech.py writes source-<slug>.html and /fr/sources/<slug>/).

Each entry: slug, name, glyph (assets/img/networks/<glyph>.svg), tagline,
lead, what we read there (three cards), what we collect and what we do not
read, the tools whose vendors state they cover it (none when unconfirmed),
three use cases (keys of uc_content.CASES) and two questions.
Pairs are (French, English).

MOCK: written by us from what the platforms make public; to be reviewed by
Licter, the limits in particular (A-FAIRE.md, section 5).
"""

NETWORKS = [
    {"slug": "facebook", "tools": ["talkwalker", "visibrain", "youscan", "meta-ads"], "name": "Facebook", "glyph": "facebook",
     "tag": ("les communautés et les groupes", "communities and groups"),
     "lead": ("Facebook reste le réseau des groupes, des pages locales et des commentaires sous les publications des marques, avec un public plus âgé qu'ailleurs. C'est souvent là que la relation client se joue en public.",
              "Facebook remains the network of groups, local pages and comments under brand posts, with an older audience than elsewhere. It is often where customer relations play out in public."),
     "reads": [(("Les commentaires sous vos publications", "Comments under your posts"), ("Ce que vos clients vous disent en public, et le ton qu'ils prennent.", "What your customers tell you in public, and the tone they take.")),
               (("Les groupes publics", "Public groups"), ("Les communautés locales, de passionnés ou de consommateurs qui parlent de votre catégorie.", "Local, enthusiast or consumer communities talking about your category.")),
               (("Les pages de vos concurrents", "Your competitors' pages"), ("Ce que leurs clients leur reprochent, et ce qu'ils saluent.", "What their customers blame them for, and what they praise."))],
     "access": ("Les pages publiques, leurs publications et leurs commentaires, et les groupes publics.", "Public pages, their posts and comments, and public groups."),
     "limits": ("Les profils privés et les groupes fermés : ils ne sont pas accessibles, et nous ne cherchons pas à y entrer.", "Private profiles and closed groups: they are not accessible, and we do not try to get in."),
     "uses": ["reputation", "touchpoints", "brand-risk"],
     "faq": [(("Le public de Facebook est-il encore pertinent ?", "Is Facebook's audience still relevant?"), ("Pour beaucoup de catégories, oui : c'est là que s'expriment les clients de 35 ans et plus, et la relation client locale.", "For many categories, yes: it is where customers over 35 speak up, and where local customer relations happen.")),
             (("Lisez-vous les avis laissés sur nos pages ?", "Do you read the reviews left on our pages?"), ("Oui, comme les commentaires : ce sont souvent les signaux les plus directs sur un produit ou un service.", "Yes, like the comments: they are often the most direct signals about a product or service."))]},

    {"slug": "instagram", "tools": ["talkwalker", "visibrain", "youscan", "soprism", "social-blade"], "name": "Instagram", "glyph": "instagram",
     "tag": ("l'image et les créateurs", "images and creators"),
     "lead": ("Sur Instagram, une marque existe d'abord par l'image : ses produits portés, montrés, détournés, et les créateurs qui en parlent. La conversation passe autant par les visuels que par les légendes.",
              "On Instagram, a brand exists through images first: its products worn, shown, repurposed, and the creators who talk about them. The conversation runs through visuals as much as captions."),
     "reads": [(("Les publications et leurs légendes", "Posts and their captions"), ("Ce qui se dit de votre marque, et dans quel univers elle apparaît.", "What is said about your brand, and in which world it appears.")),
               (("Les créateurs", "Creators"), ("Qui parle de vous, à quelle audience, et avec quel effet.", "Who talks about you, to which audience, and with what effect.")),
               (("Les commentaires", "Comments"), ("La réaction du public, souvent plus franche que la publication.", "The public's reaction, often franker than the post."))],
     "access": ("Les comptes professionnels et de créateurs publics, leurs publications, leurs commentaires et les hashtags.", "Public business and creator accounts, their posts, comments and hashtags."),
     "limits": ("Les comptes privés et les messages : jamais. Les stories, éphémères, ne sont visibles que partiellement.", "Private accounts and messages: never. Stories, which vanish, are only partly visible."),
     "uses": ["ambassadors", "campaign-impact", "rejuvenate"],
     "faq": [(("Repérez-vous votre marque dans les images ?", "Do you spot your brand in images?"), ("Oui, avec la reconnaissance visuelle de nos plateformes : un logo ou un produit visible sans être nommé est retrouvé.", "Yes, with our platforms' image recognition: a logo or product shown without being named is found.")),
             (("Pouvez-vous évaluer un créateur avant une collaboration ?", "Can you assess a creator before working with them?"), ("Oui : son audience réelle, sa croissance, ses affinités, et ce que ses abonnés disent des marques qu'il porte.", "Yes: their real audience, their growth, their affinities, and what their followers say about the brands they carry."))]},

    {"slug": "threads", "tools": ["visibrain"], "name": "Threads", "glyph": "threads",
     "tag": ("la conversation texte de Meta", "Meta's text conversation"),
     "lead": ("Threads est le réseau de conversation écrite de Meta, adossé à Instagram. Plus jeune que X, il réunit une partie des journalistes, des marques et de leurs publics.",
              "Threads is Meta's written conversation network, built on Instagram. Younger than X, it gathers part of the journalists, brands and their audiences."),
     "reads": [(("Les publications publiques", "Public posts"), ("Les réactions à chaud sur votre marque et votre actualité.", "Hot reactions to your brand and your news.")),
               (("Les réponses et les reprises", "Replies and reposts"), ("Comment un sujet circule, et qui le fait circuler.", "How a topic travels, and who carries it.")),
               (("Le déplacement depuis X", "The move from X"), ("Les comptes qui ont changé de réseau, et ce qu'ils y disent.", "The accounts that switched networks, and what they say there."))],
     "access": ("Les publications publiques et leurs réponses.", "Public posts and their replies."),
     "limits": ("Les comptes privés. Le réseau est récent : la couverture des outils d'écoute progresse encore, nous vous disons ce qui est réellement collecté.", "Private accounts. The network is recent: listening tools are still catching up, and we tell you what is actually collected."),
     "uses": ["reputation", "messaging", "campaign-impact"],
     "faq": [(("Faut-il suivre Threads en plus de X ?", "Should we follow Threads as well as X?"), ("Cela dépend de votre public. Nous mesurons d'abord où parlent les gens qui comptent pour vous, puis nous suivons les deux si besoin.", "It depends on your audience. We first measure where the people who matter to you are talking, then follow both if needed.")),
             (("La collecte est-elle complète ?", "Is collection complete?"), ("Pas encore partout : nous indiquons la part couverte avant de lancer l'étude.", "Not everywhere yet: we state what share is covered before the study starts."))]},

    {"slug": "whatsapp", "tools": ["visibrain", "talkwalker"], "name": "WhatsApp", "glyph": "whatsapp",
     "tag": ("les chaînes publiques", "public channels"),
     "lead": ("WhatsApp est d'abord une messagerie privée, et elle le reste. Ce que nous lisons, ce sont ses chaînes publiques, et ce qui en sort : les captures et les messages transférés qui finissent sur les autres réseaux.",
              "WhatsApp is a private messaging app first, and it stays that way. What we read are its public channels, and what comes out of it: screenshots and forwarded messages that end up on other networks."),
     "reads": [(("Les chaînes publiques", "Public channels"), ("Les annonces des médias, des marques et des personnalités suivies par des milliers d'abonnés.", "Announcements from media, brands and personalities followed by thousands.")),
               (("Ce qui fuit ailleurs", "What leaks elsewhere"), ("Les captures et transferts repris sur X, Facebook ou TikTok, souvent le premier signe d'une rumeur.", "Screenshots and forwards picked up on X, Facebook or TikTok, often the first sign of a rumour.")),
               (("Vos propres échanges", "Your own conversations"), ("Si vous nous confiez l'export de votre service client, nous l'analysons avec le reste.", "If you share your customer service export with us, we analyse it with the rest."))],
     "access": ("Les chaînes publiques, les contenus WhatsApp republiés ailleurs, et vos propres exports si vous nous les confiez.", "Public channels, WhatsApp content republished elsewhere, and your own exports if you share them."),
     "limits": ("Les conversations et les groupes privés : jamais. Ils sont chiffrés, et c'est très bien ainsi.", "Private chats and groups: never. They are encrypted, and rightly so."),
     "uses": ["brand-risk", "touchpoints", "reputation"],
     "faq": [(("Pouvez-vous lire les groupes WhatsApp ?", "Can you read WhatsApp groups?"), ("Non. Les groupes privés sont chiffrés et inaccessibles. Nous lisons les chaînes publiques et ce qui en ressort sur les autres réseaux.", "No. Private groups are encrypted and out of reach. We read public channels and what surfaces on other networks.")),
             (("Pourquoi en parler alors ?", "Then why mention it?"), ("Parce que beaucoup de rumeurs y naissent avant d'apparaître ailleurs : savoir le reconnaître aide à réagir plus tôt.", "Because many rumours start there before appearing elsewhere: recognising it helps you react earlier."))]},

    {"slug": "messenger", "tools": ["meta-ads", "talkwalker"], "name": "Messenger", "glyph": "messenger",
     "tag": ("la relation client en privé", "private customer conversations"),
     "lead": ("Messenger est la messagerie de Facebook, et une partie de votre service client y passe. Ces échanges sont privés : nous ne les lisons que si vous nous confiez l'export de votre page, pour les analyser avec la conversation publique.",
              "Messenger is Facebook's messaging app, and part of your customer service runs through it. These conversations are private: we only read them if you share your page's export, to analyse them with the public conversation."),
     "reads": [(("Vos conversations clients", "Your customer conversations"), ("Avec votre accord et vos exports : les motifs de contact, les irritants, les questions qui reviennent.", "With your consent and exports: contact reasons, irritants, recurring questions.")),
               (("Ce qui devient public", "What becomes public"), ("Les échanges que des clients publient en capture, souvent quand ça se passe mal.", "Conversations customers post as screenshots, often when things go wrong.")),
               (("Le lien avec Facebook", "The link with Facebook"), ("Les sujets privés qui finissent en commentaires publics sur vos pages.", "Private issues that end up as public comments on your pages."))],
     "access": ("Vos propres exports de conversations, si vous nous les confiez, et ce qui est republié publiquement.", "Your own conversation exports, if you share them, and what is republished publicly."),
     "limits": ("Les conversations des autres : jamais. Nous ne lisons aucune messagerie privée sans l'accord de son titulaire.", "Anyone else's conversations: never. We read no private messages without their owner's consent."),
     "uses": ["touchpoints", "brand-risk", "reputation"],
     "faq": [(("Accédez-vous à nos messages sans notre accord ?", "Do you access our messages without consent?"), ("Non. Seuls les exports que vous nous transmettez sont analysés, anonymisés, selon un cadre RGPD défini avec vous.", "No. Only the exports you send us are analysed, anonymised, under a GDPR framework agreed with you.")),
             (("Quel intérêt de croiser avec le public ?", "Why cross it with public data?"), ("Les irritants du service client annoncent souvent ce qui sortira demain en public : les relier permet de traiter avant.", "Customer service irritants often announce what will come out in public tomorrow: linking them lets you act first."))]},

    {"slug": "x-twitter", "tools": ["talkwalker", "visibrain", "youscan"], "name": "X / Twitter", "glyph": "x",
     "tag": ("le temps réel", "real time"),
     "lead": ("X, l'ancien Twitter, reste le réseau de l'actualité en direct : journalistes, politiques, experts et crises qui démarrent. C'est souvent là qu'un sujet devient une affaire.",
              "X, formerly Twitter, remains the network of live news: journalists, politicians, experts and crises as they start. It is often where a topic turns into a story."),
     "reads": [(("Les posts et leurs reprises", "Posts and reposts"), ("Comment un sujet s'emballe, minute par minute.", "How a topic takes off, minute by minute.")),
               (("Les comptes qui comptent", "The accounts that matter"), ("Journalistes, experts, personnalités : ceux qui font basculer une conversation.", "Journalists, experts, public figures: those who tip a conversation.")),
               (("La parole des dirigeants", "Executive voices"), ("Ce que disent vos dirigeants, ceux de vos concurrents, et l'écho qu'ils reçoivent.", "What your executives and your competitors' say, and the echo they get."))],
     "access": ("Les posts publics, leurs réponses et leurs reprises.", "Public posts, their replies and reposts."),
     "limits": ("Les comptes protégés et les messages privés. Depuis 2023, l'accès aux données de X est plus restreint et plus coûteux : nous indiquons ce qui est réellement couvert.", "Protected accounts and direct messages. Since 2023, access to X data is more restricted and costly: we state what is actually covered."),
     "uses": ["brand-risk", "leader-advocacy", "campaign-impact"],
     "faq": [(("X est-il encore utile à écouter ?", "Is X still worth listening to?"), ("Oui pour l'actualité, les médias et les crises : beaucoup de journalistes et d'experts y sont toujours.", "Yes for news, media and crises: many journalists and experts are still there.")),
             (("En combien de temps êtes-vous alertés ?", "How fast are you alerted?"), ("Avec Vigie 360, en 15 minutes, 24 h/24, après lecture par un analyste.", "With Vigie 360, within 15 minutes, 24/7, after an analyst has read it."))]},

    {"slug": "tiktok", "tools": ["visibrain", "youscan", "social-blade"], "name": "TikTok", "glyph": "tiktok",
     "tag": ("là où naissent les tendances", "where trends are born"),
     "lead": ("Sur TikTok, une tendance naît en quelques jours, avec ses sons, ses formats et ses codes. C'est le réseau où les plus jeunes parlent des marques, souvent sans les nommer dans le texte.",
              "On TikTok, a trend is born in days, with its sounds, formats and codes. It is the network where the youngest talk about brands, often without naming them in the text."),
     "reads": [(("Les vidéos et leurs sons", "Videos and their sounds"), ("Ce qui se montre et ce qui se dit, transcrit et lu.", "What is shown and what is said, transcribed and read.")),
               (("Les commentaires", "Comments"), ("La réaction du public, souvent plus parlante que la vidéo.", "The audience's reaction, often more telling than the video.")),
               (("Les tendances qui montent", "Rising trends"), ("Les formats et hashtags qui accélèrent, avant qu'ils ne saturent.", "Formats and hashtags picking up speed, before they saturate."))],
     "access": ("Les vidéos publiques, leurs descriptions, leurs commentaires et les hashtags.", "Public videos, their descriptions, comments and hashtags."),
     "limits": ("Les comptes privés et les messages. Le contenu est d'abord vidéo et sonore : sans transcription ni lecture visuelle, une grande partie échappe aux outils.", "Private accounts and messages. Content is video and sound first: without transcription and visual reading, much of it escapes the tools."),
     "uses": ["rejuvenate", "stakeholders", "ambassadors"],
     "faq": [(("Comment écoutez-vous une vidéo ?", "How do you listen to a video?"), ("Nous lisons la description, les commentaires et, quand l'outil le permet, la transcription et les éléments visibles à l'image.", "We read the description, the comments and, when the tool allows, the transcript and what is visible in the frame.")),
             (("Repérez-vous les tendances avant qu'elles n'explosent ?", "Do you spot trends before they explode?"), ("C'est l'objectif : nous suivons la vitesse des sujets, pas seulement leur volume.", "That is the point: we follow how fast topics move, not only their volume."))]},

    {"slug": "youtube", "tools": ["visibrain", "youscan", "social-blade", "google-trends"], "name": "YouTube", "glyph": "youtube",
     "tag": ("la vidéo longue et ses commentaires", "long video and its comments"),
     "lead": ("YouTube est le réseau des tests, des tutoriels et des avis détaillés. Les commentaires y sont nombreux et argumentés : une mine pour comprendre un produit vu par ceux qui l'utilisent.",
              "YouTube is the network of tests, tutorials and detailed reviews. Comments are many and argued: a goldmine to understand a product as its users see it."),
     "reads": [(("Les tests et les avis", "Tests and reviews"), ("Ce que les créateurs disent de vos produits et de ceux de vos concurrents.", "What creators say about your products and your competitors'.")),
               (("Les commentaires", "Comments"), ("Les questions, les irritants et les comparaisons du public.", "The audience's questions, irritants and comparisons.")),
               (("Les chaînes de votre catégorie", "Your category's channels"), ("Qui fait référence, et avec quelle audience.", "Who sets the reference, and with which audience."))],
     "access": ("Les vidéos publiques, leurs titres et descriptions, leurs commentaires, et les transcriptions quand elles existent.", "Public videos, their titles and descriptions, comments, and transcripts where they exist."),
     "limits": ("Les vidéos privées ou non répertoriées.", "Private or unlisted videos."),
     "uses": ["product-test", "ambassadors", "campaign-impact"],
     "faq": [(("Lisez-vous le contenu des vidéos ?", "Do you read what is said in the videos?"), ("Oui, à partir des transcriptions quand elles sont disponibles, en plus des titres et des commentaires.", "Yes, from transcripts when available, on top of titles and comments.")),
             (("Pouvez-vous comparer nos produits à ceux des concurrents ?", "Can you compare our products with competitors'?"), ("Oui : les tests et les commentaires permettent une comparaison point par point.", "Yes: tests and comments allow a point-by-point comparison."))]},

    {"slug": "linkedin", "tools": ["visibrain"], "name": "LinkedIn", "glyph": "linkedin",
     "tag": ("la parole professionnelle", "the professional voice"),
     "lead": ("LinkedIn est le réseau de la marque employeur, des dirigeants et des décideurs. Ce qui s'y dit pèse sur les recrutements, les partenaires et parfois les investisseurs.",
              "LinkedIn is the network of employer brands, executives and decision-makers. What is said there weighs on hiring, partners and sometimes investors."),
     "reads": [(("La parole des dirigeants", "Executive voices"), ("Vos dirigeants, ceux de vos concurrents, et l'écho qu'ils reçoivent.", "Your executives, your competitors', and the echo they get.")),
               (("La marque employeur", "Employer brand"), ("Ce que vos salariés et candidats disent de vous.", "What your employees and candidates say about you.")),
               (("Les débats d'une filière", "An industry's debates"), ("Les sujets qui occupent les décideurs de votre secteur.", "The topics occupying decision-makers in your sector."))],
     "access": ("Les publications publiques des pages et des profils, et leurs commentaires, selon ce que permettent les outils.", "Public posts from pages and profiles, and their comments, as far as the tools allow."),
     "limits": ("LinkedIn limite fortement la collecte automatisée : la couverture est partielle, et nous le disons avant de commencer. Les messages et les profils restreints : jamais.", "LinkedIn strongly limits automated collection: coverage is partial, and we say so before starting. Messages and restricted profiles: never."),
     "uses": ["leader-advocacy", "messaging", "reputation"],
     "faq": [(("Pouvez-vous mesurer l'impact de nos dirigeants sur LinkedIn ?", "Can you measure our executives' impact on LinkedIn?"), ("Oui, sur leurs publications publiques : portée, réactions, qui les reprend, et comparaison avec vos concurrents.", "Yes, on their public posts: reach, reactions, who picks them up, and comparison with your competitors.")),
             (("Pourquoi la couverture est-elle partielle ?", "Why is coverage partial?"), ("Parce que LinkedIn restreint l'accès à ses données. Nous combinons les sources disponibles et indiquons ce qui manque.", "Because LinkedIn restricts access to its data. We combine the available sources and state what is missing."))]},

    {"slug": "reddit", "tools": ["youscan", "radarly"], "name": "Reddit", "glyph": "reddit",
     "tag": ("les avis sans filtre", "unfiltered opinions"),
     "lead": ("Reddit rassemble des communautés de passionnés qui discutent longuement, souvent anonymement. Les avis y sont francs, détaillés et rarement sponsorisés.",
              "Reddit gathers enthusiast communities who discuss at length, often anonymously. Opinions there are frank, detailed and rarely sponsored."),
     "reads": [(("Les fils de discussion", "Discussion threads"), ("Les comparaisons, les retours d'expérience et les conseils entre utilisateurs.", "Comparisons, experience reports and advice between users.")),
               (("Les communautés (subreddits)", "Communities (subreddits)"), ("Les espaces qui parlent de votre catégorie, et leur ton.", "The spaces talking about your category, and their tone.")),
               (("Les votes", "Votes"), ("Ce que la communauté valide ou rejette.", "What the community endorses or rejects."))],
     "access": ("Les communautés et discussions publiques, avec leurs votes.", "Public communities and discussions, with their votes."),
     "limits": ("Les communautés privées et les messages. Reddit est surtout anglophone : sa place varie beaucoup d'un marché à l'autre.", "Private communities and messages. Reddit is mostly English-speaking: its weight varies a lot from one market to another."),
     "uses": ["product-test", "market-opportunities", "touchpoints"],
     "faq": [(("Reddit compte-t-il en France ?", "Does Reddit matter in France?"), ("Moins qu'aux États-Unis, mais certaines communautés françaises sont très actives, notamment sur la tech, le jeu vidéo et la consommation.", "Less than in the US, but some French communities are very active, in tech, gaming and consumer topics especially.")),
             (("Pourquoi des avis anonymes seraient-ils fiables ?", "Why would anonymous opinions be reliable?"), ("Ils sont rarement sponsorisés et souvent argumentés ; nous les lisons avec le reste, jamais seuls.", "They are rarely sponsored and often argued; we read them with the rest, never alone."))]},

    {"slug": "snapchat", "tools": [], "name": "Snapchat", "glyph": "snapchat",
     "tag": ("les plus jeunes, en privé", "the youngest, in private"),
     "lead": ("Snapchat est très utilisé par les adolescents et les jeunes adultes, mais surtout en privé. Ce qui est public, Spotlight et les stories publiques, donne une fenêtre partielle sur leurs codes.",
              "Snapchat is widely used by teenagers and young adults, but mostly in private. What is public, Spotlight and public stories, gives a partial window on their codes."),
     "reads": [(("Spotlight", "Spotlight"), ("Les vidéos publiques mises en avant, et les formats qui marchent.", "The public videos promoted, and the formats that work.")),
               (("Les stories publiques", "Public stories"), ("Les créateurs et médias qui s'adressent aux plus jeunes.", "The creators and media speaking to the youngest.")),
               (("Les codes d'une génération", "A generation's codes"), ("Les sujets, les mots et les tendances, croisés avec TikTok.", "Topics, words and trends, crossed with TikTok."))],
     "access": ("Les contenus publics (Spotlight, stories publiques), dans la mesure où les outils les couvrent.", "Public content (Spotlight, public stories), as far as tools cover it."),
     "limits": ("L'essentiel : les messages et les stories privées, éphémères et inaccessibles. Snapchat se lit donc toujours avec les autres réseaux.", "Most of it: private messages and stories, ephemeral and out of reach. Snapchat is therefore always read with other networks."),
     "uses": ["rejuvenate", "stakeholders", "segmentation"],
     "faq": [(("Peut-on vraiment écouter Snapchat ?", "Can you really listen to Snapchat?"), ("En partie seulement : la partie publique. Nous la croisons avec TikTok et Instagram pour comprendre les plus jeunes.", "Only partly: the public part. We cross it with TikTok and Instagram to understand the youngest.")),
             (("Pour quelles marques est-ce utile ?", "For which brands is it useful?"), ("Celles qui veulent rajeunir leur audience ou comprendre les 15-24 ans.", "Those who want a younger audience or to understand 15 to 24-year-olds."))]},

    {"slug": "pinterest", "tools": ["youscan"], "name": "Pinterest", "glyph": "pinterest",
     "tag": ("les intentions avant l'achat", "intent before purchase"),
     "lead": ("Sur Pinterest, les gens préparent : une maison, une tenue, un mariage, un voyage. Ce qu'ils épinglent dit ce qu'ils envisagent d'acheter, souvent des mois avant.",
              "On Pinterest, people plan: a home, an outfit, a wedding, a trip. What they pin says what they consider buying, often months ahead."),
     "reads": [(("Les épingles et les tableaux", "Pins and boards"), ("Les univers dans lesquels vos produits apparaissent.", "The worlds your products appear in.")),
               (("Les tendances saisonnières", "Seasonal trends"), ("Ce qui monte avant les fêtes, l'été, la rentrée.", "What rises before the holidays, summer, back to school.")),
               (("Les associations", "Associations"), ("Les styles, couleurs et produits qu'on associe à votre marque.", "The styles, colours and products associated with your brand."))],
     "access": ("Les épingles et les tableaux publics, et les tendances que Pinterest publie.", "Public pins and boards, and the trends Pinterest publishes."),
     "limits": ("Les tableaux secrets et les messages.", "Secret boards and messages."),
     "uses": ["market-opportunities", "product-test", "stakeholders"],
     "faq": [(("Pinterest est-il utile hors de la mode et de la déco ?", "Is Pinterest useful beyond fashion and home?"), ("Oui pour toutes les catégories qui se préparent : cuisine, voyage, beauté, fêtes, enfants.", "Yes for every category people plan for: food, travel, beauty, celebrations, children.")),
             (("Avec combien d'avance voit-on une tendance ?", "How early does a trend show?"), ("Souvent plusieurs mois : on épingle avant d'acheter.", "Often several months: people pin before they buy."))]},

    {"slug": "discord", "tools": [], "name": "Discord", "glyph": "discord",
     "tag": ("les communautés de passionnés", "enthusiast communities"),
     "lead": ("Discord réunit des communautés autour du jeu vidéo, de la tech, de la musique ou d'une marque. La plupart des serveurs sont fermés ; les serveurs publics sont une fenêtre précieuse sur les passionnés.",
              "Discord gathers communities around gaming, tech, music or a brand. Most servers are closed; public servers are a precious window on enthusiasts."),
     "reads": [(("Les serveurs publics", "Public servers"), ("Les discussions des communautés ouvertes de votre catégorie.", "Discussions in your category's open communities.")),
               (("Votre propre serveur", "Your own server"), ("Si vous en avez un, et avec votre accord : ce que votre communauté dit vraiment.", "If you have one, and with your consent: what your community really says.")),
               (("Les lancements", "Launches"), ("Les réactions des passionnés, souvent les premiers à tester.", "Enthusiasts' reactions, often the first to test."))],
     "access": ("Les serveurs publics, et votre propre serveur si vous nous y donnez accès.", "Public servers, and your own server if you give us access."),
     "limits": ("Les serveurs privés et les messages directs : jamais. La plus grande partie de Discord n'est pas publique.", "Private servers and direct messages: never. Most of Discord is not public."),
     "uses": ["ambassadors", "product-test", "segmentation"],
     "faq": [(("Pouvez-vous analyser notre serveur Discord ?", "Can you analyse our Discord server?"), ("Oui, avec votre accord et un accès dédié, dans un cadre RGPD défini avec vous.", "Yes, with your consent and dedicated access, under a GDPR framework agreed with you.")),
             (("Pourquoi Discord plutôt qu'un sondage ?", "Why Discord rather than a survey?"), ("Parce que les passionnés y disent spontanément ce qu'ils pensent, sans question orientée.", "Because enthusiasts say what they think spontaneously there, without a leading question."))]},

    {"slug": "twitch", "tools": ["youscan", "social-blade"], "name": "Twitch", "glyph": "twitch",
     "tag": ("le live et son chat", "live streams and their chat"),
     "lead": ("Twitch est le réseau du direct : jeu vidéo, discussions, événements, avec un chat qui réagit en temps réel. Une marque y est jugée à chaud, par une audience jeune et fidèle.",
              "Twitch is the network of live streams: gaming, talk shows, events, with a chat that reacts in real time. A brand is judged on the spot there, by a young and loyal audience."),
     "reads": [(("Les chats en direct", "Live chats"), ("Les réactions instantanées à un produit, une annonce, un partenariat.", "Instant reactions to a product, an announcement, a partnership.")),
               (("Les streamers", "Streamers"), ("Qui parle à votre cible, avec quelle audience et quel ton.", "Who speaks to your target, with what audience and tone.")),
               (("Les clips", "Clips"), ("Les moments repris et partagés ailleurs.", "The moments picked up and shared elsewhere."))],
     "access": ("Les chats publics des lives, les chaînes et les clips publics, selon ce que couvrent les outils.", "Public live chats, channels and public clips, as far as the tools cover them."),
     "limits": ("Les messages privés et les contenus réservés aux abonnés.", "Private messages and subscriber-only content."),
     "uses": ["ambassadors", "campaign-impact", "rejuvenate"],
     "faq": [(("Pouvez-vous mesurer un partenariat avec un streamer ?", "Can you measure a partnership with a streamer?"), ("Oui : les réactions du chat pendant le live, les clips repris, et l'écho sur les autres réseaux.", "Yes: chat reactions during the stream, the clips picked up, and the echo on other networks.")),
             (("Twitch ne concerne-t-il que le jeu vidéo ?", "Is Twitch only about gaming?"), ("Non : discussions, sport, musique et événements y ont aussi leur public.", "No: talk shows, sport, music and events have their audience there too."))]},

    {"slug": "telegram", "tools": ["visibrain", "youscan"], "name": "Telegram", "glyph": "telegram",
     "tag": ("les canaux publics", "public channels"),
     "lead": ("Telegram mêle messagerie privée et canaux publics suivis par des milliers d'abonnés. Les canaux publics comptent dans certains pays et sur certains sujets, rumeurs et informations sensibles compris.",
              "Telegram mixes private messaging with public channels followed by thousands. Public channels matter in some countries and on some topics, rumours and sensitive information included."),
     "reads": [(("Les canaux publics", "Public channels"), ("Les annonces et discussions ouvertes sur votre marque ou votre secteur.", "Open announcements and discussions about your brand or sector.")),
               (("Les groupes publics", "Public groups"), ("Les communautés ouvertes, souvent spécialisées.", "Open communities, often specialised.")),
               (("Les rumeurs", "Rumours"), ("Les contenus qui partent de Telegram vers les autres réseaux.", "Content that travels from Telegram to other networks."))],
     "access": ("Les canaux et groupes publics.", "Public channels and groups."),
     "limits": ("Les conversations et groupes privés : jamais.", "Private chats and groups: never."),
     "uses": ["brand-risk", "stakeholders", "reputation"],
     "faq": [(("Pour quelles marques Telegram compte-t-il ?", "For which brands does Telegram matter?"), ("Celles exposées à l'international, à la tech, à la finance ou aux sujets sensibles.", "Those exposed internationally, in tech, finance or sensitive topics.")),
             (("Lisez-vous les groupes privés ?", "Do you read private groups?"), ("Non, seulement ce qui est public.", "No, only what is public."))]},

    {"slug": "bluesky", "tools": ["visibrain"], "name": "Bluesky", "glyph": "bluesky",
     "tag": ("la nouvelle conversation ouverte", "the new open conversation"),
     "lead": ("Bluesky a accueilli une partie des journalistes, chercheurs et communautés partis de X. Son protocole est ouvert : les publications publiques y sont accessibles proprement.",
              "Bluesky has welcomed part of the journalists, researchers and communities who left X. Its protocol is open: public posts are cleanly accessible."),
     "reads": [(("Les publications publiques", "Public posts"), ("Les réactions sur votre marque et votre secteur.", "Reactions to your brand and your sector.")),
               (("Les experts et journalistes", "Experts and journalists"), ("Une partie des voix qui comptent y publient désormais.", "Part of the voices that matter now post there.")),
               (("La comparaison avec X", "The comparison with X"), ("Ce qui se dit ici et là, et qui a changé de réseau.", "What is said here and there, and who moved."))],
     "access": ("Les publications publiques, grâce à son protocole ouvert.", "Public posts, thanks to its open protocol."),
     "limits": ("Les messages privés. Le réseau reste plus petit que X : son poids dépend de votre public.", "Private messages. The network remains smaller than X: its weight depends on your audience."),
     "uses": ["leader-advocacy", "reputation", "brand-risk"],
     "faq": [(("Faut-il écouter Bluesky ?", "Should you listen to Bluesky?"), ("Si vos interlocuteurs y sont : journalistes, chercheurs, communautés engagées. Nous le vérifions d'abord.", "If your audiences are there: journalists, researchers, committed communities. We check that first.")),
             (("La collecte y est-elle fiable ?", "Is collection reliable there?"), ("Oui pour les publications publiques : le protocole ouvert rend l'accès plus simple qu'ailleurs.", "Yes for public posts: the open protocol makes access simpler than elsewhere."))]},

    {"slug": "vk", "tools": [], "name": "VK", "glyph": "vk",
     "tag": ("le réseau russophone", "the Russian-speaking network"),
     "lead": ("VK (VKontakte) est le premier réseau social russophone. Pour une marque présente en Russie ou dans les pays russophones, c'est là que se lit une grande partie de la conversation.",
              "VK (VKontakte) is the leading Russian-speaking social network. For a brand present in Russia or Russian-speaking countries, much of the conversation is read there."),
     "reads": [(("Les pages et communautés publiques", "Public pages and communities"), ("Ce qui se dit de votre marque et de votre catégorie.", "What is said about your brand and your category.")),
               (("Les commentaires", "Comments"), ("Les réactions du public russophone.", "The Russian-speaking public's reactions.")),
               (("Les marchés voisins", "Neighbouring markets"), ("La conversation dans les pays où VK reste utilisé.", "The conversation in countries where VK is still used."))],
     "access": ("Les pages et communautés publiques, selon la couverture des outils.", "Public pages and communities, depending on tool coverage."),
     "limits": ("Les profils privés et les messages. La couverture des outils varie selon le contexte réglementaire : nous vérifions ce qui est accessible avant de nous engager.", "Private profiles and messages. Tool coverage varies with the regulatory context: we check what is accessible before committing."),
     "uses": ["market-opportunities", "reputation", "stakeholders"],
     "faq": [(("Couvrez-vous VK aujourd'hui ?", "Do you cover VK today?"), ("Selon les outils et le contexte : nous vérifions la couverture pour votre question avant de lancer l'étude.", "Depending on the tools and the context: we check coverage for your question before starting.")),
             (("Qui lit les contenus en russe ?", "Who reads content in Russian?"), ("Nous vous le disons au cadrage : la lecture se fait dans la langue, pas par traduction automatique seule.", "We tell you at framing: reading is done in the language, not by machine translation alone."))]},

    {"slug": "wechat", "tools": [], "name": "WeChat", "glyph": "wechat",
     "tag": ("l'écosystème chinois", "the Chinese ecosystem"),
     "lead": ("WeChat (Weixin) est l'application de tout en Chine : messagerie, paiements, articles des comptes officiels. Sa partie publique, les comptes officiels et leurs articles, dit beaucoup des marques et de leur image.",
              "WeChat (Weixin) is the everything app in China: messaging, payments, articles from official accounts. Its public part, official accounts and their articles, says a lot about brands and their image."),
     "reads": [(("Les comptes officiels", "Official accounts"), ("Les articles des marques, des médias et des leaders d'opinion.", "Articles from brands, media and opinion leaders.")),
               (("Les réactions", "Reactions"), ("Les commentaires et les lectures des articles publics.", "Comments and reads on public articles.")),
               (("Votre image en Chine", "Your image in China"), ("Comment votre marque est racontée, lue en mandarin par nos consultants.", "How your brand is told, read in Mandarin by our consultants."))],
     "access": ("Les comptes officiels et leurs articles publics.", "Official accounts and their public articles."),
     "limits": ("Les messages, les groupes et les « Moments » privés : jamais.", "Messages, groups and private Moments: never."),
     "uses": ["market-opportunities", "reputation", "segmentation"],
     "faq": [(("Lisez-vous le chinois ?", "Do you read Chinese?"), ("Oui : nos consultants travaillent en mandarin et en cantonais. Un marché lu par traduction automatique est un marché lu à moitié.", "Yes: our consultants work in Mandarin and Cantonese. A market read through machine translation is a market read half-wrong.")),
             (("WeChat suffit-il pour la Chine ?", "Is WeChat enough for China?"), ("Non : nous le croisons avec Weibo, Douyin, Xiaohongshu et Bilibili.", "No: we cross it with Weibo, Douyin, Xiaohongshu and Bilibili."))]},

    {"slug": "weibo", "tools": ["talkwalker"], "name": "Weibo", "glyph": "sinaweibo",
     "tag": ("le débat public chinois", "China's public debate"),
     "lead": ("Weibo est la grande place publique chinoise : sujets tendance, célébrités, polémiques. Une crise de marque en Chine y devient souvent visible en premier.",
              "Weibo is China's great public square: trending topics, celebrities, controversies. A brand crisis in China often becomes visible there first."),
     "reads": [(("Les sujets tendance", "Trending topics"), ("Ce qui occupe le débat, et la place de votre marque.", "What occupies the debate, and your brand's place in it.")),
               (("Les célébrités et KOL", "Celebrities and KOLs"), ("Les voix qui font et défont une image.", "The voices that make and break an image.")),
               (("Les polémiques", "Controversies"), ("Les sujets sensibles à suivre au plus tôt.", "Sensitive topics to follow as early as possible."))],
     "access": ("Les publications publiques, leurs commentaires et les sujets tendance.", "Public posts, their comments and trending topics."),
     "limits": ("Les comptes restreints et les messages. Certains contenus peuvent être retirés rapidement : la veille doit être continue.", "Restricted accounts and messages. Some content can be removed quickly: monitoring has to be continuous."),
     "uses": ["brand-risk", "reputation", "stakeholders"],
     "faq": [(("Pouvez-vous nous alerter sur une crise en Chine ?", "Can you alert us to a crisis in China?"), ("Oui, avec une veille continue lue en mandarin, et un protocole d'alerte défini avec vous.", "Yes, with continuous monitoring read in Mandarin, and an alert protocol agreed with you.")),
             (("Weibo ou Douyin ?", "Weibo or Douyin?"), ("Les deux : le débat sur Weibo, les tendances de consommation sur Douyin.", "Both: debate on Weibo, consumer trends on Douyin."))]},

    {"slug": "douyin", "tools": [], "name": "Douyin", "glyph": "tiktok",
     "tag": ("les tendances vidéo en Chine", "video trends in China"),
     "lead": ("Douyin est la version chinoise de TikTok, avec ses propres créateurs, son commerce intégré et ses tendances. C'est là que se lancent beaucoup de produits de consommation en Chine.",
              "Douyin is TikTok's Chinese counterpart, with its own creators, built-in commerce and trends. It is where many consumer products launch in China."),
     "reads": [(("Les vidéos et leurs commentaires", "Videos and comments"), ("Ce qui se montre et se dit de votre catégorie.", "What is shown and said about your category.")),
               (("Les créateurs", "Creators"), ("Les KOL qui font vendre, et leur audience.", "The KOLs who drive sales, and their audience.")),
               (("Le commerce en direct", "Live commerce"), ("Les produits mis en avant, et les réactions des acheteurs.", "The products pushed, and buyers' reactions."))],
     "access": ("Les vidéos publiques et leurs commentaires, selon la couverture des outils.", "Public videos and their comments, depending on tool coverage."),
     "limits": ("Les comptes privés et les messages. Le contenu est d'abord vidéo : transcription et lecture visuelle sont nécessaires.", "Private accounts and messages. Content is video first: transcription and visual reading are needed."),
     "uses": ["stakeholders", "rejuvenate", "market-opportunities"],
     "faq": [(("Douyin et TikTok, c'est la même chose ?", "Are Douyin and TikTok the same?"), ("Même éditeur, mais deux réseaux distincts, avec des publics et des tendances différents.", "Same publisher, but two separate networks, with different audiences and trends.")),
             (("Lisez-vous les vidéos en chinois ?", "Do you read videos in Chinese?"), ("Oui, nos consultants travaillent en mandarin, à partir des descriptions, des commentaires et des transcriptions.", "Yes, our consultants work in Mandarin, from descriptions, comments and transcripts."))]},

    {"slug": "xiaohongshu", "tools": [], "name": "Xiaohongshu (RED)", "glyph": "xiaohongshu",
     "tag": ("les avis et le lifestyle en Chine", "reviews and lifestyle in China"),
     "lead": ("Xiaohongshu, ou RED, est le réseau où les consommateurs chinois partagent leurs avis, leurs achats et leurs recommandations, en beauté, mode, voyage et alimentation surtout.",
              "Xiaohongshu, or RED, is the network where Chinese consumers share their reviews, purchases and recommendations, in beauty, fashion, travel and food especially."),
     "reads": [(("Les notes et avis", "Notes and reviews"), ("Les retours d'expérience détaillés sur vos produits.", "Detailed experience reports on your products.")),
               (("Les recommandations", "Recommendations"), ("Ce qui se conseille, et ce qui se déconseille.", "What gets recommended, and what does not.")),
               (("Les créateurs", "Creators"), ("Les voix qui influencent l'achat.", "The voices that influence purchase."))],
     "access": ("Les notes publiques et leurs commentaires, selon la couverture des outils.", "Public notes and their comments, depending on tool coverage."),
     "limits": ("Les messages et les comptes privés. La couverture des outils occidentaux reste partielle : nous la vérifions avant de nous engager.", "Messages and private accounts. Western tools' coverage remains partial: we check it before committing."),
     "uses": ["product-test", "market-opportunities", "ambassadors"],
     "faq": [(("Pourquoi Xiaohongshu pour un lancement en Chine ?", "Why Xiaohongshu for a launch in China?"), ("Parce que c'est là que les consommateurs vérifient un produit avant de l'acheter.", "Because it is where consumers check a product before buying it.")),
             (("Comparez-vous avec vos concurrents ?", "Do you compare with competitors?"), ("Oui, produit par produit, à partir des avis publics.", "Yes, product by product, from public reviews."))]},

    {"slug": "bilibili", "tools": [], "name": "Bilibili", "glyph": "bilibili",
     "tag": ("la culture jeune en Chine", "youth culture in China"),
     "lead": ("Bilibili est la plateforme vidéo de la jeunesse chinoise : animation, jeu vidéo, tech, culture, avec ses commentaires qui défilent sur la vidéo (danmaku).",
              "Bilibili is the video platform of Chinese youth: animation, gaming, tech, culture, with comments scrolling over the video (danmaku)."),
     "reads": [(("Les vidéos", "Videos"), ("Les tests, les avis et les contenus de votre catégorie.", "Tests, reviews and content in your category.")),
               (("Les commentaires défilants", "Scrolling comments"), ("Les réactions à la seconde près, moment par moment.", "Reactions to the second, moment by moment.")),
               (("Les créateurs", "Creators"), ("Les voix qui comptent pour les jeunes Chinois.", "The voices that matter to young Chinese."))],
     "access": ("Les vidéos publiques et leurs commentaires, selon la couverture des outils.", "Public videos and their comments, depending on tool coverage."),
     "limits": ("Les messages et les contenus réservés. La couverture des outils occidentaux reste partielle.", "Messages and restricted content. Western tools' coverage remains partial."),
     "uses": ["rejuvenate", "ambassadors", "stakeholders"],
     "faq": [(("Pour quelles marques Bilibili compte-t-il ?", "For which brands does Bilibili matter?"), ("Celles qui visent les 15-30 ans en Chine, la tech, le jeu vidéo et la culture.", "Those targeting 15 to 30-year-olds in China, tech, gaming and culture.")),
             (("Que disent les commentaires défilants ?", "What do scrolling comments tell?"), ("La réaction exacte à chaque moment d'une vidéo : ce qui fait rire, agace ou convainc.", "The exact reaction to each moment of a video: what amuses, annoys or convinces."))]},
]
