"""The long-form section of the Perplexity tool page (SEO audit: the page was
too short, about 550 words, for "agence Perplexity", "ma marque dans
Perplexity", "être cité par Perplexity"): how Perplexity builds an answer,
why its numbered sources can be measured, which sources it puts forward, how
to find out whether a site is cited, its two crawlers (PerplexityBot and
Perplexity-User), the sources competitors have, what to do about an
unfavourable answer, and what tracking delivers. Each block is (heading,
[paragraphs]), every string a (French, English) pair. Licter statements come
from the site's own pages (fr/outils/perplexity, fr/expertise/ai-listening,
tools/tools_data.py, tools/ai_engines.py, tools/geo_guide.py,
tools/chatgpt_guide.py); public facts about Perplexity carry a `# source:`
comment."""

KICKER = ("PERPLEXITY, EN DÉTAIL", "PERPLEXITY, IN DETAIL")
TITLE = ("Votre marque dans Perplexity : les sources qu'il cite", "Your brand in Perplexity: the sources it cites")

BLOCKS = [
    (("Comment Perplexity construit une réponse", "How Perplexity builds an answer"), [
        # source: https://www.perplexity.ai/help-center/en/articles/10352895-how-does-perplexity-work (searches the internet in real time; interprets the question, searches articles, websites and journals, summarises; "Each answer includes numbered citations linking to the original sources"; read via the Wayback Machine copy of 8 December 2025, the live page blocks automated fetches)
        ("Perplexity construit chaque réponse à partir d'une recherche sur le web, faite au moment où la question est posée. Selon son centre d'aide, il interprète d'abord la question, cherche ensuite des articles, des sites et des revues, puis résume ce qu'il a trouvé. Chaque réponse porte des citations numérotées qui renvoient aux pages d'origine.",
         "Perplexity builds each answer from a web search, run at the moment the question is asked. According to its help center, it first interprets the question, then searches for articles, websites and journals, and summarises what it found. Each answer carries numbered citations that link to the original pages."),
        # source: https://www.perplexity.ai/help-center/en/articles/10352903-what-is-pro-search (Pro users can choose among models including Perplexity's own Sonar and models from OpenAI, Anthropic and Google; Pro Search keeps context from previous interactions; Wayback Machine copy of 30 December 2025)
        # source: https://www.perplexity.ai/help-center/en/articles/10352895-how-does-perplexity-work (model selector available to Pro subscribers; follow-up questions keep the context of previous queries)
        ("Perplexity ne s'appuie pas sur un seul modèle d'IA. Les abonnés peuvent choisir celui qui rédige la réponse, parmi lesquels son propre modèle, Sonar, et des modèles d'OpenAI, d'Anthropic ou de Google. La conversation garde aussi le contexte des questions précédentes. Deux personnes qui posent la même question n'obtiennent donc pas forcément la même réponse.",
         "Perplexity does not rely on a single AI model. Subscribers can choose the one that writes the answer, among them its own model, Sonar, and models from OpenAI, Anthropic or Google. The conversation also keeps the context of previous questions. Two people asking the same question therefore do not necessarily get the same answer."),
    ]),
    (("Pourquoi les sources citées par Perplexity sont mesurables", "Why the sources Perplexity cites can be measured"), [
        ("Les sources citées par Perplexity sont mesurables parce qu'elles sont affichées, numérotées, à côté de chaque réponse. Un assistant qui répond de mémoire laisse deviner d'où vient ce qu'il dit ; Perplexity le montre. On peut donc relever les sites cités, compter combien de fois chacun revient sur les questions de votre catégorie, et voir lesquels parlent de vous.",
         "The sources Perplexity cites can be measured because they are shown, numbered, next to each answer. An assistant answering from memory leaves you to guess where what it says comes from; Perplexity shows it. You can therefore record the sites cited, count how often each one comes back on your category's questions, and see which ones talk about you."),
        ("Cette mesure n'a de sens que sur plusieurs essais et dans la durée. La même question ne donne pas toujours la même réponse, ni la même liste de sources. Nous posons donc chaque question plusieurs fois, chaque mois, puis nous relevons et classons les sources citées. Une page qui revient à chaque essai pèse plus qu'une page apparue une seule fois.",
         "This measurement only makes sense over several tries and over time. The same question does not always give the same answer, nor the same list of sources. We therefore ask each question several times, every month, then record and sort the sources cited. A page that comes back on every try weighs more than a page that appeared only once."),
    ]),
    (("Quelles sources Perplexity met en avant", "Which sources Perplexity puts forward"), [
        # source: https://www.perplexity.ai/help-center/en/articles/10352155-what-is-perplexity ("All responses are supported by citations from reputable news organizations, academic publications, and established content sources"; Wayback Machine copy of 21 December 2025)
        # source: https://www.perplexity.ai/help-center/en/articles/10352903-what-is-pro-search (Pro Search draws "from articles, academic papers, forums, videos, and more, depending on your selected focus (e.g., Web, Academic, Finance, Files)")
        ("Les sources que Perplexity met en avant sont, selon lui, des médias reconnus, des publications académiques et des sites établis. Sa recherche avancée, Pro Search, puise aussi dans les forums et les vidéos, et l'utilisateur peut la restreindre à certains contenus, comme les publications académiques ou la finance. Ces catégories restent larges : elles ne disent pas quels sites comptent dans votre marché.",
         "The sources Perplexity puts forward are, by its own account, recognised news outlets, academic publications and established sites. Its advanced search, Pro Search, also draws on forums and videos, and users can restrict it to certain content, such as academic publications or finance. These categories remain broad: they do not say which sites count in your market."),
        ("La liste utile se mesure donc sur vos propres questions. Sur Perplexity, les pages récentes, la presse et les forums pèsent lourd, mais seul un relevé sur votre catégorie dit lesquels comptent pour vous. Perplexity choisit ses sources selon ses propres critères : un site absent de ses réponses n'est pas pour autant un site inutile pour vos clients.",
         "The list that matters is therefore measured on your own questions. On Perplexity, recent pages, the press and forums weigh heavily, but only a record on your category says which ones count for you. Perplexity picks its sources by its own criteria: a site missing from its answers is not, for all that, a site that is useless to your customers."),
    ]),
    (("Comment savoir si votre site est cité par Perplexity", "How to find out whether Perplexity cites your site"), [
        ("Pour savoir si votre site est cité par Perplexity, il faut lui poser les questions de vos clients et lire les sources numérotées, pas seulement le texte. Deux situations se distinguent : votre marque est nommée dans la réponse, ou votre site figure parmi les sources. On peut être cité sans être nommé, et nommé à partir de pages écrites par d'autres.",
         "To find out whether Perplexity cites your site, you have to ask it your customers' questions and read the numbered sources, not just the text. Two situations differ: your brand is named in the answer, or your site is among the sources. You can be cited without being named, and named on the basis of pages written by others."),
        ("Le relevé porte sur trois familles de questions : les questions de choix, du type « quelle marque pour ce besoin ? », les questions sur votre marque et les comparaisons avec un concurrent. Pour chacune, on note les marques citées, leur ordre et les sites en source. Mieux vaut poser chaque question dans un nouveau fil, sans contexte, comme un client qui découvre votre catégorie.",
         "The record covers three families of questions: choice questions, such as \"which brand for this need?\", questions about your brand and comparisons with a competitor. For each one, you note the brands cited, their order and the sites given as sources. It is better to ask each question in a new thread, with no context, like a customer discovering your category."),
    ]),
    (("PerplexityBot et Perplexity-User : les deux robots à connaître", "PerplexityBot and Perplexity-User: the two crawlers to know"), [
        # source: https://docs.perplexity.ai/docs/resources/perplexity-crawlers (redirect from docs.perplexity.ai/guides/bots; PerplexityBot "is designed to surface and link websites in search results on Perplexity. It is not used to crawl content for AI foundation models"; "we recommend allowing PerplexityBot in your site's robots.txt file")
        ("PerplexityBot et Perplexity-User sont les deux agents par lesquels Perplexity visite les sites. PerplexityBot sert à faire apparaître et à lier des sites dans les résultats de Perplexity ; l'éditeur indique qu'il ne collecte pas de contenus pour entraîner des modèles d'IA. Il se règle dans le fichier robots.txt, et Perplexity recommande de l'autoriser pour qu'un site apparaisse dans ses résultats.",
         "PerplexityBot and Perplexity-User are the two agents through which Perplexity visits sites. PerplexityBot is used to surface and link sites in Perplexity's results; the publisher states that it does not collect content to train AI models. It is set in the robots.txt file, and Perplexity recommends allowing it for a site to appear in its results."),
        # source: https://docs.perplexity.ai/docs/resources/perplexity-crawlers (Perplexity-User visits a page when users ask a question and may link it; "Since a user requested the fetch, this fetcher generally ignores robots.txt rules"; "Each setting works independently, and it may take up to 24 hours"; WAF users "may need to explicitly whitelist Perplexity's bots")
        ("Perplexity-User, lui, visite une page quand un utilisateur pose une question, pour l'aider à répondre et citer un lien. Comme la visite est demandée par une personne, Perplexity précise que cet agent ignore en général le robots.txt. Chaque réglage est indépendant et peut mettre jusqu'à 24 heures à s'appliquer. Un pare-feu applicatif peut aussi bloquer ces robots : un point à vérifier avec vos équipes techniques.",
         "Perplexity-User, for its part, visits a page when a user asks a question, to help answer it and cite a link. Since the visit is requested by a person, Perplexity states that this agent generally ignores robots.txt. Each setting is independent and can take up to 24 hours to apply. A web application firewall can also block these crawlers: a point to check with your technical teams."),
    ]),
    (("Ce que vos concurrents ont dans Perplexity, et pas vous", "What your competitors have in Perplexity, and you do not"), [
        ("Ce que vos concurrents ont dans Perplexity et que vous n'avez pas se lit dans ses sources. Sur une question de choix, il cite quelques marques et s'appuie sur des pages précises pour chacune. En comparant les sources qui nomment un concurrent à celles qui vous nomment, on voit où il est présent et vous absent : un comparatif, un article de presse, une discussion de forum, un site d'avis.",
         "What your competitors have in Perplexity and you do not can be read in its sources. On a choice question, it cites a few brands and relies on specific pages for each one. By comparing the sources that name a competitor with those that name you, you see where it is present and you are absent: a comparison article, a press article, a forum discussion, a review site."),
        ("Cet écart est souvent plus utile qu'un score global, parce qu'il désigne des pages réelles plutôt qu'une impression. Il montre aussi les nouveaux venus : une marque qui entre dans les sources d'un mois sur l'autre, et les pages qui l'y ont fait entrer. C'est la liste des sources de vos concurrents que vous n'avez pas, et elle se suit dans le temps.",
         "This gap is often more useful than an overall score, because it points to real pages rather than an impression. It also shows newcomers: a brand that enters the sources from one month to the next, and the pages that brought it in. It is the list of your competitors' sources that you do not have, and it is followed over time."),
    ]),
    (("Que faire si la réponse de Perplexity vous est défavorable", "What to do if Perplexity's answer is unfavourable to you"), [
        ("Si la réponse de Perplexity vous est défavorable, la première chose à lire est la liste de ses sources. Une erreur, un jugement sévère ou une information datée vient en général d'une page précise : un article ancien, un comparatif jamais mis à jour, un fil de forum. Personne ne peut modifier directement la réponse d'une IA ; on peut en revanche agir sur les pages qu'elle cite.",
         "If Perplexity's answer is unfavourable to you, the first thing to read is its list of sources. An error, a harsh judgement or outdated information usually comes from a specific page: an old article, a comparison never updated, a forum thread. Nobody can change an AI's answer directly; you can, however, act on the pages it cites."),
        ("Il faut ensuite corriger ou compléter ces sources : votre site d'abord, avec une information claire et à jour, puis la presse et les pages de référence. Comme Perplexity cherche à chaque question, une page nouvelle ou corrigée peut être reprise dès qu'elle est trouvée, sans attendre un nouveau modèle. Rien n'est garanti pour autant : on agit sur les sources, puis on mesure si la réponse change.",
         "You then need to correct or complete these sources: your site first, with clear and current information, then the press and reference pages. Since Perplexity searches on every question, a new or corrected page can be picked up as soon as it is found, without waiting for a new model. Nothing is guaranteed for all that: you act on the sources, then measure whether the answer changes."),
    ]),
    (("Ce qu'un suivi Perplexity livre", "What Perplexity tracking delivers"), [
        ("Un suivi Perplexity livre d'abord un audit des réponses : les questions clés de votre catégorie, ce que répond Perplexity, votre place face aux concurrents et les erreurs à corriger. Les mêmes questions sont ensuite reposées chaque mois, avec l'évolution des réponses, les sources citées et une note pour la communication. Licter ne produit pas les contenus ; vos équipes ou vos agences s'en chargent.",
         "Perplexity tracking first delivers an audit of the answers: your category's key questions, what Perplexity answers, your place against competitors and the errors to correct. The same questions are then asked again every month, with how the answers change, the sources cited and a note for communications. Licter does not produce the content; your teams or your agencies do."),
        ("Perplexity ne se lit pas seul. Nous comparons ses réponses à celles de ChatGPT, Claude, Gemini et Grok sur les mêmes questions, et nous le croisons avec Google Actualités pour la presse. Un audit montre ce que l'assistant répond, pas combien de personnes lui posent ces questions : pour l'estimer, on le croise avec le search listening. Aucune donnée client n'est transmise à l'IA.",
         "Perplexity is not read on its own. We compare its answers with those of ChatGPT, Claude, Gemini and Grok on the same questions, and cross it with Google News for the press. An audit shows what the assistant answers, not how many people ask it these questions: to estimate that, it is crossed with search listening. No client data is sent to the AI."),
    ]),
]
