"""One description per tool and network page (SEO plan, step 17): what sets
it apart, 150 characters at most, no ellipsis. Read by tools/build-tech.py."""

DESC = {
    # tools
    "talkwalker": ("Agence Talkwalker : nous opérons la plateforme d'écoute rachetée par Hootsuite, avec sa reconnaissance d'images, et vous livrons l'analyse.",
                   "Talkwalker agency: we run the listening platform Hootsuite bought, image recognition included, and deliver the analysis."),
    "visibrain": ("Agence Visibrain : veille temps réel des réseaux et de la presse, alertes lues par un analyste avant de vous parvenir. Crises comprises.",
                  "Visibrain agency: real-time monitoring of social and press, alerts read by an analyst before they reach you. Crises included."),
    "youscan": ("Agence YouScan : l'écoute visuelle des réseaux. Vos logos et produits repérés dans les images, et le contexte où ils apparaissent.",
                "YouScan agency: visual social listening. Your logos and products spotted in images, and the context they appear in."),
    "soprism": ("Agence SoPrism (Audiense) : nous profilons vos communautés, centres d'intérêt, affinités et médias, pour remplacer un persona déclaré.",
                "SoPrism (Audiense) agency: we profile your communities, interests, affinities and media, to replace a declared persona."),
    "radarly": ("Agence Radarly : le logiciel de Linkfluence, racheté par Meltwater, opéré par nos consultants pour suivre votre marque dans la durée.",
                "Radarly agency: Linkfluence's software, bought by Meltwater, run by our consultants to track your brand over time."),
    "brandwatch": ("Agence Brandwatch : des années de conversation archivées et des audiences fines, lues par nos analystes pour vos études consommateurs.",
                   "Brandwatch agency: years of archived conversation and fine audiences, read by our analysts for your consumer studies."),
    "sprinklr": ("Agence Sprinklr : nous reprenons votre plateforme, remettons la configuration à plat et livrons chaque mois une lecture de la voix client.",
                 "Sprinklr agency: we take over your platform, straighten out its set-up and deliver a monthly read of the customer voice."),
    "semrush": ("Agence Semrush, au-delà du SEO : ce que vos clients cherchent sur Google, lu comme une étude de marché par nos consultants.",
                "Semrush agency, beyond SEO: what your customers search for on Google, read as market research by our consultants."),
    "google-trends": ("Google Trends mis en contexte : la courbe de recherche d'un sujet croisée avec la conversation sociale, pour dater une tendance.",
                      "Google Trends in context: a topic's search curve crossed with the social conversation, to date a trend."),
    "answerthepublic": ("AnswerThePublic : les questions que votre marché pose à Google, classées et lues pour en tirer contenus, FAQ et offres.",
                        "AnswerThePublic: the questions your market asks Google, sorted and read to turn them into content, FAQs and offers."),
    "chatgpt": ("Agence ChatGPT : ce que l'IA d'OpenAI répond sur votre marque, vos concurrents et votre catégorie, et les sources qu'elle cite.",
                "ChatGPT agency: what OpenAI's assistant answers about your brand, your competitors and your category, and the sources it cites."),
    "geo": ("GEO : votre visibilité dans les réponses de ChatGPT, Claude, Gemini et Perplexity, mesurée puis améliorée par nos consultants.",
            "GEO: your visibility in ChatGPT, Claude, Gemini and Perplexity answers, measured then improved by our consultants."),
    "meta-ads": ("Bibliothèque publicitaire Meta : les campagnes de vos concurrents sur Facebook et Instagram, relevées et lues pour vos arbitrages.",
                 "Meta Ad Library: your competitors' campaigns on Facebook and Instagram, collected and read for your decisions."),
    "google-news": ("Google Actualités face au social : quand la presse reprend un sujet né sur les réseaux, et ce que cela change pour votre marque.",
                    "Google News against social: when the press picks up a topic born on social media, and what it changes for your brand."),
    "social-blade": ("Social Blade : la croissance réelle des comptes et des créateurs, pour vérifier une audience avant un partenariat.",
                     "Social Blade: the real growth of accounts and creators, to check an audience before a partnership."),
    "claude": ("Agence Claude : ce que l'assistant d'Anthropic dit de votre marque, ses sources et ses erreurs, suivis question après question.",
               "Claude agency: what Anthropic's assistant says about your brand, its sources and its mistakes, tracked question by question."),
    "gemini": ("Agence Gemini : ce que l'IA de Google répond sur votre marque, au plus près de la recherche, et comment le faire évoluer.",
               "Gemini agency: what Google's AI answers about your brand, closest to search, and how to change it."),
    "perplexity": ("Agence Perplexity : votre marque dans le moteur de réponses qui cite ses sources, et les pages qui pèsent sur sa réponse.",
                   "Perplexity agency: your brand in the answer engine that cites its sources, and the pages that shape its answer."),
    "grok": ("Agence Grok : ce que l'IA de X dit de votre marque, nourrie par la conversation en direct du réseau.",
             "Grok agency: what X's AI says about your brand, fed by the network's live conversation."),
    # networks
    "facebook": ("Social listening Facebook : les groupes, les pages locales et les commentaires sous vos publications, lus par nos analystes.",
                 "Facebook social listening: groups, local pages and comments under your posts, read by our analysts."),
    "instagram": ("Social listening Instagram : vos produits dans l'image, les créateurs qui en parlent et ce que disent les commentaires.",
                  "Instagram social listening: your products in the image, the creators who talk about them and what comments say."),
    "threads": ("Social listening Threads : la conversation écrite de Meta, où journalistes, marques et communautés se sont installés.",
                "Threads social listening: Meta's written conversation, where journalists, brands and communities have settled."),
    "whatsapp": ("Social listening WhatsApp : les chaînes publiques et ce qui en sort, sans jamais lire une conversation privée.",
                 "WhatsApp social listening: public channels and what spreads from them, never a private conversation."),
    "messenger": ("Messenger : votre service client en privé, lu seulement avec vos accès, et croisé avec ce qui se dit en public.",
                  "Messenger: your customer service in private, read only with your access, and crossed with what is said in public."),
    "x-twitter": ("Social listening X (Twitter) : l'actualité en direct, les journalistes et les crises qui démarrent, suivis en temps réel.",
                  "X (Twitter) social listening: live news, journalists and crises taking off, followed in real time."),
    "tiktok": ("Social listening TikTok : les tendances, les sons et les codes où les plus jeunes parlent des marques, lus avant qu'ils explosent.",
               "TikTok social listening: the trends, sounds and codes where the young talk about brands, read before they explode."),
    "youtube": ("Social listening YouTube : tests, tutoriels et avis détaillés, et des commentaires argumentés qui expliquent un produit.",
                "YouTube social listening: tests, tutorials and detailed reviews, and reasoned comments that explain a product."),
    "linkedin": ("Social listening LinkedIn : marque employeur, dirigeants et décideurs, ce qui se dit et ce qui pèse sur votre réputation.",
                 "LinkedIn social listening: employer brand, executives and decision makers, what is said and what weighs on your reputation."),
    "reddit": ("Social listening Reddit : des communautés de passionnés, des avis francs et détaillés, rarement sponsorisés.",
               "Reddit social listening: communities of enthusiasts, frank and detailed reviews, rarely sponsored."),
    "snapchat": ("Social listening Snapchat : Spotlight et les stories publiques, ce que les plus jeunes laissent voir d'eux.",
                 "Snapchat social listening: Spotlight and public stories, what the youngest let others see."),
    "pinterest": ("Social listening Pinterest : ce que les gens épinglent avant d'acheter, souvent des mois à l'avance.",
                  "Pinterest social listening: what people pin before they buy, often months ahead."),
    "discord": ("Social listening Discord : les serveurs publics des communautés de jeu, de tech ou de marque, et leurs débats.",
                "Discord social listening: the public servers of gaming, tech or brand communities, and their debates."),
    "twitch": ("Social listening Twitch : le direct et son chat, où une marque est jugée à chaud par une audience jeune.",
               "Twitch social listening: live streams and their chat, where a brand is judged on the spot by a young audience."),
    "telegram": ("Social listening Telegram : les canaux publics suivis par des milliers d'abonnés, utiles sur certains pays et sujets.",
                 "Telegram social listening: public channels followed by thousands, useful on some countries and topics."),
    "bluesky": ("Social listening Bluesky : le réseau ouvert où journalistes, chercheurs et communautés partis de X se retrouvent.",
                "Bluesky social listening: the open network where journalists, researchers and communities who left X gather."),
    "vk": ("Social listening VK : le premier réseau russophone, lu dans sa langue par nos analystes.",
           "VK social listening: the leading Russian-speaking network, read in its language by our analysts."),
    "wechat": ("Social listening WeChat : les comptes officiels et articles de l'application de tout en Chine, lus en chinois.",
               "WeChat social listening: official accounts and articles of China's everything app, read in Chinese."),
    "weibo": ("Social listening Weibo : la place publique chinoise, ses sujets tendance et ses polémiques, lus en mandarin.",
              "Weibo social listening: China's public square, its trending topics and controversies, read in Mandarin."),
    "douyin": ("Social listening Douyin : le TikTok chinois, ses créateurs, son commerce intégré et les tendances qui y naissent.",
               "Douyin social listening: China's TikTok, its creators, built-in commerce and the trends born there."),
    "xiaohongshu": ("Social listening Xiaohongshu (RED) : les avis et recommandations des consommateurs chinois en beauté, mode et voyage.",
                    "Xiaohongshu (RED) social listening: Chinese consumers' reviews and recommendations in beauty, fashion and travel."),
    "bilibili": ("Social listening Bilibili : la vidéo de la jeunesse chinoise, animation, jeu, tech, et ses commentaires en surimpression.",
                 "Bilibili social listening: the video platform of young China, animation, gaming, tech, and its on-screen comments."),
}
