"""The long-form section of the TikTok network page (SEO audit: the page was
too short for "social listening TikTok", "veille TikTok", "écoute TikTok
marque"): whether TikTok can be listened to, what can be read there, why it
differs from other networks, spotting trends, comments, tools, limits, the
Huda Beauty case and how TikTok connects to the other networks. Each block is
(heading, [paragraphs]), every string a (French, English) pair. Licter
figures come from article-le-bad-buzz-huda-beauty-decrypte.html and
tools/proof.py; quotes from tools/podcast_quotes.py and
article-comment-orange-analyse-tiktok-grace-au-social-listening.html. Public
facts about TikTok carry a source comment."""

KICKER = ("LE SOCIAL LISTENING SUR TIKTOK, EN DÉTAIL", "SOCIAL LISTENING ON TIKTOK, IN DETAIL")
TITLE = ("Ce qu'il faut savoir avant d'écouter TikTok.", "What to know before you listen to TikTok.")

BLOCKS = [
    (("Peut-on faire du social listening sur TikTok ?", "Can you do social listening on TikTok?"), [
        ("Oui. Les vidéos publiques, leurs descriptions, leurs hashtags et leurs commentaires peuvent être collectés et analysés, comme sur les autres réseaux. Ce qui change, c'est la matière : sur TikTok, l'essentiel du message passe par l'image, la voix et le son. Écouter TikTok demande donc de lire au-delà du texte, sinon on passe à côté d'une grande partie de ce qui se dit.",
         "Yes. Public videos, their descriptions, hashtags and comments can be collected and analysed, as on other networks. What changes is the material: on TikTok, most of the message goes through the image, the voice and the sound. Listening to TikTok therefore means reading beyond the text, or you miss a large part of what is being said."),
        ("La question n'est d'ailleurs plus de savoir si votre marque y est présente. Jean-Christophe Gatuingt, cofondateur de Visibrain, le résume dans notre podcast : « sur TikTok, il y a de grandes chances qu'on parle de votre marque, quelle que soit votre marque ». Une veille TikTok sert d'abord à savoir où, comment et par qui.",
         "The question is no longer whether your brand is there. Jean-Christophe Gatuingt, co-founder of Visibrain, sums it up in our podcast: on TikTok, there is a good chance people are talking about your brand, whatever your brand. TikTok monitoring first serves to find out where, how and by whom."),
        ("Veille TikTok et social listening TikTok ne répondent pas à la même question. La veille signale ce qui se passe : une vidéo qui démarre, un pic de mentions, une critique qui prend. Le social listening analyse la conversation dans la durée pour expliquer ce qu'elle dit d'une marque, d'une audience ou d'un marché. Sur TikTok, la première sert à réagir vite, le second à comprendre ce qui fait durer un sujet.",
         "TikTok monitoring and TikTok social listening do not answer the same question. Monitoring signals what is happening: a video taking off, a spike in mentions, a criticism catching on. Social listening analyses the conversation over time to explain what it says about a brand, an audience or a market. On TikTok, the first helps you react fast, the second helps you understand what makes a subject last."),
    ]),
    (("Qu'est-ce qu'on peut lire sur TikTok : vidéos, commentaires, sons, hashtags ?", "What can you read on TikTok: videos, comments, sounds, hashtags?"), [
        ("La description de la vidéo et ses hashtags, d'abord : c'est la partie la plus facile à collecter, et souvent la plus pauvre. Puis ce qui est dit dans la vidéo, quand une transcription existe, et ce qui est visible à l'image : un produit, un logo, un lieu. Enfin les commentaires, qui donnent la réaction du public et sont souvent plus riches que la vidéo elle-même.",
         "First the video's description and hashtags: the easiest part to collect, and often the poorest. Then what is said in the video, when a transcript exists, and what is visible in the frame: a product, a logo, a place. Finally the comments, which give the audience's reaction and are often richer than the video itself."),
        ("Le son est un cas à part. Sur TikTok, une même musique ou un même extrait audio est repris par des milliers de vidéos, et c'est souvent lui qui porte une tendance. Suivre un son, c'est suivre un format : la manière dont un sujet se raconte, se parodie et se transforme d'une vidéo à l'autre.",
         "Sound is a case apart. On TikTok, the same music or audio clip is reused by thousands of videos, and it is often what carries a trend. Following a sound means following a format: the way a subject is told, parodied and transformed from one video to the next."),
    ]),
    (("Pourquoi TikTok est différent des autres réseaux", "Why TikTok is different from other networks"), [
        # source: https://newsroom.tiktok.com/en-us/how-tiktok-recommends-videos-for-you
        ("Sur TikTok, la diffusion ne dépend pas d'abord des abonnés. Selon TikTok, ni le nombre d'abonnés d'un compte ni ses succès passés ne sont des facteurs directs de recommandation : le fil Pour toi s'appuie surtout sur les interactions des utilisateurs et sur les éléments de la vidéo, dont sa légende, son son et ses hashtags. Un compte inconnu peut donc toucher des millions de personnes.",
         "On TikTok, reach does not depend on followers first. According to TikTok, neither an account's follower count nor its past hits are direct factors in recommendations: the For You feed relies mainly on user interactions and on the video's details, including its caption, sound and hashtags. An unknown account can therefore reach millions of people."),
        ("Conséquence pour l'écoute : une liste de comptes à surveiller ne suffit pas. Il faut suivre des sujets, des mots, des sons et des formats, et lire qui les porte vraiment. Une marque y apparaît souvent à l'image ou à l'oral, sans être écrite dans la légende : une requête qui ne cherche que le nom de la marque laisse passer une partie de la conversation.",
         "The consequence for listening: a list of accounts to watch is not enough. You have to follow subjects, words, sounds and formats, and read who really carries them. A brand often appears on screen or in speech without being written in the caption: a query that only looks for the brand name lets part of the conversation slip by."),
    ]),
    (("Comment repérer une tendance TikTok avant qu'elle ne sorte du réseau ?", "How do you spot a TikTok trend before it leaves the network?"), [
        ("Une tendance se repère à sa vitesse plus qu'à son volume. Quand elle affiche de gros chiffres, elle est souvent déjà installée, voire en train de saturer. Ce qui compte, c'est l'accélération : un son, un hashtag ou une expression repris par un nombre croissant de créateurs différents, en peu de jours, et dans des communautés qui ne se parlent pas d'habitude.",
         "A trend is spotted by its speed more than its volume. When it shows big numbers, it is often already settled, or even saturating. What matters is acceleration: a sound, a hashtag or a phrase taken up by a growing number of different creators, within a few days, and in communities that do not usually talk to each other."),
        # source: https://ads.tiktok.com/help/article/how-to-use-trends
        ("TikTok publie lui-même une partie de ces signaux dans son Creative Center : hashtags, sons, créateurs et vidéos en tendance, par région et par période, avec un onglet dédié aux sons qui percent. C'est un bon point de départ, mais il dit ce qui monte, pas pourquoi, ni ce que cela signifie pour votre marque.",
         "TikTok itself publishes part of these signals in its Creative Center: trending hashtags, sounds, creators and videos, by region and by period, with a tab for breakout sounds. It is a good starting point, but it says what is rising, not why, nor what it means for your brand."),
        ("Le travail d'analyse consiste ensuite à relier ces signaux à votre catégorie : qui lance le sujet, comment il se déforme en circulant, et s'il commence à apparaître ailleurs. Bruce Hoang, directeur communication digitale et data chez Orange, le dit sans détour dans notre podcast : « toutes les tendances viennent de TikTok ».",
         "The analysis then consists of linking those signals to your category: who starts the subject, how it changes as it travels, and whether it is starting to appear elsewhere. Bruce Hoang, head of digital communication and data at Orange, puts it bluntly in our podcast: all trends come from TikTok."),
    ]),
    (("Les commentaires, la vraie conversation", "Comments, the real conversation"), [
        ("Sur TikTok, la vidéo lance un sujet, mais ce sont les commentaires qui disent comment il est reçu. On y lit l'adhésion, l'ironie, les questions, les comparaisons avec un concurrent, et parfois l'information qui manquait à la vidéo. Une vidéo neutre peut porter des commentaires très négatifs, et l'inverse est vrai aussi.",
         "On TikTok, the video starts a subject, but the comments say how it is received. You read agreement, irony, questions, comparisons with a competitor, and sometimes the information the video lacked. A neutral video can carry very negative comments, and the reverse is also true."),
        ("C'est aussi là que le sentiment automatique se trompe le plus. Les commentaires sont courts, codés, pleins d'emojis, de second degré et de références à d'autres vidéos. Un analyste qui connaît les codes du réseau et la langue du marché doit les relire avant d'en tirer une conclusion, surtout quand la décision porte sur une crise.",
         "It is also where automatic sentiment goes most wrong. Comments are short, coded, full of emojis, irony and references to other videos. An analyst who knows the network's codes and the market's language has to reread them before drawing a conclusion, especially when the decision concerns a crisis."),
        ("Les commentaires disent aussi qui regarde. Le vocabulaire employé, les références partagées et les questions posées renseignent sur le public d'une vidéo mieux que son nombre de vues. Pour une marque qui veut toucher une audience plus jeune, c'est souvent la lecture la plus utile : comprendre ce qui intéresse ce public, et ce qui le fait décrocher.",
         "Comments also tell you who is watching. The words used, the shared references and the questions asked say more about a video's audience than its view count. For a brand that wants to reach a younger audience, it is often the most useful reading: understanding what interests that audience, and what makes it switch off."),
    ]),
    (("Quels outils pour la veille TikTok ?", "Which tools for TikTok monitoring?"), [
        ("Aucun outil ne lit TikTok en entier. Nous en combinons plusieurs selon la question : Visibrain pour suivre la conversation en temps réel, YouScan pour reconnaître une marque dans les visuels même quand personne ne la nomme, Social Blade pour suivre les abonnés et les vues d'un compte jour après jour. La couverture de TikTok varie d'un éditeur à l'autre, et nous la vérifions avant chaque étude.",
         "No tool reads all of TikTok. We combine several depending on the question: Visibrain to follow the conversation in real time, YouScan to recognise a brand in visuals even when nobody names it, Social Blade to track an account's followers and views day by day. TikTok coverage varies from one publisher to the next, and we check it before every study."),
        # source: https://developers.tiktok.com/products/research-api/
        # source: https://newsroom.tiktok.com/en-eu/compliance-digital-services-act-eu
        ("TikTok propose aussi ses propres accès. Son API de recherche est réservée aux chercheurs académiques et aux organismes de recherche à but non lucratif, pour des travaux non commerciaux : une marque ne peut pas s'en servir pour sa veille. En Europe, sa bibliothèque de contenus commerciaux permet en revanche de consulter les publicités diffusées sur la plateforme, avec leurs dates et leurs principaux critères de ciblage.",
         "TikTok also offers its own access points. Its Research API is reserved for academic researchers and not-for-profit research bodies, for non-commercial work: a brand cannot use it for its monitoring. In Europe, however, its Commercial Content Library lets anyone look up the ads run on the platform, with their dates and main targeting parameters."),
    ]),
    (("Ce qu'on ne peut pas lire sur TikTok", "What you cannot read on TikTok"), [
        ("Les messages privés, les comptes privés et les vidéos dont la diffusion est limitée restent hors de portée, et c'est normal. Les partages en messagerie, qui font circuler beaucoup de vidéos, ne sont pas visibles non plus. Une veille TikTok lit ce qui est public, et seulement cela : nous ne collectons jamais de données privées.",
         "Private messages, private accounts and videos with restricted visibility remain out of reach, and rightly so. Shares through messaging, which circulate many videos, are not visible either. TikTok monitoring reads what is public, and only that: we never collect private data."),
        ("D'autres limites tiennent à la matière. Une vidéo sans texte ni transcription échappe en partie aux outils. L'ironie d'un montage, un geste ou une musique choisie pour se moquer ne se détectent pas automatiquement. Et un chiffre de vues ne dit pas qui a regardé, ni ce qu'il en a pensé. C'est pourquoi nous indiquons toujours ce qu'une étude couvre, et ce qu'elle ne couvre pas.",
         "Other limits come from the material. A video without text or transcript partly escapes the tools. The irony of an edit, a gesture or music chosen to mock are not detected automatically. And a view count does not say who watched, nor what they thought. That is why we always state what a study covers, and what it does not."),
    ]),
    (("Un exemple : la crise Huda Beauty, lue sur TikTok", "An example: the Huda Beauty crisis, read on TikTok"), [
        ("Début 2026, Huda Beauty a été la cible d'un appel au boycott. Avec Visibrain, nous avons collecté et nettoyé la conversation, puis l'avons analysée. Sur TikTok, nous avons compté 9 000 mentions, un premier pic à 9,2 millions de vues en une seule journée, puis un record le 28 janvier : 26,1 millions de vues et 267 000 partages.",
         "In early 2026, Huda Beauty was the target of a boycott call. With Visibrain, we collected and cleaned the conversation, then analysed it. On TikTok, we counted 9,000 mentions, a first peak at 9.2 million views in a single day, then a record on 28 January: 26.1 million views and 267,000 shares."),
        ("Deux enseignements ressortent. La crise était mondiale, présente dans 51 langues. Et ce sont les micro-influenceurs, pas les grands comptes, qui dominaient et faisaient le plus de vues : une illustration directe de la façon dont TikTok diffuse. Au total, malgré 242 millions de vues en quelques jours, notre lecture concluait à une « crise » qui n'en était pas vraiment une.",
         "Two lessons stand out. The crisis was global, present in 51 languages. And it was micro-influencers, not large accounts, who dominated and drew the most views: a direct illustration of how TikTok spreads content. Overall, despite 242 million views in a few days, our reading concluded it was a \"crisis\" that was not really one."),
    ]),
    (("TikTok et les autres réseaux", "TikTok and the other networks"), [
        ("Un sujet né sur TikTok ne reste pas sur TikTok. Pendant la crise Huda Beauty, la conversation s'est propagée en parallèle sur Instagram, avec 6 000 publications, 28 fois plus que la période précédente, et 198 000 commentaires le 28 janvier, et sur X, avec 40 000 tweets et des retweets multipliés par 230 en 24 heures.",
         "A subject born on TikTok does not stay on TikTok. During the Huda Beauty crisis, the conversation spread in parallel on Instagram, with 6,000 posts, 28 times the previous period, and 198,000 comments on 28 January, and on X, with 40,000 tweets and retweets up 230-fold in 24 hours."),
        ("C'est pourquoi nous lisons rarement TikTok seul. X montre comment un sujet est repris par les médias et les journalistes, Instagram comment il touche les communautés d'une marque, YouTube comment il s'installe dans des formats plus longs. Croiser ces sources permet de savoir si une tendance TikTok reste un phénomène de réseau ou devient un sujet de marché.",
         "That is why we rarely read TikTok alone. X shows how a subject is taken up by media and journalists, Instagram how it reaches a brand's communities, YouTube how it settles into longer formats. Crossing these sources tells you whether a TikTok trend stays a network phenomenon or becomes a market subject."),
    ]),
    (("Ce qu'une marque peut décider grâce à l'écoute de TikTok", "What a brand can decide by listening to TikTok"), [
        ("Rajeunir ses audiences, d'abord : comprendre ce que les plus jeunes disent d'une catégorie, avec leurs mots et leurs formats, avant de chercher à leur parler. Repérer les bons ambassadeurs, ensuite : les créateurs qui parlent déjà de votre univers et que leur public écoute, quel que soit leur nombre d'abonnés. Anticiper, enfin : voir venir une tendance ou une critique avant qu'elle n'atteigne les autres réseaux.",
         "First, rejuvenating audiences: understanding what the youngest say about a category, in their words and formats, before trying to speak to them. Then, finding the right ambassadors: the creators who already talk about your world and whom their audience listens to, whatever their follower count. Finally, anticipating: seeing a trend or a criticism coming before it reaches other networks."),
        ("Pour une veille continue et la gestion de crise, voir notre offre Vigie 360. Pour une étude ponctuelle, une première lecture de TikTok sur votre marque ou votre catégorie part de la même règle que nos autres travaux : la décision à prendre d'abord, les outils ensuite.",
         "For continuous monitoring and crisis management, see our Vigie 360 offer. For a one-off study, a first read of TikTok on your brand or category follows the same rule as our other work: the decision to make first, the tools second."),
    ]),
]
