"""The tools of Tech & tools: one page each (tools/build-tech.py writes
tech-<slug>.html and /fr/outils/<slug>/).

Each entry: slug, name (fr_name when French differs), letter (monogram),
tag (second line of the H1), lead, what (answer to "What is X?"), facts
(the fact sheet), features (what it lets you analyse), deliver (what we
deliver with it), uses (keys of uc_content.CASES), limits, pair (tools we
cross it with) and faq. Pairs are (French, English).

The facts were checked in October 2026 against the vendors' sites,
Wikipedia and the trade press (owners, dates, coverage, limits). Anything
that could not be confirmed is left out. Check again before each release:
these tools change hands often (Hootsuite bought Talkwalker in 2024,
Audiense SoPrism in 2022, Meltwater Linkfluence in 2021, Adobe Semrush in
2026).
"""

ACCESS_PAID = ("Payant, sur devis", "Paid, on quote")
ACCESS_FREE = ("Gratuit", "Free")

TOOLS = [
    {"slug": "talkwalker", "name": "Talkwalker", "letter": "T",
     "tag": ("lu par des analystes", "read by analysts"),
     "lead": ("Talkwalker est l'une des plateformes d'écoute sociale les plus complètes du marché. Nous l'opérons pour nos clients : couverture large, plusieurs marchés, plusieurs langues, et une analyse qui arrive sous forme de réponse.",
              "Talkwalker is one of the most complete social listening platforms on the market. We run it for our clients: broad coverage, several markets, several languages, and an analysis that arrives as an answer."),
     "what": ("Talkwalker est une plateforme d'écoute sociale et d'intelligence consommateur fondée au Luxembourg en 2009, rachetée par Hootsuite en 2024. Elle analyse les conversations des réseaux sociaux, de la presse en ligne, des blogs, des forums et des avis, avec analyse du sentiment et reconnaissance d'images.",
              "Talkwalker is a social listening and consumer intelligence platform founded in Luxembourg in 2009 and bought by Hootsuite in 2024. It analyses conversations across social networks, online press, blogs, forums and reviews, with sentiment analysis and image recognition."),
     "facts": [(("Éditeur", "Publisher"), ("Hootsuite, depuis 2024", "Hootsuite, since 2024")),
               (("Origine", "Origin"), ("Luxembourg, 2009", "Luxembourg, 2009")),
               (("Langues", "Languages"), ("187 annoncées par l'éditeur", "187, per the vendor")),
               (("Accès", "Access"), ACCESS_PAID)],
     "features": [(("L'écoute sur la durée", "Listening over time"), ("Volumes, sujets et tonalité, avec un historique qui permet les lectures avant / après.", "Volumes, topics and tone, with a history that allows before / after reads.")),
                  (("Plusieurs marchés, plusieurs langues", "Several markets, several languages"), ("Un même périmètre appliqué à plusieurs pays, sans reconstruire la requête.", "One perimeter applied to several countries, without rebuilding the query.")),
                  (("La reconnaissance d'images", "Image recognition"), ("Logos, scènes et objets détectés dans les visuels, pas seulement dans le texte.", "Logos, scenes and objects detected in visuals, not only in text.")),
                  (("Les alertes et les pics", "Alerts and spikes"), ("Détection des hausses anormales et tableaux de bord de crise.", "Detection of abnormal rises and crisis dashboards."))],
     "deliver": [(("Suivi de marque continu", "Continuous brand tracking"), [("Périmètre par marque, gamme et marché", "Perimeter per brand, range and market"), ("Sujets et tonalité semaine après semaine", "Topics and tone week after week"), ("Comparaison avec vos concurrents", "Comparison with your competitors"), ("Note mensuelle : ce qui a bougé et pourquoi", "Monthly note: what moved and why")]),
                 (("Lecture de campagne", "Campaign reads"), [("Avant / après sur le même périmètre", "Before / after on the same perimeter"), ("Par audience et par plateforme", "By audience and by platform"), ("L'organique séparé du payant", "Organic separated from paid"), ("Bilan sous quinze jours", "Review within a fortnight")]),
                 (("Étude de marché et de catégorie", "Market and category study"), [("La conversation d'une catégorie entière", "A whole category's conversation"), ("Les besoins mal couverts", "Needs nobody covers well"), ("Les sujets qui accélèrent", "Topics gaining speed"), ("Comparaison multi-marchés", "Multi-market comparison")])],
     "uses": ["reputation", "campaign-impact", "market-opportunities"],
     "limits": [(("Seulement le public", "Public data only"), ("Comme toutes les plateformes d'écoute, elle ne lit que ce qui est public : ni messages privés, ni comptes fermés.", "Like every listening platform, it only reads what is public: no private messages, no closed accounts.")),
                (("Une couverture inégale selon les réseaux", "Uneven coverage across networks"), ("Les réseaux restreignent l'accès à leurs données ; nous vérifions ce qui est couvert pour votre question avant de commencer.", "Networks restrict access to their data; we check what is covered for your question before starting."))],
     "pair": ["visibrain", "youscan", "soprism"],
     "faq": [(("Faut-il notre propre licence Talkwalker ?", "Do we need our own Talkwalker licence?"), ("Non. La licence est la nôtre : vous achetez l'analyse, pas un accès, et personne chez vous n'a à apprendre l'outil.", "No. The licence is ours: you buy the analysis, not a seat, and nobody on your side has to learn the tool.")),
             (("Talkwalker appartient-il à Hootsuite ?", "Does Hootsuite own Talkwalker?"), ("Oui, depuis 2024. Cela ne change rien pour vous : nous restons indépendants de l'éditeur.", "Yes, since 2024. It changes nothing for you: we remain independent of the publisher.")),
             (("Peut-on le combiner avec un autre outil ?", "Can it be combined with another tool?"), ("C'est le cas le plus fréquent : la plupart des questions se règlent avec deux outils croisés.", "That is the most common case: most questions are answered by two tools crossed together."))]},

    {"slug": "visibrain", "name": "Visibrain", "letter": "V",
     "tag": ("quand les minutes comptent", "when minutes count"),
     "lead": ("Visibrain est la plateforme française de veille en temps réel, pensée pour les équipes de communication. Nous l'utilisons quand il faut savoir vite : un sujet qui démarre, une crise qui se forme, un dirigeant mis en cause.",
              "Visibrain is the French real-time monitoring platform, built for communication teams. We use it when you need to know fast: a topic taking off, a crisis forming, an executive under fire."),
     "what": ("Visibrain est une plateforme de veille du web et des réseaux sociaux fondée à Paris en 2011. Elle surveille en temps réel les réseaux, la presse en ligne et les blogs, et sert surtout à protéger la réputation et à prévenir les crises.",
              "Visibrain is a web and social media monitoring platform founded in Paris in 2011. It monitors networks, online press and blogs in real time, and serves mainly to protect reputation and prevent crises."),
     "facts": [(("Éditeur", "Publisher"), ("Visibrain, indépendant", "Visibrain, independent")),
               (("Origine", "Origin"), ("Paris, 2011", "Paris, 2011")),
               (("Réseaux", "Networks"), ("X, Facebook, Instagram, TikTok, YouTube, LinkedIn, Threads, Telegram, Bluesky", "X, Facebook, Instagram, TikTok, YouTube, LinkedIn, Threads, Telegram, Bluesky")),
               (("Accès", "Access"), ACCESS_PAID)],
     "features": [(("Le temps réel", "Real time"), ("La conversation à l'instant, sans attendre l'export de la semaine.", "The conversation as it happens, without waiting for the weekly export.")),
                  (("Les alertes", "Alerts"), ("Par e-mail, SMS, Slack ou Telegram, selon le protocole convenu.", "By email, text, Slack or Telegram, according to the agreed protocol.")),
                  (("Les médias et leurs relais", "Media and their relays"), ("Qui reprend quoi, et comment un sujet passe des réseaux à la presse.", "Who picks up what, and how a topic crosses from social to press.")),
                  (("La préparation de crise", "Crisis preparation"), ("Des périmètres par marque, dirigeant et marché, prêts avant qu'il ne se passe quelque chose.", "Perimeters per brand, executive and market, ready before anything happens."))],
     "deliver": [(("Veille 24 h/24", "24/7 monitoring"), [("Périmètres par marque, dirigeant et marché", "Perimeters per brand, executive and market"), ("Seuils convenus avec vous", "Thresholds agreed with you"), ("Alerte lue par un analyste avant envoi", "Alert read by an analyst before sending"), ("Escalade définie à l'avance", "Escalation defined in advance")]),
                 (("Accompagnement de crise", "Crisis support"), [("Suivi en direct du sujet", "Live tracking of the topic"), ("Qui relaie, avec quelle portée", "Who relays it, with what reach"), ("Un point quotidien tant que ça dure", "A daily update while it lasts"), ("Un bilan une fois retombé", "A review once it settles")]),
                 (("Veille sectorielle et dirigeants", "Sector and executive watch"), [("Réglementation, concurrents, activisme", "Regulation, competitors, activism"), ("Part de voix par porte-parole", "Share of voice per spokesperson"), ("Cartographie des médias", "Media mapping"), ("Synthèse hebdomadaire", "Weekly digest")])],
     "uses": ["brand-risk", "leader-advocacy", "reputation"],
     "limits": [(("Seulement le public", "Public data only"), ("Elle ne lit que les publications publiques.", "It only reads public posts.")),
                (("La vitesse avant la profondeur", "Speed before depth"), ("Faite pour réagir vite ; pour une étude de fond sur la durée, nous la croisons avec une plateforme plus analytique.", "Built to react fast; for an in-depth study over time, we cross it with a more analytical platform."))],
     "pair": ["talkwalker", "google-news", "radarly"],
     "faq": [(("Est-ce la même chose que Vigie 360 ?", "Is it the same as Vigie 360?"), ("Vigie 360 est notre offre de veille ; Visibrain est l'une des plateformes derrière. Vous achetez le service et le protocole, pas le logiciel.", "Vigie 360 is our monitoring offer; Visibrain is one of the platforms behind it. You buy the service and the protocol, not the software.")),
             (("Qu'est-ce qui déclenche une alerte ?", "What triggers an alert?"), ("Un seuil convenu avec vous, plus la lecture d'un analyste : le volume d'un mot-clé seul crée de fausses alertes à trois heures du matin.", "A threshold agreed with you, plus an analyst's read: keyword volume alone creates false alarms at three in the morning.")),
             (("Couvre-t-elle la presse ?", "Does it cover the press?"), ("Oui, la presse en ligne et les blogs, en plus des réseaux : le passage de l'un à l'autre est souvent le signal qui compte.", "Yes, online press and blogs as well as networks: the crossing from one to the other is often the signal that matters."))]},

    {"slug": "youscan", "name": "YouScan", "letter": "Y",
     "tag": ("ce que dit l'image", "what the image says"),
     "lead": ("YouScan lit ce qui apparaît dans les images, pas seulement dans les légendes : vos logos, vos produits, et le contexte dans lequel ils sont montrés. Nous l'utilisons pour voir la partie de la conversation que le texte ne dit pas.",
              "YouScan reads what appears in images, not only in captions: your logos, your products, and the context they are shown in. We use it to see the part of the conversation that text does not say."),
     "what": ("YouScan est une plateforme d'écoute des réseaux sociaux fondée à Kyiv en 2009, connue pour son analyse visuelle : elle détecte dans les images les logos, objets, scènes et activités, et complète l'analyse du texte et des audiences.",
              "YouScan is a social media listening platform founded in Kyiv in 2009, known for its visual analysis: it detects logos, objects, scenes and activities in images, alongside text and audience analysis."),
     "facts": [(("Éditeur", "Publisher"), ("YouScan, indépendant", "YouScan, independent")),
               (("Origine", "Origin"), ("Kyiv, Ukraine, 2009", "Kyiv, Ukraine, 2009")),
               (("Point fort", "Strength"), ("L'analyse visuelle (Visual Insights)", "Visual analysis (Visual Insights)")),
               (("Accès", "Access"), ACCESS_PAID)],
     "features": [(("Les logos sans légende", "Logos without captions"), ("Votre marque reconnue dans les visuels, même quand personne ne la nomme.", "Your brand recognised in visuals, even when nobody names it.")),
                  (("Le contexte d'usage", "The context of use"), ("Où, quand et avec qui vos produits apparaissent.", "Where, when and with whom your products appear.")),
                  (("Les tendances", "Trends"), ("Les sujets et les visuels qui montent dans votre catégorie.", "The topics and visuals rising in your category.")),
                  (("L'assistant IA", "The AI assistant"), ("Insights Copilot, pour interroger les données collectées ; nous vérifions toujours ce qu'il répond.", "Insights Copilot, to query the collected data; we always check what it answers."))],
     "deliver": [(("Suivi visuel de marque", "Visual brand tracking"), [("Logos et packagings détectés", "Logos and packaging detected"), ("Le volume invisible au texte", "Volume invisible to text"), ("Vos concurrents dans les mêmes images", "Your competitors in the same images"), ("Détournements et contrefaçons repérés", "Misuse and counterfeits spotted")]),
                 (("Études produit et usage", "Product and usage studies"), [("Les occasions et lieux d'usage", "Occasions and places of use"), ("Ce qui est montré avec le produit", "What is shown with the product"), ("Les irritants visibles à l'image", "Irritants visible in the image"), ("Comparaison de gammes", "Range comparison")]),
                 (("Repérage de créateurs", "Creator scouting"), [("Ceux qui montrent déjà le produit", "Those already showing the product"), ("Leur audience vérifiée", "Their audience checked"), ("Leur style et leur ton", "Their style and tone"), ("Une liste courte avec les risques", "A shortlist with the risks")])],
     "uses": ["product-test", "ambassadors", "campaign-impact"],
     "limits": [(("Les faux positifs", "False positives"), ("La détection d'image n'est jamais parfaite : nous vérifions un échantillon à la main au démarrage.", "Image detection is never perfect: we check a sample by hand at setup.")),
                (("Moins utile hors produit visible", "Less useful without a visible product"), ("Pour un service B2B, l'image dit peu ; d'autres outils répondent mieux, et nous le disons.", "For a B2B service, images say little; other tools answer better, and we say so."))],
     "pair": ["talkwalker", "social-blade", "soprism"],
     "faq": [(("Remplace-t-elle l'écoute du texte ?", "Does it replace text listening?"), ("Non, elle la complète : seule, elle manque le débat ; avec le texte, elle ajoute souvent un volume que personne ne comptait.", "No, it completes it: alone it misses the debate; with text, it often adds volume nobody was counting.")),
             (("Sur quels réseaux est-elle utile ?", "On which networks is it useful?"), ("Les réseaux d'abord visuels : Instagram, TikTok, Pinterest, YouTube.", "Visual-first networks: Instagram, TikTok, Pinterest, YouTube.")),
             (("Détecte-t-elle nos emballages ?", "Does it detect our packaging?"), ("La détection va au-delà du logo ; le périmètre est défini avec vous, sur des exemples, avant la première lecture.", "Detection goes beyond the logo; the perimeter is set with you, on samples, before the first read."))]},

    {"slug": "soprism", "name": "SoPrism", "letter": "S",
     "tag": ("qui ils sont vraiment", "who they really are"),
     "lead": ("SoPrism décrit les audiences à partir de leurs centres d'intérêt et de leurs affinités sur Facebook et Instagram. Nous l'utilisons pour savoir qui sont vraiment vos publics, et ceux de vos concurrents.",
              "SoPrism describes audiences from their interests and affinities on Facebook and Instagram. We use it to know who your audiences really are, and your competitors'."),
     "what": ("SoPrism est un outil d'analyse d'audience fondé en Belgique, racheté en 2022 par Audiense, dont il fait aujourd'hui partie (Audiense Discover). Il construit des profils d'audience à partir des données agrégées et anonymes de Meta : centres d'intérêt, affinités, géographie.",
              "SoPrism is an audience analysis tool founded in Belgium and bought in 2022 by Audiense, which it is now part of (Audiense Discover). It builds audience profiles from Meta's aggregated, anonymous data: interests, affinities, geography."),
     "facts": [(("Éditeur", "Publisher"), ("Audiense, depuis 2022", "Audiense, since 2022")),
               (("Origine", "Origin"), ("Belgique", "Belgium")),
               (("Données", "Data"), ("Facebook et Instagram, agrégées", "Facebook and Instagram, aggregated")),
               (("Accès", "Access"), ACCESS_PAID)],
     "features": [(("Les centres d'intérêt", "Interests"), ("Ce qui passionne une audience, classé par affinité réelle.", "What an audience cares about, ranked by real affinity.")),
                  (("Les audiences concurrentes", "Competitors' audiences"), ("Qui ils touchent que vous ne touchez pas, et l'inverse.", "Who they reach that you do not, and the reverse.")),
                  (("La géographie", "Geography"), ("Du monde à la ville, pour comparer des marchés.", "From the world down to a city, to compare markets.")),
                  (("Les segments et les personas", "Segments and personas"), ("Des groupes décrits par leur comportement, pas par un atelier.", "Groups described by behaviour, not by a workshop."))],
     "deliver": [(("Personas", "Personas"), [("Le profil de votre audience réelle", "The profile of your real audience"), ("Ses médias et ses marques", "Its media and its brands"), ("Les dix critères qui comptent", "The ten criteria that matter"), ("Un persona utilisable", "A persona you can use")]),
                 (("Analyse concurrentielle d'audience", "Competitive audience analysis"), [("Recouvrement avec vos concurrents", "Overlap with competitors"), ("Ce qu'ils touchent, pas vous", "What they reach, you do not"), ("Les angles de conquête", "Acquisition angles"), ("Les marchés comparés", "Markets compared")]),
                 (("Activation", "Activation"), [("Segments traduits en ciblage", "Segments turned into targeting"), ("Créateurs choisis sur l'audience", "Creators chosen on audience"), ("Messages par segment", "Messages per segment"), ("Conséquences pour le plan média", "Media plan implications")])],
     "uses": ["segmentation", "rejuvenate", "ambassadors"],
     "limits": [(("Seulement Meta", "Meta only"), ("Ses données viennent de Facebook et d'Instagram : nous les croisons avec d'autres sources pour les autres réseaux.", "Its data comes from Facebook and Instagram: we cross it with other sources for the other networks.")),
                (("Des centres d'intérêt, pas des conversations", "Interests, not conversations"), ("Il dit qui sont les gens, pas ce qu'ils disent : l'écoute sociale complète la lecture.", "It says who people are, not what they say: social listening completes the read."))],
     "pair": ["talkwalker", "social-blade", "meta-ads"],
     "faq": [(("Est-ce un panel de sondage ?", "Is it a survey panel?"), ("Non : il lit des comportements qui existent déjà, sans questionnaire ni biais de déclaration.", "No: it reads behaviour that already exists, with no questionnaire and no declaration bias.")),
             (("SoPrism appartient-il à Audiense ?", "Does Audiense own SoPrism?"), ("Oui, depuis 2022 ; l'outil fait aujourd'hui partie d'Audiense Discover.", "Yes, since 2022; the tool is now part of Audiense Discover.")),
             (("Les données sont-elles conformes au RGPD ?", "Is the data GDPR compliant?"), ("L'outil travaille sur des données agrégées et anonymes, pas sur des profils individuels.", "The tool works on aggregated, anonymous data, not on individual profiles."))]},

    {"slug": "radarly", "name": "Radarly", "letter": "R",
     "tag": ("lu par des analystes", "read by analysts"),
     "lead": ("Radarly est la plateforme d'écoute sociale créée par le français Linkfluence, aujourd'hui intégrée à Meltwater. Nous la prenons pour suivre une marque dans la durée, avec un même référentiel de sujets pour plusieurs équipes.",
              "Radarly is the social listening platform created by France's Linkfluence, now part of Meltwater. We pick it to follow a brand over time, with one shared set of topics for several teams."),
     "what": ("Radarly est le logiciel d'intelligence sociale de Linkfluence, fondé à Paris en 2006 et racheté par Meltwater en 2021. Il écoute les réseaux sociaux, la presse, les blogs, les forums et les avis, avec analyse du sentiment, détection des pics et segmentation des audiences.",
              "Radarly is the social intelligence software of Linkfluence, founded in Paris in 2006 and bought by Meltwater in 2021. It listens to social networks, press, blogs, forums and reviews, with sentiment analysis, spike detection and audience segmentation."),
     "facts": [(("Éditeur", "Publisher"), ("Meltwater, depuis 2021", "Meltwater, since 2021")),
               (("Origine", "Origin"), ("Linkfluence, Paris, 2006", "Linkfluence, Paris, 2006")),
               (("Langues", "Languages"), ("60 annoncées par l'éditeur", "60, per the vendor")),
               (("Accès", "Access"), ACCESS_PAID)],
     "features": [(("Le classement des conversations", "Sorting conversations"), ("Des sujets et des catégories définis avec vous, appliqués à toute la collecte.", "Topics and categories set with you, applied to the whole collection.")),
                  (("Les pics et anomalies", "Spikes and anomalies"), ("Ce qui sort de l'ordinaire, signalé tôt.", "What breaks the pattern, flagged early.")),
                  (("Les audiences", "Audiences"), ("Segments et personas à partir de ceux qui parlent.", "Segments and personas from the people talking.")),
                  (("Les tableaux de bord", "Dashboards"), ("Un référentiel partagé par plusieurs équipes.", "One frame shared by several teams."))],
     "deliver": [(("Suivi de marque continu", "Continuous brand tracking"), [("Périmètre par marque et marché", "Perimeter per brand and market"), ("Sujets et tonalité suivis", "Topics and tone tracked"), ("Comparaison concurrentielle", "Competitive comparison"), ("Note mensuelle", "Monthly note")]),
                 (("Lecture des communautés", "Community reads"), [("Qui parle de la marque", "Who talks about the brand"), ("Leurs centres d'intérêt", "Their interests"), ("Les recoupements avec vos cibles", "Overlaps with your targets"), ("Comment leur parler", "How to speak to them")]),
                 (("Tableaux de bord d'équipe", "Team dashboards"), [("Une vue par équipe", "One view per team"), ("Indicateurs choisis avec vous", "Indicators chosen with you"), ("Revue trimestrielle", "Quarterly review"), ("Formation à la lecture", "Training to read them")])],
     "uses": ["reputation", "segmentation", "messaging"],
     "limits": [(("Une marque en transition", "A brand in transition"), ("Depuis le rachat, l'outil est proposé dans l'offre de Meltwater ; nous vérifions la configuration disponible avant chaque projet.", "Since the acquisition, the tool is offered within Meltwater's range; we check the available setup before each project.")),
                (("Seulement le public", "Public data only"), ("Comme les autres plateformes, il ne lit que ce qui est public.", "Like the other platforms, it only reads what is public."))],
     "pair": ["talkwalker", "visibrain", "soprism"],
     "faq": [(("Faut-il notre propre licence ?", "Do we need our own licence?"), ("Non. Si vous en avez déjà une, nous pouvons la reprendre et la faire produire.", "No. If you already have one, we can take it over and make it produce.")),
             (("Quelle différence avec Talkwalker ?", "How is it different from Talkwalker?"), ("Les deux font de l'écoute sociale. Nous choisissons selon la question, et les croisons souvent.", "Both do social listening. We choose by the question, and often cross them."))]},


    {"slug": "brandwatch", "name": "Brandwatch", "letter": "B",
     "tag": ("la recherche consommateur en profondeur", "consumer research in depth"),
     "lead": ("Brandwatch est la plateforme des équipes insights : des années de conversation archivées, des audiences fines, et une recherche qu'on peut pousser loin. Nous l'opérons quand la question demande du recul et de la précision.",
              "Brandwatch is the insights teams' platform: years of archived conversation, fine-grained audiences, and research you can push far. We run it when the question needs perspective and precision."),
     "what": ("Brandwatch est une plateforme d'intelligence consommateur fondée à Brighton en 2007 et rachetée par Cision en 2021. Son module Consumer Research archive la conversation de 100 millions de sources en ligne ; la plateforme a absorbé Crimson Hexagon, Qriously et Falcon.io.",
              "Brandwatch is a consumer intelligence platform founded in Brighton in 2007 and bought by Cision in 2021. Its Consumer Research module archives the conversation of 100 million online sources; the platform has absorbed Crimson Hexagon, Qriously and Falcon.io."),
     "facts": [(("Éditeur", "Publisher"), ("Cision, depuis 2021", "Cision, since 2021")),
               (("Origine", "Origin"), ("Brighton, Royaume-Uni, 2007", "Brighton, UK, 2007")),
               (("Sources", "Sources"), ("100 millions de sources en ligne, selon l'éditeur", "100 million online sources, per the vendor")),
               (("Accès", "Access"), ACCESS_PAID)],
     "features": [(("L'historique", "The archive"), ("Des années de conversation, pour comparer une période à une autre et voir d'où vient un sujet.", "Years of conversation, to compare one period with another and see where a topic comes from.")),
                  (("Les requêtes fines", "Fine-grained queries"), ("Un périmètre précis, qui sépare votre marque du bruit, des homonymes et des concurrents.", "A precise perimeter that separates your brand from the noise, the homonyms and the competitors.")),
                  (("Les audiences", "Audiences"), ("Qui parle, de quels pays, avec quels centres d'intérêt et quelles professions.", "Who is talking, from which countries, with which interests and occupations.")),
                  (("Les pics expliqués", "Spikes explained"), ("Les hausses de volume détectées, avec les publications et les sujets qui les portent.", "Volume rises detected, with the posts and topics that drive them."))],
     "deliver": [(("Étude consommateur", "Consumer study"), [("La question posée à des années de conversation", "Your question put to years of conversation"), ("Les besoins et les irritants", "Needs and pain points"), ("Le vocabulaire de vos clients", "Your customers' own words"), ("Une recommandation, pas un export", "A recommendation, not an export")]),
                 (("Lecture de catégorie", "Category read"), [("Toute une catégorie, plusieurs marchés", "A whole category, several markets"), ("Les sujets qui montent, et ceux qui retombent", "Topics rising, and topics fading"), ("Votre place face aux concurrents", "Your place against competitors"), ("Les signaux à suivre ensuite", "The signals to follow next")]),
                 (("Segmentation des audiences", "Audience segmentation"), [("Des segments construits sur ce qui est dit", "Segments built on what is said"), ("Leurs sujets et leurs sources", "Their topics and their sources"), ("Les voix qui comptent pour chacun", "The voices that matter to each"), ("Des personas vérifiables", "Personas that can be checked")])],
     "uses": ["segmentation", "market-opportunities", "touchpoints"],
     "limits": [(("Seulement le public", "Public data only"), ("Comme toutes les plateformes d'écoute, elle ne lit que ce qui est public : ni messages privés, ni comptes fermés.", "Like every listening platform, it only reads what is public: no private messages, no closed accounts.")),
                (("Un outil d'expert", "An expert's tool"), ("Sa puissance tient à des requêtes longues à écrire et à entretenir : c'est ce travail que nous faisons à votre place.", "Its power lies in queries that take time to write and maintain: that is the work we do in your place."))],
     "pair": ["talkwalker", "soprism", "google-trends"],
     "faq": [(("Faut-il notre propre licence Brandwatch ?", "Do we need our own Brandwatch licence?"), ("Pas pour une étude : nous choisissons l'outil selon la question. Si vous avez déjà une licence, nous pouvons aussi l'opérer pour vous : c'est Social Listening as a Service.", "Not for a study: we pick the tool by the question. If you already have a licence, we can also run it for you: that is Social Listening as a Service.")),
             (("Brandwatch appartient-il à Cision ?", "Does Cision own Brandwatch?"), ("Oui, depuis 2021. Cela ne change rien pour vous : nous restons indépendants de l'éditeur.", "Yes, since 2021. It changes nothing for you: we remain independent of the publisher.")),
             (("Brandwatch ou Talkwalker ?", "Brandwatch or Talkwalker?"), ("Cela dépend de la question : la profondeur de l'historique et des audiences d'un côté, l'image et le suivi continu de l'autre. Souvent, nous croisons les deux.", "It depends on the question: depth of archive and audiences on one side, images and continuous tracking on the other. Often, we cross the two."))]},

    {"slug": "sprinklr", "name": "Sprinklr", "letter": "S",
     "tag": ("la voix du client à l'échelle du groupe", "the customer voice at group scale"),
     "lead": ("Sprinklr est la plateforme d'expérience client des grands groupes : écoute, publication, service client et marketing au même endroit. Quand votre groupe l'utilise, nous l'opérons pour en tirer des réponses, pas seulement des tableaux de bord.",
              "Sprinklr is the customer experience platform of large groups: listening, publishing, customer care and marketing in one place. When your group uses it, we run it to get answers out of it, not only dashboards."),
     "what": ("Sprinklr est une plateforme de gestion de l'expérience client fondée à New York en 2009 par Ragy Thomas, cotée au New York Stock Exchange depuis 2021. Son module Sprinklr Insights couvre l'écoute sociale, les avis et l'intelligence consommateur, à côté de Sprinklr Social, Service et Marketing.",
              "Sprinklr is a customer experience management platform founded in New York in 2009 by Ragy Thomas, listed on the New York Stock Exchange since 2021. Its Sprinklr Insights module covers social listening, reviews and consumer intelligence, alongside Sprinklr Social, Service and Marketing."),
     "facts": [(("Éditeur", "Publisher"), ("Sprinklr, coté au NYSE (CXM)", "Sprinklr, listed on the NYSE (CXM)")),
               (("Origine", "Origin"), ("New York, 2009", "New York, 2009")),
               (("Modules", "Modules"), ("Insights, Social, Service, Marketing", "Insights, Social, Service, Marketing")),
               (("Accès", "Access"), ACCESS_PAID)],
     "features": [(("L'écoute à l'échelle du groupe", "Listening at group scale"), ("Plusieurs marques, plusieurs pays et plusieurs équipes sur un même socle.", "Several brands, countries and teams on one foundation.")),
                  (("Les avis et le feedback", "Reviews and feedback"), ("Les avis clients lus avec la conversation sociale, pour une seule voix du client.", "Customer reviews read alongside the social conversation, for one voice of the customer.")),
                  (("Le lien avec le service client", "The link with customer care"), ("Ce qui remonte au service client, croisé avec ce qui se dit en public.", "What reaches customer care, crossed with what is said in public.")),
                  (("Les tableaux de bord partagés", "Shared dashboards"), ("Des vues par équipe, du comité de direction aux marchés.", "Views per team, from the executive committee to the markets."))],
     "deliver": [(("Votre licence, enfin exploitée", "Your licence, finally used"), [("Requêtes et taxonomie revues", "Queries and taxonomy reviewed"), ("Tableaux de bord utiles par équipe", "Useful dashboards per team"), ("Une lecture mensuelle par un analyste", "A monthly read by an analyst"), ("Vos équipes formées à l'essentiel", "Your teams trained on what matters")]),
                 (("Voix du client", "Voice of the customer"), [("Social, avis et service client croisés", "Social, reviews and care crossed"), ("Les irritants par parcours", "Pain points by journey"), ("Les priorités chiffrées", "Priorities with figures"), ("Une restitution aux équipes concernées", "A readout to the teams concerned")]),
                 (("Réputation multi-pays", "Multi-country reputation"), [("Un même périmètre pour tous les marchés", "One perimeter for every market"), ("Lu dans la langue de chaque pays", "Read in each country's language"), ("Alertes convenues avec vous", "Alerts agreed with you"), ("Synthèse pour la direction", "A summary for leadership")])],
     "uses": ["reputation", "touchpoints", "brand-risk"],
     "limits": [(("Seulement le public, côté écoute", "Public data only, for listening"), ("L'écoute ne lit que ce qui est public ; les conversations privées ne viennent que de vos propres canaux de service.", "Listening only reads what is public; private conversations only come from your own care channels.")),
                (("Une plateforme lourde à paramétrer", "A heavy platform to configure"), ("Beaucoup de modules, et une valeur qui dépend de la configuration : c'est souvent là que tout se joue, et là que nous intervenons.", "Many modules, and value that depends on the set-up: that is often where everything is decided, and where we step in."))],
     "pair": ["talkwalker", "visibrain", "brandwatch"],
     "faq": [(("Nous avons déjà Sprinklr : pouvez-vous l'opérer ?", "We already have Sprinklr: can you run it?"), ("Oui. Nous reprenons votre configuration, la remettons à plat et livrons chaque mois une lecture : c'est notre offre Social Listening as a Service.", "Yes. We take over your set-up, straighten it out and deliver a read every month: that is our Social Listening as a Service offer.")),
             (("Faut-il une licence Sprinklr pour travailler avec vous ?", "Do we need a Sprinklr licence to work with you?"), ("Non. Si vous n'en avez pas, nous choisissons avec vous l'outil adapté à la question.", "No. If you do not have one, we choose the right tool for the question with you.")),
             (("Sprinklr remplace-t-il des analystes ?", "Does Sprinklr replace analysts?"), ("Non : la plateforme collecte et classe ; il faut encore quelqu'un pour lire, relier les signaux et dire quoi décider.", "No: the platform collects and sorts; someone still has to read, connect the signals and say what to decide."))]},
    {"slug": "semrush", "name": "Semrush", "letter": "S",
     "tag": ("lu au-delà du SEO", "read beyond SEO"),
     "lead": ("Semrush montre ce que votre marché tape dans les moteurs de recherche, qui y répond, et désormais comment les IA parlent des marques. Nous l'utilisons pour lire la demande, pas pour faire du référencement.",
              "Semrush shows what your market types into search engines, who answers it, and now how AI talks about brands. We use it to read demand, not to do SEO."),
     "what": ("Semrush est une plateforme de visibilité en ligne et de marketing de recherche fondée à Boston en 2008, rachetée par Adobe en 2026. Elle couvre la recherche de mots-clés, l'analyse des concurrents, le référencement, la publicité et, depuis peu, la visibilité des marques dans les réponses des IA.",
              "Semrush is an online visibility and search marketing platform founded in Boston in 2008 and bought by Adobe in 2026. It covers keyword research, competitor analysis, SEO, advertising and, more recently, brand visibility in AI answers."),
     "facts": [(("Éditeur", "Publisher"), ("Adobe, depuis 2026", "Adobe, since 2026")),
               (("Origine", "Origin"), ("Boston, 2008", "Boston, 2008")),
               (("Couverture", "Coverage"), ("142 bases géographiques, selon l'éditeur", "142 geographic databases, per the vendor")),
               (("Accès", "Access"), ("Payant, essai gratuit", "Paid, free trial"))],
     "features": [(("La demande par mot et par pays", "Demand by word and country"), ("La taille d'un sujet, marché par marché.", "A topic's size, market by market.")),
                  (("Les mots exacts du marché", "The market's own words"), ("Les formulations du public, pas celles de la marque.", "The public's phrasing, not the brand's.")),
                  (("La place des concurrents", "Competitors' position"), ("Qui ressort sur vos sujets, et avec quels contenus.", "Who comes up on your topics, and with which content.")),
                  (("La visibilité dans les IA", "Visibility in AI"), ("Comment les marques apparaissent dans ChatGPT, Gemini ou les AI Overviews de Google.", "How brands appear in ChatGPT, Gemini or Google's AI Overviews."))],
     "deliver": [(("Lecture de la demande", "Demand reads"), [("Les questions d'une catégorie, classées", "A category's questions, ranked"), ("Les besoins mal couverts", "Needs nobody covers well"), ("Les écarts entre marchés", "Gaps between markets"), ("Une synthèse pour le marketing", "A summary for marketing")]),
                 (("Benchmark concurrentiel", "Competitive benchmark"), [("Votre visibilité face aux concurrents", "Your visibility against competitors"), ("Les sujets où ils vous devancent", "Topics where they lead"), ("Les contenus qui captent la demande", "Content capturing demand"), ("Les priorités", "The priorities")]),
                 (("Recherche et conversation croisées", "Search and conversation crossed"), [("Ce qui se cherche et ce qui se dit", "What is searched and what is said"), ("Les sujets bruyants sans demande", "Loud topics without demand"), ("Les demandes silencieuses", "Silent demand"), ("Une recommandation commune", "One joint recommendation")])],
     "uses": ["market-opportunities", "product-test", "touchpoints"],
     "limits": [(("Des estimations", "Estimates"), ("Les volumes et le trafic sont modélisés, pas mesurés sur les sites : ils servent à comparer, pas à compter.", "Volumes and traffic are modelled, not measured on sites: they serve to compare, not to count.")),
                (("La recherche, pas l'opinion", "Search, not opinion"), ("Elle dit ce que les gens cherchent, pas ce qu'ils pensent : nous la croisons avec l'écoute sociale.", "It says what people look for, not what they think: we cross it with social listening."))],
     "pair": ["google-trends", "answerthepublic", "geo"],
     "faq": [(("Faites-vous du SEO ?", "Do you do SEO?"), ("Non. Nous lisons la recherche pour comprendre un marché ; l'optimisation de votre site reste le travail de votre agence.", "No. We read search to understand a market; optimising your site remains your agency's job.")),
             (("Semrush appartient-il à Adobe ?", "Does Adobe own Semrush?"), ("Oui, depuis avril 2026.", "Yes, since April 2026."))]},

    {"slug": "google-trends", "name": "Google Trends", "letter": "G",
     "tag": ("mis en contexte", "put in context"),
     "lead": ("Google Trends montre l'intérêt de recherche dans le temps, par pays et par région. Une courbe simple, que nous lisons avec le reste : elle date un sujet, le compare à un autre, et dit s'il monte vraiment.",
              "Google Trends shows search interest over time, by country and region. A simple curve that we read with the rest: it dates a topic, compares it to another, and says whether it is really rising."),
     "what": ("Google Trends est un outil gratuit de Google, lancé en 2006, qui montre la popularité relative des recherches par période, par région et par catégorie, à partir d'un échantillon des recherches Google depuis 2004.",
              "Google Trends is a free Google tool, launched in 2006, that shows the relative popularity of searches by period, region and category, from a sample of Google searches since 2004."),
     "facts": [(("Éditeur", "Publisher"), ("Google", "Google")),
               (("Lancement", "Launch"), ("2006", "2006")),
               (("Historique", "History"), ("Depuis 2004", "Since 2004")),
               (("Accès", "Access"), ACCESS_FREE)],
     "features": [(("L'intérêt dans le temps", "Interest over time"), ("Dater un sujet, et voir s'il revient chaque année.", "Date a topic, and see whether it comes back each year.")),
                  (("La comparaison de termes", "Comparing terms"), ("Votre marque face à un concurrent, une tendance face à une autre.", "Your brand against a competitor, one trend against another.")),
                  (("Les régions", "Regions"), ("Où un sujet prend, avant qu'il ne s'étende.", "Where a topic takes off, before it spreads.")),
                  (("Les requêtes associées", "Related queries"), ("Ce que les gens cherchent autour du sujet, y compris sur YouTube et dans Google Actualités.", "What people look for around the topic, including on YouTube and Google News."))],
     "deliver": [(("Validation de tendance", "Trend validation"), [("La courbe de recherche du sujet", "The topic's search curve"), ("La comparaison avec la conversation", "The comparison with the conversation"), ("Le verdict : monte, plafonne ou retombe", "The verdict: rising, flat or falling"), ("Les marchés où elle prend", "The markets where it takes off")]),
                 (("Comparaison de marques", "Brand comparison"), [("Votre marque face aux concurrents", "Your brand against competitors"), ("Sur plusieurs pays", "Across several countries"), ("Les moments qui ont fait bouger la courbe", "The moments that moved the curve"), ("Une lecture mensuelle", "A monthly read")]),
                 (("Calendrier des sujets", "Topic calendar"), [("Les pics saisonniers", "Seasonal peaks"), ("Le bon moment pour prendre la parole", "The right time to speak"), ("Les sujets récurrents", "Recurring topics"), ("Un calendrier pour vos équipes", "A calendar for your teams")])],
     "uses": ["stakeholders", "market-opportunities", "campaign-impact"],
     "limits": [(("Des indices, pas des volumes", "Indices, not volumes"), ("L'échelle va de 0 à 100 par rapport au pic : elle ne donne pas de nombre de recherches.", "The scale runs from 0 to 100 against the peak: it gives no number of searches.")),
                (("Un échantillon", "A sample"), ("Les résultats viennent d'un échantillon et peuvent varier d'une requête à l'autre ; les petits volumes sont exclus.", "Results come from a sample and can vary between queries; small volumes are excluded."))],
     "pair": ["semrush", "answerthepublic", "talkwalker"],
     "faq": [(("Google Trends est gratuit : pourquoi passer par vous ?", "Google Trends is free: why go through you?"), ("La courbe est publique, la lecture ne l'est pas : seule, elle se lit mal. Nous la croisons avec la conversation et des volumes réels.", "The curve is public, the reading is not: on its own it reads badly. We cross it with the conversation and real volumes.")),
             (("Les chiffres sont-ils des volumes ?", "Are the figures volumes?"), ("Non, ce sont des indices relatifs de 0 à 100. C'est pourquoi nous les complétons avec Semrush.", "No, they are relative indices from 0 to 100. That is why we complete them with Semrush."))]},

    {"slug": "answerthepublic", "name": "AnswerThePublic", "letter": "A",
     "tag": ("les questions du marché", "the market's questions"),
     "lead": ("AnswerThePublic montre les questions que les gens posent autour d'un sujet, telles qu'ils les tapent : pourquoi, comment, lequel, est-ce que. Nous nous en servons pour entendre un marché avant qu'il ne s'adresse à vous.",
              "AnswerThePublic shows the questions people ask around a subject, as they type them: why, how, which, is it. We use it to hear a market before it speaks to you."),
     "what": ("AnswerThePublic est un outil d'écoute de la recherche lancé au Royaume-Uni en 2014 et racheté en 2022 par NP Digital, l'agence de Neil Patel. Il visualise les questions, comparaisons et recherches associées à partir des suggestions des moteurs de recherche.",
              "AnswerThePublic is a search listening tool launched in the UK in 2014 and bought in 2022 by NP Digital, Neil Patel's agency. It visualises questions, comparisons and related searches from search engine suggestions."),
     "facts": [(("Éditeur", "Publisher"), ("NP Digital, depuis 2022", "NP Digital, since 2022")),
               (("Origine", "Origin"), ("Royaume-Uni, 2014", "UK, 2014")),
               (("Données", "Data"), ("Suggestions des moteurs de recherche", "Search engine suggestions")),
               (("Accès", "Access"), ("Gratuit limité, ou payant", "Limited free, or paid"))],
     "features": [(("Les questions par type", "Questions by type"), ("Pourquoi, comment, lequel, quand : chaque famille dit autre chose.", "Why, how, which, when: each family says something else.")),
                  (("Les comparaisons", "Comparisons"), ("Ce que le marché met en balance : « X ou Y », « X contre Y ».", "What the market weighs up: \"X or Y\", \"X versus Y\".")),
                  (("Par langue et par pays", "By language and country"), ("Les questions changent d'un marché à l'autre.", "Questions change from one market to the next.")),
                  (("Les alertes", "Alerts"), ("Les nouvelles questions qui apparaissent sur un sujet suivi.", "New questions appearing on a tracked topic."))],
     "deliver": [(("Cartographie des questions", "Question map"), [("Les questions d'un sujet, regroupées", "A subject's questions, grouped"), ("Les doutes qui freinent l'achat", "Doubts holding back a purchase"), ("Les comparaisons avec vos concurrents", "Comparisons with competitors"), ("Les priorités de réponse", "What to answer first")]),
                 (("Plan de contenus", "Content plan"), [("Les sujets, dans les mots du public", "Topics, in the public's words"), ("Un format par question", "A format per question"), ("Croisé avec la conversation", "Crossed with the conversation"), ("Un calendrier", "A calendar")]),
                 (("Pistes produit", "Product leads"), [("Les besoins qui reviennent", "Needs that come back"), ("Les irritants exprimés", "Irritants expressed"), ("Ce que les offres ne règlent pas", "What offers do not solve"), ("Une synthèse pour l'innovation", "A summary for innovation")])],
     "uses": ["touchpoints", "product-test", "messaging"],
     "limits": [(("Des suggestions, pas des volumes", "Suggestions, not volumes"), ("L'outil part de l'autocomplétion : il montre ce qui se cherche, pas combien.", "The tool starts from autocomplete: it shows what is searched, not how much.")),
                (("Une version gratuite bridée", "A capped free version"), ("Le nombre de recherches gratuites est limité ; nous travaillons avec nos accès.", "Free searches are limited; we work with our own access."))],
     "pair": ["semrush", "google-trends", "chatgpt"],
     "faq": [(("C'est un outil gratuit : pourquoi passer par vous ?", "It is a free tool: why go through you?"), ("La liste des questions est accessible ; la lecture, le tri et le croisement avec le reste du marché ne le sont pas.", "The list of questions is open; the reading, the sorting and the crossing with the rest of the market are not.")),
             (("D'où viennent les questions ?", "Where do the questions come from?"), ("Des suggestions des moteurs de recherche : ce que les gens commencent à taper, et ce que le moteur complète.", "From search engine suggestions: what people start typing, and what the engine completes."))]},

    {"slug": "chatgpt", "name": "ChatGPT", "letter": "C",
     "tag": ("ce que l'IA dit de vous", "what AI says about you"),
     "lead": ("De plus en plus de gens posent leurs questions à une IA plutôt qu'à un moteur de recherche. Nous lisons ce que ChatGPT répond sur votre marque et votre catégorie, et d'où il le tient.",
              "More and more people ask an AI rather than a search engine. We read what ChatGPT answers about your brand and your category, and where it gets it from."),
     "what": ("ChatGPT est l'assistant conversationnel d'OpenAI, lancé en novembre 2022. Depuis fin 2024, il peut chercher sur le web et citer ses sources. Ce n'est pas un outil d'écoute : c'est une source d'opinion à part entière, qu'il faut auditer.",
              "ChatGPT is OpenAI's conversational assistant, launched in November 2022. Since late 2024 it can search the web and cite its sources. It is not a listening tool: it is a source of opinion in its own right, to be audited."),
     "facts": [(("Éditeur", "Publisher"), ("OpenAI", "OpenAI")),
               (("Lancement", "Launch"), ("Novembre 2022", "November 2022")),
               (("Recherche web", "Web search"), ("Oui, avec sources, depuis 2024", "Yes, with sources, since 2024")),
               (("Accès", "Access"), ("Gratuit ou payant", "Free or paid"))],
     "features": [(("Ce que l'IA recommande", "What AI recommends"), ("Les marques citées sur les questions de votre catégorie, et dans quel ordre.", "The brands cited on your category's questions, and in which order.")),
                  (("Les sources citées", "The sources cited"), ("Les sites et articles sur lesquels s'appuie la réponse.", "The sites and articles the answer relies on.")),
                  (("Les erreurs", "Errors"), ("Les informations fausses ou datées sur votre marque.", "False or outdated information about your brand.")),
                  (("L'évolution", "Change over time"), ("Les mêmes questions posées dans le temps, pour suivre les réponses.", "The same questions asked over time, to follow the answers."))],
     "deliver": [(("Audit des réponses de l'IA", "AI answer audit"), [("Les questions clés de votre catégorie", "Your category's key questions"), ("Ce que répond l'IA", "What the AI answers"), ("Votre place face aux concurrents", "Your place against competitors"), ("Les erreurs à corriger", "Errors to correct")]),
                 (("Suivi régulier", "Regular tracking"), [("Les mêmes questions chaque mois", "The same questions every month"), ("L'évolution des réponses", "How answers change"), ("Les nouvelles marques citées", "Newly cited brands"), ("Une note pour la communication", "A note for communication")]),
                 (("Plan d'action", "Action plan"), [("Les contenus qui manquent", "Missing content"), ("Les sources à renforcer", "Sources to strengthen"), ("Les messages à clarifier", "Messages to clarify"), ("Le lien avec le GEO", "The link with GEO")])],
     "uses": ["reputation", "brand-risk", "messaging"],
     "limits": [(("Des réponses variables", "Answers that vary"), ("La même question ne donne pas toujours la même réponse : nous posons chaque question plusieurs fois et comparons.", "The same question does not always get the same answer: we ask each question several times and compare.")),
                (("Ce n'est pas de l'écoute", "It is not listening"), ("ChatGPT n'a pas accès à toute la conversation des réseaux : il complète l'écoute sociale, il ne la remplace pas.", "ChatGPT has no access to the whole social conversation: it completes social listening, it does not replace it."))],
     "pair": ["geo", "claude", "gemini"],
     "faq": [(("Pourquoi suivre ce que répond une IA ?", "Why track what an AI answers?"), ("Parce qu'une partie de vos clients s'y informe avant d'acheter, et que la réponse ne vient pas de vous.", "Because part of your customers get their information there before buying, and the answer does not come from you.")),
             (("Pouvez-vous changer ce que l'IA répond ?", "Can you change what the AI answers?"), ("Pas directement : nous identifions les contenus et les sources qui nourrissent la réponse, c'est là qu'on agit (voir GEO).", "Not directly: we identify the content and sources that feed the answer, which is where you act (see GEO).")),
             (("Transmettez-vous nos données à l'IA ?", "Do you send our data to the AI?"), ("Non. Nous posons des questions publiques ; aucune donnée client n'est transmise.", "No. We ask public questions; no client data is sent."))]},

    {"slug": "geo", "name": "GEO", "letter": "G",
     "tag": ("votre place dans les réponses des IA", "your place in AI answers"),
     "lead": ("Le GEO (generative engine optimisation) mesure et améliore la visibilité d'une marque dans les réponses des moteurs d'IA. Nous partons de ce que les IA répondent, puis des sources qui les nourrissent.",
              "GEO (generative engine optimisation) measures and improves a brand's visibility in the answers of AI engines. We start from what the AIs answer, then from the sources that feed them."),
     "what": ("Le GEO est une pratique, pas un logiciel. Le terme vient d'un article de recherche publié fin 2023 par des chercheurs de Princeton, Georgia Tech, de l'Allen Institute for AI et de l'IIT Delhi : il mesure la place d'une source dans les réponses rédigées par une IA, là où le SEO mesure une position dans une liste de liens.",
              "GEO is a practice, not software. The term comes from a research paper published in late 2023 by researchers from Princeton, Georgia Tech, the Allen Institute for AI and IIT Delhi: it measures a source's place in answers written by an AI, where SEO measures a position in a list of links."),
     "facts": [(("Nature", "Type"), ("Une pratique, pas un outil", "A practice, not a tool")),
               (("Origine", "Origin"), ("Article de recherche, 2023", "Research paper, 2023")),
               (("Moteurs", "Engines"), ("ChatGPT, Gemini, Perplexity, AI Overviews", "ChatGPT, Gemini, Perplexity, AI Overviews")),
               (("Mesure", "Measure"), ("Être cité dans la réponse", "Being cited in the answer"))],
     "features": [(("Votre part de réponse", "Your share of answer"), ("Sur les questions de votre catégorie, combien de fois vous êtes cité.", "On your category's questions, how often you are cited.")),
                  (("Les sources qui comptent", "The sources that count"), ("Les sites, articles et forums que les IA reprennent.", "The sites, articles and forums the AIs draw on.")),
                  (("La comparaison des moteurs", "Engines compared"), ("ChatGPT, Gemini, Perplexity et les AI Overviews de Google ne citent pas les mêmes marques.", "ChatGPT, Gemini, Perplexity and Google's AI Overviews do not cite the same brands.")),
                  (("Les leviers", "The levers"), ("Les contenus à produire ou corriger, et où.", "The content to produce or correct, and where."))],
     "deliver": [(("Diagnostic GEO", "GEO diagnostic"), [("Votre part de réponse face aux concurrents", "Your share of answer against competitors"), ("Les questions où vous êtes absent", "Questions where you are absent"), ("Les sources qui vous citent ou non", "Sources that cite you or not"), ("Les priorités", "The priorities")]),
                 (("Suivi mensuel", "Monthly tracking"), [("Le même panel de questions", "The same question panel"), ("L'évolution de votre visibilité", "How your visibility changes"), ("Les nouveaux concurrents cités", "Newly cited competitors"), ("Une note de synthèse", "A summary note")]),
                 (("Recommandations de contenus", "Content recommendations"), [("Les sujets à couvrir", "Topics to cover"), ("Les sources à travailler", "Sources to work on"), ("Les informations à corriger", "Information to correct"), ("Le lien avec vos agences", "The link with your agencies")])],
     "uses": ["reputation", "messaging", "market-opportunities"],
     "limits": [(("Des réponses qui bougent", "Answers that move"), ("Les moteurs changent souvent : c'est pourquoi nous suivons le même panel de questions dans le temps.", "Engines change often: that is why we follow the same question panel over time.")),
                (("Pas de garantie", "No guarantee"), ("Personne ne contrôle la réponse d'une IA ; on agit sur les sources, et on mesure l'effet.", "Nobody controls an AI's answer; you act on the sources, and measure the effect."))],
     "pair": ["chatgpt", "perplexity", "gemini"],
     "faq": [(("Quelle différence entre GEO et SEO ?", "How is GEO different from SEO?"), ("Le SEO vise une place dans une liste de liens ; le GEO vise une mention dans une réponse rédigée par une IA, souvent sans clic. Les leviers se recoupent en partie.", "SEO aims for a place in a list of links; GEO aims for a mention in an answer written by an AI, often with no click. The levers overlap in part.")),
             (("Produisez-vous les contenus ?", "Do you produce the content?"), ("Non : nous mesurons, expliquons et recommandons ; la production reste à vos équipes ou à vos agences.", "No: we measure, explain and recommend; production stays with your teams or agencies.")),
             (("Combien coûte un audit GEO ?", "How much does a GEO audit cost?"), ("Sur devis : le prix dépend du nombre de marques, de questions, d'assistants IA et de marchés suivis, et du rythme des mesures. Après un premier échange de trente minutes, nous envoyons une proposition chiffrée.", "On quotation: the price depends on the number of brands, questions, AI assistants and markets followed, and on how often we measure. After a first thirty-minute call, we send a costed proposal.")),
             (("Comment mesurez-vous la visibilité IA d'une marque ?", "How do you measure a brand's AI visibility?"), ("Nous posons les questions de vos clients à chaque assistant, plusieurs fois, et relevons la présence de la marque, son rang, le ton, l'exactitude des faits et les sources citées. La même mesure, répétée chaque mois ou chaque trimestre, montre ce qui change.", "We put your customers' questions to each assistant, several times, and record the brand's presence, rank, tone, the accuracy of the facts and the sources cited. The same measure, repeated every month or quarter, shows what changes.")),
             (("Combien de temps avant de voir un effet ?", "How long before you see an effect?"), ("Pour les assistants qui cherchent en ligne, une source corrigée peut compter dès qu'elle est réindexée, en quelques semaines. Pour ce qui vient des données d'entraînement, il faut attendre les versions suivantes des modèles : c'est plus long, et ce n'est pas garanti.", "For assistants that search online, a corrected source can count as soon as it is re-indexed, within weeks. For what comes from training data, you have to wait for the next model versions: it takes longer, and it is not guaranteed."))]},

    {"slug": "meta-ads", "name": "Meta Ads", "letter": "M",
     "tag": ("les campagnes à découvert", "campaigns in the open"),
     "lead": ("La bibliothèque publicitaire de Meta montre les publicités en cours sur Facebook, Instagram et les autres applications de Meta. Nous la lisons pour voir ce que vos concurrents poussent, depuis quand, et avec quels messages.",
              "Meta's Ad Library shows the ads running on Facebook, Instagram and Meta's other apps. We read it to see what your competitors push, since when, and with which messages."),
     "what": ("La bibliothèque publicitaire de Meta (Ad Library) est une base publique, créée en 2018 pour la transparence, qui recense les publicités diffusées sur les applications de Meta : créations, date de début, statut. Pour les publicités diffusées dans l'Union européenne, elle conserve des informations supplémentaires.",
              "Meta's Ad Library is a public database, created in 2018 for transparency, that lists the ads running on Meta's apps: creatives, start date, status. For ads delivered in the European Union, it keeps additional information."),
     "facts": [(("Éditeur", "Publisher"), ("Meta", "Meta")),
               (("Création", "Created"), ("2018, ouverte à toutes les publicités en 2019", "2018, open to all ads in 2019")),
               (("Applications", "Apps"), ("Facebook, Instagram, Messenger…", "Facebook, Instagram, Messenger…")),
               (("Accès", "Access"), ACCESS_FREE)],
     "features": [(("Les publicités actives", "Active ads"), ("Toutes les publicités en cours d'un annonceur, avec leurs visuels.", "All an advertiser's running ads, with their visuals.")),
                  (("La durée des campagnes", "Campaign duration"), ("Depuis quand une publicité tourne, signe de ce qui marche.", "How long an ad has been running, a sign of what works.")),
                  (("Les messages et les formats", "Messages and formats"), ("Les angles, les visuels et les appels à l'action.", "Angles, visuals and calls to action.")),
                  (("Les versions par pays", "Versions by country"), ("Comment une campagne change d'un marché à l'autre.", "How a campaign changes from one market to another."))],
     "deliver": [(("Veille publicitaire concurrentielle", "Competitive ad monitoring"), [("Les campagnes actives de vos concurrents", "Competitors' active campaigns"), ("Leurs messages, classés", "Their messages, sorted"), ("Les nouveautés du mois", "What is new this month"), ("Une note pour le marketing", "A note for marketing")]),
                 (("Lecture de campagne", "Campaign reads"), [("La part payante d'un pic de conversation", "The paid share of a spike"), ("Ce que l'organique a ajouté", "What organic added"), ("Les messages repris par le public", "Messages the public picked up"), ("Le bilan avant / après", "The before / after review")]),
                 (("Benchmark créatif", "Creative benchmark"), [("Les angles de votre catégorie", "Your category's angles"), ("Les formats qui durent", "Formats that last"), ("Les territoires libres", "Open territories"), ("Des pistes pour vos agences", "Leads for your agencies")])],
     "uses": ["campaign-impact", "messaging", "market-opportunities"],
     "limits": [(("Pas de budgets", "No budgets"), ("Pour les publicités commerciales, la bibliothèque ne montre ni dépenses ni portée : nous en déduisons le rythme et la durée, pas les montants.", "For commercial ads, the library shows neither spend nor reach: we infer pace and duration, not amounts.")),
                (("Une mémoire limitée hors UE", "Limited memory outside the EU"), ("Les publicités commerciales inactives ne sont pas conservées hors de l'Union européenne.", "Inactive commercial ads are not kept outside the European Union."))],
     "pair": ["soprism", "talkwalker", "social-blade"],
     "faq": [(("La bibliothèque est publique : pourquoi passer par vous ?", "The library is public: why go through you?"), ("Elle montre les publicités une par une. Nous les classons, les relions à la conversation, et vous disons ce qu'elles révèlent de la stratégie de vos concurrents.", "It shows ads one by one. We sort them, link them to the conversation, and tell you what they reveal about your competitors' strategy.")),
             (("Voit-on les budgets ?", "Can you see budgets?"), ("Seulement pour les publicités politiques ou d'enjeu social, que Meta n'accepte plus dans l'Union européenne depuis octobre 2025. Pour les autres, non.", "Only for political or social-issue ads, which Meta no longer accepts in the European Union since October 2025. For the others, no."))]},

    {"slug": "google-news", "name": "Google News", "fr_name": "Google Actualités", "letter": "G",
     "tag": ("la presse face au social", "the press against social"),
     "lead": ("Google Actualités rassemble la couverture presse au fil de l'eau. Nous la mettons en face de la conversation sociale : un sujet né dans les médias ne se lit pas comme un sujet né sur TikTok.",
              "Google News gathers press coverage as it lands. We set it against the social conversation: a topic born in the media does not read like a topic born on TikTok."),
     "what": ("Google Actualités (Google News) est l'agrégateur d'actualités de Google, lancé en 2002. Il regroupe automatiquement les articles de dizaines de milliers d'éditeurs dans de nombreuses langues, et propose une couverture complète de chaque sujet.",
              "Google News is Google's news aggregator, launched in 2002. It automatically groups articles from tens of thousands of publishers in many languages, and offers full coverage of each story."),
     "facts": [(("Éditeur", "Publisher"), ("Google", "Google")),
               (("Lancement", "Launch"), ("2002", "2002")),
               (("Couverture", "Coverage"), ("Plus de 50 000 éditeurs, 38 langues", "50,000+ publishers, 38 languages")),
               (("Accès", "Access"), ACCESS_FREE)],
     "features": [(("La couverture d'un sujet", "A story's coverage"), ("Tous les articles sur un même sujet, regroupés.", "Every article on the same story, grouped.")),
                  (("Au fil de l'eau", "As it lands"), ("Les articles dès leur publication.", "Articles as soon as they are published.")),
                  (("L'origine d'un sujet", "Where a topic starts"), ("Presse d'abord ou réseaux d'abord : la chronologie le dit.", "Press first or social first: the timeline tells.")),
                  (("Les titres qui comptent", "The outlets that matter"), ("Quels médias ont couvert le sujet, et lesquels ont été repris.", "Which media covered it, and which were picked up."))],
     "deliver": [(("Veille presse et social", "Press and social monitoring"), [("La couverture de votre marque", "Your brand's coverage"), ("Les reprises sur les réseaux", "Pick-ups on social"), ("Les alertes quand un article circule", "Alerts when an article spreads"), ("Une revue mensuelle", "A monthly review")]),
                 (("Lecture de crise", "Crisis reads"), [("La chronologie presse et réseaux", "The press and social timeline"), ("Les médias qui ont amplifié", "Media that amplified"), ("Les angles repris", "Angles picked up"), ("Les recommandations de réponse", "Response recommendations")]),
                 (("Bilan de prise de parole", "Announcement review"), [("Les retombées d'une annonce", "An announcement's coverage"), ("Son écho sur les réseaux", "Its echo on social"), ("Les messages restés", "The messages that stuck"), ("Le bilan pour la direction", "The review for leadership")])],
     "uses": ["brand-risk", "leader-advocacy", "reputation"],
     "limits": [(("Une sélection algorithmique", "An algorithmic selection"), ("Google choisit les éditeurs et l'ordre des articles selon ses propres critères ; ce n'est pas une revue de presse exhaustive.", "Google picks publishers and article order by its own criteria; it is not an exhaustive press review.")),
                (("Le texte intégral", "Full text"), ("L'accès aux articles payants dépend des titres et de vos abonnements.", "Access to paywalled articles depends on the outlets and your subscriptions."))],
     "pair": ["visibrain", "talkwalker", "geo"],
     "faq": [(("Remplacez-vous une revue de presse ?", "Do you replace a press review?"), ("Pas forcément : nous ajoutons ce qu'elle ne fait pas, le lien avec la conversation sociale et ce qu'il faut en faire.", "Not necessarily: we add what it does not, the link with the social conversation and what to do about it.")),
             (("Pourquoi la presse compte-t-elle pour l'IA ?", "Why does the press matter for AI?"), ("Les IA s'appuient souvent sur la presse pour répondre : votre couverture médiatique pèse sur votre visibilité dans leurs réponses.", "AIs often rely on the press to answer: your media coverage weighs on your visibility in their answers."))]},

    {"slug": "social-blade", "name": "Social Blade", "letter": "S",
     "tag": ("la croissance des comptes", "how accounts grow"),
     "lead": ("Social Blade suit l'évolution des abonnés et des vues des comptes et des créateurs, dans le temps. Nous l'utilisons pour vérifier une audience avant de travailler avec elle.",
              "Social Blade tracks how accounts and creators gain followers and views over time. We use it to check an audience before working with it."),
     "what": ("Social Blade est un site américain, créé en 2008, qui suit les statistiques publiques des comptes de créateurs, sur YouTube surtout, mais aussi Twitch, Instagram, TikTok et Facebook : historique des abonnés et des vues, classements, estimations.",
              "Social Blade is a US site, created in 2008, that tracks creator accounts' public statistics, on YouTube mostly, but also Twitch, Instagram, TikTok and Facebook: follower and view history, rankings, estimates."),
     "facts": [(("Éditeur", "Publisher"), ("Social Blade LLC", "Social Blade LLC")),
               (("Origine", "Origin"), ("États-Unis, 2008", "USA, 2008")),
               (("Réseaux", "Networks"), ("YouTube, Twitch, Instagram, TikTok, Facebook", "YouTube, Twitch, Instagram, TikTok, Facebook")),
               (("Accès", "Access"), ("Gratuit, options payantes", "Free, paid options"))],
     "features": [(("L'historique des comptes", "Account history"), ("Abonnés et vues, jour après jour.", "Followers and views, day after day.")),
                  (("Les pics suspects", "Suspicious spikes"), ("Les hausses brutales qui méritent une question.", "Sudden jumps that deserve a question.")),
                  (("Les classements", "Rankings"), ("Où se situe un créateur dans sa catégorie.", "Where a creator stands in their category.")),
                  (("Les comparaisons", "Comparisons"), ("Plusieurs comptes sur la même échelle.", "Several accounts on one scale."))],
     "deliver": [(("Vérification de créateurs", "Creator checks"), [("La courbe de chaque créateur pressenti", "Each shortlisted creator's curve"), ("Les pics à expliquer", "Spikes to explain"), ("Croisée avec l'audience réelle", "Crossed with the real audience"), ("Un avis avant contrat", "An opinion before signing")]),
                 (("Benchmark de comptes", "Account benchmark"), [("Vos comptes face aux concurrents", "Your accounts against competitors"), ("Par plateforme", "Per platform"), ("Les périodes de croissance", "Growth periods"), ("Ce qui les explique", "What explains them")]),
                 (("Suivi d'un programme d'influence", "Influence programme tracking"), [("La progression des créateurs partenaires", "Partner creators' progress"), ("L'effet de vos campagnes", "Your campaigns' effect"), ("Les créateurs à renouveler", "Creators to renew"), ("Le bilan", "The review")])],
     "uses": ["ambassadors", "leader-advocacy", "rejuvenate"],
     "limits": [(("Des estimations de revenus grossières", "Rough revenue estimates"), ("Les revenus affichés sont des fourchettes calculées, pas des chiffres réels : nous ne les utilisons pas.", "The revenues shown are calculated ranges, not real figures: we do not use them.")),
                (("Plus de X", "No more X"), ("Les statistiques de X ont été retirées en 2025, après la hausse des prix de son accès aux données.", "X statistics were removed in 2025, after X raised its data access prices."))],
     "pair": ["soprism", "youscan", "meta-ads"],
     "faq": [(("Social Blade suffit-il pour choisir un créateur ?", "Is Social Blade enough to pick a creator?"), ("Non : il dit comment un compte grandit, pas qui le suit. Nous le croisons avec l'analyse de l'audience réelle.", "No: it says how an account grows, not who follows it. We cross it with an analysis of the real audience.")),
             (("Les chiffres sont-ils exacts ?", "Are the figures exact?"), ("Ce sont des données publiques relevées par l'outil : elles servent à repérer des tendances et des anomalies, pas à facturer.", "They are public data collected by the tool: they serve to spot trends and anomalies, not to invoice."))]},
]


# ------------------------------------------------------------------ AI assistants
# with ChatGPT above: what each one answers about a brand is audited the same
# way (GEO). Facts kept to the publisher, the launch, web search and access;
# no model version is named.
def _assistant(slug, name, letter, tag, lead, what, facts, features, limit2, pair, faq):
    return {
        "slug": slug, "name": name, "letter": letter, "tag": tag, "lead": lead, "what": what, "facts": facts, "features": features,
        "deliver": [(("Audit des réponses", "Answer audit"), [("Les questions clés de votre catégorie", "Your category's key questions"), ("Ce que répond l'assistant", "What the assistant answers"), ("Votre place face aux concurrents", "Your place against competitors"), ("Les erreurs à corriger", "Errors to correct")]),
                    (("Suivi régulier", "Regular tracking"), [("Les mêmes questions chaque mois", "The same questions every month"), ("L'évolution des réponses", "How answers change"), ("Les sources citées", "The sources cited"), ("Une note pour la communication", "A note for communication")]),
                    (("Comparaison des assistants", "Assistants compared"), [("ChatGPT, Claude, Gemini, Perplexity, Grok", "ChatGPT, Claude, Gemini, Perplexity, Grok"), ("Qui vous cite, et qui ne vous cite pas", "Who cites you, and who does not"), ("Les écarts de discours", "Differences in what they say"), ("Les priorités GEO", "GEO priorities")])],
        "uses": ["reputation", "brand-risk", "messaging"],
        "limits": [(("Des réponses variables", "Answers that vary"), ("La même question ne donne pas toujours la même réponse : nous posons chaque question plusieurs fois et comparons.", "The same question does not always get the same answer: we ask each question several times and compare.")), limit2],
        "pair": pair, "faq": faq,
    }


TOOLS += [
    _assistant("claude", "Claude", "C", ("ce que Claude dit de vous", "what Claude says about you"),
        ("Claude, l'assistant d'Anthropic, est de plus en plus utilisé en entreprise pour se renseigner, comparer et rédiger. Nous lisons ce qu'il répond sur votre marque et votre catégorie.",
         "Claude, Anthropic's assistant, is increasingly used at work to look things up, compare and write. We read what it answers about your brand and your category."),
        ("Claude est l'assistant conversationnel d'Anthropic, une entreprise d'IA basée à San Francisco, lancé en mars 2023. Il peut chercher sur le web et citer ses sources. Comme ChatGPT, c'est une source d'opinion à part entière, à auditer.",
         "Claude is the conversational assistant of Anthropic, an AI company based in San Francisco, launched in March 2023. It can search the web and cite its sources. Like ChatGPT, it is a source of opinion in its own right, to be audited."),
        [(("Éditeur", "Publisher"), ("Anthropic", "Anthropic")), (("Lancement", "Launch"), ("Mars 2023", "March 2023")),
         (("Recherche web", "Web search"), ("Oui, avec sources", "Yes, with sources")), (("Accès", "Access"), ("Gratuit ou payant", "Free or paid"))],
        [(("Ce que Claude recommande", "What Claude recommends"), ("Les marques citées sur les questions de votre catégorie, et dans quel ordre.", "The brands cited on your category's questions, and in which order.")),
         (("Les sources citées", "The sources cited"), ("Les sites et articles sur lesquels il s'appuie quand il cherche sur le web.", "The sites and articles it relies on when it searches the web.")),
         (("Les erreurs", "Errors"), ("Les informations fausses ou datées sur votre marque.", "False or outdated information about your brand.")),
         (("Un public professionnel", "A professional audience"), ("Un assistant très présent en entreprise : ce qu'il dit pèse sur les décideurs.", "An assistant widely used at work: what it says weighs on decision-makers."))],
        (("Ce n'est pas de l'écoute", "It is not listening"), ("Claude ne lit pas la conversation des réseaux sociaux : il complète l'écoute sociale, il ne la remplace pas.", "Claude does not read the social conversation: it completes social listening, it does not replace it.")),
        ["chatgpt", "gemini", "geo"],
        [(("Pourquoi auditer Claude en plus de ChatGPT ?", "Why audit Claude as well as ChatGPT?"), ("Parce que les assistants ne citent pas les mêmes marques ni les mêmes sources : votre place peut être bonne dans l'un et absente dans l'autre.", "Because assistants do not cite the same brands or sources: your place can be good in one and absent in another.")),
         (("Transmettez-vous nos données à l'IA ?", "Do you send our data to the AI?"), ("Non. Nous posons des questions publiques ; aucune donnée client n'est transmise.", "No. We ask public questions; no client data is sent."))]),

    _assistant("gemini", "Gemini", "G", ("l'IA de Google", "Google's AI"),
        ("Gemini est l'assistant de Google, présent dans son application, dans Android et dans les outils Google. Nous lisons ce qu'il répond sur votre marque, et d'où il le tient.",
         "Gemini is Google's assistant, available in its own app, in Android and in Google's tools. We read what it answers about your brand, and where it gets it from."),
        ("Gemini est l'assistant conversationnel de Google. Lancé en mars 2023 sous le nom de Bard, il a été renommé Gemini en février 2024. Il s'appuie sur la recherche Google et cite ses sources ; sa diffusion dans l'écosystème Google lui donne une audience considérable.",
         "Gemini is Google's conversational assistant. Launched in March 2023 as Bard, it was renamed Gemini in February 2024. It draws on Google Search and cites its sources; its reach across Google's ecosystem gives it a very large audience."),
        [(("Éditeur", "Publisher"), ("Google", "Google")), (("Lancement", "Launch"), ("2023, sous le nom de Bard", "2023, as Bard")),
         (("Recherche web", "Web search"), ("Oui, via la recherche Google", "Yes, through Google Search")), (("Accès", "Access"), ("Gratuit ou payant", "Free or paid"))],
        [(("Ce que Gemini recommande", "What Gemini recommends"), ("Les marques citées sur vos questions, et dans quel ordre.", "The brands cited on your questions, and in which order.")),
         (("Le lien avec la recherche Google", "The link with Google Search"), ("Les sources reprises, souvent proches de celles qui ressortent sur Google.", "The sources it picks up, often close to those that rank on Google.")),
         (("Les erreurs", "Errors"), ("Les informations fausses ou datées sur votre marque.", "False or outdated information about your brand.")),
         (("Une audience immense", "A huge audience"), ("Android, l'application et les outils Google : une réponse vue par beaucoup.", "Android, the app and Google's tools: an answer seen by many."))],
        (("Ce n'est pas de l'écoute", "It is not listening"), ("Gemini ne lit pas la conversation des réseaux : il complète l'écoute sociale, il ne la remplace pas.", "Gemini does not read the social conversation: it completes social listening, it does not replace it.")),
        ["chatgpt", "google-trends", "geo"],
        [(("Gemini et Bard, c'est la même chose ?", "Are Gemini and Bard the same?"), ("Oui : Google a renommé Bard en Gemini en février 2024.", "Yes: Google renamed Bard to Gemini in February 2024.")),
         (("Le SEO suffit-il pour être cité par Gemini ?", "Is SEO enough to be cited by Gemini?"), ("Il aide, puisque Gemini s'appuie sur la recherche Google, mais il ne suffit pas : voir notre page GEO.", "It helps, since Gemini draws on Google Search, but it is not enough: see our GEO page."))]),

    _assistant("perplexity", "Perplexity", "P", ("le moteur de réponses", "the answer engine"),
        ("Perplexity se présente comme un moteur de réponses : chaque réponse s'appuie sur une recherche web et cite ses sources. Nous lisons ce qu'il dit de votre marque, et quels sites il cite.",
         "Perplexity calls itself an answer engine: each answer is built on a web search and cites its sources. We read what it says about your brand, and which sites it cites."),
        ("Perplexity est un moteur de réponses par IA, édité par Perplexity AI, une entreprise de San Francisco fondée en 2022. Contrairement à un assistant classique, il cherche systématiquement sur le web et affiche ses sources, ce qui le rend très lisible pour un audit.",
         "Perplexity is an AI answer engine, published by Perplexity AI, a San Francisco company founded in 2022. Unlike a classic assistant, it always searches the web and shows its sources, which makes it very readable for an audit."),
        [(("Éditeur", "Publisher"), ("Perplexity AI", "Perplexity AI")), (("Origine", "Origin"), ("San Francisco, 2022", "San Francisco, 2022")),
         (("Recherche web", "Web search"), ("Toujours, avec sources", "Always, with sources")), (("Accès", "Access"), ("Gratuit ou payant", "Free or paid"))],
        [(("Les sources, en clair", "Sources, in plain sight"), ("Chaque réponse liste les sites utilisés : on voit d'où vient l'image de votre marque.", "Each answer lists the sites used: you see where your brand's image comes from.")),
         (("Ce qu'il recommande", "What it recommends"), ("Les marques citées sur les questions de votre catégorie.", "The brands cited on your category's questions.")),
         (("La presse et les forums", "Press and forums"), ("Les articles, avis et discussions qui pèsent dans ses réponses.", "The articles, reviews and discussions that weigh in its answers.")),
         (("L'évolution", "Change over time"), ("Les mêmes questions, suivies dans le temps.", "The same questions, followed over time."))],
        (("Des sources choisies par l'outil", "Sources picked by the tool"), ("Perplexity choisit ses sources selon ses propres critères : un site absent ne veut pas dire un site inutile.", "Perplexity picks its sources by its own criteria: a missing site does not mean a useless one.")),
        ["chatgpt", "google-news", "geo"],
        [(("Pourquoi Perplexity est-il utile pour un audit ?", "Why is Perplexity useful for an audit?"), ("Parce qu'il montre ses sources à chaque réponse : on sait sur quels sites agir.", "Because it shows its sources with every answer: you know which sites to act on.")),
         (("Transmettez-vous nos données à l'IA ?", "Do you send our data to the AI?"), ("Non. Nous posons des questions publiques ; aucune donnée client n'est transmise.", "No. We ask public questions; no client data is sent."))]),

    _assistant("grok", "Grok", "G", ("l'IA de X", "X's AI"),
        ("Grok est l'assistant de xAI, intégré à X. Il puise dans les publications de X en temps réel : ce qu'il dit de votre marque reflète souvent ce qui s'y dit à chaud.",
         "Grok is xAI's assistant, built into X. It draws on X posts in real time: what it says about your brand often reflects what is being said there right now."),
        ("Grok est l'assistant conversationnel de xAI, la société d'IA d'Elon Musk, lancé en novembre 2023. Il est intégré au réseau X et accessible sur son propre site ; sa particularité est son accès aux publications de X en temps réel.",
         "Grok is the conversational assistant of xAI, Elon Musk's AI company, launched in November 2023. It is built into the X network and available on its own site; what sets it apart is its real-time access to X posts."),
        [(("Éditeur", "Publisher"), ("xAI", "xAI")), (("Lancement", "Launch"), ("Novembre 2023", "November 2023")),
         (("Sources", "Sources"), ("Le web et les publications de X", "The web and X posts")), (("Accès", "Access"), ("Gratuit ou payant", "Free or paid"))],
        [(("Ce que Grok dit de vous", "What Grok says about you"), ("Les réponses sur votre marque, souvent nourries par la conversation de X.", "Answers about your brand, often fed by the conversation on X.")),
         (("Le lien avec X", "The link with X"), ("Les publications qu'il reprend, et le ton qu'il en tire.", "The posts it picks up, and the tone it draws from them.")),
         (("Les sujets chauds", "Hot topics"), ("Une crise ou une polémique sur X se retrouve vite dans ses réponses.", "A crisis or a row on X quickly shows up in its answers.")),
         (("Les erreurs", "Errors"), ("Les informations fausses ou datées sur votre marque.", "False or outdated information about your brand."))],
        (("Le reflet de X", "A mirror of X"), ("Ses réponses peuvent reprendre le ton d'une polémique en cours : nous les lisons avec la conversation de X, pas seules.", "Its answers can echo the tone of a running row: we read them with the conversation on X, not on their own.")),
        ["chatgpt", "visibrain", "geo"],
        [(("Pourquoi auditer Grok ?", "Why audit Grok?"), ("Parce qu'il est intégré à X et s'appuie sur ses publications : il amplifie ce qui s'y dit de vous.", "Because it is built into X and draws on its posts: it amplifies what is said about you there.")),
         (("Grok est-il lié à X ?", "Is Grok tied to X?"), ("Oui : il est édité par xAI et intégré au réseau X.", "Yes: it is published by xAI and built into the X network."))]),
]
