# -*- coding: utf-8 -*-
"""Content of the use-case pages, in French and English.

Edit the text here, then rebuild the pages:

    python3 tools/build-usecases.py

MOCK: drafted from the site's own copy. Every figure used here already
appears elsewhere on the site (20+ languages, 15-minute alerts, 5,000+
behavioural criteria, a panel of about three billion consumers); the
examples are illustrative. To be validated by Licter before going live.

Each text is a pair (fr, en). French typography (non-breaking spaces before
: ; ? ! and inside « ») is applied by the build, so write plain spaces.
"""

SITE = "https://www.licter.com"   # to confirm: used for canonical URLs, hreflang and the sitemap

HUB = {
    "slug": ("cas-usage", "use-cases"),
    "seo_title": ("Cas d'usage de la social data : 12 questions business | Licter",
                  "Social data use cases: 12 business questions | Licter"),
    "meta": ("Mesurer une campagne, suivre sa e-réputation, segmenter ses audiences, repérer les tendances : 12 cas d'usage de la social data, lus par des consultants.",
             "Measure a campaign, monitor your reputation, segment your audiences, spot the next trend: 12 social data use cases, read by consultants."),
    "kicker": ("Cas d'usage", "Use cases"),
    "h1": ("Douze questions business, douze réponses dans la data sociale.",
           "Twelve business questions, twelve answers in social data."),
    "intro": ("Quatre familles de questions : ce que vos campagnes ont vraiment changé, ce que le marché dit de vous, qui sont vraiment vos audiences, et ce qu'il faut lancer ensuite. Pour chacune, nous lisons ce que les gens publient, recherchent et demandent à l'IA, et un consultant vous dit ce que cela signifie.",
              "Four families of questions: what your campaigns actually changed, what the market says about you, who your audiences really are, and what to build next. For each one we read what people post, search and ask AI, and a consultant tells you what it means."),
}

FAMILIES = [
  {
    "key": "communication",
    "slug": ("communication", "communication"),
    "name": ("Communication", "Communication"),
    "seo_title": ("Mesurer l'impact de sa communication avec la social data | Licter",
                  "Measure your communication with social data | Licter"),
    "meta": ("Impact des campagnes et des événements, prise de parole des dirigeants, choix des ambassadeurs : ce que la conversation en ligne dit de votre communication.",
             "Campaign and event impact, executive visibility, choosing ambassadors: what the online conversation says about your communication."),
    "h1": ("Rendez mesurables chaque campagne, chaque événement, chaque porte-parole.",
           "Make every campaign, event and spokesperson measurable."),
    "intro": ("Vous savez déjà ce que vous avez publié. La vraie question est ce que cela a déplacé : dans quelles audiences, sur quelles plateformes, et si les voix qui l'ont porté étaient les bonnes. La conversation en ligne répond à ces trois questions, à condition de la lire au-delà des volumes.",
              "You already know what you published. The real question is what it moved: in which audiences, on which platforms, and whether the voices carrying it were the right ones. The online conversation answers all three, provided you read it beyond the volumes."),
    "why": ("Un tableau de bord compte les mentions. Il ne dit pas si elles viennent des bonnes personnes, ni si elles ont changé une opinion. Nous comparons la conversation avant et après, audience par audience, et nous vous disons ce qui a vraiment bougé et pourquoi.",
            "A dashboard counts mentions. It does not tell you whether they come from the right people, or whether they changed a mind. We compare the conversation before and after, audience by audience, and tell you what actually moved and why."),
    "video": ("l-OevQ4q8js", "55:08", ("Des millions de tweets à gérer, en direct.", "Millions of tweets to handle, live."), "Paris 2024", "C. Legall"),
    "faq": [
      (("Peut-on mesurer l'impact d'une campagne qui n'a pas de lien de conversion ?", "Can you measure a campaign that has no conversion link?"),
       ("Oui. Nous mesurons ce que la campagne a déplacé dans la conversation : volume, tonalité, thèmes, et surtout quelles audiences ont changé de position. C'est souvent plus parlant qu'un taux de clic.",
        "Yes. We measure what the campaign moved in the conversation: volume, tone, themes, and above all which audiences changed their position. That often says more than a click-through rate.")),
      (("Faut-il nous prévenir avant le lancement ?", "Do you need to know before the launch?"),
       ("C'est préférable, pour fixer la période de référence, mais pas indispensable : la conversation est publique et archivée, nous pouvons reconstituer l'avant après coup.",
        "It helps to set the baseline, but it is not required: the conversation is public and archived, so we can rebuild the before after the fact.")),
      (("Quelles plateformes couvrez-vous ?", "Which platforms do you cover?"),
       ("Les réseaux sociaux (TikTok, Instagram, X, LinkedIn, YouTube, Facebook), la presse en ligne, les forums et avis, la recherche, et les réponses des IA génératives.",
        "Social networks (TikTok, Instagram, X, LinkedIn, YouTube, Facebook), online press, forums and reviews, search, and the answers of generative AI.")),
    ],
  },
  {
    "key": "brand",
    "slug": ("sante-de-marque", "brand-health"),
    "name": ("Santé de marque", "Brand health"),
    "seo_title": ("Santé de marque et e-réputation : la lire avant la crise | Licter",
                  "Brand health and reputation, read before the crisis | Licter"),
    "meta": ("Suivre l'image et la réputation de votre marque, construire votre discours, repérer les risques tôt : la santé de marque lue en continu dans la conversation.",
             "Track your brand image and reputation, shape your messaging, catch risks early: brand health read continuously in the conversation."),
    "h1": ("Sachez ce que le marché dit de vous, avant que ça ne devienne un problème.",
           "Know what the market says about you, before it becomes a problem."),
    "intro": ("La santé de marque n'est pas une étude trimestrielle. C'est un signal continu, déjà public : ce que vos clients disent de vous, les mots qu'ils reprennent, les sujets qui s'attachent à votre nom. Le travail consiste à le lire à temps, et à séparer le bruit de ce qui compte.",
              "Brand health is not a quarterly survey. It is a continuous signal, already public: what your customers say about you, the words they repeat, the subjects that attach to your name. The work is to read it in time, and to tell the noise from what matters."),
    "why": ("Une alerte sur un mot-clé se déclenche dès que le volume monte, y compris pour rien. Nous lisons qui parle, dans quelle langue et avec quelle portée, et un analyste vous prévient quand un sujet mérite votre attention, pas avant.",
            "A keyword alert fires as soon as volume rises, including for nothing. We read who is talking, in which language and with what reach, and an analyst tells you when a subject deserves your attention, not before."),
    "video": ("z3EkLWjQXMQ", "56:29", ("La social room a changé notre façon de travailler.", "The social room changed the way we work."), "SNCF", "M. Fleurbaey"),
    "faq": [
      (("Quelle différence entre e-réputation et santé de marque ?", "What is the difference between online reputation and brand health?"),
       ("L'e-réputation regarde ce qui se dit de vous. La santé de marque ajoute qui le dit, avec quelle influence, et comment cela évolue face à vos concurrents. C'est ce second niveau qui permet de décider.",
        "Online reputation looks at what is said about you. Brand health adds who says it, with what influence, and how it moves against your competitors. That second level is what lets you decide.")),
      (("En combien de temps êtes-vous alertés ?", "How fast are you alerted?"),
       ("La veille tourne 24 h/24, et les alertes partent en 15 minutes, dans plus de vingt langues, avec un protocole d'escalade défini avec vous.",
        "Monitoring runs 24/7, and alerts go out within 15 minutes, in more than twenty languages, with an escalation protocol agreed with you.")),
      (("Remplacez-vous notre outil de veille ?", "Do you replace our monitoring tool?"),
       ("Pas forcément. Si vous avez déjà une plateforme, nous pouvons la faire produire des décisions. Sinon, la licence est la nôtre.",
        "Not necessarily. If you already have a platform, we can make it produce decisions. If not, the licence is ours.")),
    ],
  },
  {
    "key": "audiences",
    "slug": ("audiences", "audiences"),
    "name": ("Audiences", "Audiences"),
    "seo_title": ("Connaître ses audiences par le comportement observé | Licter",
                  "Know your audiences through observed behaviour | Licter"),
    "meta": ("Segmenter vos cibles, rajeunir votre audience, comprendre les attentes à chaque étape : vos audiences lues dans ce qu'elles font, pas ce qu'elles déclarent.",
             "Segment your targets, reach younger audiences, understand expectations at every touchpoint: your audiences read in what they do, not what they declare."),
    "h1": ("Remplacez l'atelier persona par le comportement observé.",
           "Replace the persona workshop with observed behaviour."),
    "intro": ("Les préférences déclarées et le comportement réel coïncident rarement. Le panel montre ce que les gens font, suivent, achètent et disent quand personne ne leur pose de question : un panel d'environ trois milliards de consommateurs, lu par des analystes.",
              "Declared preferences and actual behaviour rarely match. The panel shows what people do, follow, buy and say when no one is asking them a question: a panel of about three billion consumers, read by analysts."),
    "why": ("Un persona construit en atelier reflète ce que l'équipe croit savoir. Nous partons de ce que vos clients font réellement, et nous faisons apparaître les communautés que le brief n'avait pas vues, souvent là où se trouve l'opportunité.",
            "A persona built in a workshop reflects what the team believes. We start from what your customers actually do, and bring out the communities the brief had not seen, which is often where the opportunity is."),
    "video": ("moW2HYtTor8", "51:29", ("Internet, pour capter la voix du consommateur.", "The internet, to capture the consumer's voice."), "L'Oréal", "C. Besson"),
    "faq": [
      (("D'où viennent les données d'audience ?", "Where does the audience data come from?"),
       ("D'un panel comportemental d'environ trois milliards de consommateurs, croisé avec la conversation publique et la recherche. Les données sont agrégées : nous lisons des communautés, pas des individus.",
        "From a behavioural panel of about three billion consumers, crossed with the public conversation and search. The data is aggregated: we read communities, not individuals.")),
      (("Combien de critères pour décrire une audience ?", "How many criteria describe an audience?"),
       ("Plus de 5 000 critères comportementaux : centres d'intérêt, régime média, affinités de marque, sociodémographie.",
        "More than 5,000 behavioural criteria: interests, media diet, brand affinities, sociodemographics.")),
      (("Est-ce compatible avec le RGPD ?", "Is it GDPR compliant?"),
       ("Oui. Nous travaillons sur des données publiques ou agrégées et anonymisées, sans suivi d'individus.",
        "Yes. We work on public or aggregated, anonymised data, with no tracking of individuals.")),
    ],
  },
  {
    "key": "trends",
    "slug": ("tendances-innovation", "trends-innovation"),
    "name": ("Tendances & innovation", "Trends & innovation"),
    "seo_title": ("Tendances et innovation : tester, repérer, décider | Licter",
                  "Spot trends and test products with social data | Licter"),
    "meta": ("Tester vos produits, repérer les opportunités de marché, cartographier les tendances qui montent : décidez quoi lancer sur des preuves, pas des convictions.",
             "Test your products, spot market opportunities, map the trends on the rise: decide what to build on evidence, not conviction."),
    "h1": ("Décidez quoi construire sur des preuves, pas sur des convictions.",
           "Decide what to build on evidence, not conviction."),
    "intro": ("Toute décision produit est un pari sur ce que les gens voudront. La conversation d'un marché le dit généralement en premier : les besoins mal couverts, les irritants des produits existants, les sujets qui montent avant d'arriver dans les études.",
              "Every product decision is a bet on what people will want. The conversation of a market usually says it first: the needs nobody covers well, the irritants of existing products, the topics rising before they reach the surveys."),
    "why": ("Une tendance repérée dans une étude annuelle est déjà connue de tous. Nous suivons l'évolution des sujets mois après mois, nous distinguons ce qui monte vraiment de ce qui fait du bruit, et nous vous disons quoi lancer, quoi surveiller et quoi arrêter.",
            "A trend spotted in an annual survey is already known to everyone. We follow topics month after month, tell what is really rising from what is just noise, and tell you what to build, what to watch and what to stop."),
    "video": ("UElJ_Pdd0wo", "58:39", ("Toutes les tendances partent désormais de TikTok.", "Every trend now starts on TikTok."), "Orange", "B. Hoang"),
    "faq": [
      (("Combien de temps à l'avance repère-t-on une tendance ?", "How early can a trend be spotted?"),
       ("Souvent plusieurs mois avant qu'elle n'apparaisse dans les études classiques : les communautés de niche en parlent bien avant le grand public.",
        "Often several months before it shows up in conventional surveys: niche communities talk about it long before the wider public.")),
      (("Pouvez-vous analyser les produits de nos concurrents ?", "Can you analyse our competitors' products?"),
       ("Oui. Les avis, les forums et les réseaux parlent autant de leurs produits que des vôtres : nous comparons les forces et les irritants, produit par produit.",
        "Yes. Reviews, forums and networks talk as much about their products as yours: we compare strengths and irritants, product by product.")),
      (("Quelle différence avec une étude de marché ?", "How is this different from market research?"),
       ("Une étude interroge des gens sur ce qu'ils pensent. Nous lisons ce qu'ils disent et font spontanément, en continu, à l'échelle de tout un marché.",
        "A survey asks people what they think. We read what they say and do spontaneously, continuously, across a whole market.")),
    ],
  },
]

# The four steps are the same method everywhere; each case says what they
# mean for it. (name, what happens)
STEPS = [
    ("Cadrage", "Framing"),
    ("Collecte", "Collection"),
    ("Analyse", "Analysis"),
    ("Décision", "Decision"),
]

CASES = [
  # ------------------------------------------------------------ communication
  {
    "key": "campaign-impact", "family": "communication",
    "slug": ("mesurer-impact-campagne", "measure-campaign-impact"),
    "name": ("Mesurer l'impact d'un événement ou d'une campagne", "Analyse the impact of an event or campaign"),
    "seo_title": ("Mesurer l'impact d'une campagne ou d'un événement | Licter",
                  "Measure the impact of a campaign or event | Licter"),
    "meta": ("Ce qu'un lancement, un sponsoring ou une prise de parole a vraiment déplacé : volume, portée, tonalité, et quelles audiences ont changé de position.",
             "What a launch, a sponsorship or a keynote actually shifted: volume, reach, tone, and which audiences changed their position."),
    "h1": ("Mesurer l'impact d'un événement ou d'une campagne, au-delà des vues.",
           "Measure the impact of an event or campaign, beyond the views."),
    "intro": ("Un lancement, un sponsoring, une prise de parole : les chiffres de diffusion disent combien de personnes ont vu. Ils ne disent pas ce qui a changé dans leur tête. Nous lisons la conversation avant et après, audience par audience, pour vous dire ce que la campagne a réellement déplacé.",
              "A launch, a sponsorship, a keynote: reach figures tell you how many people saw it. They do not tell you what changed in their minds. We read the conversation before and after, audience by audience, to tell you what the campaign actually moved."),
    "questions": [
      ("Notre campagne a-t-elle changé la façon dont on parle de nous ?", "Did our campaign change the way people talk about us?"),
      ("Quelles audiences ont réagi, et lesquelles sont restées indifférentes ?", "Which audiences reacted, and which ones stayed indifferent?"),
      ("Qui a porté le message : nos contenus, les créateurs, la presse ?", "Who carried the message: our content, creators, the press?"),
      ("Qu'est-ce qu'on refait, et qu'est-ce qu'on arrête ?", "What do we do again, and what do we stop?"),
    ],
    "sources": [
      (("Réseaux sociaux", "Social networks"), ("TikTok, Instagram, X, LinkedIn, YouTube, Facebook : posts, commentaires, partages.", "TikTok, Instagram, X, LinkedIn, YouTube, Facebook: posts, comments, shares.")),
      (("Presse et blogs", "Press and blogs"), ("Les reprises, les angles, les titres qui ont circulé.", "Pick-ups, angles, the headlines that travelled.")),
      (("Recherche", "Search"), ("Ce que la campagne a déclenché comme recherches, avant et après.", "The searches the campaign triggered, before and after.")),
      (("IA générative", "Generative AI"), ("Ce que les assistants répondent désormais quand on les interroge sur votre marque.", "What assistants now answer when asked about your brand.")),
    ],
    "steps": [
      ("On fixe la période de référence, les objectifs de la campagne et les audiences qui comptent.", "We set the baseline period, the campaign's goals and the audiences that matter."),
      ("On collecte la conversation avant, pendant et après, sur toutes les plateformes concernées.", "We collect the conversation before, during and after, across every relevant platform."),
      ("Un analyste lit les pics, les thèmes et les voix, et compare avec la moyenne de votre catégorie.", "An analyst reads the peaks, themes and voices, and compares with your category's average."),
      ("On vous présente ce qui a marché, ce qui n'a pas pris, et ce qu'on changerait pour la prochaine.", "We walk you through what worked, what did not land, and what we would change next time."),
    ],
    "deliverables": [
      ("Une lecture avant / après de la conversation, ventilée par audience et par plateforme.", "A before / after read of the conversation, broken down by audience and platform."),
      ("Les pics expliqués : qui les a déclenchés, avec quel contenu.", "The peaks explained: who triggered them, with which content."),
      ("La comparaison avec la moyenne de votre catégorie.", "The comparison with your category's average."),
      ("Trois recommandations pour la prochaine campagne.", "Three recommendations for the next campaign."),
    ],
    "example": ("Exemple illustratif : une marque alimentaire lance une sauce avec une campagne TV. La conversation montre que ce sont les recettes de créateurs sur TikTok qui ont porté le lancement, pas la publicité. Recommandation : basculer une partie du budget média vers des partenariats créateurs.",
                "Illustrative example: a food brand launches a sauce with a TV campaign. The conversation shows that creators' recipes on TikTok carried the launch, not the ad. Recommendation: move part of the media budget to creator partnerships."),
    "faq": [
      (("Combien de temps après la campagne peut-on mesurer ?", "How soon after the campaign can you measure?"),
       ("Une première lecture est possible dès la fin de la campagne ; une lecture complète prend quelques jours.", "A first read is possible as soon as the campaign ends; a full read takes a few days.")),
      (("Mesurez-vous aussi les événements physiques ?", "Do you also measure physical events?"),
       ("Oui : salons, sponsorings, conférences. Ce qui compte est ce qu'ils ont fait dire en ligne, et à qui.", "Yes: trade shows, sponsorships, conferences. What counts is what they got people saying online, and who.")),
      (("Peut-on comparer plusieurs campagnes ?", "Can you compare several campaigns?"),
       ("Oui, avec la même méthode et la même référence, pour savoir laquelle a vraiment déplacé la conversation.", "Yes, with the same method and baseline, to know which one really moved the conversation.")),
    ],
  },
  {
    "key": "leader-advocacy", "family": "communication",
    "slug": ("prise-de-parole-dirigeants", "leader-advocacy"),
    "name": ("Optimiser la prise de parole de vos dirigeants", "Optimise your leader advocacy strategy"),
    "seo_title": ("Prise de parole des dirigeants : mesurer leur influence | Licter",
                  "Executive visibility: measure your leaders' influence | Licter"),
    "meta": ("Comment vos dirigeants sont entendus face à leurs pairs, sur quels sujets leur voix retient l'attention, et où elle ajoute du bruit.",
             "How your executives are heard next to their peers, on which subjects their voice earns attention, and where it adds noise."),
    "h1": ("Optimiser la prise de parole de vos dirigeants, sujet par sujet.",
           "Optimise your leaders' voice, subject by subject."),
    "intro": ("Un dirigeant qui prend la parole engage la marque. Encore faut-il savoir sur quels sujets il est attendu, face à quels pairs, et devant quelles audiences. Nous mesurons sa part de voix sujet par sujet, pour concentrer ses prises de parole là où elles comptent.",
              "An executive who speaks commits the brand. You still need to know on which subjects they are expected, against which peers, and in front of which audiences. We measure their share of voice subject by subject, to focus their voice where it counts."),
    "questions": [
      ("Sur quels sujets notre dirigeant est-il légitime aux yeux du public ?", "On which subjects is our leader credible to the public?"),
      ("Comment se situe-t-il face aux dirigeants de nos concurrents ?", "How do they compare with our competitors' leaders?"),
      ("Quels formats et quelles plateformes lui donnent le plus d'écho ?", "Which formats and platforms give them the most resonance?"),
      ("Où sa parole ajoute-t-elle du bruit plutôt que du sens ?", "Where does their voice add noise rather than meaning?"),
    ],
    "sources": [
      (("LinkedIn", "LinkedIn"), ("Les publications, les réactions et qui les relaie.", "Posts, reactions and who relays them.")),
      (("Presse économique", "Business press"), ("Les interviews, les citations et leurs reprises.", "Interviews, quotes and their pick-ups.")),
      (("X et podcasts", "X and podcasts"), ("Les débats où le dirigeant est cité ou attendu.", "The debates where the leader is quoted or expected.")),
      (("Panel de pairs", "Peer set"), ("Les dirigeants comparables dans votre secteur.", "Comparable leaders in your sector.")),
    ],
    "steps": [
      ("On choisit avec vous le panel de pairs et les sujets stratégiques.", "We agree the peer set and the strategic subjects with you."),
      ("On collecte les prises de parole et ce qu'elles ont fait dire, sur douze mois.", "We collect the statements and what they got people saying, over twelve months."),
      ("Un analyste mesure la part de voix et la tonalité, sujet par sujet.", "An analyst measures share of voice and tone, subject by subject."),
      ("On vous propose un calendrier éditorial : quels sujets, quels formats, quels relais.", "We propose an editorial plan: which subjects, which formats, which relays."),
    ],
    "deliverables": [
      ("La part de voix par porte-parole, sujet par sujet, face à un panel de pairs.", "Share of voice per spokesperson, topic by topic, against a peer set."),
      ("La carte des sujets où la parole est attendue, et de ceux à éviter.", "The map of subjects where the voice is expected, and those to avoid."),
      ("Les relais qui amplifient ses messages.", "The relays that amplify their messages."),
      ("Un plan de prise de parole sur six mois.", "A six-month speaking plan."),
    ],
    "example": ("Exemple illustratif : un PDG publie chaque semaine sur l'innovation, sans écho. La lecture montre que son audience l'attend sur l'emploi et l'industrie en région, où ses pairs sont absents. Recommandation : recentrer ses prises de parole sur ces deux sujets.",
                "Illustrative example: a CEO posts every week about innovation, with little echo. The read shows their audience expects them on jobs and regional industry, where their peers are absent. Recommendation: refocus their voice on those two subjects."),
    "faq": [
      (("Travaillez-vous avec les équipes de communication du dirigeant ?", "Do you work with the leader's communication team?"),
       ("Oui : nous leur donnons une lecture et des recommandations, elles gardent la main sur les messages.", "Yes: we give them a read and recommendations, they keep control of the messages.")),
      (("Peut-on suivre plusieurs porte-parole ?", "Can you follow several spokespeople?"),
       ("Oui, jusqu'à tout un comité de direction, avec la même méthode.", "Yes, up to a whole executive committee, with the same method.")),
      (("Est-ce utile en période de crise ?", "Is it useful in a crisis?"),
       ("C'est justement là que savoir sur quoi le dirigeant est attendu évite les faux pas.", "That is exactly when knowing what the leader is expected to address avoids missteps.")),
    ],
  },
  {
    "key": "ambassadors", "family": "communication",
    "slug": ("identifier-ambassadeurs", "find-brand-ambassadors"),
    "name": ("Identifier les bons ambassadeurs", "Identify the right ambassadors"),
    "seo_title": ("Identifier les bons ambassadeurs et créateurs | Licter",
                  "Identify the right brand ambassadors and creators | Licter"),
    "meta": ("Trouvez les créateurs et les voix publiques dont l'audience recoupe vraiment la vôtre, pas ceux qui ont le plus d'abonnés.",
             "Find the creators and public voices whose audience genuinely overlaps yours, not the ones with the largest follower count."),
    "h1": ("Identifier les bons ambassadeurs, pas les plus gros comptes.",
           "Identify the right ambassadors, not the biggest accounts."),
    "intro": ("Le nombre d'abonnés est le critère le plus visible et le moins utile. Ce qui compte est le recouvrement entre l'audience d'un créateur et la vôtre, son affinité avec votre catégorie, et les risques attachés à son nom. Nous classons les voix sur ces trois critères.",
              "Follower count is the most visible criterion and the least useful. What counts is the overlap between a creator's audience and yours, their affinity with your category, and the risks attached to their name. We rank voices on those three criteria."),
    "questions": [
      ("Quels créateurs parlent déjà à nos clients, ou à ceux qu'on veut ?", "Which creators already speak to our customers, or to the ones we want?"),
      ("Leur audience recoupe-t-elle vraiment la nôtre ?", "Does their audience genuinely overlap ours?"),
      ("Y a-t-il des risques attachés à leur nom ?", "Are there risks attached to their name?"),
      ("Micro-influenceurs ou grands comptes : qu'est-ce qui rapporte le plus ?", "Micro-influencers or big accounts: what pays off best?"),
    ],
    "sources": [
      (("Panel d'audience", "Audience panel"), ("Qui suit chaque créateur, et ce qu'ils suivent d'autre.", "Who follows each creator, and what else they follow.")),
      (("Réseaux sociaux", "Social networks"), ("Leurs contenus, leurs partenariats passés, les réactions.", "Their content, past partnerships, reactions.")),
      (("Controverses", "Controversies"), ("L'historique public des polémiques et prises de position.", "The public history of controversies and stances.")),
      (("Votre audience", "Your audience"), ("Les communautés qui parlent déjà de votre marque.", "The communities already talking about your brand.")),
    ],
    "steps": [
      ("On définit l'audience cible et les valeurs à respecter.", "We define the target audience and the values to respect."),
      ("On repère les voix qui parlent à cette audience, au-delà des listes habituelles.", "We find the voices speaking to that audience, beyond the usual lists."),
      ("Un analyste mesure le recouvrement, l'affinité et le risque de chacune.", "An analyst measures each one's overlap, affinity and risk."),
      ("On vous remet une liste courte classée, avec nos recommandations de format.", "We hand you a ranked shortlist, with our format recommendations."),
    ],
    "deliverables": [
      ("Une liste courte classée, avec recouvrement d'audience, affinité et signaux de risque.", "A ranked shortlist with audience overlap, affinity and risk flags."),
      ("Les créateurs émergents avant qu'ils ne deviennent chers.", "Emerging creators before they become expensive."),
      ("Le profil de l'audience de chacun.", "The audience profile of each."),
      ("Des recommandations de format et de plateforme.", "Format and platform recommendations."),
    ],
    "example": ("Exemple illustratif : une maison de luxe vise la Gen Z. Les plus gros comptes mode ont une audience déjà acquise ; trois créateurs de taille moyenne touchent la Gen Z aspirationnelle, avec une affinité forte pour la maison. Recommandation : un programme avec eux plutôt qu'une grande campagne.",
                "Illustrative example: a luxury house targets Gen Z. The biggest fashion accounts reach an audience it already has; three mid-size creators reach aspirational Gen Z with strong affinity for the house. Recommendation: a programme with them rather than one big campaign."),
    "faq": [
      (("Gérez-vous la relation avec les créateurs ?", "Do you manage the relationship with creators?"),
       ("Non : nous choisissons avec vous les bons profils, votre agence ou vos équipes les activent.", "No: we choose the right profiles with you, your agency or teams activate them.")),
      (("Mesurez-vous aussi les campagnes d'influence ?", "Do you also measure influencer campaigns?"),
       ("Oui, avec la même méthode que pour une campagne : ce qu'elle a déplacé, et chez qui.", "Yes, with the same method as any campaign: what it moved, and in whom.")),
      (("Couvrez-vous les créateurs étrangers ?", "Do you cover creators abroad?"),
       ("Oui, dans plus de vingt langues, lus par des analystes qui parlent la langue.", "Yes, in more than twenty languages, read by analysts who speak them.")),
    ],
  },
  # ------------------------------------------------------------ brand health
  {
    "key": "reputation", "family": "brand",
    "slug": ("e-reputation-image-de-marque", "brand-reputation-monitoring"),
    "name": ("Surveiller l'image et la réputation de votre marque", "Monitor your brand image and reputation"),
    "seo_title": ("E-réputation : surveiller l'image de votre marque | Licter",
                  "Brand reputation monitoring, read by analysts | Licter"),
    "meta": ("Suivez l'image, la tonalité et les sujets attachés à votre nom, en continu et sur tous vos marchés, avec une alerte 24 h/24 sur les ruptures.",
             "Track image, sentiment and the subjects attached to your name, continuously and across markets, with 24/7 alerting on the breaks."),
    "h1": ("Surveiller l'image et la réputation de votre marque, en continu.",
           "Monitor your brand image and reputation, continuously."),
    "intro": ("Votre réputation se joue tous les jours, sur des plateformes et dans des langues que vos équipes ne peuvent pas toutes suivre. Nous lisons en continu ce qui se dit de vous, les sujets qui s'attachent à votre nom et la façon dont ils évoluent face à vos concurrents.",
              "Your reputation plays out every day, on platforms and in languages your teams cannot all follow. We continuously read what is said about you, the subjects that attach to your name and how they move against your competitors."),
    "questions": [
      ("Que dit-on de nous, et est-ce que ça change ?", "What is being said about us, and is it changing?"),
      ("Quels sujets s'attachent à notre nom, en bien et en mal ?", "Which subjects attach to our name, good and bad?"),
      ("Comment se situe-t-on face à nos concurrents ?", "How do we compare with our competitors?"),
      ("Qu'est-ce qui mérite une réaction, et qu'est-ce qui n'est que du bruit ?", "What deserves a response, and what is just noise?"),
    ],
    "sources": [
      (("Réseaux sociaux", "Social networks"), ("Tout ce qui mentionne votre marque, vos produits, vos dirigeants.", "Everything that mentions your brand, products, leaders.")),
      (("Avis et forums", "Reviews and forums"), ("Les avis clients et les discussions de fond.", "Customer reviews and in-depth discussions.")),
      (("Presse en ligne", "Online press"), ("Les articles et leurs reprises.", "Articles and their pick-ups.")),
      (("IA générative", "Generative AI"), ("Ce que les assistants disent de vous.", "What assistants say about you.")),
    ],
    "steps": [
      ("On définit le périmètre : marques, produits, marchés, langues, concurrents.", "We set the perimeter: brands, products, markets, languages, competitors."),
      ("La veille tourne en continu, 24 h/24, dans plus de vingt langues.", "Monitoring runs continuously, 24/7, in more than twenty languages."),
      ("Un analyste lit les évolutions et qualifie ce qui compte.", "An analyst reads the changes and qualifies what matters."),
      ("Vous recevez une lecture régulière et une alerte dès qu'un sujet rompt la tendance.", "You receive a regular read and an alert as soon as a subject breaks the trend."),
    ],
    "deliverables": [
      ("Une lecture en direct de votre réputation, avec alerte 24 h/24 sur les ruptures.", "A live read of your reputation, with 24/7 alerting on the breaks."),
      ("Le suivi des sujets attachés à votre nom, mois après mois.", "The subjects attached to your name, month after month."),
      ("La comparaison avec vos concurrents.", "The comparison with your competitors."),
      ("Une note d'analyse mensuelle, pas un tableau de bord de plus.", "A monthly analysis note, not one more dashboard."),
    ],
    "example": ("Exemple illustratif : une maison de maroquinerie voit ses mentions négatives monter. La lecture montre que les hausses de prix sont acceptées, mais que l'accueil en boutique concentre 38 % des critiques. Recommandation : former les équipes boutique avant la prochaine hausse.",
                "Illustrative example: a leather goods house sees negative mentions rise. The read shows price increases are accepted, but the in-store welcome accounts for 38% of the criticism. Recommendation: train boutique teams before the next increase."),
    "faq": [
      (("En quoi est-ce différent d'un outil de veille ?", "How is this different from a monitoring tool?"),
       ("L'outil collecte ; nos analystes lisent, qualifient et vous disent quoi faire. Vous recevez une décision, pas un export.", "The tool collects; our analysts read, qualify and tell you what to do. You get a decision, not an export.")),
      (("Couvrez-vous plusieurs pays ?", "Do you cover several countries?"),
       ("Oui, dans plus de vingt langues, avec des analystes qui parlent la langue du marché.", "Yes, in more than twenty languages, with analysts who speak the market's language.")),
      (("Quel engagement ?", "What commitment?"),
       ("Un forfait mensuel, sans engagement, avec des études illimitées à l'intérieur.", "A fixed monthly fee, no commitment, with unlimited studies inside it.")),
    ],
  },
  {
    "key": "messaging", "family": "brand",
    "slug": ("discours-de-marque", "brand-messaging"),
    "name": ("Construire votre discours de marque", "Develop your brand messaging"),
    "seo_title": ("Construire votre discours de marque avec la social data | Licter",
                  "Build your brand messaging with social data | Licter"),
    "meta": ("Voyez quels mots, promesses et preuves vos audiences reprennent vraiment, et lesquels ne quittent jamais vos présentations.",
             "See which words, claims and proofs your audiences actually repeat, and which ones never leave your presentations."),
    "h1": ("Construire votre discours de marque avec les mots de vos clients.",
           "Build your brand messaging in your customers' words."),
    "intro": ("Une plateforme de marque se construit souvent en interne, avec les mots de l'entreprise. Vos clients en utilisent d'autres. Nous mesurons quels mots, quelles promesses et quelles preuves circulent vraiment, pour que votre discours reprenne ceux qui portent.",
              "A brand platform is often built internally, in the company's words. Your customers use others. We measure which words, claims and proofs actually travel, so your messaging picks up the ones that carry."),
    "questions": [
      ("Quels mots nos clients utilisent-ils pour parler de nous ?", "Which words do our customers use to talk about us?"),
      ("Nos promesses sont-elles reprises, ou restent-elles dans nos présentations ?", "Are our claims repeated, or do they stay in our presentations?"),
      ("Quelles preuves rendent un message crédible dans notre catégorie ?", "Which proofs make a message credible in our category?"),
      ("Comment nos concurrents occupent-ils le terrain ?", "How do our competitors hold the ground?"),
    ],
    "sources": [
      (("Conversation client", "Customer conversation"), ("Les mots employés spontanément pour parler de la catégorie.", "The words people use spontaneously about the category.")),
      (("Recherche", "Search"), ("Les questions que les gens posent vraiment.", "The questions people actually ask.")),
      (("Concurrents", "Competitors"), ("Leurs messages et ce que le public en reprend.", "Their messages and what the public picks up.")),
      (("IA générative", "Generative AI"), ("Les termes que les assistants associent à votre marque.", "The terms assistants associate with your brand.")),
    ],
    "steps": [
      ("On part de votre plateforme de marque et de vos messages actuels.", "We start from your brand platform and current messages."),
      ("On collecte la conversation de votre catégorie et de vos concurrents.", "We collect the conversation of your category and competitors."),
      ("Un analyste classe les mots et les preuves par traction.", "An analyst ranks words and proofs by traction."),
      ("On vous propose un vocabulaire à adopter, et un autre à abandonner.", "We propose a vocabulary to adopt, and one to drop."),
    ],
    "deliverables": [
      ("Le vocabulaire de votre marché, classé par traction.", "The vocabulary your market uses, ranked by traction."),
      ("Les promesses reprises et celles qui ne prennent pas.", "The claims that get repeated and those that do not land."),
      ("Les preuves qui rendent un message crédible.", "The proofs that make a message credible."),
      ("Une grille pour tester vos prochains messages.", "A grid to test your next messages."),
    ],
    "example": ("Exemple illustratif : un constructeur met en avant les accélérations de son modèle électrique. Ses clients parlent surtout de silence, de coffre et de coût d'usage. Recommandation : réécrire le discours familles autour de ces trois mots.",
                "Illustrative example: a carmaker highlights its EV's acceleration. Its customers mostly talk about silence, boot space and running costs. Recommendation: rewrite the family messaging around those three words."),
    "faq": [
      (("Travaillez-vous avec notre agence ?", "Do you work with our agency?"),
       ("Oui : nous lui donnons la matière, elle écrit. C'est souvent le meilleur duo.", "Yes: we give them the material, they write. It is often the best pairing.")),
      (("Peut-on tester un message avant de le lancer ?", "Can a message be tested before launch?"),
       ("On peut mesurer ses chances : les mots et les preuves qu'il utilise sont-ils ceux qui circulent déjà ?", "We can measure its chances: do its words and proofs match those already travelling?")),
      (("Combien de temps ?", "How long does it take?"),
       ("Quelques jours pour une première lecture, deux à trois semaines pour un travail complet.", "A few days for a first read, two to three weeks for a full piece of work.")),
    ],
  },
  {
    "key": "brand-risk", "family": "brand",
    "slug": ("risques-de-marque-crise", "brand-risk-crisis"),
    "name": ("Identifier et désamorcer les risques de marque", "Identify and mitigate brand risks"),
    "seo_title": ("Détecter les risques de marque et prévenir les crises | Licter",
                  "Detect brand risks and prevent crises | Licter"),
    "meta": ("Repérez les signaux faibles tôt, tant qu'ils restent maîtrisables : une rumeur, un appel au boycott, une controverse fournisseur. Alertes en 15 minutes.",
             "Catch weak signals early, while they are still containable: a rumour, a boycott call, a supplier controversy. Alerts within 15 minutes."),
    "h1": ("Identifier et désamorcer les risques de marque, avant la crise.",
           "Identify and mitigate brand risks, before the crisis."),
    "intro": ("Une crise commence presque toujours par un signal faible : un post, une rumeur, un appel au boycott dans une communauté de niche. Tant qu'il reste là, il est maîtrisable. Nous le repérons tôt, nous évaluons sa capacité à se propager, et nous vous prévenons à temps.",
              "A crisis almost always starts with a weak signal: a post, a rumour, a boycott call in a niche community. While it stays there, it is containable. We catch it early, assess how far it can spread, and warn you in time."),
    "questions": [
      ("Quels sujets pourraient devenir une crise pour nous ?", "Which subjects could become a crisis for us?"),
      ("Ce signal va-t-il se propager, ou s'éteindre de lui-même ?", "Will this signal spread, or fade on its own?"),
      ("Qui le porte, et avec quelle influence ?", "Who carries it, and with what influence?"),
      ("Faut-il répondre, et comment ?", "Should we respond, and how?"),
    ],
    "sources": [
      (("Communautés de niche", "Niche communities"), ("Forums, groupes, comptes spécialisés où les sujets naissent.", "Forums, groups, specialist accounts where subjects are born.")),
      (("Réseaux sociaux", "Social networks"), ("La propagation, compte par compte.", "The spread, account by account.")),
      (("Presse", "Press"), ("Le moment où un sujet passe dans les médias.", "The moment a subject reaches the media.")),
      (("Plus de vingt langues", "More than twenty languages"), ("Les risques qui naissent à l'étranger.", "The risks that start abroad.")),
    ],
    "steps": [
      ("On cartographie avec vous les risques de votre secteur et votre protocole d'escalade.", "We map your sector's risks and your escalation protocol with you."),
      ("La veille tourne 24 h/24, avec des seuils fixés par un éditeur, pas un algorithme.", "Monitoring runs 24/7, with thresholds set by an editor, not an algorithm."),
      ("Un analyste qualifie chaque signal : portée, porteurs, vitesse.", "An analyst qualifies each signal: reach, carriers, speed."),
      ("Vous êtes alerté en 15 minutes, avec une recommandation de réponse.", "You are alerted within 15 minutes, with a recommended response."),
    ],
    "deliverables": [
      ("Des alertes en 15 minutes, dans plus de vingt langues, avec un protocole d'escalade.", "15-minute alerts, 20+ languages, with an escalation protocol."),
      ("La cartographie des risques de votre secteur.", "The risk map of your sector."),
      ("Une recommandation de réponse pour chaque alerte.", "A recommended response for each alert."),
      ("Un bilan après chaque épisode.", "A review after each episode."),
    ],
    "example": ("Exemple illustratif : un éditeur de jeux vidéo voit monter les critiques le week-end de sortie. La lecture montre que les crashs serveurs concentrent la colère, pas le jeu. Recommandation : communiquer chaque jour sur les correctifs, sans communication de crise.",
                "Illustrative example: a video game publisher sees criticism rise on launch weekend. The read shows server crashes concentrate the anger, not the game. Recommendation: post daily on fixes, with no crisis communication."),
    "faq": [
      (("Qui reçoit les alertes ?", "Who receives the alerts?"),
       ("Les personnes que vous désignez, sur le canal que vous choisissez, selon le protocole défini avant le lancement.", "Whoever you decide, on the channel you decide, following the protocol agreed before launch.")),
      (("Comment éviter les fausses alertes ?", "How do you avoid false alarms?"),
       ("Un analyste qualifie chaque signal avant l'alerte. Les seuils sont éditoriaux, pas seulement des volumes.", "An analyst qualifies every signal before alerting. Thresholds are editorial, not just volumes.")),
      (("Nous accompagnez-vous pendant la crise ?", "Do you support us during the crisis?"),
       ("Oui : lecture en continu, points réguliers avec vos équipes et bilan à la sortie.", "Yes: continuous reading, regular check-ins with your teams and a review at the end.")),
    ],
  },
  # ------------------------------------------------------------ audiences
  {
    "key": "segmentation", "family": "audiences",
    "slug": ("segmentation-cibles", "audience-segmentation"),
    "name": ("Segmenter vos profils cibles", "Segment your target profiles"),
    "seo_title": ("Segmentation d'audience par le comportement réel | Licter",
                  "Audience segmentation from real behaviour | Licter"),
    "meta": ("Profilez qui achète, visite et parle réellement de vous : sociodémographie, centres d'intérêt, régime média, affinités de marque. Plus de 5 000 critères.",
             "Profile who actually buys, visits and talks about you: sociodemographics, interests, media diet, brand affinities. More than 5,000 criteria."),
    "h1": ("Segmenter vos profils cibles à partir de ce qu'ils font vraiment.",
           "Segment your target profiles from what they actually do."),
    "intro": ("Une segmentation déclarative dit ce que les gens pensent d'eux-mêmes. Nous partons de leur comportement : ce qu'ils suivent, achètent, recherchent et partagent. Le résultat, ce sont des communautés réelles, avec leur taille, leurs attentes et leurs médias.",
              "A declarative segmentation says what people think of themselves. We start from their behaviour: what they follow, buy, search and share. The result is real communities, with their size, expectations and media."),
    "questions": [
      ("Qui sont vraiment nos clients, au-delà de l'âge et du sexe ?", "Who really are our customers, beyond age and gender?"),
      ("Quelles communautés composent notre audience ?", "Which communities make up our audience?"),
      ("Où les toucher, et avec quels messages ?", "Where to reach them, and with which messages?"),
      ("Quelle communauté représente la plus grosse opportunité ?", "Which community is the biggest opportunity?"),
    ],
    "sources": [
      (("Panel comportemental", "Behavioural panel"), ("Environ trois milliards de consommateurs, plus de 5 000 critères.", "About three billion consumers, more than 5,000 criteria.")),
      (("Réseaux sociaux", "Social networks"), ("Qui parle de vous et de votre catégorie.", "Who talks about you and your category.")),
      (("Recherche", "Search"), ("Ce que chaque communauté cherche.", "What each community searches for.")),
      (("Affinités de marque", "Brand affinities"), ("Les marques et médias qu'elles suivent aussi.", "The brands and media they also follow.")),
    ],
    "steps": [
      ("On part de votre brief et des cibles actuelles.", "We start from your brief and current targets."),
      ("On identifie les communautés qui composent réellement votre audience.", "We identify the communities that really make up your audience."),
      ("Un analyste mesure l'affinité, la pénétration et l'opportunité de chacune.", "An analyst measures each one's affinity, penetration and opportunity."),
      ("On vous recommande les communautés à prioriser et comment les toucher.", "We recommend which communities to prioritise and how to reach them."),
    ],
    "deliverables": [
      ("Des personas précis bâtis sur plus de 5 000 critères comportementaux.", "Precise personas built on 5,000+ behavioural criteria."),
      ("La carte des communautés de votre audience.", "The map of your audience's communities."),
      ("Les scores d'affinité, de pénétration et d'opportunité.", "Affinity, penetration and opportunity scores."),
      ("Le plan média qui en découle.", "The media plan that follows."),
    ],
    "example": ("Exemple illustratif : une marque alimentaire cible les étudiants. La segmentation montre que les abonnés des créateurs food aiment la marque mais l'achètent peu : opportunité 86 sur 100, contre 31 pour les étudiants. Recommandation : réorienter le plan média.",
                "Illustrative example: a food brand targets students. The segmentation shows food creators' followers love the brand but barely buy it: opportunity 86 out of 100, against 31 for students. Recommendation: shift the media plan."),
    "faq": [
      (("Faut-il nous fournir nos données clients ?", "Do we need to share our customer data?"),
       ("Non. Nous pouvons les croiser si vous le souhaitez, mais le panel suffit pour une première segmentation.", "No. We can cross them if you wish, but the panel is enough for a first segmentation.")),
      (("Combien de segments en moyenne ?", "How many segments on average?"),
       ("Généralement cinq à huit communautés, assez distinctes pour être actionnables.", "Usually five to eight communities, distinct enough to act on.")),
      (("Peut-on segmenter un marché étranger ?", "Can you segment a foreign market?"),
       ("Oui, avec des analystes qui parlent la langue et connaissent le marché.", "Yes, with analysts who speak the language and know the market.")),
    ],
  },
  {
    "key": "rejuvenate", "family": "audiences",
    "slug": ("rajeunir-audience", "reach-younger-audiences"),
    "name": ("Rajeunir vos audiences", "Rejuvenate your audiences"),
    "seo_title": ("Rajeunir son audience : la génération suivante | Licter",
                  "Reach younger audiences: understand the next generation | Licter"),
    "meta": ("Comprenez ce qui compte pour la génération suivante de votre catégorie, et à quelle distance elle se situe de votre base actuelle.",
             "Understand what the next generation of your category cares about, and how far that sits from your current base."),
    "h1": ("Rajeunir vos audiences sans perdre celles que vous avez.",
           "Reach younger audiences without losing the ones you have."),
    "intro": ("La génération suivante de votre catégorie ne parle ni des mêmes sujets, ni sur les mêmes plateformes, ni avec les mêmes mots. Nous mesurons l'écart entre votre audience actuelle et celle que vous voulez, et nous vous montrons par où le combler.",
              "The next generation of your category does not talk about the same subjects, on the same platforms or in the same words. We measure the gap between your current audience and the one you want, and show you where to bridge it."),
    "questions": [
      ("Qu'est-ce qui compte pour les 18-30 ans dans notre catégorie ?", "What matters to 18 to 30 year olds in our category?"),
      ("À quelle distance sont-ils de notre audience actuelle ?", "How far are they from our current audience?"),
      ("Sur quelles plateformes et avec quels créateurs les toucher ?", "On which platforms and with which creators to reach them?"),
      ("Comment rajeunir sans froisser notre base ?", "How to get younger without alienating our base?"),
    ],
    "sources": [
      (("Panel comportemental", "Behavioural panel"), ("Les centres d'intérêt et médias de la génération visée.", "The interests and media of the target generation.")),
      (("TikTok, Instagram, Twitch", "TikTok, Instagram, Twitch"), ("Là où la génération suivante parle de la catégorie.", "Where the next generation talks about the category.")),
      (("Créateurs", "Creators"), ("Les voix qu'elle suit et en qui elle a confiance.", "The voices it follows and trusts.")),
      (("Votre base actuelle", "Your current base"), ("Pour mesurer l'écart, point par point.", "To measure the gap, point by point.")),
    ],
    "steps": [
      ("On définit la génération visée et votre base actuelle.", "We define the target generation and your current base."),
      ("On collecte ce que chacune suit, dit et achète.", "We collect what each one follows, says and buys."),
      ("Un analyste mesure l'écart, sujet par sujet et plateforme par plateforme.", "An analyst measures the gap, subject by subject and platform by platform."),
      ("On vous propose les ponts : sujets, formats, créateurs, produits d'entrée.", "We propose the bridges: subjects, formats, creators, entry products."),
    ],
    "deliverables": [
      ("L'analyse de l'écart entre votre audience actuelle et celle que vous visez.", "A gap analysis between your audience today and the one you want."),
      ("Les sujets et les plateformes de la génération suivante.", "The subjects and platforms of the next generation."),
      ("Les créateurs qui font le lien.", "The creators who bridge the gap."),
      ("Un plan pour rajeunir sans perdre votre base.", "A plan to get younger without losing your base."),
    ],
    "example": ("Exemple illustratif : une maison de maroquinerie a une clientèle de collectionneurs fidèles. La Gen Z rêve de la marque mais ne peut pas encore se l'offrir : affinité 71, pénétration 9. Recommandation : un produit d'entrée et un programme créateurs.",
                "Illustrative example: a leather goods house has a loyal base of collectors. Gen Z dreams of the brand but cannot afford it yet: affinity 71, penetration 9. Recommendation: an entry product and a creator programme."),
    "faq": [
      (("Faut-il être sur TikTok pour rajeunir ?", "Do we need to be on TikTok to get younger?"),
       ("Pas forcément. Nous vous disons où la génération visée parle de votre catégorie : c'est parfois Twitch, YouTube ou des forums.", "Not necessarily. We tell you where the target generation talks about your category: sometimes it is Twitch, YouTube or forums.")),
      (("Risque-t-on de perdre nos clients actuels ?", "Do we risk losing current customers?"),
       ("C'est précisément ce que l'analyse de l'écart permet d'éviter : on voit où les deux audiences se rejoignent.", "That is exactly what the gap analysis avoids: we see where the two audiences meet.")),
      (("En combien de temps ?", "How long does it take?"),
       ("Deux à trois semaines pour une analyse complète.", "Two to three weeks for a full analysis.")),
    ],
  },
  {
    "key": "touchpoints", "family": "audiences",
    "slug": ("parcours-client-attentes", "customer-expectations-touchpoints"),
    "name": ("Comprendre les attentes à chaque point de contact", "Understand expectations at every touchpoint"),
    "seo_title": ("Parcours client : les attentes à chaque point de contact | Licter",
                  "Customer journey: expectations at every touchpoint | Licter"),
    "meta": ("Cartographiez les attentes avant, pendant et après l'achat, et là où l'expérience se casse, classées par fréquence.",
             "Map what people expect before, during and after purchase, and where the experience breaks down, ranked by how often they surface."),
    "h1": ("Comprendre les attentes de vos clients à chaque point de contact.",
           "Understand what your customers expect at every touchpoint."),
    "intro": ("Vos clients racontent leur parcours en ligne : ce qu'ils attendaient, ce qui les a déçus, ce qui les a fait revenir. Nous lisons ces récits pour cartographier les attentes avant, pendant et après l'achat, et les points où l'expérience se casse.",
              "Your customers tell their journey online: what they expected, what disappointed them, what made them come back. We read those stories to map expectations before, during and after purchase, and the points where the experience breaks down."),
    "questions": [
      ("Qu'attendent nos clients à chaque étape du parcours ?", "What do our customers expect at each step of the journey?"),
      ("Où l'expérience se casse-t-elle le plus souvent ?", "Where does the experience break down most often?"),
      ("Qu'est-ce qui les fait revenir, ou partir chez un concurrent ?", "What makes them come back, or leave for a competitor?"),
      ("Quels irritants corriger en premier ?", "Which irritants should we fix first?"),
    ],
    "sources": [
      (("Avis clients", "Customer reviews"), ("Les récits d'expérience, étape par étape.", "Experience stories, step by step.")),
      (("Réseaux sociaux", "Social networks"), ("Les réclamations publiques et les réponses du service client.", "Public complaints and customer service replies.")),
      (("Forums", "Forums"), ("Les discussions détaillées avant achat.", "The detailed pre-purchase discussions.")),
      (("Recherche", "Search"), ("Les questions posées à chaque étape.", "The questions asked at each step.")),
    ],
    "steps": [
      ("On découpe avec vous le parcours client en étapes.", "We split the customer journey into steps with you."),
      ("On collecte ce qui se dit de chaque étape, chez vous et chez vos concurrents.", "We collect what is said about each step, for you and your competitors."),
      ("Un analyste classe les attentes et les irritants par fréquence.", "An analyst ranks expectations and irritants by frequency."),
      ("On vous remet les priorités : quoi corriger d'abord, et ce que ça rapporte.", "We hand you the priorities: what to fix first, and what it brings."),
    ],
    "deliverables": [
      ("Les attentes et les points de friction, classés par fréquence.", "Expectations and friction points, ordered by how often they surface."),
      ("La carte du parcours vue par vos clients.", "The journey map as your customers see it."),
      ("La comparaison avec vos concurrents, étape par étape.", "The comparison with your competitors, step by step."),
      ("Les trois irritants à corriger en priorité.", "The three irritants to fix first."),
    ],
    "example": ("Exemple illustratif : une marque alimentaire vendue en ligne voit ses avis baisser. 62 % des posts négatifs parlent de colis en retard ou abîmés ; le produit reste salué. Recommandation : changer de transporteur et le dire publiquement.",
                "Illustrative example: a food brand sold online sees its reviews drop. 62% of negative posts are about late or damaged parcels; the product is still praised. Recommendation: change carrier and say so publicly."),
    "faq": [
      (("Est-ce utile pour un site e-commerce ?", "Is it useful for an e-commerce site?"),
       ("Oui, et aussi pour les magasins, les services et les parcours hybrides.", "Yes, and also for stores, services and hybrid journeys.")),
      (("Remplace-t-on les enquêtes de satisfaction ?", "Does it replace satisfaction surveys?"),
       ("Non, ça les complète : l'enquête mesure, la conversation explique.", "No, it complements them: the survey measures, the conversation explains.")),
      (("Peut-on suivre les progrès dans le temps ?", "Can progress be tracked over time?"),
       ("Oui, avec une lecture régulière des mêmes étapes.", "Yes, with a regular read of the same steps.")),
    ],
  },
  # ------------------------------------------------------------ trends
  {
    "key": "product-test", "family": "trends",
    "slug": ("tester-evaluer-produits", "product-testing"),
    "name": ("Tester et évaluer vos produits", "Test and evaluate your products"),
    "seo_title": ("Tester et évaluer vos produits avec la social data | Licter",
                  "Test and evaluate your products with social data | Licter"),
    "meta": ("Lisez le verdict non filtré sur vos produits et ceux de vos concurrents : ce qui est loué, retourné ou contourné.",
             "Read the unfiltered verdict on your products and your competitors': what gets praised, returned, or worked around."),
    "h1": ("Tester et évaluer vos produits sur le verdict non filtré de vos clients.",
           "Test and evaluate your products on your customers' unfiltered verdict."),
    "intro": ("Vos clients testent vos produits tous les jours, et ils en parlent : ce qu'ils adorent, ce qu'ils renvoient, ce qu'ils bricolent pour contourner un défaut. Ce verdict non filtré existe aussi pour vos concurrents. Nous le lisons produit par produit.",
              "Your customers test your products every day, and they talk about it: what they love, what they return, what they work around to fix a flaw. That unfiltered verdict exists for your competitors too. We read it product by product."),
    "questions": [
      ("Qu'est-ce que nos clients aiment vraiment dans nos produits ?", "What do our customers really love about our products?"),
      ("Quels défauts reviennent, et à quelle fréquence ?", "Which flaws keep coming up, and how often?"),
      ("Comment nos produits se comparent-ils à ceux des concurrents ?", "How do our products compare with competitors'?"),
      ("Quelles améliorations prioriser ?", "Which improvements should come first?"),
    ],
    "sources": [
      (("Avis produits", "Product reviews"), ("Sites marchands, comparateurs, forums spécialisés.", "Retail sites, comparison sites, specialist forums.")),
      (("Vidéos de test", "Review videos"), ("Les tests et unboxings sur YouTube et TikTok.", "Tests and unboxings on YouTube and TikTok.")),
      (("Réseaux sociaux", "Social networks"), ("Les usages réels et les astuces des utilisateurs.", "Real uses and users' workarounds.")),
      (("Concurrents", "Competitors"), ("Les mêmes sources, pour leurs produits.", "The same sources, for their products.")),
    ],
    "steps": [
      ("On choisit les produits à évaluer, les vôtres et ceux des concurrents.", "We choose the products to evaluate, yours and competitors'."),
      ("On collecte tout ce qui se dit de chacun.", "We collect everything said about each one."),
      ("Un analyste classe les forces et les irritants, produit par produit.", "An analyst ranks strengths and irritants, product by product."),
      ("On vous remet un verdict et des priorités d'amélioration.", "We hand you a verdict and improvement priorities."),
    ],
    "deliverables": [
      ("Les forces et les irritants par produit, les vôtres et les leurs.", "Strengths and irritants per product, yours and theirs."),
      ("Le classement des défauts par fréquence.", "Flaws ranked by frequency."),
      ("Les usages imprévus qui ouvrent des pistes.", "Unexpected uses that open new leads."),
      ("Les priorités pour la prochaine version.", "Priorities for the next version."),
    ],
    "example": ("Exemple illustratif : un éditeur de jeux vidéo lit les réactions à sa bêta. Le scénario et les graphismes sont loués ; les microtransactions et le lag concentrent les critiques. Recommandation : corriger le lag avant la sortie et revoir le modèle économique.",
                "Illustrative example: a video game publisher reads reactions to its beta. The story and graphics are praised; microtransactions and lag concentrate the criticism. Recommendation: fix the lag before release and rethink the pricing model."),
    "faq": [
      (("Peut-on évaluer un produit pas encore sorti ?", "Can you evaluate a product not yet released?"),
       ("Oui, à partir des réactions à une bêta, un teaser ou aux produits concurrents déjà sur le marché.", "Yes, from reactions to a beta, a teaser or competing products already on the market.")),
      (("Combien d'avis faut-il ?", "How many reviews does it take?"),
       ("Quelques centaines suffisent souvent pour dégager les tendances ; nous vous disons si le volume est trop faible.", "A few hundred are often enough to see patterns; we tell you if the volume is too low.")),
      (("Couvrez-vous les avis à l'étranger ?", "Do you cover reviews abroad?"),
       ("Oui, dans plus de vingt langues.", "Yes, in more than twenty languages.")),
    ],
  },
  {
    "key": "market-opportunities", "family": "trends",
    "slug": ("analyse-marche-opportunites", "market-opportunities"),
    "name": ("Analyser les marchés et repérer les opportunités", "Analyse markets and identify opportunities"),
    "seo_title": ("Analyse de marché : repérer les opportunités | Licter",
                  "Market analysis: find the opportunities nobody covers | Licter"),
    "meta": ("Dimensionnez la conversation d'un marché, repérez les besoins non couverts et les espaces que personne n'a pris.",
             "Size the conversation of a market, spot the unmet needs and the whitespace nobody has claimed yet, before your competitors do."),
    "h1": ("Analyser un marché et repérer les opportunités que personne n'a prises.",
           "Analyse a market and find the opportunities nobody has claimed."),
    "intro": ("Avant d'entrer sur un marché ou de lancer une gamme, il faut savoir de quoi les gens parlent, ce qu'ils cherchent et ce qu'ils ne trouvent pas. La conversation d'un marché fait apparaître ces besoins mal couverts, souvent avant les études.",
              "Before entering a market or launching a range, you need to know what people talk about, what they look for and what they cannot find. A market's conversation reveals those unmet needs, often before the surveys."),
    "questions": [
      ("Quelle est la taille réelle de la conversation sur ce marché ?", "How big is the conversation in this market, really?"),
      ("Quels besoins reviennent sans trouver de réponse ?", "Which needs keep coming up without an answer?"),
      ("Où se positionnent nos concurrents, et où sont-ils absents ?", "Where do competitors stand, and where are they absent?"),
      ("Faut-il y aller, et avec quelle offre ?", "Should we go, and with what offer?"),
    ],
    "sources": [
      (("Conversation du marché", "Market conversation"), ("Réseaux, forums, avis, sur tout le marché visé.", "Networks, forums, reviews, across the target market.")),
      (("Recherche", "Search"), ("La demande exprimée, et celle qui reste sans réponse.", "The demand expressed, and the demand left unanswered.")),
      (("Concurrents", "Competitors"), ("Leur présence et ce qu'on leur reproche.", "Their presence and what people hold against them.")),
      (("Panel d'audience", "Audience panel"), ("Qui porte chaque besoin.", "Who carries each need.")),
    ],
    "steps": [
      ("On délimite le marché : catégorie, pays, langues.", "We define the market: category, countries, languages."),
      ("On collecte la conversation et la demande exprimée.", "We collect the conversation and the expressed demand."),
      ("Un analyste repère les besoins mal couverts et les espaces libres.", "An analyst finds the unmet needs and the open spaces."),
      ("On vous recommande où aller, avec quelle offre et quels messages.", "We recommend where to go, with which offer and messages."),
    ],
    "deliverables": [
      ("Une carte de la demande, avec les manques que vos concurrents ne couvrent pas.", "A map of demand, with the gaps your competitors are not covering."),
      ("La taille de la conversation, segment par segment.", "The size of the conversation, segment by segment."),
      ("Le positionnement des concurrents.", "Competitors' positioning."),
      ("Une recommandation go / no go argumentée.", "A reasoned go / no-go recommendation."),
    ],
    "example": ("Exemple illustratif : un constructeur hésite sur sa prochaine gamme. La conversation montre que l'électrique d'occasion a été multiplié par plus de dix, sans offre certifiée claire. Recommandation : lancer une offre d'occasion certifiée.",
                "Illustrative example: a carmaker hesitates over its next range. The conversation shows used EVs grew more than tenfold, with no clear certified offer. Recommendation: launch a certified used-EV offer."),
    "faq": [
      (("Pouvez-vous analyser un marché étranger ?", "Can you analyse a foreign market?"),
       ("Oui, avec des analystes qui parlent la langue du marché, pas par traduction automatique.", "Yes, with analysts who speak the market's language, not through machine translation.")),
      (("Est-ce une étude de marché ?", "Is this market research?"),
       ("C'est complémentaire : nous lisons ce qui se dit spontanément, à l'échelle de tout un marché.", "It is complementary: we read what is said spontaneously, across a whole market.")),
      (("Combien de temps ?", "How long does it take?"),
       ("Deux à trois semaines pour une analyse complète d'un marché.", "Two to three weeks for a full market analysis.")),
    ],
  },
  {
    "key": "stakeholders", "family": "trends",
    "slug": ("cartographie-parties-prenantes-tendances", "stakeholder-trend-mapping"),
    "name": ("Cartographier vos parties prenantes et les tendances à venir", "Map out your stakeholders and future trends"),
    "seo_title": ("Cartographie des parties prenantes et des tendances | Licter",
                  "Stakeholder and trend mapping | Licter"),
    "meta": ("Suivez les communautés, les experts et les institutions qui façonnent une catégorie, et les tendances qui en sortent.",
             "Follow the communities, experts and institutions that shape a category, and the trends breaking out of it before they go mainstream."),
    "h1": ("Cartographier vos parties prenantes et les tendances qui arrivent.",
           "Map your stakeholders and the trends on their way."),
    "intro": ("Une catégorie est façonnée par des communautés, des experts, des médias et des institutions. Les tendances naissent dans certaines d'entre elles avant de gagner le grand public. Nous cartographions qui compte, et nous suivons les sujets qui prennent de la vitesse.",
              "A category is shaped by communities, experts, media and institutions. Trends are born in some of them before reaching the wider public. We map who matters, and follow the topics gaining speed."),
    "questions": [
      ("Qui façonne vraiment notre catégorie ?", "Who really shapes our category?"),
      ("Quels sujets montent, et depuis quelles communautés ?", "Which topics are rising, and from which communities?"),
      ("Quelles tendances vont arriver chez nos clients ?", "Which trends will reach our customers?"),
      ("Avec qui dialoguer, et quand ?", "Who should we talk to, and when?"),
    ],
    "sources": [
      (("Communautés", "Communities"), ("Les groupes où les sujets naissent.", "The groups where topics are born.")),
      (("Experts et médias", "Experts and media"), ("Les voix que la catégorie écoute.", "The voices the category listens to.")),
      (("Institutions", "Institutions"), ("Régulateurs, associations, ONG.", "Regulators, associations, NGOs.")),
      (("Évolution des sujets", "Topic trends"), ("Mois après mois, sur dix-huit mois.", "Month after month, over eighteen months.")),
    ],
    "steps": [
      ("On définit la catégorie et les enjeux qui vous concernent.", "We define the category and the issues that concern you."),
      ("On repère les acteurs et on suit l'évolution des sujets.", "We identify the players and follow how topics evolve."),
      ("Un analyste distingue ce qui monte vraiment de ce qui fait du bruit.", "An analyst tells what is really rising from what is just noise."),
      ("On vous dit quoi lancer, quoi surveiller, quoi arrêter.", "We tell you what to build, what to watch, what to stop."),
    ],
    "deliverables": [
      ("La carte des parties prenantes et des sujets qui accélèrent.", "The stakeholder map and the topics gaining velocity."),
      ("Les tendances classées : à lancer, à surveiller, à arrêter.", "Trends sorted: build, watch, stop."),
      ("Les communautés où elles naissent.", "The communities where they are born."),
      ("Une lecture régulière pour suivre leur évolution.", "A regular read to follow how they evolve."),
    ],
    "example": ("Exemple illustratif : un éditeur de jeux suit dix-huit mois de conversation. Les cozy games ont dépassé le battle royale au neuvième mois, portés par les audiences des streamers. Recommandation : axer le prochain titre sur le cozy et la coopération.",
                "Illustrative example: a game publisher follows eighteen months of conversation. Cozy games overtook battle royale in month nine, carried by streamers' audiences. Recommendation: build the next title around cozy and co-op play."),
    "faq": [
      (("Sur quelle période lisez-vous les tendances ?", "Over what period do you read trends?"),
       ("Généralement dix-huit mois, pour distinguer une vraie tendance d'un effet de mode.", "Usually eighteen months, to tell a real trend from a passing fad.")),
      (("Est-ce utile pour les affaires publiques ?", "Is it useful for public affairs?"),
       ("Oui : la cartographie des parties prenantes sert autant aux affaires publiques qu'au marketing.", "Yes: stakeholder mapping serves public affairs as much as marketing.")),
      (("À quelle fréquence mettez-vous à jour ?", "How often do you update?"),
       ("Chaque mois, ou en continu avec la veille.", "Every month, or continuously with monitoring.")),
    ],
  },
]

# ------------------------------------------------------------------ extras
# Client interviews from the Audience First channel, one per use case.
VOICES = {
    "paris2024": ("l-OevQ4q8js", "55:08", ("Des millions de tweets à gérer, en direct.", "Millions of tweets to handle, live."), "Paris 2024", "C. Legall"),
    "axa": ("0HfWWSB0v78", "54:27", ("Ce que la diversité des médias rapporte vraiment.", "What media diversity actually buys you."), "AXA", "Z. Gebran"),
    "lvmh": ("CEFJc7tP4hU", "41:22", ("600 000 abonnés en deux ans.", "600k followers in two years."), "LVMH", "Clara Mallien"),
    "sncf": ("z3EkLWjQXMQ", "56:29", ("La social room a changé notre façon de travailler.", "The social room changed the way we work."), "SNCF", "M. Fleurbaey"),
    "loreal": ("moW2HYtTor8", "51:29", ("Internet, pour capter la voix du consommateur.", "The internet, to capture the consumer's voice."), "L'Oréal", "C. Besson"),
    "kantar": ("NwA84KwnDKU", "53:14", ("Consommer est devenu un acte militant.", "Consumption has become an act of activism."), "Kantar", "G. Lefloch"),
    "paris": ("JSI5LBi8K-g", "51:52", ("Peut-on capter la voix des Parisiens ?", "Can you capture the voice of Parisians?"), "Ville de Paris", "B. Tailly & F. Lootvoet"),
    "orange": ("UElJ_Pdd0wo", "58:39", ("Toutes les tendances partent désormais de TikTok.", "Every trend now starts on TikTok."), "Orange", "B. Hoang"),
    "francedigitale": ("EOkpQ_v-3kw", "45:24", ("Le meilleur argent, c'est celui de vos clients.", "The best money is your customers' money."), "France Digitale", "A. Labarrière"),
    "dassault": ("cnwA-t0Vqk4", "1:00:32", ("Les réseaux sociaux nous aident à faire de meilleurs produits.", "Social media helps us build better products."), "Dassault Systèmes", "Jean-Stéphane Bou"),
    "seb": ("1PXRd4_JgEc", "1:03:49", ("Ce n'est pas une étude s'il n'y a pas de plan d'action.", "It is not a study if there is no action plan."), "Groupe SEB", "Hélène Classine"),
    "transat": ("yEe6j9oLmQY", "53:28", ("J'ai vécu deux révolutions.", "I have lived through two revolutions."), "Transat Café l'Or", "Antoine Robin"),
}

# Blog articles, by file name.
ARTICLES = {
    "article-alerting-thresholds-are-editorial.html": ("Les seuils d'alerte sont un choix éditorial", "Alerting thresholds are an editorial choice"),
    "article-behaviour-against-declaration.html": ("Le comportement contre la déclaration", "Behaviour against declaration"),
    "article-language-coverage-is-not-translation.html": ("Couvrir une langue n'est pas la traduire", "Language coverage is not translation"),
    "article-the-persona-workshop-replaced.html": ("L'atelier persona, remplacé", "The persona workshop, replaced"),
    "article-the-trend-you-already-missed.html": ("La tendance que vous avez déjà ratée", "The trend you already missed"),
    "article-the-voices-that-actually-carry.html": ("Les voix qui portent vraiment", "The voices that actually carry"),
    "article-weak-signals-before-they-trend.html": ("Les signaux faibles, avant qu'ils ne deviennent tendance", "Weak signals, before they trend"),
    "article-what-a-platform-cannot-do-alone.html": ("Ce qu'une plateforme ne fait pas seule", "What a platform cannot do on its own"),
    "article-where-panels-and-surveys-disagree.html": ("Là où le panel et l'étude se contredisent", "Where panels and surveys disagree"),
}

# Per case: our approach, three returns on the investment, the client
# interview, the related articles. MOCK: to be validated by Licter.
EXTRA = {
  "campaign-impact": {
    "approach": ("Nous ne regardons pas la campagne isolément. Nous fixons d'abord une période de référence, puis nous comparons la conversation avant et après, audience par audience, face à la moyenne de votre catégorie. Ce qui compte n'est pas le pic de volume, mais ce qui reste une fois le pic retombé, et chez qui.",
                 "We never look at the campaign on its own. We first set a baseline, then compare the conversation before and after, audience by audience, against your category's average. What counts is not the volume peak but what remains once it has passed, and in whom."),
    "roi": [(("Un budget mieux placé", "Budget where it pays"), ("Vous savez quels leviers ont vraiment porté la campagne : la suivante mise sur eux.", "You know which levers really carried the campaign: the next one backs them.")),
            (("Un bilan en jours", "A review in days"), ("Une première lecture dès la fin de la campagne, pas un bilan trois mois plus tard.", "A first read as soon as the campaign ends, not a review three months later.")),
            (("Des arbitrages défendables", "Decisions you can defend"), ("Des preuves chiffrées, audience par audience, pour arbitrer en comité.", "Evidence, audience by audience, to settle choices in committee."))],
    "voice": "paris2024", "articles": ["article-what-a-platform-cannot-do-alone.html", "article-the-voices-that-actually-carry.html"],
  },
  "leader-advocacy": {
    "approach": ("Nous partons des sujets sur lesquels votre dirigeant est légitime, pas de ceux sur lesquels il aimerait l'être. Nous mesurons sa part de voix sujet par sujet face à un panel de pairs choisi avec vous, et nous regardons qui relaie ses messages. Le résultat est un plan de prise de parole, pas un classement.",
                 "We start from the subjects on which your leader is credible, not the ones they would like to own. We measure their share of voice subject by subject against a peer set chosen with you, and look at who relays their messages. The result is a speaking plan, not a ranking."),
    "roi": [(("Moins de prises de parole perdues", "Fewer wasted statements"), ("Le dirigeant parle là où il est attendu, et plus là où il ajoute du bruit.", "The leader speaks where they are expected, no longer where they add noise.")),
            (("Une visibilité qui profite à la marque", "Visibility that serves the brand"), ("Ses sujets et ceux de l'entreprise se renforcent au lieu de se disperser.", "Their subjects and the company's reinforce each other instead of scattering.")),
            (("Des faux pas évités", "Missteps avoided"), ("Savoir sur quoi il est attendu protège aussi en période sensible.", "Knowing what they are expected to address also protects in sensitive times."))],
    "voice": "axa", "articles": ["article-the-voices-that-actually-carry.html", "article-where-panels-and-surveys-disagree.html"],
  },
  "ambassadors": {
    "approach": ("Nous ne partons pas d'une liste d'influenceurs. Nous partons de votre audience cible, et nous cherchons les voix qu'elle écoute vraiment. Chaque voix est ensuite classée sur trois critères : recouvrement d'audience, affinité avec votre catégorie et risques attachés à son nom.",
                 "We do not start from a list of influencers. We start from your target audience, and look for the voices it actually listens to. Each voice is then ranked on three criteria: audience overlap, affinity with your category and risks attached to its name."),
    "roi": [(("Un budget d'influence qui touche les bonnes personnes", "Influence spend that reaches the right people"), ("Vous payez pour une audience qui recoupe la vôtre, pas pour des abonnés.", "You pay for an audience that overlaps yours, not for followers.")),
            (("Des créateurs repérés tôt", "Creators found early"), ("Les voix émergentes coûtent moins cher avant de devenir évidentes.", "Emerging voices cost less before they become obvious.")),
            (("Des polémiques évitées", "Controversies avoided"), ("Les signaux de risque sont vérifiés avant de signer.", "Risk flags are checked before signing."))],
    "voice": "lvmh", "articles": ["article-the-voices-that-actually-carry.html", "article-the-persona-workshop-replaced.html"],
  },
  "reputation": {
    "approach": ("Nous lisons votre réputation en continu, dans toutes les langues de vos marchés, et nous la comparons à celle de vos concurrents. Un analyste qualifie les évolutions chaque mois, et vous alerte dès qu'un sujet rompt la tendance. Vous recevez une note d'analyse, pas un tableau de bord de plus.",
                 "We read your reputation continuously, in every language of your markets, and compare it with your competitors'. An analyst qualifies the changes every month, and alerts you as soon as a subject breaks the trend. You get an analysis note, not one more dashboard."),
    "roi": [(("Des problèmes vus à temps", "Problems seen in time"), ("Une alerte 24 h/24 quand un sujet change, avant qu'il ne coûte.", "A 24/7 alert when a subject shifts, before it costs you.")),
            (("Moins de temps passé à surveiller", "Less time spent watching"), ("Vos équipes lisent une note mensuelle au lieu de trier des mentions.", "Your teams read a monthly note instead of sorting mentions.")),
            (("Un budget prévisible", "A predictable budget"), ("Un forfait mensuel, sans engagement, avec des études illimitées à l'intérieur.", "A fixed monthly fee, no commitment, with unlimited studies inside it."))],
    "voice": "sncf", "articles": ["article-language-coverage-is-not-translation.html", "article-alerting-thresholds-are-editorial.html"],
  },
  "messaging": {
    "approach": ("Nous confrontons votre plateforme de marque à la conversation réelle de votre catégorie. Nous classons les mots, les promesses et les preuves par traction, chez vous et chez vos concurrents, pour voir lesquels circulent et lesquels restent dans vos présentations.",
                 "We set your brand platform against the real conversation of your category. We rank words, claims and proofs by traction, for you and your competitors, to see which ones travel and which ones stay in your presentations."),
    "roi": [(("Des messages qui portent", "Messages that land"), ("Votre discours reprend les mots que vos clients utilisent déjà.", "Your messaging uses the words your customers already use.")),
            (("Moins d'allers-retours avec l'agence", "Fewer rounds with the agency"), ("Un brief appuyé sur des preuves, pas sur des intuitions.", "A brief built on evidence, not hunches.")),
            (("Un terrain que vos concurrents n'occupent pas", "Ground your competitors do not hold"), ("Les promesses libres de votre catégorie apparaissent clairement.", "The unclaimed claims of your category show up clearly."))],
    "voice": "loreal", "articles": ["article-where-panels-and-surveys-disagree.html", "article-behaviour-against-declaration.html"],
  },
  "brand-risk": {
    "approach": ("Nous cartographions avec vous les risques propres à votre secteur, puis nous fixons des seuils d'alerte avec un éditeur, pas un algorithme. Chaque signal est qualifié par un analyste avant de vous être envoyé : qui le porte, avec quelle influence, à quelle vitesse il se propage.",
                 "We map your sector's own risks with you, then set alert thresholds with an editor, not an algorithm. Every signal is qualified by an analyst before it reaches you: who carries it, with what influence, how fast it spreads."),
    "roi": [(("Des crises évitées", "Crises avoided"), ("Un signal traité quand il est encore maîtrisable coûte moins qu'une crise.", "A signal handled while still containable costs less than a crisis.")),
            (("Une alerte en 15 minutes", "Alerted within 15 minutes"), ("Dans plus de vingt langues, avec un protocole d'escalade défini à l'avance.", "In more than twenty languages, with an escalation protocol set in advance.")),
            (("Pas de fausses alertes", "No false alarms"), ("Vos équipes ne sont dérangées que pour ce qui compte.", "Your teams are only disturbed for what matters."))],
    "voice": "kantar", "articles": ["article-weak-signals-before-they-trend.html", "article-alerting-thresholds-are-editorial.html"],
  },
  "segmentation": {
    "approach": ("Nous partons de ce que vos clients font, pas de ce qu'ils déclarent. Le panel comportemental fait apparaître les communautés qui composent réellement votre audience ; nous mesurons pour chacune l'affinité, la pénétration et l'opportunité, et nous en tirons les priorités du plan média.",
                 "We start from what your customers do, not what they declare. The behavioural panel reveals the communities that really make up your audience; for each one we measure affinity, penetration and opportunity, and turn them into media plan priorities."),
    "roi": [(("Un plan média qui vise juste", "A media plan that hits"), ("Le budget va aux communautés où l'opportunité est la plus forte.", "Budget goes to the communities with the strongest opportunity.")),
            (("Des cibles oubliées retrouvées", "Overlooked targets found"), ("Les communautés que le brief n'avait pas vues apparaissent.", "The communities the brief had missed come to light.")),
            (("Des personas qui durent", "Personas that last"), ("Bâtis sur plus de 5 000 critères, ils se mettent à jour avec les données.", "Built on more than 5,000 criteria, they update with the data."))],
    "voice": "paris", "articles": ["article-the-persona-workshop-replaced.html", "article-behaviour-against-declaration.html"],
  },
  "rejuvenate": {
    "approach": ("Nous comparons point par point la génération que vous visez et votre base actuelle : sujets, plateformes, créateurs, mots. L'écart devient une liste de ponts concrets, pour rajeunir votre audience sans perdre celle que vous avez.",
                 "We compare, point by point, the generation you want and your current base: subjects, platforms, creators, words. The gap becomes a list of concrete bridges, to reach younger audiences without losing the one you have."),
    "roi": [(("Des clients pour les dix prochaines années", "Customers for the next ten years"), ("Vous préparez la relève de votre base avant qu'elle ne vieillisse.", "You prepare the next generation of your base before it ages.")),
            (("Moins d'essais à l'aveugle", "Fewer blind tests"), ("Vous savez où et avec qui parler à la génération suivante.", "You know where and with whom to talk to the next generation.")),
            (("Une base actuelle préservée", "Your current base kept"), ("Les ponts passent par ce que les deux audiences partagent.", "The bridges go through what both audiences share."))],
    "voice": "orange", "articles": ["article-the-persona-workshop-replaced.html", "article-the-trend-you-already-missed.html"],
  },
  "touchpoints": {
    "approach": ("Nous découpons avec vous le parcours client en étapes, puis nous lisons ce que vos clients racontent de chacune, chez vous et chez vos concurrents. Les attentes et les irritants sont classés par fréquence, pour savoir quoi corriger en premier.",
                 "We split the customer journey into steps with you, then read what your customers say about each one, for you and your competitors. Expectations and irritants are ranked by frequency, so you know what to fix first."),
    "roi": [(("Moins de clients perdus", "Fewer customers lost"), ("Vous corrigez d'abord les irritants qui font partir.", "You fix first the irritants that make people leave.")),
            (("Moins de réclamations", "Fewer complaints"), ("Les problèmes récurrents sont traités à la source.", "Recurring problems are dealt with at the source.")),
            (("Des investissements bien ciblés", "Well-aimed investment"), ("Chaque étape du parcours est priorisée par ce qu'elle rapporte.", "Each step of the journey is prioritised by what it brings."))],
    "voice": "francedigitale", "articles": ["article-where-panels-and-surveys-disagree.html", "article-behaviour-against-declaration.html"],
  },
  "product-test": {
    "approach": ("Nous lisons le verdict non filtré sur vos produits et ceux de vos concurrents : avis, vidéos de test, forums, usages détournés. Un analyste classe les forces et les irritants par fréquence, produit par produit, et en tire les priorités de la prochaine version.",
                 "We read the unfiltered verdict on your products and your competitors': reviews, test videos, forums, workarounds. An analyst ranks strengths and irritants by frequency, product by product, and turns them into priorities for the next version."),
    "roi": [(("Des retours produits en moins", "Fewer returns"), ("Les défauts qui font renvoyer un produit sont corrigés en priorité.", "The flaws that make people return a product are fixed first.")),
            (("Une feuille de route appuyée sur des preuves", "An evidence-based roadmap"), ("La prochaine version répond à ce que les clients disent vraiment.", "The next version answers what customers actually say.")),
            (("Des idées gratuites", "Free ideas"), ("Les usages détournés ouvrent des pistes produit que personne n'a testées.", "Workarounds open product leads nobody has tested."))],
    "voice": "dassault", "articles": ["article-where-panels-and-surveys-disagree.html", "article-the-trend-you-already-missed.html"],
  },
  "market-opportunities": {
    "approach": ("Nous délimitons avec vous le marché, puis nous en lisons toute la conversation et la demande exprimée en recherche. Les besoins qui reviennent sans réponse et les espaces que vos concurrents n'occupent pas deviennent une recommandation argumentée : y aller ou non, et avec quelle offre.",
                 "We define the market with you, then read its whole conversation and the demand expressed in search. The needs that keep coming up unanswered and the spaces your competitors do not hold become a reasoned recommendation: go or not, and with which offer."),
    "roi": [(("Un lancement moins risqué", "A less risky launch"), ("Vous entrez sur un marché en sachant ce qui y manque.", "You enter a market knowing what it lacks.")),
            (("Un avantage d'avance", "A head start"), ("Les besoins apparaissent dans la conversation avant les études.", "Needs show up in the conversation before the surveys.")),
            (("Moins d'études de marché ad hoc", "Fewer one-off market studies"), ("Un forfait mensuel remplace les études au coup par coup.", "A fixed monthly fee replaces one-off studies."))],
    "voice": "seb", "articles": ["article-the-trend-you-already-missed.html", "article-language-coverage-is-not-translation.html"],
  },
  "stakeholders": {
    "approach": ("Nous repérons les communautés, les experts, les médias et les institutions qui façonnent votre catégorie, puis nous suivons l'évolution des sujets mois après mois, sur dix-huit mois. Un analyste distingue ce qui monte vraiment de ce qui fait du bruit, et vous dit quoi lancer, surveiller ou arrêter.",
                 "We identify the communities, experts, media and institutions that shape your category, then follow how topics evolve month after month, over eighteen months. An analyst tells what is really rising from what is just noise, and tells you what to build, watch or stop."),
    "roi": [(("Des tendances prises avant les autres", "Trends caught before others"), ("Vous agissez quand un sujet monte, pas quand il est partout.", "You act when a topic is rising, not when it is everywhere.")),
            (("Moins de paris ratés", "Fewer failed bets"), ("Les modes passagères sont écartées avant d'y investir.", "Passing fads are ruled out before you invest.")),
            (("Les bons interlocuteurs", "The right people to talk to"), ("Vous savez qui compte dans votre catégorie, et quand leur parler.", "You know who matters in your category, and when to talk to them."))],
    "voice": "transat", "articles": ["article-weak-signals-before-they-trend.html", "article-the-trend-you-already-missed.html"],
  },
}

# Family pages, "a read, not a dashboard": what a dashboard shows next to
# what the read says, on the same illustrative case. MOCK.
DASHBOARD = {
  "communication": {
    "rows": [(("Mentions", "Mentions"), "57 006", "up"), (("Portée estimée", "Estimated reach"), "4,2 M", "up"),
             (("Sentiment", "Sentiment"), "+18 %", "up"), (("Mot le plus cité", "Top word"), ("recette", "recipe"), "")],
    "note": (("Le lancement a été porté par les recettes des créateurs sur TikTok, pas par la publicité TV : 46 % des posts les partagent, 14 % parlent de la pub.",
              "The launch was carried by creators' recipes on TikTok, not by the TV ad: 46% of posts share them, 14% mention the ad."),
             ("Basculer un tiers du média payé vers des partenariats créateurs.", "Move a third of paid media to creator partnerships.")),
  },
  "brand": {
    "rows": [(("Mentions", "Mentions"), "5 140", "up"), (("Sentiment", "Sentiment"), "−12 %", "down"),
             (("Mentions négatives", "Negative mentions"), "1 953", "up"), (("Mot le plus cité", "Top word"), ("boutique", "boutique"), "")],
    "note": (("Les hausses de prix sont acceptées ; c'est l'accueil en boutique qui concentre 38 % des critiques.",
              "Price increases are accepted; the in-store welcome accounts for 38% of the criticism."),
             ("Former les équipes boutique avant la prochaine hausse.", "Train boutique teams before the next increase.")),
  },
  "audiences": {
    "rows": [(("Audience totale", "Total audience"), "15 640", "up"), (("Âge dominant", "Main age group"), "35-49", ""),
             (("Genre", "Gender"), ("58 % femmes", "58% women"), ""), (("Centre d'intérêt n° 1", "Top interest"), ("cuisine", "cooking"), "")],
    "note": (("Les abonnés des créateurs food aiment la marque mais l'achètent peu : opportunité 86 sur 100, contre 31 pour les étudiants visés par le brief.",
              "Food creators' followers love the brand but barely buy it: opportunity 86 out of 100, against 31 for the students the brief targets."),
             ("Réorienter le plan média vers les audiences des créateurs food.", "Shift the media plan toward food creators' audiences.")),
  },
  "trends": {
    "rows": [(("Sujets suivis", "Topics tracked"), "8", ""), (("Sujet n° 1", "Top topic"), ("Snacks protéinés", "High-protein snacks"), "up"),
             (("Plus forte hausse", "Fastest riser"), "+460", "up"), (("Plus forte baisse", "Biggest drop"), "−52", "down")],
    "note": (("Le protéiné fait le plus de bruit, mais l'alimentation upcyclée est passée de rien à la quatrième place en un an, sans concurrent installé.",
              "Protein is the loudest, but upcycled food went from nowhere to fourth place in a year, with no established competitor."),
             ("Tester une gamme upcyclée sur un marché avant que la concurrence ne s'en aperçoive.", "Pilot an upcycled range in one market before competitors notice.")),
  },
}
